/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import VariationalSW.Auto.Sec1Introduction
public import VariationalSW.Auto.Sec3LongJumpEstimates
public import VariationalSW.Auto.Sec4ShortJumpEstimatesLargeP
public import VariationalSW.Auto.Sec5ShortJumpEstimatesSmallP
public import VariationalSW.Auto.MarcinkiewiczInterpolation
public import VariationalSW.Auto.HardyLittlewoodMaximal
public import VariationalSW.Auto.CalderonZygmund
public import VariationalSW.Auto.KhintchineInequality
public import VariationalSW.Auto.SteinInterpolation
public import VariationalSW.Auto.VectorValuedCalderonZygmund
public import VariationalSW.Auto.LepingleInequality
public import VariationalSW.Auto.FeffermanSteinInequality
public import VariationalSW.Auto.RestrictedTypeInterpolation
public import VariationalSW.Auto.LittlewoodPaleyInequality
public import VariationalSW.Auto.JonesSeegerWrightJumpInequality
public import VariationalSW.Auto.OscillatoryIntegralEstimates
public import VariationalSW.Auto.CarlesonSjolin
public import VariationalSW.Auto.SeegerLocalizedMultipliers
public import VariationalSW.Auto.SharpVariationNorm

/-!
# VariationalSW

This file was automatically generated by Claude.

Top-level import file of the library `VariationalSW`.
-/
