/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import VariationalSW.Auto.CalderonZygmund
public import VariationalSW.Auto.HardyLittlewoodMaximal
public import VariationalSW.Auto.MarcinkiewiczInterpolation

/-!
# The Fefferman–Stein vector-valued maximal inequality

This file was automatically generated by Claude.

This file proves the **Fefferman–Stein vector-valued maximal inequality** on `ℝⁿ` for the
`ℓ²` sum and `1 < p < ∞`. The statements of the main theorems depend on Mathlib and the local
definition `fsMaximal` only; the proofs use `VariationalSW.Auto.HardyLittlewoodMaximal`,
`VariationalSW.Auto.MarcinkiewiczInterpolation` and the dyadic Calderón–Zygmund selection of
`VariationalSW.Auto.CalderonZygmund`.

## Statement

* `fsMaximal n f x = sup_{r > 0} |B(x,r)|⁻¹ ∫_{B(x,r)} |f|` (centered closed balls, valued in
  `ℝ≥0∞`) for `f : EuclideanSpace ℝ (Fin n) → ℂ`; `fsMaximal_eq_hlMaximal` identifies it with
  `hlMaximal volume`.
* `fefferman_stein`: for `n ≥ 1` and `1 < p < ∞` there is `C : ℝ≥0` such that for every finite
  family `(fᵢ)_{i ∈ s}` of a.e. strongly measurable functions
  `‖(∑ᵢ (M fᵢ)²)^(1/2)‖_p ≤ C ‖(∑ᵢ |fᵢ|²)^(1/2)‖_p` (no integrability assumption; both sides
  may be infinite). `fefferman_stein_const` gives the explicit constant `fsConst n p ^ (1/p)`.
* `fs_lintegral_le`: the same in integral form for `F : ℝⁿ → EuclideanSpace ℂ ι`.

## Proof outline

* `p = 2` (`fs_lintegral_sum_sq_le`): sum of the scalar `L²` bounds of the Hardy–Littlewood
  maximal theorem.
* Weak type `(1,1)` (`fs_volume_lt_le`): `|{(∑ᵢ (M Fᵢ)²)^(1/2) > t}| ≤ C t⁻¹ ‖F‖₁`. Calderón–Zygmund
  selection of maximal dyadic cubes for `|F|_{ℓ²}` at height `t`; the modified functions `ũᵢ`
  (`fsGood`: `|Fᵢ|` off `Ω`, the average of `|Fᵢ|` over the selected cube on `Ω`) satisfy
  `M Fᵢ ≤ 2ⁿ M ũᵢ` off the enlarged set `Ω*` (a ball centered off `Ω*` that meets a selected
  cube `Q` contains `Q` after doubling, `fs_czCube_subset_closedBall`) and, by Minkowski's
  inequality for the `ℓ²` norm of averages (`fs_sum_sq_lintegral_le`),
  `∫ ∑ᵢ ũᵢ² ≤ 2ⁿ t ‖F‖₁`; conclude with the case `p = 2` and Chebyshev.
* `1 < p < 2` (`fs_lintegral_le_of_lt_two`): Marcinkiewicz interpolation of the truncated
  operators `F ↦ (min (M Fᵢ) N)ᵢ` (`fsTrunc`, values in `EuclideanSpace ℝ ι`) between weak `(1,1)`
  and strong `(2,2)`, then monotone convergence in `N`.
* `2 < p < ∞` (`fs_lintegral_le_of_two_lt`): the weighted inequality
  `∫ (M f)² |w| ≤ C ∫ |f|² M w` (`fs_weighted_sq`), obtained by Marcinkiewicz interpolation
  between the measures `M w dx` and `|w| dx` of the weighted weak type `(1,1)` bound
  (`fs_weighted_weak`, Vitali covering and `w(3B) ≤ 4ⁿ |B| inf_B M w`) and the trivial `L^∞`
  bound; then duality with `r = p/2`: testing `G = ∑ᵢ (M Fᵢ)²` against `w = G_N^{r-1}` for the
  bounded, compactly supported truncations `G_N` of `G`, Hölder's inequality and the scalar
  maximal theorem in `L^{r'}` give `∫ G_N^r ≤ C^r ∫ |F|^{2r}`; monotone convergence.

## References

* C. Fefferman and E. M. Stein, *Some maximal inequalities*, Amer. J. Math. **93** (1971),
  107–115.
* E. M. Stein, *Harmonic Analysis: Real-Variable Methods, Orthogonality, and Oscillatory
  Integrals*, Princeton University Press, 1993, Chapter II, §1.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, §5.6.
-/

@[expose] public section

namespace Auto

open MeasureTheory Metric Set Filter Topology
open scoped ENNReal NNReal

noncomputable section

/-! ### The maximal function and preliminaries -/

/-- The centered Hardy–Littlewood maximal function on `ℝⁿ = EuclideanSpace ℝ (Fin n)` over
closed balls of positive radius, valued in `ℝ≥0∞`:
`fsMaximal n f x = sup_{r > 0} |B(x,r)|⁻¹ ∫_{B(x,r)} |f|`. -/
def fsMaximal (n : ℕ) (f : EuclideanSpace ℝ (Fin n) → ℂ) (x : EuclideanSpace ℝ (Fin n)) :
    ℝ≥0∞ :=
  ⨆ (r : ℝ) (_ : 0 < r), (volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ

section Prelim

variable {n : ℕ}

lemma fs_hfin (x : EuclideanSpace ℝ (Fin n)) (r : ℝ) : volume (closedBall x r) ≠ ∞ :=
  measure_closedBall_lt_top.ne

/-- `fsMaximal` agrees with the maximal function `hlMaximal volume` of
`VariationalSW.Auto.HardyLittlewoodMaximal` (which also allows radii `r ≤ 0`). -/
theorem fsMaximal_eq_hlMaximal (f : EuclideanSpace ℝ (Fin n) → ℂ) :
    fsMaximal n f = hlMaximal volume f := by
  funext x
  refine le_antisymm (iSup₂_le fun r _ => hlBallAverage_le_hlMaximal volume f x r)
    (iSup_le fun r => ?_)
  rcases lt_trichotomy r 0 with hr | rfl | hr
  · rw [hlBallAverage_of_neg _ _ _ hr]
    exact zero_le
  · refine (hlBallAverage_le_iSup_rat_gt fs_hfin f x 0).trans (iSup₂_le fun q hq => ?_)
    exact le_iSup₂_of_le (f := fun (r : ℝ) (_ : 0 < r) =>
      (volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ) (q : ℝ) hq le_rfl
  · exact le_iSup₂_of_le (f := fun (r : ℝ) (_ : 0 < r) =>
      (volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ) r hr le_rfl

/-- Scaling of the volume of Euclidean balls. -/
lemma fs_volume_closedBall_mul (x : EuclideanSpace ℝ (Fin n)) {c r : ℝ} (hc : 0 ≤ c)
    (hr : 0 ≤ r) :
    volume (closedBall x (c * r)) = ENNReal.ofReal (c ^ n) * volume (closedBall x r) := by
  rw [Measure.addHaar_closedBall _ _ (mul_nonneg hc hr), Measure.addHaar_closedBall _ _ hr,
    finrank_euclideanSpace_fin, mul_pow, ENNReal.ofReal_mul (pow_nonneg hc _), mul_assoc]

lemma fs_doubling (x : EuclideanSpace ℝ (Fin n)) (r : ℝ) (hr : 0 ≤ r) :
    volume (closedBall x (3 * r)) ≤ ((3 ^ n : ℝ≥0) : ℝ≥0∞) * volume (closedBall x r) := by
  rw [fs_volume_closedBall_mul x (by norm_num) hr]
  apply le_of_eq
  congr 1
  rw [ENNReal.ofReal_pow (by norm_num)]
  simp

lemma fs_measurable_maximal {E : Type*} [NormedAddCommGroup E]
    {f : EuclideanSpace ℝ (Fin n) → E} (hf : AEStronglyMeasurable f volume) :
    Measurable (hlMaximal volume f) :=
  measurable_hlMaximal fs_hfin hf

/-- The constant of the Hardy–Littlewood maximal theorem in integral form. -/
def fsK (n : ℕ) (q : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal (2 ^ q * q * ((3 ^ n : ℝ≥0) : ℝ) / (q - 1))

lemma fsK_ne_top (n : ℕ) (q : ℝ) : fsK n q ≠ ∞ := ENNReal.ofReal_ne_top

/-- The Hardy–Littlewood maximal theorem on `ℝⁿ` in integral form:
`∫ (M f)^q ≤ K ∫ ‖f‖^q` for `1 < q < ∞`. -/
theorem fs_lintegral_maximal_rpow_le {E : Type*} [NormedAddCommGroup E] {q : ℝ} (hq : 1 < q)
    {f : EuclideanSpace ℝ (Fin n) → E} (hf : AEStronglyMeasurable f volume) :
    ∫⁻ x, hlMaximal volume f x ^ q ≤ fsK n q * ∫⁻ x, ‖f x‖ₑ ^ q :=
  lintegral_hlMaximal_rpow_le_of_weak hq
    (fun _ hg t => hlMaximal_weak_one fs_hfin fs_doubling hg t) hf
    (fs_measurable_maximal hf).aemeasurable

/-- The `L²` case in integral form, with natural powers. -/
theorem fs_lintegral_maximal_sq_le {E : Type*} [NormedAddCommGroup E]
    {f : EuclideanSpace ℝ (Fin n) → E} (hf : AEStronglyMeasurable f volume) :
    ∫⁻ x, hlMaximal volume f x ^ 2 ≤ fsK n 2 * ∫⁻ x, ‖f x‖ₑ ^ 2 := by
  have h := fs_lintegral_maximal_rpow_le (q := 2) one_lt_two hf
  simp only [ENNReal.rpow_two] at h
  exact h

end Prelim

section Euclid

variable {𝕜 : Type*} [RCLike 𝕜] {ι : Type*} [Fintype ι]

lemma fs_enorm_sq_euclidean (v : EuclideanSpace 𝕜 ι) : ‖v‖ₑ ^ 2 = ∑ i, ‖v i‖ₑ ^ 2 := by
  simp only [enorm_eq_nnnorm, EuclideanSpace.nnnorm_eq, ← ENNReal.coe_pow, NNReal.sq_sqrt,
    ENNReal.ofNNReal_finsetSum]

lemma fs_enorm_euclidean (v : EuclideanSpace 𝕜 ι) :
    ‖v‖ₑ = (∑ i, ‖v i‖ₑ ^ 2) ^ (1 / 2 : ℝ) := by
  rw [← fs_enorm_sq_euclidean, ← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]
  norm_num

lemma fs_enorm_apply_le (v : EuclideanSpace 𝕜 ι) (i : ι) : ‖v i‖ₑ ≤ ‖v‖ₑ := by
  simp only [enorm_eq_nnnorm, ENNReal.coe_le_coe]
  exact PiLp.nnnorm_apply_le v i

/-- Componentwise monotonicity of the Euclidean norm. -/
lemma fs_norm_le_of_le {v w : EuclideanSpace ℝ ι} (h0 : ∀ i, 0 ≤ v i) (h : ∀ i, v i ≤ w i) :
    ‖v‖ ≤ ‖w‖ := by
  rw [EuclideanSpace.norm_eq, EuclideanSpace.norm_eq]
  refine Real.sqrt_le_sqrt (Finset.sum_le_sum fun i _ => ?_)
  simp only [Real.norm_eq_abs, sq_abs]
  exact pow_le_pow_left₀ (h0 i) (h i) 2

end Euclid

/-! ### Weak type `(1,1)` of the vector-valued maximal operator -/

section Weak

variable {n : ℕ} {ι : Type*} [Fintype ι]

omit [Fintype ι] in
lemma fs_measurable_apply {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι}
    (hF : Measurable F) (i : ι) : Measurable fun y => F y i :=
  (measurable_pi_apply i).comp ((MeasurableEquiv.toLp 2 (ι → ℂ)).symm.measurable.comp hF)

/-- The pointwise `ℓ²` norm of `F`, as a complex function. -/
def fsNormC (F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι) :
    EuclideanSpace ℝ (Fin n) → ℂ :=
  fun y => ((‖F y‖ : ℝ) : ℂ)

@[simp]
lemma enorm_fsNormC (F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι)
    (y : EuclideanSpace ℝ (Fin n)) : ‖fsNormC F y‖ₑ = ‖F y‖ₑ := by
  rw [fsNormC, ← ofReal_norm, ← ofReal_norm, Complex.norm_real, norm_norm]

/-- The average of `‖h‖` over the dyadic cube with index `p`, valued in `ℝ≥0∞`. -/
def fsCubeAvg (h : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℤ × (Fin n → ℤ)) : ℝ≥0∞ :=
  (volume (czCube p))⁻¹ * ∫⁻ y in czCube p, ‖h y‖ₑ

lemma fsCubeAvg_mul_volume (h : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℤ × (Fin n → ℤ)) :
    fsCubeAvg h p * volume (czCube p) = ∫⁻ y in czCube p, ‖h y‖ₑ := by
  rw [fsCubeAvg, mul_comm, ← mul_assoc,
    ENNReal.mul_inv_cancel (volume_czCube_ne_zero p) (volume_czCube_ne_top p), one_mul]

open Classical in
/-- The modified function of the Fefferman–Stein argument: `‖h‖` off the Calderón–Zygmund
exceptional set `Ω` of `g` at height `s`, and the average of `‖h‖` over the selected cube on
`Ω`. -/
def fsGood (g : EuclideanSpace ℝ (Fin n) → ℂ) (s : ℝ) (h : EuclideanSpace ℝ (Fin n) → ℂ) :
    EuclideanSpace ℝ (Fin n) → ℝ≥0∞ :=
  (czBadSet g s).piecewise (fun x => fsCubeAvg h (czSel g s x)) (fun x => ‖h x‖ₑ)

variable {g h : EuclideanSpace ℝ (Fin n) → ℂ} {s : ℝ}

lemma fsGood_of_notMem {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czBadSet g s) :
    fsGood g s h x = ‖h x‖ₑ := by
  classical
  simp [fsGood, Set.piecewise_eq_of_notMem _ _ _ hx]

lemma fsGood_of_mem {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ czBadSet g s) :
    fsGood g s h x = fsCubeAvg h (czSel g s x) := by
  classical
  simp [fsGood, Set.piecewise_eq_of_mem _ _ _ hx]

section CZ

variable (hn : 0 < n) (hs : 0 < s) (hg : ∫⁻ y, ‖g y‖ₑ ≠ ∞)
include hn hs hg

lemma fsGood_of_mem_czCube {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx g s)
    {y : EuclideanSpace ℝ (Fin n)} (hy : y ∈ czCube p) : fsGood g s h y = fsCubeAvg h p := by
  obtain ⟨hyΩ, hsel⟩ := czSel_eq_of_mem_czIdx hn hs hg hp hy
  rw [fsGood_of_mem hyΩ, hsel]

lemma measurable_fsGood (hh : Measurable fun y => ‖h y‖ₑ) : Measurable (fsGood g s h) := by
  classical
  intro U hU
  have hA : (fun x => fsCubeAvg h (czSel g s x)) ⁻¹' U ∩ czBadSet g s =
      ⋃ p ∈ czIdx g s ∩ {p | fsCubeAvg h p ∈ U}, czCube p := by
    ext x
    simp only [mem_inter_iff, mem_preimage, mem_iUnion, exists_prop, mem_ofPred_eq]
    constructor
    · rintro ⟨hxU, hx⟩
      exact ⟨czSel g s x, ⟨⟨x, hx, rfl⟩, hxU⟩, mem_czCube_self _ x⟩
    · rintro ⟨p, ⟨hp, hpU⟩, hx⟩
      obtain ⟨hxΩ, hsel⟩ := czSel_eq_of_mem_czIdx hn hs hg hp hx
      exact ⟨by rw [hsel]; exact hpU, hxΩ⟩
  have hΩ := measurableSet_czBadSet hn hs hg
  rw [fsGood, Set.piecewise_preimage, Set.ite]
  refine MeasurableSet.union ?_ ((hh hU).diff hΩ)
  rw [hA]; exact measurableSet_biUnion_czCube _

lemma fsCubeAvg_le_of_le (hle : ∀ y, ‖h y‖ₑ ≤ ‖g y‖ₑ) {p : ℤ × (Fin n → ℤ)}
    (hp : p ∈ czIdx g s) : fsCubeAvg h p ≤ 2 ^ n * ENNReal.ofReal s := by
  have h1 : fsCubeAvg h p * volume (czCube p) ≤
      2 ^ n * ENNReal.ofReal s * volume (czCube p) := by
    rw [fsCubeAvg_mul_volume]
    exact (lintegral_mono fun y => hle y).trans (setLIntegral_czCube_le hn hs hg hp)
  exact (ENNReal.mul_le_mul_iff_left (volume_czCube_ne_zero p) (volume_czCube_ne_top p)).1 h1

lemma fsGood_ne_top (hle : ∀ y, ‖h y‖ₑ ≤ ‖g y‖ₑ) (x : EuclideanSpace ℝ (Fin n)) :
    fsGood g s h x ≠ ∞ := by
  by_cases hx : x ∈ czBadSet g s
  · rw [fsGood_of_mem hx]
    exact ne_top_of_le_ne_top (ENNReal.mul_ne_top (ENNReal.pow_ne_top ENNReal.ofNat_ne_top)
      ENNReal.ofReal_ne_top) (fsCubeAvg_le_of_le hn hs hg hle ⟨x, hx, rfl⟩)
  · rw [fsGood_of_notMem hx]
    exact enorm_ne_top

omit hn hs hg in
/-- Geometry of the enlarged exceptional set: if `x ∉ Ω*` and the closed ball `B(x,r)` meets a
selected cube `Q`, then `Q ⊆ B(x, 2r)`. -/
lemma fs_czCube_subset_closedBall {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czStar g s)
    {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx g s) {r : ℝ} {z : EuclideanSpace ℝ (Fin n)}
    (hzQ : z ∈ czCube p) (hzB : z ∈ closedBall x r) : czCube p ⊆ closedBall x (2 * r) := by
  set ℓ := Real.sqrt n * (2 : ℝ) ^ p.1
  have hfar : 2 * ℓ < dist x (czCorner p) := by
    by_contra hle
    push Not at hle
    exact hx (mem_biUnion hp (mem_closedBall.2 hle))
  have hz1 : dist z (czCorner p) ≤ ℓ := by
    rw [dist_eq_norm]; exact norm_sub_le_of_mem_czCube hzQ (czCorner_mem p)
  have hzx : dist z x ≤ r := mem_closedBall.1 hzB
  have hℓr : ℓ < r := by
    have := dist_triangle x z (czCorner p)
    rw [dist_comm x z] at this
    linarith
  intro y hy
  have hyz : dist y z ≤ ℓ := by rw [dist_eq_norm]; exact norm_sub_le_of_mem_czCube hy hzQ
  rw [mem_closedBall]
  linarith [dist_triangle y z x]

/-- The key comparison: for `x ∉ Ω*`, `∫_{B(x,r)} ‖h‖ ≤ ∫_{B(x,2r)} ũ`. -/
lemma fs_setLIntegral_closedBall_le {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czStar g s)
    (r : ℝ) :
    ∫⁻ y in closedBall x r, ‖h y‖ₑ ≤ ∫⁻ y in closedBall x (2 * r), fsGood g s h y := by
  rcases lt_or_ge r 0 with hr | hr
  · rw [closedBall_eq_empty.2 hr]
    simp
  have hBB : closedBall x r ⊆ closedBall x (2 * r) := closedBall_subset_closedBall (by linarith)
  have hΩ := measurableSet_czBadSet hn hs hg
  rw [← lintegral_indicator measurableSet_closedBall,
    ← lintegral_indicator measurableSet_closedBall, ← lintegral_add_compl _ hΩ,
    ← lintegral_add_compl (fun y => (closedBall x (2 * r)).indicator (fsGood g s h) y) hΩ]
  refine add_le_add ?_ ?_
  · rw [czBadSet_eq_biUnion hn hs hg, lintegral_biUnion czIdx_countable
      (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hg),
      lintegral_biUnion czIdx_countable
      (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hg)]
    refine ENNReal.tsum_le_tsum fun p => ?_
    by_cases hQ : ∃ z ∈ czCube (p : ℤ × (Fin n → ℤ)), z ∈ closedBall x r
    · obtain ⟨z, hzQ, hzB⟩ := hQ
      have hsub := fs_czCube_subset_closedBall hx p.2 hzQ hzB
      calc ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)),
            (closedBall x r).indicator (fun y => ‖h y‖ₑ) y
          ≤ ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖h y‖ₑ :=
            lintegral_mono fun y => indicator_le_self _ _ y
        _ = fsCubeAvg h p * volume (czCube (p : ℤ × (Fin n → ℤ))) :=
            (fsCubeAvg_mul_volume h p).symm
        _ = ∫⁻ _ in czCube (p : ℤ × (Fin n → ℤ)), fsCubeAvg h p :=
            (setLIntegral_const _ _).symm
        _ = _ := by
            refine setLIntegral_congr_fun (measurableSet_czCube _) fun y hy => ?_
            rw [indicator_of_mem (hsub hy), fsGood_of_mem_czCube hn hs hg p.2 hy]
    · push Not at hQ
      have h0 : ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)),
          (closedBall x r).indicator (fun y => ‖h y‖ₑ) y = 0 := by
        rw [setLIntegral_congr_fun (measurableSet_czCube _) fun y hy =>
          indicator_of_notMem (hQ y hy) _]
        simp
      rw [h0]
      exact zero_le
  · refine setLIntegral_mono' hΩ.compl fun y hy => ?_
    by_cases hyB : y ∈ closedBall x r
    · rw [indicator_of_mem hyB, indicator_of_mem (hBB hyB), fsGood_of_notMem hy]
    · rw [indicator_of_notMem hyB]
      exact zero_le

/-- Pointwise comparison of maximal functions off `Ω*`: `M h ≤ 2ⁿ M ũ`. -/
lemma fs_hlMaximal_le_of_notMem_czStar (hle : ∀ y, ‖h y‖ₑ ≤ ‖g y‖ₑ)
    {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czStar g s) :
    hlMaximal volume h x ≤
      2 ^ n * hlMaximal volume (fun y => (fsGood g s h y).toReal) x := by
  refine iSup_le fun r => ?_
  rcases lt_or_ge r 0 with hr | hr
  · rw [hlBallAverage_of_neg _ _ _ hr]
    exact zero_le
  refine le_trans ?_ (mul_le_mul_right (hlBallAverage_le_hlMaximal _ _ x (2 * r)) _)
  have henorm : ∀ y, ‖(fsGood g s h y).toReal‖ₑ = fsGood g s h y := fun y => by
    rw [Real.enorm_eq_ofReal ENNReal.toReal_nonneg,
      ENNReal.ofReal_toReal (fsGood_ne_top hn hs hg hle y)]
  have hvol : volume (closedBall x (2 * r)) = 2 ^ n * volume (closedBall x r) := by
    rw [fs_volume_closedBall_mul x (by norm_num) hr, ENNReal.ofReal_pow (by norm_num)]
    simp
  unfold hlBallAverage
  simp only [henorm]
  rw [hvol, ENNReal.mul_inv (Or.inl (pow_ne_zero _ two_ne_zero))
    (Or.inl (ENNReal.pow_ne_top ENNReal.ofNat_ne_top)), ← mul_assoc, ← mul_assoc,
    ENNReal.mul_inv_cancel (pow_ne_zero _ two_ne_zero) (ENNReal.pow_ne_top ENNReal.ofNat_ne_top),
    one_mul]
  exact mul_le_mul_right (fs_setLIntegral_closedBall_le hn hs hg hx r) _

end CZ

/-- Minkowski's integral inequality for the `ℓ²` norm, squared:
`∑ᵢ (∫ ‖Fᵢ‖)² ≤ (∫ ‖F‖)²`. -/
lemma fs_sum_sq_lintegral_le {α : Type*} [MeasurableSpace α] (μ : Measure α)
    {F : α → EuclideanSpace ℂ ι} (hF : ∀ i, AEMeasurable (fun y => ‖F y i‖ₑ) μ)
    (hfin : ∫⁻ y, ‖F y‖ₑ ∂μ ≠ ∞) :
    ∑ i, (∫⁻ y, ‖F y i‖ₑ ∂μ) ^ 2 ≤ (∫⁻ y, ‖F y‖ₑ ∂μ) ^ 2 := by
  set B := ∫⁻ y, ‖F y‖ₑ ∂μ
  set b : ι → ℝ≥0∞ := fun i => ∫⁻ y, ‖F y i‖ₑ ∂μ
  have hb : ∀ i, b i ≠ ∞ := fun i =>
    ne_top_of_le_ne_top hfin (lintegral_mono fun y => fs_enorm_apply_le (F y) i)
  set S := ∑ i, b i ^ 2
  have hStop : S ≠ ∞ := ENNReal.sum_ne_top.2 fun i _ => ENNReal.pow_ne_top (hb i)
  set σ := S ^ (1 / 2 : ℝ)
  have hσtop : σ ≠ ∞ := ENNReal.rpow_ne_top_of_nonneg (by norm_num) hStop
  have hσS : σ ^ 2 = S := by
    rw [← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]; norm_num
  have hS : S ≤ σ * B := by
    calc S = ∑ i, b i * b i := by simp only [S, sq]
      _ = ∫⁻ y, ∑ i, b i * ‖F y i‖ₑ ∂μ := by
          rw [lintegral_finsetSum' _ fun i _ => (hF i).const_mul _]
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [lintegral_const_mul' _ _ (hb i)]
      _ ≤ ∫⁻ y, σ * ‖F y‖ₑ ∂μ := by
          refine lintegral_mono fun y => ?_
          have := ENNReal.inner_le_Lp_mul_Lq Finset.univ b (fun i => ‖F y i‖ₑ)
            Real.HolderConjugate.two_two
          simp only [ENNReal.rpow_two] at this
          rw [fs_enorm_euclidean (F y)]
          exact this
      _ = σ * B := lintegral_const_mul' _ _ hσtop
  by_cases hσ0 : σ = 0
  · rw [← hσS, hσ0]
    simp
  have h1 : σ * σ ≤ B * σ := by
    rw [← sq, hσS, mul_comm B]
    exact hS
  have h2 : σ ≤ B := (ENNReal.mul_le_mul_iff_left hσ0 hσtop).1 h1
  rw [← hσS]
  exact pow_le_pow_left₀ zero_le h2 2

/-- The `L²` estimate of the modified functions: `∫ ∑ᵢ ũᵢ² ≤ 2ⁿ s ∫ ‖F‖`. -/
lemma fs_lintegral_sum_sq_fsGood_le (hn : 0 < n) {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι}
    (hF : Measurable F) (hint : Integrable (fsNormC F)) (hs : 0 < s) :
    ∫⁻ y, ∑ i, fsGood (fsNormC F) s (fun z => F z i) y ^ 2 ≤
      2 ^ n * ENNReal.ofReal s * ∫⁻ y, ‖F y‖ₑ := by
  set g := fsNormC F
  have hgF : ∀ y, ‖g y‖ₑ = ‖F y‖ₑ := enorm_fsNormC F
  have hg : ∫⁻ y, ‖g y‖ₑ ≠ ∞ := hint.2.ne
  have hFfin : ∫⁻ y, ‖F y‖ₑ ≠ ∞ := by simpa [hgF] using hg
  have hΩ := measurableSet_czBadSet hn hs hg
  rw [← lintegral_add_compl _ hΩ, ← lintegral_add_compl (fun y => ‖F y‖ₑ) hΩ, mul_add]
  refine add_le_add ?_ ?_
  · rw [czBadSet_eq_biUnion hn hs hg, lintegral_biUnion czIdx_countable
      (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hg),
      lintegral_biUnion czIdx_countable
      (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hg),
      ← ENNReal.tsum_mul_left]
    refine ENNReal.tsum_le_tsum fun p => ?_
    have hp := p.2
    rw [setLIntegral_congr_fun
      (g := fun _ => ∑ i, fsCubeAvg (fun z => F z i) (p : ℤ × (Fin n → ℤ)) ^ 2)
      (measurableSet_czCube _) fun y hy => by
      simp only [fsGood_of_mem_czCube hn hs hg hp hy], setLIntegral_const]
    set A := fsCubeAvg g p
    have hA : A ≤ 2 ^ n * ENNReal.ofReal s := fsCubeAvg_le_of_le hn hs hg (fun y => le_rfl) hp
    have hfinQ : ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖F y‖ₑ ≠ ∞ :=
      ne_top_of_le_ne_top hFfin (setLIntegral_le_lintegral _ _)
    have hmink : ∑ i, fsCubeAvg (fun z => F z i) p ^ 2 ≤ A ^ 2 := by
      simp only [A, fsCubeAvg, mul_pow, ← Finset.mul_sum, hgF]
      exact mul_le_mul_right (fs_sum_sq_lintegral_le _
        (fun i => (fs_measurable_apply hF i).enorm.aemeasurable) hfinQ) _
    calc (∑ i, fsCubeAvg (fun z => F z i) p ^ 2) * volume (czCube (p : ℤ × (Fin n → ℤ)))
        ≤ A ^ 2 * volume (czCube (p : ℤ × (Fin n → ℤ))) := by gcongr
      _ = A * (A * volume (czCube (p : ℤ × (Fin n → ℤ)))) := by ring
      _ ≤ (2 ^ n * ENNReal.ofReal s) * (A * volume (czCube (p : ℤ × (Fin n → ℤ)))) := by
          gcongr
      _ = 2 ^ n * ENNReal.ofReal s * ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖F y‖ₑ := by
          rw [fsCubeAvg_mul_volume]
          simp only [hgF]
  · rw [← lintegral_const_mul' _ _ (by finiteness)]
    refine lintegral_mono_ae ((ae_restrict_iff' hΩ.compl).2 ?_)
    filter_upwards [ae_enorm_le_of_notMem_czBadSet hn (s := s) hint] with y hy hyΩ
    have hyΩ' : y ∉ czBadSet g s := hyΩ
    simp only [fsGood_of_notMem hyΩ']
    rw [← fs_enorm_sq_euclidean, sq]
    have hy' := hy hyΩ'
    rw [hgF] at hy'
    calc ‖F y‖ₑ * ‖F y‖ₑ ≤ ENNReal.ofReal s * ‖F y‖ₑ := mul_le_mul_left hy' _
      _ ≤ 2 ^ n * ENNReal.ofReal s * ‖F y‖ₑ := by
          gcongr
          exact le_mul_of_one_le_left zero_le (one_le_pow₀ one_le_two)

/-- The constant of the weak type `(1,1)` bound of the vector-valued maximal operator. -/
def fsWeakC (n : ℕ) : ℝ≥0∞ := ENNReal.ofReal ((4 * Real.sqrt n) ^ n) + 8 ^ n * fsK n 2

lemma fsWeakC_ne_top (n : ℕ) : fsWeakC n ≠ ∞ :=
  ENNReal.add_ne_top.2 ⟨ENNReal.ofReal_ne_top,
    ENNReal.mul_ne_top (ENNReal.pow_ne_top ENNReal.ofNat_ne_top) (fsK_ne_top _ _)⟩

/-- **Weak type `(1,1)` of the vector-valued maximal operator** (Fefferman–Stein), for measurable
`F` with `∫ ‖F‖ < ∞`: `|{x | t² < ∑ᵢ (M Fᵢ x)²}| ≤ C t⁻¹ ∫ ‖F‖`. -/
theorem fs_volume_lt_le_of_measurable (hn : 0 < n)
    {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι} (hF : Measurable F)
    (hfin : ∫⁻ y, ‖F y‖ₑ ≠ ∞) {t : ℝ} (ht : 0 < t) :
    volume {x | ENNReal.ofReal t ^ 2 < ∑ i, hlMaximal volume (fun y => F y i) x ^ 2} ≤
      fsWeakC n * (ENNReal.ofReal t)⁻¹ * ∫⁻ y, ‖F y‖ₑ := by
  set g := fsNormC F
  have hgF : ∀ y, ‖g y‖ₑ = ‖F y‖ₑ := enorm_fsNormC F
  have hgm : Measurable g := Complex.measurable_ofReal.comp hF.norm
  have hint : Integrable g := ⟨hgm.aestronglyMeasurable, by
    simp only [HasFiniteIntegral, hgF]; exact hfin.lt_top⟩
  have hg : ∫⁻ y, ‖g y‖ₑ ≠ ∞ := hint.2.ne
  set τ := ENNReal.ofReal t
  have hτ0 : τ ≠ 0 := (ENNReal.ofReal_pos.2 ht).ne'
  have hτt : τ ≠ ∞ := ENNReal.ofReal_ne_top
  set u : ι → EuclideanSpace ℝ (Fin n) → ℝ := fun i y => (fsGood g t (fun z => F z i) y).toReal
  have hle : ∀ i y, ‖F y i‖ₑ ≤ ‖g y‖ₑ := fun i y => by
    rw [hgF]; exact fs_enorm_apply_le _ _
  have hum : ∀ i, Measurable (u i) := fun i =>
    (measurable_fsGood hn ht hg (fs_measurable_apply hF i).enorm).ennreal_toReal
  have hu_enorm : ∀ i y, ‖u i y‖ₑ = fsGood g t (fun z => F z i) y := fun i y => by
    rw [Real.enorm_eq_ofReal ENNReal.toReal_nonneg,
      ENNReal.ofReal_toReal (fsGood_ne_top hn ht hg (hle i) y)]
  set G : EuclideanSpace ℝ (Fin n) → ℝ≥0∞ := fun x => 4 ^ n * ∑ i, hlMaximal volume (u i) x ^ 2
  have hsub : {x | τ ^ 2 < ∑ i, hlMaximal volume (fun y => F y i) x ^ 2} ⊆
      czStar g t ∪ {x | τ ^ 2 ≤ G x} := by
    intro x hx
    by_cases hxs : x ∈ czStar g t
    · exact Or.inl hxs
    · refine Or.inr (show τ ^ 2 ≤ G x from le_of_lt (lt_of_lt_of_le hx ?_))
      simp only [G, Finset.mul_sum]
      refine Finset.sum_le_sum fun i _ => ?_
      calc hlMaximal volume (fun y => F y i) x ^ 2 ≤ (2 ^ n * hlMaximal volume (u i) x) ^ 2 :=
            pow_le_pow_left₀ zero_le (fs_hlMaximal_le_of_notMem_czStar hn ht hg (hle i) hxs) 2
        _ = 4 ^ n * hlMaximal volume (u i) x ^ 2 := by
            rw [mul_pow, ← pow_mul, mul_comm n 2, pow_mul]
            norm_num
  have hstar : volume (czStar g t) ≤
      ENNReal.ofReal ((4 * Real.sqrt n) ^ n) * τ⁻¹ * ∫⁻ y, ‖F y‖ₑ := by
    refine (volume_czStar_le hn ht hg).trans ?_
    rw [mul_assoc]
    gcongr
    simpa [hgF] using volume_czBadSet_le hn ht hg
  have hMm : ∀ i, Measurable fun x => hlMaximal volume (u i) x ^ 2 := fun i =>
    (fs_measurable_maximal (hum i).aestronglyMeasurable).pow_const 2
  have hGint : ∫⁻ x, G x ≤ 8 ^ n * fsK n 2 * τ * ∫⁻ y, ‖F y‖ₑ := by
    calc ∫⁻ x, G x = 4 ^ n * ∑ i, ∫⁻ x, hlMaximal volume (u i) x ^ 2 := by
          rw [lintegral_const_mul' _ _ (by finiteness),
            lintegral_finsetSum' _ fun i _ => (hMm i).aemeasurable]
      _ ≤ 4 ^ n * ∑ i, fsK n 2 * ∫⁻ x, ‖u i x‖ₑ ^ 2 := by
          gcongr with i
          exact fs_lintegral_maximal_sq_le (hum i).aestronglyMeasurable
      _ = 4 ^ n * fsK n 2 * ∫⁻ x, ∑ i, fsGood g t (fun z => F z i) x ^ 2 := by
          rw [mul_assoc, ← Finset.mul_sum, lintegral_finsetSum' _ fun i _ =>
            ((measurable_fsGood hn ht hg (fs_measurable_apply hF i).enorm).pow_const
              2).aemeasurable]
          simp only [hu_enorm]
      _ ≤ 4 ^ n * fsK n 2 * (2 ^ n * τ * ∫⁻ y, ‖F y‖ₑ) := by
          gcongr
          exact fs_lintegral_sum_sq_fsGood_le hn hF hint ht
      _ = 8 ^ n * fsK n 2 * τ * ∫⁻ y, ‖F y‖ₑ := by
          rw [show (8 : ℝ≥0∞) ^ n = 4 ^ n * 2 ^ n by rw [← mul_pow]; norm_num]
          ring
  have hGm : AEMeasurable G :=
    (Measurable.const_mul (Finset.measurable_sum _ fun i _ => hMm i) _).aemeasurable
  have harith : 8 ^ n * fsK n 2 * τ * (∫⁻ y, ‖F y‖ₑ) / τ ^ 2 =
      8 ^ n * fsK n 2 * τ⁻¹ * ∫⁻ y, ‖F y‖ₑ := by
    rw [div_eq_mul_inv, pow_two, ENNReal.mul_inv (Or.inl hτ0) (Or.inl hτt)]
    calc 8 ^ n * fsK n 2 * τ * (∫⁻ y, ‖F y‖ₑ) * (τ⁻¹ * τ⁻¹) =
          8 ^ n * fsK n 2 * τ⁻¹ * (∫⁻ y, ‖F y‖ₑ) * (τ * τ⁻¹) := by ring
      _ = _ := by rw [ENNReal.mul_inv_cancel hτ0 hτt, mul_one]
  calc volume {x | τ ^ 2 < ∑ i, hlMaximal volume (fun y => F y i) x ^ 2}
      ≤ volume (czStar g t) + volume {x | τ ^ 2 ≤ G x} :=
        (measure_mono hsub).trans (measure_union_le _ _)
    _ ≤ ENNReal.ofReal ((4 * Real.sqrt n) ^ n) * τ⁻¹ * (∫⁻ y, ‖F y‖ₑ) +
          (∫⁻ x, G x) / τ ^ 2 :=
        add_le_add hstar (meas_ge_le_lintegral_div hGm (pow_ne_zero 2 hτ0)
          (ENNReal.pow_ne_top hτt))
    _ ≤ ENNReal.ofReal ((4 * Real.sqrt n) ^ n) * τ⁻¹ * (∫⁻ y, ‖F y‖ₑ) +
          8 ^ n * fsK n 2 * τ * (∫⁻ y, ‖F y‖ₑ) / τ ^ 2 := by gcongr
    _ = fsWeakC n * τ⁻¹ * ∫⁻ y, ‖F y‖ₑ := by
        rw [harith, fsWeakC]
        ring

/-- **Weak type `(1,1)` of the vector-valued maximal operator** (Fefferman–Stein), for a.e.
strongly measurable `F` with `∫ ‖F‖ < ∞`: `|{x | t² < ∑ᵢ (M Fᵢ x)²}| ≤ C t⁻¹ ∫ ‖F‖`. -/
theorem fs_volume_lt_le (hn : 0 < n)
    {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι} (hF : AEStronglyMeasurable F volume)
    (hfin : ∫⁻ y, ‖F y‖ₑ ≠ ∞) {t : ℝ} (ht : 0 < t) :
    volume {x | ENNReal.ofReal t ^ 2 < ∑ i, hlMaximal volume (fun y => F y i) x ^ 2} ≤
      fsWeakC n * (ENNReal.ofReal t)⁻¹ * ∫⁻ y, ‖F y‖ₑ := by
  have hGG : F =ᵐ[volume] hF.mk F := hF.ae_eq_mk
  have hM : ∀ i, hlMaximal volume (fun y => F y i) = hlMaximal volume (fun y => hF.mk F y i) :=
    fun i => hlMaximal_congr_ae (hGG.mono fun y hy => by simp only [hy])
  have hint : ∫⁻ y, ‖F y‖ₑ = ∫⁻ y, ‖hF.mk F y‖ₑ :=
    lintegral_congr_ae (hGG.mono fun y hy => by simp only [hy])
  have key : ∀ x, ∑ i, hlMaximal volume (fun y => F y i) x ^ 2 =
      ∑ i, hlMaximal volume (fun y => hF.mk F y i) x ^ 2 :=
    fun x => Finset.sum_congr rfl fun i _ => by rw [hM i]
  simp only [key, hint]
  exact fs_volume_lt_le_of_measurable hn hF.stronglyMeasurable_mk.measurable (hint ▸ hfin) ht

end Weak

/-! ### The case `p = 2` and the case `1 < p < 2` (Marcinkiewicz interpolation) -/

section Interp

variable {n : ℕ} {ι : Type*} [Fintype ι]

omit [Fintype ι] in
lemma fs_aesm_apply {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι}
    (hF : AEStronglyMeasurable F volume) (i : ι) :
    AEStronglyMeasurable (fun y => F y i) volume :=
  (EuclideanSpace.proj i).continuous.comp_aestronglyMeasurable hF

/-- **The case `p = 2`**: `∫ ∑ᵢ (M Fᵢ)² ≤ K ∫ ‖F‖²`. -/
theorem fs_lintegral_sum_sq_le {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι}
    (hF : AEStronglyMeasurable F volume) :
    ∫⁻ x, ∑ i, hlMaximal volume (fun y => F y i) x ^ 2 ≤ fsK n 2 * ∫⁻ x, ‖F x‖ₑ ^ 2 := by
  rw [lintegral_finsetSum' _ fun i _ =>
    ((fs_measurable_maximal (fs_aesm_apply hF i)).pow_const 2).aemeasurable]
  simp only [fs_enorm_sq_euclidean]
  rw [lintegral_finsetSum' _ fun i _ => ((fs_aesm_apply hF i).enorm.pow_const 2),
    Finset.mul_sum]
  exact Finset.sum_le_sum fun i _ => fs_lintegral_maximal_sq_le (fs_aesm_apply hF i)

/-- The truncated vector-valued maximal operator `x ↦ (min (M Fᵢ x) N)ᵢ ∈ ℓ²`, to which the
Marcinkiewicz interpolation theorem is applied. -/
def fsTrunc (N : ℕ) (F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι)
    (x : EuclideanSpace ℝ (Fin n)) : EuclideanSpace ℝ ι :=
  WithLp.toLp 2 (fun i => (min (hlMaximal volume (fun y => F y i) x) N).toReal)

omit [Fintype ι] in
lemma enorm_fsTrunc_apply (N : ℕ) (F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι)
    (x : EuclideanSpace ℝ (Fin n)) (i : ι) :
    ‖fsTrunc N F x i‖ₑ = min (hlMaximal volume (fun y => F y i) x) N := by
  change ‖(min (hlMaximal volume (fun y => F y i) x) N).toReal‖ₑ = _
  rw [Real.enorm_eq_ofReal ENNReal.toReal_nonneg, ENNReal.ofReal_toReal]
  exact ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) (min_le_right _ _)

lemma enorm_fsTrunc_sq (N : ℕ) (F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι)
    (x : EuclideanSpace ℝ (Fin n)) :
    ‖fsTrunc N F x‖ₑ ^ 2 = ∑ i, min (hlMaximal volume (fun y => F y i) x) N ^ 2 := by
  rw [fs_enorm_sq_euclidean]
  simp only [enorm_fsTrunc_apply]

set_option linter.unusedFintypeInType false in
lemma aestronglyMeasurable_fsTrunc (N : ℕ) {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι}
    (hF : AEStronglyMeasurable F volume) : AEStronglyMeasurable (fsTrunc N F) volume :=
  ((MeasurableEquiv.toLp 2 (ι → ℝ)).measurable.comp (measurable_pi_iff.2 fun i =>
    ((fs_measurable_maximal (fs_aesm_apply hF i)).min measurable_const).ennreal_toReal))
    |>.aestronglyMeasurable

lemma fs_iSup_rpow_sum_min_sq (a : ι → ℝ≥0∞) {q : ℝ} (hq : 0 < q) :
    ⨆ N : ℕ, (∑ i, min (a i) N ^ 2) ^ q = (∑ i, a i ^ 2) ^ q := by
  have h1 : ∀ i, ⨆ N : ℕ, min (a i) N ^ 2 = a i ^ 2 := by
    intro i
    have h0 : ⨆ N : ℕ, min (a i) N = a i := by
      rw [← inf_iSup_eq, ENNReal.iSup_natCast]
      simp
    conv_rhs => rw [← h0]
    exact (Monotone.map_iSup_of_continuousAt (ENNReal.continuous_pow 2).continuousAt
      (fun _ _ h => pow_le_pow_left₀ zero_le h 2) (by simp)).symm
  have hmono : ∀ i, Monotone fun N : ℕ => min (a i) N ^ 2 := fun i _ _ h =>
    pow_le_pow_left₀ zero_le (min_le_min_left _ (Nat.cast_le.2 h)) 2
  have h2 : ⨆ N : ℕ, ∑ i, min (a i) N ^ 2 = ∑ i, a i ^ 2 := by
    rw [← ENNReal.finsetSum_iSup_of_monotone hmono]
    exact Finset.sum_congr rfl fun i _ => h1 i
  conv_rhs => rw [← h2]
  exact (Monotone.map_iSup_of_continuousAt ENNReal.continuous_rpow_const.continuousAt
    (ENNReal.monotone_rpow_of_nonneg hq.le) (ENNReal.zero_rpow_of_pos hq)).symm

lemma fsWeakC_pos (n : ℕ) : 0 < fsWeakC n := by
  have hK : 0 < fsK n 2 := ENNReal.ofReal_pos.2 (by norm_num)
  exact lt_of_lt_of_le (ENNReal.mul_pos (pow_ne_zero _ (by norm_num)) hK.ne')
    le_add_self

/-- The constant of the case `1 < p < 2`. -/
def fsC1 (n : ℕ) (p : ℝ) : ℝ≥0∞ :=
  ((marcinkiewiczConst 1 2 p : ℝ≥0∞) * ((fsWeakC n).toNNReal : ℝ≥0∞) ^ (1 - (2 - 2 / p)) *
    ((fsK n 2 ^ (1 / 2 : ℝ)).toNNReal : ℝ≥0∞) ^ (2 - 2 / p)) ^ p

lemma fsC1_ne_top (n : ℕ) {p : ℝ} (hp1 : 1 < p) (hp2 : p < 2) : fsC1 n p ≠ ∞ := by
  have hθ0 : 0 ≤ 2 - 2 / p := by
    rw [sub_nonneg, div_le_iff₀ (by linarith)]; linarith
  have hθ1 : 0 ≤ 1 - (2 - 2 / p) := by
    have : 2 / p < 2 := by rw [div_lt_iff₀ (by linarith)]; linarith
    have : 1 < 2 / p := by rw [lt_div_iff₀ (by linarith)]; linarith
    linarith
  refine ENNReal.rpow_ne_top_of_nonneg (by linarith) (ENNReal.mul_ne_top
    (ENNReal.mul_ne_top ENNReal.coe_ne_top
      (ENNReal.rpow_ne_top_of_nonneg hθ1 ENNReal.coe_ne_top))
    (ENNReal.rpow_ne_top_of_nonneg hθ0 ENNReal.coe_ne_top))

/-- **The case `1 < p < 2`**, by Marcinkiewicz interpolation between the weak type `(1,1)` bound
and the case `p = 2`. -/
theorem fs_lintegral_le_of_lt_two (hn : 0 < n) {p : ℝ} (hp1 : 1 < p) (hp2 : p < 2)
    {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι} (hF : AEStronglyMeasurable F volume) :
    ∫⁻ x, (∑ i, hlMaximal volume (fun y => F y i) x ^ 2) ^ (p / 2) ≤
      fsC1 n p * ∫⁻ x, ‖F x‖ₑ ^ p := by
  have hp0 : 0 < p := by linarith
  set D : Set (EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι) :=
    {G | AEStronglyMeasurable G volume} with hDdef
  have hD : IsTruncationClosed D := fun G hG s _ =>
    ⟨aestronglyMeasurable_indicator_lt_norm hG s, aestronglyMeasurable_indicator_norm_le hG s⟩
  set A : ℝ≥0 := (fsWeakC n).toNNReal
  have hA : (A : ℝ≥0∞) = fsWeakC n := ENNReal.coe_toNNReal (fsWeakC_ne_top n)
  set B : ℝ≥0 := (fsK n 2 ^ (1 / 2 : ℝ)).toNNReal
  have hB : (B : ℝ≥0∞) = fsK n 2 ^ (1 / 2 : ℝ) :=
    ENNReal.coe_toNNReal (ENNReal.rpow_ne_top_of_nonneg (by norm_num) (fsK_ne_top n 2))
  have key : ∀ N : ℕ, ∫⁻ x, (∑ i, min (hlMaximal volume (fun y => F y i) x) N ^ 2) ^ (p / 2) ≤
      fsC1 n p * ∫⁻ x, ‖F x‖ₑ ^ p := by
    intro N
    have hTA : HasWeakTypeOn (fsTrunc N) D 1 A volume volume := by
      refine hasWeakTypeOn_of_forall_real fun G hG t ht => ?_
      have hG' : AEStronglyMeasurable G volume := hG
      rw [ENNReal.ofReal_one, ENNReal.rpow_one, eLpNorm_one_eq_lintegral_enorm hG']
      by_cases hfin : ∫⁻ y, ‖G y‖ₑ = ∞
      · rw [hfin, ENNReal.mul_top (by rw [hA]; exact (fsWeakC_pos n).ne'),
          ENNReal.top_div_of_ne_top ENNReal.ofReal_ne_top]
        exact le_top
      have hw := fs_volume_lt_le hn hG' hfin ht
      refine (measure_mono fun x (hx : t < ‖fsTrunc N G x‖) => ?_).trans (hw.trans_eq ?_)
      · change ENNReal.ofReal t ^ 2 < ∑ i, hlMaximal volume (fun y => G y i) x ^ 2
        have h1 : ENNReal.ofReal t < ‖fsTrunc N G x‖ₑ := by
          rw [← ofReal_norm]
          exact (ENNReal.ofReal_lt_ofReal_iff_of_nonneg ht.le).2 hx
        calc ENNReal.ofReal t ^ 2 < ‖fsTrunc N G x‖ₑ ^ 2 := ENNReal.pow_lt_pow_left two_ne_zero h1
          _ = ∑ i, min (hlMaximal volume (fun y => G y i) x) N ^ 2 := enorm_fsTrunc_sq N G x
          _ ≤ _ := Finset.sum_le_sum fun i _ => pow_le_pow_left₀ zero_le (min_le_left _ _) 2
      · rw [hA, div_eq_mul_inv]
        ring
    have hTB : HasWeakTypeOn (fsTrunc N) D 2 B volume volume := by
      refine HasStrongTypeOn.hasWeakTypeOn two_pos fun G hG => ?_
      have hG' : AEStronglyMeasurable G volume := hG
      rw [eLpNorm_ofReal_eq_lintegral_rpow_enorm (aestronglyMeasurable_fsTrunc N hG') two_pos,
        eLpNorm_ofReal_eq_lintegral_rpow_enorm hG' two_pos, hB,
        ← ENNReal.mul_rpow_of_nonneg _ _ (by norm_num)]
      refine ENNReal.rpow_le_rpow ?_ (by norm_num)
      simp only [ENNReal.rpow_two, enorm_fsTrunc_sq]
      refine le_trans (lintegral_mono fun x => Finset.sum_le_sum fun i _ =>
        pow_le_pow_left₀ zero_le (min_le_left _ _) 2) (fs_lintegral_sum_sq_le hG')
    have hsub : IsSublinearOn (fsTrunc N) D volume := by
      intro G hG H _
      have hG' : AEStronglyMeasurable G volume := hG
      refine ae_of_all _ fun x => ?_
      have hne : ∀ a : ℝ≥0∞, min a N ≠ ∞ := fun a =>
        ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) (min_le_right _ _)
      refine (fs_norm_le_of_le (w := fsTrunc N G x + fsTrunc N H x)
        (fun i => ENNReal.toReal_nonneg) fun i => ?_).trans (norm_add_le _ _)
      change (min (hlMaximal volume (fun y => (G + H) y i) x) N).toReal ≤
        (min (hlMaximal volume (fun y => G y i) x) N).toReal +
          (min (hlMaximal volume (fun y => H y i) x) N).toReal
      rw [← ENNReal.toReal_add (hne _) (hne _)]
      refine ENNReal.toReal_mono (ENNReal.add_ne_top.2 ⟨hne _, hne _⟩) ?_
      have hadd : (fun y => (G + H) y i) = (fun y => G y i) + (fun y => H y i) := by
        funext y; simp
      rw [hadd]
      exact (min_le_min_right _ (hlMaximal_add_le (fs_aesm_apply hG' i) x)).trans
        (min_add_le_add_min_enn _ _ _)
    have hθ : 1 / p = (1 - (2 - 2 / p)) / 1 + (2 - 2 / p) / 2 := by
      field_simp
      ring
    have hint := eLpNorm_le_of_hasWeakTypeOn one_pos hp1 hp2 hθ hTA hTB hsub hD
      (show F ∈ D from hF) hF (aestronglyMeasurable_fsTrunc N hF)
    rw [eLpNorm_ofReal_eq_lintegral_rpow_enorm (aestronglyMeasurable_fsTrunc N hF) hp0,
      eLpNorm_ofReal_eq_lintegral_rpow_enorm hF hp0] at hint
    have h2 := ENNReal.rpow_le_rpow hint hp0.le
    rw [← ENNReal.rpow_mul, ENNReal.mul_rpow_of_nonneg _ _ hp0.le, ← ENNReal.rpow_mul,
      one_div_mul_cancel hp0.ne', ENNReal.rpow_one, ENNReal.rpow_one] at h2
    refine le_trans (le_of_eq ?_) h2
    refine lintegral_congr fun x => ?_
    rw [fs_enorm_euclidean, ← ENNReal.rpow_mul]
    simp only [enorm_fsTrunc_apply]
    congr 1
    ring
  have hpt : ∀ x, (∑ i, hlMaximal volume (fun y => F y i) x ^ 2) ^ (p / 2) =
      ⨆ N : ℕ, (∑ i, min (hlMaximal volume (fun y => F y i) x) N ^ 2) ^ (p / 2) := fun x =>
    (fs_iSup_rpow_sum_min_sq _ (by linarith)).symm
  simp_rw [hpt]
  rw [lintegral_iSup' (fun N => ?_) (ae_of_all _ fun x N N' hNN' => ?_)]
  · exact iSup_le key
  · exact ((Finset.measurable_sum _ fun i _ =>
      ((fs_measurable_maximal (fs_aesm_apply hF i)).min measurable_const).pow_const 2).pow_const
      _).aemeasurable
  · exact ENNReal.rpow_le_rpow (Finset.sum_le_sum fun i _ => pow_le_pow_left₀ zero_le
      (min_le_min_left _ (Nat.cast_le.2 hNN')) 2) (by linarith)

end Interp

/-! ### The weighted inequality `∫ (M f)² w ≤ C ∫ |f|² M w` -/

section Weighted

variable {n : ℕ} {E : Type*} [NormedAddCommGroup E]

lemma fs_volume_closedBall_eq (x y : EuclideanSpace ℝ (Fin n)) {r : ℝ} (hr : 0 ≤ r) :
    volume (closedBall x r) = volume (closedBall y r) := by
  rw [Measure.addHaar_closedBall _ x hr, Measure.addHaar_closedBall _ y hr]

/-- The ball estimate behind the weighted weak type bound: if the average of `‖f‖` over
`B = B(c,r)` exceeds `τ`, then `w(3B) ≤ 4ⁿ τ⁻¹ ∫_B ‖f‖ M w`. -/
lemma fs_withDensity_closedBall_le {w : EuclideanSpace ℝ (Fin n) → ℝ}
    {f : EuclideanSpace ℝ (Fin n) → E} {c : EuclideanSpace ℝ (Fin n)} {r : ℝ} (hr : 0 < r)
    {τ : ℝ≥0∞} (hτ0 : τ ≠ 0) (hτ : τ < hlBallAverage volume f c r) :
    volume.withDensity (fun x => ‖w x‖ₑ) (closedBall c (3 * r)) ≤
      4 ^ n / τ * ∫⁻ y in closedBall c r, hlMaximal volume w y * ‖f y‖ₑ := by
  set m := volume (closedBall c r)
  have hm0 : m ≠ 0 := (measure_closedBall_pos volume c hr).ne'
  have hmt : m ≠ ∞ := fs_hfin c r
  have hτt : τ ≠ ∞ := ne_top_of_lt hτ
  set I := ∫⁻ y in closedBall c r, ‖f y‖ₑ
  set J := ∫⁻ y in closedBall c r, hlMaximal volume w y * ‖f y‖ₑ
  set ν3 := volume.withDensity (fun x => ‖w x‖ₑ) (closedBall c (3 * r))
  have hν3 : ν3 = ∫⁻ z in closedBall c (3 * r), ‖w z‖ₑ :=
    withDensity_apply _ measurableSet_closedBall
  have hy : ∀ y ∈ closedBall c r, ν3 ≤ 4 ^ n * m * hlMaximal volume w y := by
    intro y hy
    have hsub : closedBall c (3 * r) ⊆ closedBall y (4 * r) := by
      intro z hz
      rw [mem_closedBall] at hz hy ⊢
      have := dist_triangle z c y
      rw [dist_comm c y] at this
      linarith
    have hvol : volume (closedBall y (4 * r)) = 4 ^ n * m := by
      rw [fs_volume_closedBall_mul y (by norm_num) hr.le, fs_volume_closedBall_eq y c hr.le,
        ENNReal.ofReal_pow (by norm_num)]
      simp [m]
    have hv0 : volume (closedBall y (4 * r)) ≠ 0 := by
      rw [hvol]; exact mul_ne_zero (pow_ne_zero _ (by norm_num)) hm0
    have hvt : volume (closedBall y (4 * r)) ≠ ∞ := fs_hfin y _
    calc ν3 = ∫⁻ z in closedBall c (3 * r), ‖w z‖ₑ := hν3
      _ ≤ ∫⁻ z in closedBall y (4 * r), ‖w z‖ₑ := lintegral_mono_set hsub
      _ = volume (closedBall y (4 * r)) * hlBallAverage volume w y (4 * r) := by
          rw [hlBallAverage, ← mul_assoc, ENNReal.mul_inv_cancel hv0 hvt, one_mul]
      _ ≤ volume (closedBall y (4 * r)) * hlMaximal volume w y :=
          mul_le_mul_right (hlBallAverage_le_hlMaximal _ _ _ _) _
      _ = 4 ^ n * m * hlMaximal volume w y := by rw [hvol]
  have hτm : τ * m ≤ I := by
    have h1 : τ * m ≤ m⁻¹ * I * m := mul_le_mul_left hτ.le _
    rwa [mul_comm m⁻¹ I, mul_assoc, ENNReal.inv_mul_cancel hm0 hmt, mul_one] at h1
  have hmain : m * (τ * ν3) ≤ m * (4 ^ n * J) := by
    calc m * (τ * ν3) = (τ * m) * ν3 := by ring
      _ ≤ I * ν3 := mul_le_mul_left hτm _
      _ ≤ ∫⁻ y in closedBall c r, ‖f y‖ₑ * ν3 := lintegral_mul_const_le _ _
      _ ≤ ∫⁻ y in closedBall c r, ‖f y‖ₑ * (4 ^ n * m * hlMaximal volume w y) :=
          setLIntegral_mono' measurableSet_closedBall fun y hy' => mul_le_mul_right (hy y hy') _
      _ = ∫⁻ y in closedBall c r, (4 ^ n * m) * (hlMaximal volume w y * ‖f y‖ₑ) :=
          lintegral_congr fun y => by ring
      _ = 4 ^ n * m * J :=
          lintegral_const_mul' _ _
            (ENNReal.mul_ne_top (ENNReal.pow_ne_top ENNReal.ofNat_ne_top) hmt)
      _ = m * (4 ^ n * J) := by ring
  have h2 : τ * ν3 ≤ 4 ^ n * J := (ENNReal.mul_le_mul_iff_right hm0 hmt).1 hmain
  calc ν3 = τ⁻¹ * (τ * ν3) := by rw [← mul_assoc, ENNReal.inv_mul_cancel hτ0 hτt, one_mul]
    _ ≤ τ⁻¹ * (4 ^ n * J) := mul_le_mul_right h2 _
    _ = 4 ^ n / τ * J := by rw [div_eq_mul_inv]; ring

/-- **Weighted weak type `(1,1)`** (Fefferman–Stein): for every weight `w` and `τ > 0`,
`w {M f > τ} ≤ 4ⁿ τ⁻¹ ∫ ‖f‖ M w`. -/
theorem fs_weighted_weak {w : EuclideanSpace ℝ (Fin n) → ℝ} {f : EuclideanSpace ℝ (Fin n) → E}
    (hf : AEStronglyMeasurable f volume) {τ : ℝ≥0∞} (hτ0 : τ ≠ 0) :
    volume.withDensity (fun x => ‖w x‖ₑ) {x | τ < hlMaximal volume f x} ≤
      4 ^ n / τ * ∫⁻ y, hlMaximal volume w y * ‖f y‖ₑ := by
  set ν := volume.withDensity (fun x => ‖w x‖ₑ)
  set L := {x | τ < hlMaximal volume f x}
  have hmeas : MeasurableSet L := measurableSet_lt measurable_const (fs_measurable_maximal hf)
  have hq : ∀ x ∈ L, ∃ q : ℚ, 0 < (q : ℝ) ∧ τ < hlBallAverage volume f x q := by
    intro x hx
    obtain ⟨r, hr⟩ := lt_iSup_iff.1 (show τ < hlMaximal volume f x from hx)
    have h0 := (measure_closedBall_le_of_lt_hlBallAverage hr).1
    obtain ⟨q, hq⟩ := lt_iSup_iff.1 (hr.trans_le (hlBallAverage_le_iSup_rat_gt fs_hfin f x r))
    obtain ⟨hrq, hq'⟩ := lt_iSup_iff.1 hq
    exact ⟨q, h0.trans_lt hrq, hq'⟩
  choose! ρ hρpos hρ using hq
  rw [hmeas.measure_eq_iSup_isCompact ν]
  refine iSup_le fun K => iSup_le fun hKL => iSup_le fun hK => ?_
  obtain ⟨F, hFK, hKF⟩ := hK.elim_nhds_subcover (fun x => closedBall x (ρ x))
    fun x hx => closedBall_mem_nhds x (hρpos x (hKL hx))
  obtain ⟨S, hSF, hdisj, hcov⟩ := exists_disjoint_subfamily_closedBall_subset_three_mul F
    (fun x => x) (fun x => (ρ x : ℝ))
  calc ν K ≤ ν (⋃ x ∈ F, closedBall x (ρ x : ℝ)) := measure_mono hKF
    _ ≤ ν (⋃ j ∈ S, closedBall j (3 * (ρ j : ℝ))) := by
        refine measure_mono (iUnion₂_subset fun i hi => ?_)
        obtain ⟨j, hj, -, hsub⟩ := hcov i hi
        exact hsub.trans (subset_biUnion_of_mem (u := fun j => closedBall j (3 * (ρ j : ℝ))) hj)
    _ ≤ ∑ j ∈ S, ν (closedBall j (3 * (ρ j : ℝ))) := measure_biUnion_finset_le S _
    _ ≤ ∑ j ∈ S, 4 ^ n / τ * ∫⁻ y in closedBall j (ρ j : ℝ), hlMaximal volume w y * ‖f y‖ₑ :=
        Finset.sum_le_sum fun j hj => fs_withDensity_closedBall_le
          (hρpos j (hKL (hFK j (hSF hj)))) hτ0 (hρ j (hKL (hFK j (hSF hj))))
    _ = 4 ^ n / τ * ∫⁻ y in ⋃ j ∈ S, closedBall j (ρ j : ℝ), hlMaximal volume w y * ‖f y‖ₑ := by
        rw [← Finset.mul_sum, lintegral_biUnion_finset hdisj fun _ _ => measurableSet_closedBall]
    _ ≤ 4 ^ n / τ * ∫⁻ y, hlMaximal volume w y * ‖f y‖ₑ :=
        mul_le_mul_right (setLIntegral_le_lintegral _ _) _

/-- The constant of the weighted `L²` inequality. -/
def fsKw (n : ℕ) : ℝ≥0∞ := marcinkiewiczBoundTop 1 2 (4 ^ n) (1 / 2)

lemma fsKw_ne_top (n : ℕ) : fsKw n ≠ ∞ := marcinkiewiczBoundTop_ne_top _ _ _ _

/-- **The Fefferman–Stein weighted inequality**: for every weight `w` (a.e. strongly measurable
and real-valued; only `|w|` matters) and every `f`, `∫ (M f)² |w| ≤ C ∫ ‖f‖² M w`, with `C`
depending only on `n`. -/
theorem fs_weighted_sq {w : EuclideanSpace ℝ (Fin n) → ℝ} (hw : AEStronglyMeasurable w volume)
    {f : EuclideanSpace ℝ (Fin n) → E} (hf : AEStronglyMeasurable f volume) :
    ∫⁻ x, ‖w x‖ₑ * hlMaximal volume f x ^ 2 ≤
      fsKw n * ∫⁻ x, hlMaximal volume w x * ‖f x‖ₑ ^ 2 := by
  set ν := volume.withDensity (fun x => ‖w x‖ₑ)
  set μ := volume.withDensity (hlMaximal volume w)
  have hMw := fs_measurable_maximal hw
  have hμac : μ ≪ volume := withDensity_absolutelyContinuous _ _
  set D : Set (EuclideanSpace ℝ (Fin n) → E) := {g | AEStronglyMeasurable g volume} with hDdef
  have hD : IsTruncationClosed D := fun g hg s _ =>
    ⟨aestronglyMeasurable_indicator_lt_norm hg s, aestronglyMeasurable_indicator_norm_le hg s⟩
  have hne : ∀ (N : ℕ) (a : ℝ≥0∞), min a N ≠ ∞ := fun N a =>
    ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) (min_le_right _ _)
  have key : ∀ N : ℕ, ∫⁻ x, min (hlMaximal volume f x) N ^ (2 : ℝ) ∂ν ≤
      fsKw n * ∫⁻ x, ‖f x‖ₑ ^ (2 : ℝ) ∂μ := by
    intro N
    have hTA : HasWeakTypeOn (hlMaximalTrunc volume N) D 1 (4 ^ n) μ ν := by
      intro g hg t ht
      have hg' : AEStronglyMeasurable g volume := hg
      unfold distributionFunction
      rw [ENNReal.rpow_one, ENNReal.ofReal_one, eLpNorm_one_eq_lintegral_enorm (hg'.mono_ac hμac),
        lintegral_withDensity_eq_lintegral_mul₀ hMw.aemeasurable hg'.enorm]
      calc ν {x | t < ‖hlMaximalTrunc volume N g x‖ₑ} ≤ ν {x | t < hlMaximal volume g x} := by
            refine measure_mono fun x hx => ?_
            have hx' : t < ‖hlMaximalTrunc volume N g x‖ₑ := hx
            rw [enorm_hlMaximalTrunc] at hx'
            exact hx'.trans_le (min_le_left _ _)
        _ ≤ 4 ^ n / t * ∫⁻ y, hlMaximal volume w y * ‖g y‖ₑ := fs_weighted_weak hg' ht.ne'
        _ = ((4 ^ n : ℝ≥0) : ℝ≥0∞) *
              (∫⁻ y, (hlMaximal volume w * fun y => ‖g y‖ₑ) y) / t := by
            simp only [Pi.mul_apply]
            rw [div_eq_mul_inv, div_eq_mul_inv]
            push_cast
            ring
    have hTB : HasLinftyBoundOn (hlMaximalTrunc volume N) D 1 ν := by
      intro g _ s hs
      refine ae_of_all _ fun y => ?_
      have hs0 : 0 ≤ s := (norm_nonneg _).trans (hs y)
      have hMg : hlMaximal volume g y ≤ ENNReal.ofReal s :=
        hlMaximal_le_of_ae_enorm_le (ae_of_all _ fun z => by
          rw [← ofReal_norm]
          exact ENNReal.ofReal_le_ofReal (hs z)) y
      rw [hlMaximalTrunc, Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg, NNReal.coe_one,
        one_mul]
      exact ENNReal.toReal_le_of_le_ofReal hs0 ((min_le_left _ _).trans hMg)
    have hsub : IsSublinearOn (hlMaximalTrunc volume N) D ν := by
      intro g hg h _
      refine ae_of_all _ fun x => ?_
      simp only [hlMaximalTrunc, Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg]
      rw [← ENNReal.toReal_add (hne _ _) (hne _ _)]
      refine ENNReal.toReal_mono (ENNReal.add_ne_top.2 ⟨hne _ _, hne _ _⟩) ?_
      exact (min_le_min_right _ (hlMaximal_add_le hg x)).trans (min_add_le_add_min_enn _ _ _)
    have hTf : AEStronglyMeasurable (hlMaximalTrunc volume N f) ν :=
      ((fs_measurable_maximal hf).min measurable_const).ennreal_toReal.aestronglyMeasurable
    have := lintegral_rpow_le_of_hasWeakTypeOn_of_linfty (T := hlMaximalTrunc volume N) one_pos
      one_lt_two (by norm_num : (0 : ℝ) < 1 / 2) (by norm_num) hTA hTB hsub hD
      (show f ∈ D from hf) (hf.mono_ac hμac) hTf
    simp only [enorm_hlMaximalTrunc] at this
    exact this
  have hpt : ∀ x, hlMaximal volume f x ^ (2 : ℝ) =
      ⨆ N : ℕ, min (hlMaximal volume f x) N ^ (2 : ℝ) := fun x => by
    have h1 : ⨆ N : ℕ, min (hlMaximal volume f x) N = hlMaximal volume f x := by
      rw [← inf_iSup_eq, ENNReal.iSup_natCast]
      simp
    conv_lhs => rw [← h1]
    exact Monotone.map_iSup_of_continuousAt ENNReal.continuous_rpow_const.continuousAt
      (ENNReal.monotone_rpow_of_nonneg (by norm_num)) (ENNReal.zero_rpow_of_pos (by norm_num))
  have hsup : ∫⁻ x, hlMaximal volume f x ^ (2 : ℝ) ∂ν ≤ fsKw n * ∫⁻ x, ‖f x‖ₑ ^ (2 : ℝ) ∂μ := by
    simp_rw [hpt]
    rw [lintegral_iSup' (fun N =>
      (((fs_measurable_maximal hf).min measurable_const).pow_const _).aemeasurable)
      (ae_of_all _ fun x N N' h => ENNReal.rpow_le_rpow
        (min_le_min_left _ (Nat.cast_le.2 h)) (by norm_num))]
    exact iSup_le key
  rw [lintegral_withDensity_eq_lintegral_mul₀ hw.enorm
      ((fs_measurable_maximal hf).pow_const _).aemeasurable,
    lintegral_withDensity_eq_lintegral_mul₀ hMw.aemeasurable (hf.enorm.pow_const _)] at hsup
  simpa only [Pi.mul_apply, ENNReal.rpow_two] using hsup

end Weighted

/-! ### The case `2 < p < ∞`, by duality -/

section Duality

variable {n : ℕ} {ι : Type*} [Fintype ι]

/-- The constant of the case `2 < p < ∞`. -/
def fsC2 (n : ℕ) (p : ℝ) : ℝ≥0∞ :=
  (fsKw n * fsK n (p / 2 / (p / 2 - 1)) ^ (1 / (p / 2 / (p / 2 - 1)))) ^ (p / 2)

lemma fsC2_ne_top (n : ℕ) {p : ℝ} (hp : 2 < p) : fsC2 n p ≠ ∞ := by
  have hr : 0 < p / 2 / (p / 2 - 1) := div_pos (by linarith) (by linarith)
  exact ENNReal.rpow_ne_top_of_nonneg (by linarith) (ENNReal.mul_ne_top (fsKw_ne_top n)
    (ENNReal.rpow_ne_top_of_nonneg (by positivity) (fsK_ne_top _ _)))

/-- **The case `2 < p < ∞`**, by duality from the weighted inequality and the scalar maximal
theorem in `L^{(p/2)'}`. -/
theorem fs_lintegral_le_of_two_lt {p : ℝ} (hp : 2 < p)
    {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι} (hF : AEStronglyMeasurable F volume) :
    ∫⁻ x, (∑ i, hlMaximal volume (fun y => F y i) x ^ 2) ^ (p / 2) ≤
      fsC2 n p * ∫⁻ x, ‖F x‖ₑ ^ p := by
  set r := p / 2 with hrdef
  have hr : 1 < r := by rw [hrdef]; linarith
  have hr0 : 0 < r := by linarith
  set q := r / (r - 1) with hqdef
  have hrq : r.HolderConjugate q := Real.HolderConjugate.conjExponent hr
  have hq : 1 < q := hrq.symm.lt
  have hr1q : (r - 1) * q = r := by
    rw [hqdef]; field_simp [show r - 1 ≠ 0 by linarith]
  set G : EuclideanSpace ℝ (Fin n) → ℝ≥0∞ := fun x => ∑ i, hlMaximal volume (fun y => F y i) x ^ 2
  have hGm : Measurable G := Finset.measurable_sum _ fun i _ =>
    (fs_measurable_maximal (fs_aesm_apply hF i)).pow_const 2
  set H : EuclideanSpace ℝ (Fin n) → ℝ≥0∞ := fun x => ‖F x‖ₑ ^ 2
  have hHm : AEMeasurable H := hF.enorm.pow_const 2
  have hHp : ∀ x, ‖F x‖ₑ ^ p = H x ^ r := fun x => by
    simp only [H, hrdef]
    rw [← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]
    congr 1
    push_cast
    ring
  set GN : ℕ → EuclideanSpace ℝ (Fin n) → ℝ≥0∞ := fun N =>
    (closedBall (0 : EuclideanSpace ℝ (Fin n)) N).indicator (fun x => min (G x) N)
  have hGN_le : ∀ N x, GN N x ≤ min (G x) N := fun N x => by
    by_cases hx : x ∈ closedBall (0 : EuclideanSpace ℝ (Fin n)) N
    · simp only [GN, indicator_of_mem hx, le_refl]
    · simp only [GN, indicator_of_notMem hx, zero_le]
  have hGN_ne_top : ∀ N x, GN N x ≠ ∞ := fun N x =>
    ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) ((hGN_le N x).trans (min_le_right _ _))
  have hGNm : ∀ N, Measurable (GN N) := fun N =>
    (hGm.min measurable_const).indicator measurableSet_closedBall
  set wN : ℕ → EuclideanSpace ℝ (Fin n) → ℝ := fun N x => (GN N x ^ (r - 1)).toReal
  have hwN : ∀ N x, ‖wN N x‖ₑ = GN N x ^ (r - 1) := fun N x => by
    rw [Real.enorm_eq_ofReal ENNReal.toReal_nonneg, ENNReal.ofReal_toReal
      (ENNReal.rpow_ne_top_of_nonneg (by linarith) (hGN_ne_top N x))]
  have hwNm : ∀ N, Measurable (wN N) := fun N => ((hGNm N).pow_const _).ennreal_toReal
  have key : ∀ N : ℕ, ∫⁻ x, GN N x ^ r ≤ fsC2 n p * ∫⁻ x, ‖F x‖ₑ ^ p := by
    intro N
    set X := ∫⁻ x, GN N x ^ r
    have hX : X ≠ ∞ := by
      refine ne_top_of_le_ne_top (b := ∫⁻ x, (closedBall (0 : EuclideanSpace ℝ (Fin n)) N).indicator
        (fun _ => ((N : ℝ≥0∞) ^ r)) x) ?_ (lintegral_mono fun x => ?_)
      · rw [lintegral_indicator_const measurableSet_closedBall]
        exact ENNReal.mul_ne_top (ENNReal.rpow_ne_top_of_nonneg hr0.le
          (ENNReal.natCast_ne_top N)) (fs_hfin _ _)
      · by_cases hx : x ∈ closedBall (0 : EuclideanSpace ℝ (Fin n)) N
        · rw [indicator_of_mem hx]
          exact ENNReal.rpow_le_rpow ((hGN_le N x).trans (min_le_right _ _)) hr0.le
        · simp only [GN, indicator_of_notMem hx, ENNReal.zero_rpow_of_pos hr0, le_refl]
    set Mw := hlMaximal volume (wN N)
    have hMwm : Measurable Mw := fs_measurable_maximal (hwNm N).aestronglyMeasurable
    have step1 : X ≤ ∫⁻ x, ‖wN N x‖ₑ * G x := by
      refine lintegral_mono fun x => ?_
      rw [hwN]
      by_cases h0 : GN N x = 0
      · rw [h0, ENNReal.zero_rpow_of_pos hr0]
        exact zero_le
      · calc GN N x ^ r = GN N x ^ (r - 1) * GN N x ^ (1 : ℝ) := by
              rw [← ENNReal.rpow_add _ _ h0 (hGN_ne_top N x)]
              ring_nf
          _ ≤ GN N x ^ (r - 1) * G x := by
              rw [ENNReal.rpow_one]
              exact mul_le_mul_right ((hGN_le N x).trans (min_le_left _ _)) _
    have step2 : ∫⁻ x, ‖wN N x‖ₑ * G x ≤ fsKw n * ∫⁻ x, Mw x * H x := by
      simp only [G, Finset.mul_sum]
      rw [lintegral_finsetSum' (f := fun i x => ‖wN N x‖ₑ * hlMaximal volume (fun y => F y i) x ^ 2)
        _ fun i _ => ((hwNm N).enorm.mul
        ((fs_measurable_maximal (fs_aesm_apply hF i)).pow_const 2)).aemeasurable]
      calc ∑ i, ∫⁻ x, ‖wN N x‖ₑ * hlMaximal volume (fun y => F y i) x ^ 2
          ≤ ∑ i, fsKw n * ∫⁻ x, Mw x * ‖F x i‖ₑ ^ 2 :=
            Finset.sum_le_sum fun i _ =>
              fs_weighted_sq (hwNm N).aestronglyMeasurable (fs_aesm_apply hF i)
        _ = fsKw n * ∫⁻ x, Mw x * H x := by
            rw [← Finset.mul_sum, ← lintegral_finsetSum' (f := fun i x => Mw x * ‖F x i‖ₑ ^ 2)
              _ fun i _ =>
              (hMwm.aemeasurable.mul ((fs_aesm_apply hF i).enorm.pow_const 2))]
            congr 1
            refine lintegral_congr fun x => ?_
            simp only [H, fs_enorm_sq_euclidean, Finset.mul_sum]
    have step3 : ∫⁻ x, Mw x * H x ≤
        (∫⁻ x, H x ^ r) ^ (1 / r) * (∫⁻ x, Mw x ^ q) ^ (1 / q) := by
      have := ENNReal.lintegral_mul_le_Lp_mul_Lq volume hrq hHm hMwm.aemeasurable
      simp only [Pi.mul_apply] at this
      refine le_trans (le_of_eq (lintegral_congr fun x => mul_comm _ _)) this
    have step4 : ∫⁻ x, Mw x ^ q ≤ fsK n q * X := by
      refine (fs_lintegral_maximal_rpow_le hq (hwNm N).aestronglyMeasurable).trans_eq ?_
      congr 1
      refine lintegral_congr fun x => ?_
      rw [hwN, ← ENNReal.rpow_mul, hr1q]
    set Y := ∫⁻ x, H x ^ r
    have hcomb : X ≤ fsKw n * fsK n q ^ (1 / q) * Y ^ (1 / r) * X ^ (1 / q) := by
      calc X ≤ fsKw n * ((∫⁻ x, H x ^ r) ^ (1 / r) * (∫⁻ x, Mw x ^ q) ^ (1 / q)) :=
            step1.trans (step2.trans (mul_le_mul_right step3 _))
        _ ≤ fsKw n * (Y ^ (1 / r) * (fsK n q * X) ^ (1 / q)) := by
            gcongr
        _ = fsKw n * fsK n q ^ (1 / q) * Y ^ (1 / r) * X ^ (1 / q) := by
            rw [ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]
            ring
    have h5 := rpow_le_of_le_mul_rpow hrq hX hcomb
    have h6 := ENNReal.rpow_le_rpow h5 hr0.le
    rw [← ENNReal.rpow_mul, one_div_mul_cancel hr0.ne', ENNReal.rpow_one,
      ENNReal.mul_rpow_of_nonneg _ _ hr0.le, ← ENNReal.rpow_mul, one_div_mul_cancel hr0.ne',
      ENNReal.rpow_one] at h6
    refine h6.trans_eq ?_
    rw [show Y = ∫⁻ x, ‖F x‖ₑ ^ p from lintegral_congr fun x => (hHp x).symm]
    rfl
  have hpt : ∀ x, G x ^ r = ⨆ N : ℕ, GN N x ^ r := fun x => by
    refine le_antisymm ?_ (iSup_le fun N => ENNReal.rpow_le_rpow
      ((hGN_le N x).trans (min_le_left _ _)) hr0.le)
    have h1 : ⨆ N : ℕ, min (G x) N = G x := by
      rw [← inf_iSup_eq, ENNReal.iSup_natCast]
      simp
    conv_lhs => rw [← h1]
    rw [Monotone.map_iSup_of_continuousAt ENNReal.continuous_rpow_const.continuousAt
      (ENNReal.monotone_rpow_of_nonneg hr0.le) (ENNReal.zero_rpow_of_pos hr0)]
    refine iSup_le fun N => ?_
    set N' := max N ⌈‖x‖⌉₊
    have hx : x ∈ closedBall (0 : EuclideanSpace ℝ (Fin n)) N' := by
      rw [mem_closedBall, dist_zero_right]
      exact (Nat.le_ceil _).trans (Nat.cast_le.2 (le_max_right _ _))
    refine le_iSup_of_le N' (ENNReal.rpow_le_rpow ?_ hr0.le)
    simp only [GN, indicator_of_mem hx]
    exact min_le_min_left _ (Nat.cast_le.2 (le_max_left _ _))
  have hmono : ∀ x, Monotone fun N => GN N x ^ r := fun x N N' hNN' => by
    refine ENNReal.rpow_le_rpow ?_ hr0.le
    by_cases hx : x ∈ closedBall (0 : EuclideanSpace ℝ (Fin n)) N
    · have hx' : x ∈ closedBall (0 : EuclideanSpace ℝ (Fin n)) N' :=
        closedBall_subset_closedBall (Nat.cast_le.2 hNN') hx
      simp only [GN, indicator_of_mem hx, indicator_of_mem hx']
      exact min_le_min_left _ (Nat.cast_le.2 hNN')
    · simp only [GN, indicator_of_notMem hx, zero_le]
  calc ∫⁻ x, G x ^ r = ∫⁻ x, ⨆ N : ℕ, GN N x ^ r := lintegral_congr hpt
    _ = ⨆ N : ℕ, ∫⁻ x, GN N x ^ r :=
        lintegral_iSup' (fun N => ((hGNm N).pow_const _).aemeasurable) (ae_of_all _ hmono)
    _ ≤ fsC2 n p * ∫⁻ x, ‖F x‖ₑ ^ p := iSup_le key

end Duality

/-! ### The main theorem -/

section Main

/-- The constant of the Fefferman–Stein inequality in integral form, for `1 < p < ∞`. -/
def fsConst (n : ℕ) (p : ℝ) : ℝ≥0∞ :=
  if p < 2 then fsC1 n p else if p = 2 then fsK n 2 else fsC2 n p

lemma fsConst_ne_top (n : ℕ) {p : ℝ} (hp : 1 < p) : fsConst n p ≠ ∞ := by
  unfold fsConst
  split_ifs with h1 h2
  · exact fsC1_ne_top n hp h1
  · exact fsK_ne_top n 2
  · exact fsC2_ne_top n (lt_of_le_of_ne (not_lt.1 h1) (Ne.symm h2))

/-- **The Fefferman–Stein inequality in integral form**, for `F : ℝⁿ → ℓ²(ι)` (`ι` finite):
`∫ (∑ᵢ (M Fᵢ)²)^(p/2) ≤ C ∫ ‖F‖^p` for `1 < p < ∞`. -/
theorem fs_lintegral_le {n : ℕ} (hn : 0 < n) {ι : Type*} [Fintype ι] {p : ℝ} (hp : 1 < p)
    {F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ ι} (hF : AEStronglyMeasurable F volume) :
    ∫⁻ x, (∑ i, hlMaximal volume (fun y => F y i) x ^ 2) ^ (p / 2) ≤
      fsConst n p * ∫⁻ x, ‖F x‖ₑ ^ p := by
  unfold fsConst
  split_ifs with h1 h2
  · exact fs_lintegral_le_of_lt_two hn hp h1 hF
  · subst h2
    rw [show (2 : ℝ) / 2 = 1 by norm_num]
    simp only [ENNReal.rpow_one, ENNReal.rpow_two]
    exact fs_lintegral_sum_sq_le hF
  · exact fs_lintegral_le_of_two_lt (lt_of_le_of_ne (not_lt.1 h1) (Ne.symm h2)) hF

universe u

/-- **The Fefferman–Stein vector-valued maximal inequality**, with an explicit constant:
for `n ≥ 1`, `1 < p < ∞`, every finite family `(fᵢ)_{i ∈ s}` of a.e. strongly measurable
functions on `ℝⁿ`,
`‖(∑ᵢ (M fᵢ)²)^(1/2)‖_p ≤ C_{n,p} ‖(∑ᵢ |fᵢ|²)^(1/2)‖_p` with `C_{n,p} = fsConst n p ^ (1/p)`. -/
theorem fefferman_stein_const (n : ℕ) (hn : 1 ≤ n) {p : ℝ} (hp : 1 < p) {ι : Type u}
    (s : Finset ι) (f : ι → EuclideanSpace ℝ (Fin n) → ℂ)
    (hf : ∀ i ∈ s, AEStronglyMeasurable (f i) volume) :
    eLpNorm (fun x => (∑ i ∈ s, fsMaximal n (f i) x ^ 2) ^ (1 / 2 : ℝ)) (ENNReal.ofReal p)
        volume ≤
      fsConst n p ^ (1 / p) *
        eLpNorm (fun x => Real.sqrt (∑ i ∈ s, ‖f i x‖ ^ 2)) (ENNReal.ofReal p) volume := by
  have hp0 : 0 < p := by linarith
  set F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ s := fun x =>
    WithLp.toLp 2 (fun i : s => f i x)
  have hF : AEStronglyMeasurable F volume :=
    ((MeasurableEquiv.toLp 2 (s → ℂ)).measurable.comp_aemeasurable
      (AEMeasurable.of_eval fun i => (hf i i.2).aemeasurable)).aestronglyMeasurable
  have hM : ∀ x, ∑ i ∈ s, fsMaximal n (f i) x ^ 2 =
      ∑ i : s, hlMaximal volume (fun y => F y i) x ^ 2 := fun x => by
    simp only [fsMaximal_eq_hlMaximal]
    exact (Finset.sum_coe_sort s (fun i => hlMaximal volume (f i) x ^ 2)).symm
  have hLm : Measurable fun x => (∑ i ∈ s, fsMaximal n (f i) x ^ 2) ^ (1 / 2 : ℝ) := by
    simp only [fsMaximal_eq_hlMaximal]
    exact (Finset.measurable_sum _ fun i hi =>
      (fs_measurable_maximal (hf i hi)).pow_const 2).pow_const _
  have hR : (fun x => Real.sqrt (∑ i ∈ s, ‖f i x‖ ^ 2)) = fun x => ‖F x‖ := funext fun x => by
    rw [EuclideanSpace.norm_eq]
    exact congrArg Real.sqrt (Finset.sum_coe_sort s fun i => ‖f i x‖ ^ 2).symm
  rw [hR, eLpNorm_norm F hF, eLpNorm_ofReal_eq_lintegral_rpow_enorm hF hp0,
    eLpNorm_eq_lintegral_rpow_enorm_toReal (by simpa using hp0) ENNReal.ofReal_ne_top
      hLm.aestronglyMeasurable, ENNReal.toReal_ofReal hp0.le,
    ← ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]
  refine ENNReal.rpow_le_rpow ?_ (by positivity)
  refine le_trans (le_of_eq (lintegral_congr fun x => ?_)) (fs_lintegral_le (by omega) hp hF)
  rw [enorm_eq_self, ← ENNReal.rpow_mul, hM x]
  congr 1
  ring

/-- **The Fefferman–Stein vector-valued maximal inequality** (C. Fefferman–E. M. Stein, 1971):
for `n ≥ 1` and `1 < p < ∞` there is a constant `C` such that for every finite family
`(fᵢ)_{i ∈ s}` of a.e. strongly measurable complex functions on `ℝⁿ`,
`‖(∑ᵢ (M fᵢ)²)^(1/2)‖_{L^p} ≤ C ‖(∑ᵢ |fᵢ|²)^(1/2)‖_{L^p}`,
where `M = fsMaximal n` is the centered Hardy–Littlewood maximal function over balls. -/
theorem fefferman_stein (n : ℕ) (hn : 1 ≤ n) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ≥0, ∀ {ι : Type u} (s : Finset ι) (f : ι → EuclideanSpace ℝ (Fin n) → ℂ),
      (∀ i ∈ s, AEStronglyMeasurable (f i) volume) →
      eLpNorm (fun x => (∑ i ∈ s, fsMaximal n (f i) x ^ 2) ^ (1 / 2 : ℝ)) (ENNReal.ofReal p)
          volume ≤
        C * eLpNorm (fun x => Real.sqrt (∑ i ∈ s, ‖f i x‖ ^ 2)) (ENNReal.ofReal p) volume := by
  refine ⟨(fsConst n p ^ (1 / p)).toNNReal, fun s f hf => ?_⟩
  have hp0 : 0 ≤ 1 / p := one_div_nonneg.2 (by linarith)
  rw [ENNReal.coe_toNNReal (ENNReal.rpow_ne_top_of_nonneg hp0 (fsConst_ne_top n hp))]
  exact fefferman_stein_const n hn hp s f hf

end Main

end

end Auto
