/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import VariationalSW.Auto.MarcinkiewiczInterpolation

/-!
# The Hardy–Littlewood maximal theorem

This file was automatically generated by Claude.

This file proves the **Hardy–Littlewood maximal theorem** for the centered maximal function over
closed balls in a pseudometric measure space with a doubling condition, the first part of
Blueprint Lemma 2.4 (`lem:maximal`) of `blueprints/discrete-sw.tex`, and specializes it to the
blueprint's cube maximal functions on `E = EuclideanSpace ℝ (Fin n)` and on `G = ℤⁿ`. The
statements depend on Mathlib only (the proofs also use
`VariationalSW.Auto.MarcinkiewiczInterpolation`).

It was adapted from the user's project `lean-discretesw` (file
`DiscreteSW/Auto/HardyLittlewoodMaximal.lean`); "Blueprint" and "the blueprint" in the
docstrings refer to the blueprint `blueprints/discrete-sw.tex` of that project.

## Formulation

* `X` is a pseudometric space with a measure `μ` (Borel sets measurable), `f : X → E` with `E` a
  normed additive group (so vector-valued inputs are allowed).
* `hlBallAverage μ f x r = μ(B(x,r))⁻¹ ∫_{B(x,r)} ‖f‖` over closed balls, and
  `hlMaximal μ f x = sup_{r ∈ ℝ} hlBallAverage μ f x r`, valued in `ℝ≥0∞`. By the conventions
  of `ℝ≥0∞` balls of measure `0` or `∞` (and radii `r < 0`) contribute `0`; radius `0` is
  allowed, which matters for counting measure.
* Doubling hypothesis, constant `C : ℝ≥0`: `μ(B(x,3r)) ≤ C μ(B(x,r))` for all `x` and `r ≥ 0`.
* The weak type bound is `μ {x | t < M f x} ≤ C / t * ∫ ‖f‖` for every `t : ℝ≥0∞` (outer measure,
  no measurability of the level set needed in the countable case). It is proved
  * on countable spaces (`hlMaximal_weak_one_of_countable`, no further hypotheses) by applying the
    finite covering estimate to finite subsets of the level set, and
  * on second countable spaces with an s-finite inner regular measure that is finite on balls
    (`hlMaximal_weak_one`) via compact subsets of the level set and finite subcovers; there the
    level set is measurable (`measurable_hlMaximal`: rational radii suffice, by continuity of the
    ball measure from above).
* Strong type: `eLpNorm (M f) p μ ≤ hlMaximalConst C p * eLpNorm f p μ` for `1 < p < ∞`, with the
  explicit constant `hlMaximalConst C p = (2^p p C/(p-1))^(1/p)`, and
  `M f ≤ ‖f‖_∞` pointwise (`hlMaximal_le_eLpNormEssSup`), hence `‖M f‖_∞ ≤ ‖f‖_∞`.

## Main results

* `exists_disjoint_subfamily_closedBall_subset_three_mul`: finite Vitali lemma (largest first
  selection, threefold dilations).
* `measure_biUnion_closedBall_le_of_doubling`: `μ(⋃ B_i) ≤ C t⁻¹ ∫ ‖f‖` for finite families with
  `μ(B_i) ≤ t⁻¹ ∫_{B_i} ‖f‖`.
* `hlMaximal_weak_one_of_countable`, `hlMaximal_weak_one`: weak type `(1,1)`.
* `eLpNorm_hlMaximal_le_of_countable`, `eLpNorm_hlMaximal_le`: strong type `(p,p)`,
  `1 < p < ∞` (Marcinkiewicz interpolation of weak `(1,1)` with the `L^∞` bound, applied to the
  truncations `min (M f) N` and monotone convergence).
* `hlMaximal_le_eLpNormEssSup`, `eLpNorm_hlMaximal_top_le`: the `L^∞` bound, constant one.
* Blueprint form on `E = EuclideanSpace ℝ (Fin n)` with Lebesgue measure: `cubeMaximalEuclidean`
  (sup over `r ≥ 0` of averages over `{y | ∀ i, |y i - x i| ≤ r}`),
  `cubeMaximalEuclidean_weak_one` (constant `3ⁿ`), `eLpNorm_cubeMaximalEuclidean_le`,
  `eLpNorm_cubeMaximalEuclidean_top_le`, `measurable_cubeMaximalEuclidean`; deduced from the sup
  metric on `Fin n → ℝ` through the volume preserving equivalence.
* Blueprint form on `G = ℤⁿ` (`Fin n → ℤ`) with counting measure: `cubeMaximalInt`
  (sup over integer radii `R ≥ 0` of averages over `{y | ∀ i, |y i - x i| ≤ R}`),
  `cubeMaximalInt_weak_one` (constant `5ⁿ`), `eLpNorm_cubeMaximalInt_le`,
  `eLpNorm_cubeMaximalInt_top_le`.

## References

* G. H. Hardy and J. E. Littlewood, *A maximal theorem with function-theoretic applications*,
  Acta Math. **54** (1930), 81–116.
* E. M. Stein, *Singular Integrals and Differentiability Properties of Functions*, Princeton
  University Press, 1970, Chapter I, §1.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, Theorem 2.1.6.
-/

@[expose] public section

namespace Auto

open MeasureTheory Metric Set Filter Topology
open scoped ENNReal NNReal

noncomputable section

section General

variable {X E : Type*} [PseudoMetricSpace X] [MeasurableSpace X] [NormedAddCommGroup E]
  {μ : Measure X}

/-- The average `μ(B(x,r))⁻¹ ∫_{B(x,r)} ‖f‖` of `‖f‖` over the closed ball `B(x,r)`, valued in
`ℝ≥0∞`. With the conventions of `ℝ≥0∞` it vanishes when `μ(B(x,r)) = 0` or `μ(B(x,r)) = ∞`
(in particular for `r < 0`). -/
def hlBallAverage (μ : Measure X) (f : X → E) (x : X) (r : ℝ) : ℝ≥0∞ :=
  (μ (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ

/-- The centered Hardy–Littlewood maximal function over closed balls,
`M f(x) = sup_r μ(B(x,r))⁻¹ ∫_{B(x,r)} ‖f‖`, valued in `ℝ≥0∞`. Radii `r < 0` and balls of measure
`0` or `∞` contribute `0`; the radius `r = 0` (the ball `B(x,0)`) is included. -/
def hlMaximal (μ : Measure X) (f : X → E) (x : X) : ℝ≥0∞ :=
  ⨆ r : ℝ, hlBallAverage μ f x r

theorem hlBallAverage_le_hlMaximal (μ : Measure X) (f : X → E) (x : X) (r : ℝ) :
    hlBallAverage μ f x r ≤ hlMaximal μ f x :=
  le_iSup (fun r => hlBallAverage μ f x r) r

omit [MeasurableSpace X] in
/-- A closed ball is contained in its threefold dilate. -/
theorem closedBall_subset_closedBall_three_mul (x : X) (r : ℝ) :
    closedBall x r ⊆ closedBall x (3 * r) := by
  rcases le_or_gt 0 r with hr | hr
  · exact closedBall_subset_closedBall (by linarith)
  · rw [closedBall_eq_empty.2 hr]
    exact empty_subset _

omit [MeasurableSpace X] in
/-- **Finite Vitali covering lemma, largest-first selection** (proof of Blueprint Lemma 2.4
(`lem:maximal`)): every finite family of closed balls `B(c i, r i)`, `i ∈ s`, has a pairwise
disjoint subfamily `S ⊆ s` such that every ball of the family is contained in the threefold
dilate `B(c j, 3 r j)` of a selected ball with `r i ≤ r j`. -/
theorem exists_disjoint_subfamily_closedBall_subset_three_mul {ι : Type*} (s : Finset ι)
    (c : ι → X) (r : ι → ℝ) :
    ∃ S ⊆ s, (S : Set ι).PairwiseDisjoint (fun i => closedBall (c i) (r i)) ∧
      ∀ i ∈ s, ∃ j ∈ S, r i ≤ r j ∧ closedBall (c i) (r i) ⊆ closedBall (c j) (3 * r j) := by
  classical
  induction s using Finset.strongInduction with
  | H s ih =>
  rcases s.eq_empty_or_nonempty with rfl | hs
  · exact ⟨∅, by simp, by simp, by simp⟩
  obtain ⟨i, his, hmax⟩ := s.exists_max_image r hs
  set s' := (s.erase i).filter
    (fun j => Disjoint (closedBall (c j) (r j)) (closedBall (c i) (r i))) with hs'def
  have hs' : s' ⊂ s := (Finset.filter_subset _ _).trans_ssubset (Finset.erase_ssubset his)
  obtain ⟨S', hS's, hS'disj, hS'cov⟩ := ih s' hs'
  refine ⟨insert i S', ?_, ?_, ?_⟩
  · exact Finset.insert_subset his
      (hS's.trans ((Finset.filter_subset _ _).trans (Finset.erase_subset _ _)))
  · rw [Finset.coe_insert]
    refine hS'disj.insert fun j hj _ => ?_
    exact ((Finset.mem_filter.1 (hS's hj)).2).symm
  · intro j hj
    by_cases hji : j = i
    · subst hji
      exact ⟨j, Finset.mem_insert_self _ _, le_rfl, closedBall_subset_closedBall_three_mul _ _⟩
    by_cases hd : Disjoint (closedBall (c j) (r j)) (closedBall (c i) (r i))
    · obtain ⟨k, hk, h1, h2⟩ :=
        hS'cov j (Finset.mem_filter.2 ⟨Finset.mem_erase.2 ⟨hji, hj⟩, hd⟩)
      exact ⟨k, Finset.mem_insert_of_mem hk, h1, h2⟩
    · refine ⟨i, Finset.mem_insert_self _ _, hmax j hj, ?_⟩
      obtain ⟨z, hz1, hz2⟩ := Set.not_disjoint_iff.1 hd
      intro y hy
      rw [mem_closedBall] at hy hz1 hz2 ⊢
      have hji' := hmax j hj
      calc dist y (c i) ≤ dist y (c j) + dist (c j) z + dist z (c i) := dist_triangle4 _ _ _ _
        _ ≤ r j + r j + r i := by
          rw [dist_comm (c j) z]
          gcongr
        _ ≤ 3 * r i := by linarith

variable [OpensMeasurableSpace X]

/-- **Finite covering estimate** (proof of Blueprint Lemma 2.4 (`lem:maximal`)): if `μ` satisfies
the doubling condition `μ(B(x,3r)) ≤ C μ(B(x,r))` and every ball of a finite family satisfies
`μ(B_i) ≤ t⁻¹ ∫_{B_i} ‖f‖`, then `μ(⋃ B_i) ≤ C t⁻¹ ∫ ‖f‖`. -/
theorem measure_biUnion_closedBall_le_of_doubling {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    {ι : Type*} (s : Finset ι) (c : ι → X) (r : ι → ℝ) (hr : ∀ i ∈ s, 0 ≤ r i) (t : ℝ≥0∞)
    (f : X → E)
    (h : ∀ i ∈ s, μ (closedBall (c i) (r i)) ≤ t⁻¹ * ∫⁻ y in closedBall (c i) (r i), ‖f y‖ₑ ∂μ) :
    μ (⋃ i ∈ s, closedBall (c i) (r i)) ≤ C / t * ∫⁻ y, ‖f y‖ₑ ∂μ := by
  obtain ⟨S, hSs, hdisj, hcov⟩ := exists_disjoint_subfamily_closedBall_subset_three_mul s c r
  calc μ (⋃ i ∈ s, closedBall (c i) (r i))
      ≤ μ (⋃ j ∈ S, closedBall (c j) (3 * r j)) := by
        refine measure_mono (iUnion₂_subset fun i hi => ?_)
        obtain ⟨j, hj, -, hsub⟩ := hcov i hi
        exact hsub.trans (subset_biUnion_of_mem (u := fun j => closedBall (c j) (3 * r j)) hj)
    _ ≤ ∑ j ∈ S, μ (closedBall (c j) (3 * r j)) := measure_biUnion_finset_le S _
    _ ≤ ∑ j ∈ S, (C : ℝ≥0∞) * μ (closedBall (c j) (r j)) :=
        Finset.sum_le_sum fun j hj => hC _ _ (hr j (hSs hj))
    _ = C * ∑ j ∈ S, μ (closedBall (c j) (r j)) := (Finset.mul_sum _ _ _).symm
    _ ≤ C * ∑ j ∈ S, t⁻¹ * ∫⁻ y in closedBall (c j) (r j), ‖f y‖ₑ ∂μ := by
        gcongr with j hj
        exact h j (hSs hj)
    _ = C * (t⁻¹ * ∫⁻ y in ⋃ j ∈ S, closedBall (c j) (r j), ‖f y‖ₑ ∂μ) := by
        rw [← Finset.mul_sum,
          lintegral_biUnion_finset hdisj (fun _ _ => measurableSet_closedBall)]
    _ ≤ C * (t⁻¹ * ∫⁻ y, ‖f y‖ₑ ∂μ) := by
        exact mul_le_mul_right (mul_le_mul_right (setLIntegral_le_lintegral _ _) _) _
    _ = C / t * ∫⁻ y, ‖f y‖ₑ ∂μ := by rw [div_eq_mul_inv, mul_assoc]

omit [OpensMeasurableSpace X] in
/-- If the average over `B(x,r)` exceeds `t`, then `r ≥ 0` and `μ(B(x,r)) ≤ t⁻¹ ∫_{B(x,r)} ‖f‖`. -/
theorem measure_closedBall_le_of_lt_hlBallAverage {f : X → E} {x : X} {r : ℝ} {t : ℝ≥0∞}
    (h : t < hlBallAverage μ f x r) :
    0 ≤ r ∧ μ (closedBall x r) ≤ t⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ := by
  unfold hlBallAverage at h
  set m := μ (closedBall x r)
  set I := ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ
  have hne : m⁻¹ * I ≠ 0 := (lt_of_le_of_lt zero_le h).ne'
  obtain ⟨hminv, hI⟩ := mul_ne_zero_iff.1 hne
  have hmtop : m ≠ ∞ := ENNReal.inv_ne_zero.1 hminv
  have hm0 : m ≠ 0 := by
    intro hm
    exact hI (setLIntegral_measure_zero _ _ hm)
  refine ⟨?_, ?_⟩
  · by_contra hr
    exact hm0 (by simp [m, closedBall_eq_empty.2 (not_le.1 hr)])
  have htop : t ≠ ∞ := ne_top_of_lt h
  rcases eq_or_ne t 0 with rfl | ht0
  · rw [ENNReal.inv_zero, ENNReal.top_mul hI]
    exact le_top
  have hmul : t * m ≤ I := by
    calc t * m ≤ m⁻¹ * I * m := mul_le_mul_left h.le _
      _ = I := by rw [mul_comm, ← mul_assoc, ENNReal.mul_inv_cancel hm0 hmtop, one_mul]
  rw [mul_comm, ← div_eq_mul_inv, ENNReal.le_div_iff_mul_le (Or.inl ht0) (Or.inl htop),
    mul_comm]
  exact hmul

omit [OpensMeasurableSpace X] in
/-- Averages are monotone in the pointwise norm (almost everywhere). -/
theorem hlBallAverage_mono {F : Type*} [NormedAddCommGroup F] {f : X → E} {g : X → F}
    (h : ∀ᵐ y ∂μ, ‖f y‖ₑ ≤ ‖g y‖ₑ) (x : X) (r : ℝ) :
    hlBallAverage μ f x r ≤ hlBallAverage μ g x r :=
  mul_le_mul_right (lintegral_mono_ae (ae_restrict_of_ae h)) _

omit [OpensMeasurableSpace X] in
/-- The maximal function is monotone in the pointwise norm (almost everywhere). -/
theorem hlMaximal_mono {F : Type*} [NormedAddCommGroup F] {f : X → E} {g : X → F}
    (h : ∀ᵐ y ∂μ, ‖f y‖ₑ ≤ ‖g y‖ₑ) (x : X) : hlMaximal μ f x ≤ hlMaximal μ g x :=
  iSup_mono fun r => hlBallAverage_mono h x r

omit [OpensMeasurableSpace X] in
/-- The maximal function only depends on the almost everywhere class of the input. -/
theorem hlMaximal_congr_ae {f g : X → E} (h : f =ᵐ[μ] g) : hlMaximal μ f = hlMaximal μ g := by
  funext x
  refine le_antisymm (hlMaximal_mono ?_ x) (hlMaximal_mono ?_ x)
  · filter_upwards [h] with y hy
    rw [hy]
  · filter_upwards [h] with y hy
    rw [hy]

omit [OpensMeasurableSpace X] in
/-- Subadditivity of averages for a.e. strongly measurable inputs. -/
theorem hlBallAverage_add_le {f g : X → E} (hf : AEStronglyMeasurable f μ) (x : X) (r : ℝ) :
    hlBallAverage μ (f + g) x r ≤ hlBallAverage μ f x r + hlBallAverage μ g x r := by
  unfold hlBallAverage
  rw [← mul_add, ← lintegral_add_left' hf.restrict.enorm]
  exact mul_le_mul_right (lintegral_mono fun y => enorm_add_le _ _) _

omit [OpensMeasurableSpace X] in
/-- Subadditivity of the maximal function: `M (f + g) ≤ M f + M g` for a.e. strongly measurable
`f`. -/
theorem hlMaximal_add_le {f g : X → E} (hf : AEStronglyMeasurable f μ) (x : X) :
    hlMaximal μ (f + g) x ≤ hlMaximal μ f x + hlMaximal μ g x :=
  iSup_le fun r => (hlBallAverage_add_le hf x r).trans
    (add_le_add (hlBallAverage_le_hlMaximal _ _ _ _) (hlBallAverage_le_hlMaximal _ _ _ _))

omit [OpensMeasurableSpace X] in
/-- If `‖f‖ ≤ c` almost everywhere, then `M f ≤ c` everywhere. -/
theorem hlMaximal_le_of_ae_enorm_le {f : X → E} {c : ℝ≥0∞} (h : ∀ᵐ y ∂μ, ‖f y‖ₑ ≤ c)
    (x : X) : hlMaximal μ f x ≤ c := by
  refine iSup_le fun r => ?_
  unfold hlBallAverage
  calc (μ (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ
      ≤ (μ (closedBall x r))⁻¹ * ∫⁻ _ in closedBall x r, c ∂μ :=
        mul_le_mul_right (lintegral_mono_ae (ae_restrict_of_ae h)) _
    _ = c * ((μ (closedBall x r))⁻¹ * μ (closedBall x r)) := by
        rw [setLIntegral_const]
        ring
    _ ≤ c * 1 := mul_le_mul_right (ENNReal.inv_mul_le_one _) _
    _ = c := mul_one c

omit [OpensMeasurableSpace X] in
/-- **Pointwise `L^∞` bound** (Blueprint Lemma 2.4 (`lem:maximal`), case `p = ∞`, constant one):
`M f(x) ≤ ‖f‖_{L^∞}` for every `x`. -/
theorem hlMaximal_le_eLpNormEssSup (f : X → E) (x : X) :
    hlMaximal μ f x ≤ eLpNormEssSup f μ :=
  hlMaximal_le_of_ae_enorm_le ae_le_eLpNormEssSup x

omit [OpensMeasurableSpace X] in
/-- **`L^∞` bound** (Blueprint Lemma 2.4 (`lem:maximal`), case `p = ∞`, constant one):
`‖M f‖_{L^∞} ≤ ‖f‖_{L^∞}` (the measurability hypothesis makes `eLpNorm` meaningful). -/
theorem eLpNorm_hlMaximal_top_le {f : X → E} (hM : AEMeasurable (hlMaximal μ f) μ) :
    eLpNorm (hlMaximal μ f) ∞ μ ≤ eLpNorm f ∞ μ := by
  by_cases hf : AEStronglyMeasurable f μ
  · rw [eLpNorm_exponent_top hM.aestronglyMeasurable, eLpNorm_exponent_top hf]
    refine essSup_le_of_ae_le _ (ae_of_all _ fun x => ?_)
    change ‖hlMaximal μ f x‖ₑ ≤ _
    rw [enorm_eq_self]
    exact hlMaximal_le_eLpNormEssSup f x
  · rw [eLpNorm_of_not_aestronglyMeasurable hf]
    exact le_top

/-- Continuity of the ball measure from above, in the form used for the maximal function: the
average over `B(x,r)` is at most the supremum of the averages over `B(x,q)`, `q > r` rational
(if balls have finite measure). -/
theorem hlBallAverage_le_iSup_rat_gt (hfin : ∀ (x : X) (r : ℝ), μ (closedBall x r) ≠ ∞)
    (f : X → E) (x : X) (r : ℝ) :
    hlBallAverage μ f x r ≤ ⨆ (q : ℚ) (_ : r < q), hlBallAverage μ f x q := by
  have hinf : ⨅ q : {q : ℚ // r < q}, μ (closedBall x (q : ℝ)) = μ (closedBall x r) := by
    rw [← Directed.measure_iInter (fun q => measurableSet_closedBall.nullMeasurableSet)]
    · congr 1
      ext y
      simp only [mem_iInter, mem_closedBall, Subtype.forall]
      exact ⟨fun h => le_of_forall_lt_rat_imp_le fun q hq => h q hq,
        fun h q hq => h.trans (le_of_lt hq)⟩
    · intro q₁ q₂
      refine ⟨⟨min q₁.1 q₂.1, ?_⟩, ?_, ?_⟩
      · rw [Rat.cast_min]
        exact lt_min q₁.2 q₂.2
      · exact closedBall_subset_closedBall (by rw [Rat.cast_min]; exact min_le_left _ _)
      · exact closedBall_subset_closedBall (by rw [Rat.cast_min]; exact min_le_right _ _)
    · obtain ⟨q, hq⟩ := exists_rat_gt r
      exact ⟨⟨q, hq⟩, hfin _ _⟩
  unfold hlBallAverage
  calc (μ (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ
      = (⨅ q : {q : ℚ // r < q}, μ (closedBall x (q : ℝ)))⁻¹ *
          ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ := by rw [hinf]
    _ = ⨆ q : {q : ℚ // r < q}, (μ (closedBall x (q : ℝ)))⁻¹ *
          ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ := by rw [ENNReal.inv_iInf, ENNReal.iSup_mul]
    _ ≤ ⨆ q : {q : ℚ // r < q}, (μ (closedBall x (q : ℝ)))⁻¹ *
          ∫⁻ y in closedBall x (q : ℝ), ‖f y‖ₑ ∂μ :=
        iSup_mono fun q => mul_le_mul_right
          (lintegral_mono_set (closedBall_subset_closedBall (le_of_lt q.2))) _
    _ ≤ ⨆ (q : ℚ) (_ : r < q), (μ (closedBall x (q : ℝ)))⁻¹ *
          ∫⁻ y in closedBall x (q : ℝ), ‖f y‖ₑ ∂μ :=
        iSup_le fun q => le_iSup₂_of_le q.1 q.2 le_rfl

/-- Rational radii suffice: `M f(x) = sup_{q ∈ ℚ} μ(B(x,q))⁻¹ ∫_{B(x,q)} ‖f‖` (if balls have
finite measure). -/
theorem hlMaximal_eq_iSup_rat (hfin : ∀ (x : X) (r : ℝ), μ (closedBall x r) ≠ ∞)
    (f : X → E) (x : X) : hlMaximal μ f x = ⨆ q : ℚ, hlBallAverage μ f x q :=
  le_antisymm
    (iSup_le fun r => (hlBallAverage_le_iSup_rat_gt hfin f x r).trans
      (iSup₂_le fun q _ => le_iSup (fun q : ℚ => hlBallAverage μ f x q) q))
    (iSup_le fun q => hlBallAverage_le_hlMaximal μ f x q)

section Measurability

variable [SecondCountableTopology X] [SFinite μ]

/-- For a fixed radius, the average is a measurable function of the center (a measurable
parameter integral). -/
theorem measurable_hlBallAverage {f : X → E} (hf : Measurable fun y => ‖f y‖ₑ) (r : ℝ) :
    Measurable fun x => hlBallAverage μ f x r := by
  set S : Set (X × X) := {p | dist p.2 p.1 ≤ r} with hSdef
  have hS : MeasurableSet S :=
    (isClosed_le (continuous_snd.dist continuous_fst) continuous_const).measurableSet
  have hslice : ∀ x, Prod.mk x ⁻¹' S = closedBall x r := fun x => by
    ext y
    simp [S, mem_closedBall]
  have h1 : Measurable fun x => μ (closedBall x r) := by
    simp_rw [← hslice]
    exact measurable_measure_prodMk_left hS
  have h2 : Measurable fun x => ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ := by
    have : (fun x => ∫⁻ y in closedBall x r, ‖f y‖ₑ ∂μ) =
        fun x => ∫⁻ y, S.indicator (fun p => ‖f p.2‖ₑ) (x, y) ∂μ := by
      funext x
      rw [← lintegral_indicator measurableSet_closedBall]
      congr 1
    rw [this]
    exact ((hf.comp measurable_snd).indicator hS).lintegral_prod_right'
  exact h1.inv.mul h2

/-- **Measurability of the maximal function** (proof of Blueprint Lemma 2.4 (`lem:maximal`)):
if balls have finite measure (and `X` is second countable, `μ` s-finite), then `M f` is
measurable for every a.e. strongly measurable `f`; rational radii suffice. -/
theorem measurable_hlMaximal (hfin : ∀ (x : X) (r : ℝ), μ (closedBall x r) ≠ ∞) {f : X → E}
    (hf : AEStronglyMeasurable f μ) : Measurable (hlMaximal μ f) := by
  rw [hlMaximal_congr_ae hf.ae_eq_mk]
  have : hlMaximal μ (hf.mk f) = fun x => ⨆ q : ℚ, hlBallAverage μ (hf.mk f) x q :=
    funext fun x => hlMaximal_eq_iSup_rat hfin _ x
  rw [this]
  exact Measurable.iSup fun q => measurable_hlBallAverage hf.stronglyMeasurable_mk.enorm _

end Measurability

/-- The finite covering estimate applied to balls on which the average exceeds `t`. -/
theorem measure_biUnion_le_of_lt_hlBallAverage {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    (f : X → E) (t : ℝ≥0∞) (F : Finset X) (ρ : X → ℝ)
    (h : ∀ x ∈ F, t < hlBallAverage μ f x (ρ x)) :
    μ (⋃ x ∈ F, closedBall x (ρ x)) ≤ C / t * ∫⁻ y, ‖f y‖ₑ ∂μ :=
  measure_biUnion_closedBall_le_of_doubling hC F id ρ
    (fun x hx => (measure_closedBall_le_of_lt_hlBallAverage (h x hx)).1) t f
    (fun x hx => (measure_closedBall_le_of_lt_hlBallAverage (h x hx)).2)

/-- **Weak type `(1,1)` on countable spaces** (Blueprint Lemma 2.4 (`lem:maximal`), weak bound,
the lattice case): if `X` is countable and `μ(B(x,3r)) ≤ C μ(B(x,r))` for all `x` and `r ≥ 0`, then
for every `f` and every `t`, `μ {M f > t} ≤ C t⁻¹ ∫ ‖f‖` (proved on finite subsets of the level
set). -/
theorem hlMaximal_weak_one_of_countable [Countable X] {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    (f : X → E) (t : ℝ≥0∞) :
    μ {x | t < hlMaximal μ f x} ≤ C / t * ∫⁻ y, ‖f y‖ₑ ∂μ := by
  classical
  set L := {x | t < hlMaximal μ f x} with hLdef
  have hr : ∀ x ∈ L, ∃ r, t < hlBallAverage μ f x r := fun x hx => lt_iSup_iff.1 hx
  choose! ρ hρ using hr
  have hL : L = ⋃ F ∈ {F : Finset X | (F : Set X) ⊆ L}, (F : Set X) := by
    refine Set.ext fun x => ⟨fun hx => mem_biUnion (x := {x}) (by simpa using hx) (by simp),
      fun hx => ?_⟩
    obtain ⟨F, hF, hxF⟩ := mem_iUnion₂.1 hx
    exact hF hxF
  calc μ L = μ (⋃ F ∈ {F : Finset X | (F : Set X) ⊆ L}, (F : Set X)) := congrArg μ hL
    _ = ⨆ F ∈ {F : Finset X | (F : Set X) ⊆ L}, μ (F : Set X) := by
        refine measure_biUnion_eq_iSup (Set.to_countable _) ?_
        intro F hF G hG
        refine ⟨F ∪ G, ?_, ?_, ?_⟩
        · change ((F ∪ G : Finset X) : Set X) ⊆ L
          rw [Finset.coe_union]
          exact union_subset hF hG
        · exact Finset.coe_subset.2 Finset.subset_union_left
        · exact Finset.coe_subset.2 Finset.subset_union_right
    _ ≤ C / t * ∫⁻ y, ‖f y‖ₑ ∂μ := by
        refine iSup₂_le fun F hF => ?_
        have hF' : ∀ x ∈ F, t < hlBallAverage μ f x (ρ x) := fun x hx => hρ x (hF hx)
        calc μ (F : Set X) ≤ μ (⋃ x ∈ F, closedBall x (ρ x)) := by
              refine measure_mono fun x hx => mem_biUnion hx (mem_closedBall_self ?_)
              exact (measure_closedBall_le_of_lt_hlBallAverage (hF' x hx)).1
          _ ≤ _ := measure_biUnion_le_of_lt_hlBallAverage hC f t F ρ hF'

/-- **Weak type `(1,1)` on inner regular spaces** (Blueprint Lemma 2.4 (`lem:maximal`), weak bound,
the Euclidean case): let `X` be second countable, `μ` s-finite and inner regular (with respect to
compact sets), with balls of finite measure and `μ(B(x,3r)) ≤ C μ(B(x,r))` for all `x`, `r ≥ 0`.
Then for every a.e. strongly measurable `f` and every `t`, `μ {M f > t} ≤ C t⁻¹ ∫ ‖f‖`
(proved on finite subcovers of compact subsets of the level set). -/
theorem hlMaximal_weak_one [SecondCountableTopology X] [SFinite μ] [μ.InnerRegular]
    (hfin : ∀ (x : X) (r : ℝ), μ (closedBall x r) ≠ ∞) {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    {f : X → E} (hf : AEStronglyMeasurable f μ) (t : ℝ≥0∞) :
    μ {x | t < hlMaximal μ f x} ≤ C / t * ∫⁻ y, ‖f y‖ₑ ∂μ := by
  set L := {x | t < hlMaximal μ f x} with hLdef
  have hmeas : MeasurableSet L := measurableSet_lt measurable_const (measurable_hlMaximal hfin hf)
  have hq : ∀ x ∈ L, ∃ q : ℚ, 0 < (q : ℝ) ∧ t < hlBallAverage μ f x q := by
    intro x hx
    obtain ⟨r, hr⟩ := lt_iSup_iff.1 (show t < hlMaximal μ f x from hx)
    have h0 := (measure_closedBall_le_of_lt_hlBallAverage hr).1
    obtain ⟨q, hq⟩ := lt_iSup_iff.1 (hr.trans_le (hlBallAverage_le_iSup_rat_gt hfin f x r))
    obtain ⟨hrq, hq'⟩ := lt_iSup_iff.1 hq
    exact ⟨q, h0.trans_lt hrq, hq'⟩
  choose! ρ hρpos hρ using hq
  rw [hmeas.measure_eq_iSup_isCompact]
  refine iSup_le fun K => iSup_le fun hKL => iSup_le fun hK => ?_
  obtain ⟨F, hFK, hKF⟩ := hK.elim_nhds_subcover (fun x => closedBall x (ρ x))
    fun x hx => closedBall_mem_nhds x (hρpos x (hKL hx))
  calc μ K ≤ μ (⋃ x ∈ F, closedBall x (ρ x : ℝ)) := measure_mono hKF
    _ ≤ _ := measure_biUnion_le_of_lt_hlBallAverage hC f t F (fun x => (ρ x : ℝ))
        fun x hx => hρ x (hKL (hFK x hx))

/-! ### Strong type `(p, p)` via Marcinkiewicz interpolation -/

/-- The truncated real-valued maximal function `min (M f) N`: a real-valued, everywhere
subadditive operator to which the Marcinkiewicz interpolation theorem applies. -/
def hlMaximalTrunc (μ : Measure X) (N : ℕ) (f : X → E) (x : X) : ℝ :=
  (min (hlMaximal μ f x) N).toReal

omit [OpensMeasurableSpace X] in
theorem enorm_hlMaximalTrunc (N : ℕ) (f : X → E) (x : X) :
    ‖hlMaximalTrunc μ N f x‖ₑ = min (hlMaximal μ f x) N := by
  rw [hlMaximalTrunc, Real.enorm_eq_ofReal ENNReal.toReal_nonneg, ENNReal.ofReal_toReal]
  exact ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) (min_le_right _ _)

/-- `min (a + b) c ≤ min a c + min b c` in `ℝ≥0∞`. -/
theorem min_add_le_add_min_enn (a b c : ℝ≥0∞) : min (a + b) c ≤ min a c + min b c := by
  by_cases ha : a ≤ c
  · by_cases hb : b ≤ c
    · rw [min_eq_left ha, min_eq_left hb]
      exact min_le_left _ _
    · rw [min_eq_right (not_le.1 hb).le]
      exact (min_le_right _ _).trans le_add_self
  · rw [min_eq_right (not_le.1 ha).le]
    exact (min_le_right _ _).trans le_self_add

/-- The strong type constant `C_p = (2^p p C / (p - 1))^(1/p)` of the Hardy–Littlewood maximal
theorem, for doubling constant `C` and `1 < p < ∞`. -/
def hlMaximalConst (C : ℝ≥0) (p : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal (2 ^ p * p * C / (p - 1)) ^ (1 / p)

/-- The strong type constant is finite. -/
theorem hlMaximalConst_ne_top (C : ℝ≥0) {p : ℝ} (hp : 0 < p) : hlMaximalConst C p ≠ ∞ :=
  ENNReal.rpow_ne_top_of_nonneg (by positivity) ENNReal.ofReal_ne_top

omit [OpensMeasurableSpace X] in
/-- **Strong type `(p, p)` in integral form, from the weak type `(1, 1)` bound** (proof of
Blueprint Lemma 2.4 (`lem:maximal`)): Marcinkiewicz interpolation between weak `(1,1)` and
`L^∞` gives `∫ (M f)^p ≤ 2^p p C/(p-1) ∫ ‖f‖^p` for `1 < p < ∞`. -/
theorem lintegral_hlMaximal_rpow_le_of_weak [SFinite μ] {C : ℝ≥0} {p : ℝ} (hp : 1 < p)
    (hweak : ∀ g : X → E, AEStronglyMeasurable g μ → ∀ t : ℝ≥0∞,
      μ {x | t < hlMaximal μ g x} ≤ C / t * ∫⁻ y, ‖g y‖ₑ ∂μ)
    {f : X → E} (hf : AEStronglyMeasurable f μ) (hM : AEMeasurable (hlMaximal μ f) μ) :
    ∫⁻ x, hlMaximal μ f x ^ p ∂μ ≤
      ENNReal.ofReal (2 ^ p * p * C / (p - 1)) * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  set D : Set (X → E) := {g | AEStronglyMeasurable g μ} with hDdef
  have hD : IsTruncationClosed D := fun g hg s _ =>
    ⟨aestronglyMeasurable_indicator_lt_norm hg s, aestronglyMeasurable_indicator_norm_le hg s⟩
  have hne : ∀ (N : ℕ) (a : ℝ≥0∞), min a N ≠ ∞ := fun N a =>
    ne_top_of_le_ne_top (ENNReal.natCast_ne_top N) (min_le_right _ _)
  have key : ∀ N : ℕ, ∫⁻ x, min (hlMaximal μ f x) N ^ p ∂μ ≤
      ENNReal.ofReal (2 ^ p * p * C / (p - 1)) * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
    intro N
    have hTA : HasWeakTypeOn (hlMaximalTrunc μ N) D 1 C μ μ := by
      intro g hg t _
      unfold distributionFunction
      rw [ENNReal.rpow_one, ENNReal.ofReal_one, eLpNorm_one_eq_lintegral_enorm hg]
      calc μ {x | t < ‖hlMaximalTrunc μ N g x‖ₑ} ≤ μ {x | t < hlMaximal μ g x} := by
            refine measure_mono fun x hx => ?_
            have hx' : t < ‖hlMaximalTrunc μ N g x‖ₑ := hx
            rw [enorm_hlMaximalTrunc] at hx'
            exact hx'.trans_le (min_le_left _ _)
        _ ≤ C / t * ∫⁻ y, ‖g y‖ₑ ∂μ := hweak g hg t
        _ = C * (∫⁻ y, ‖g y‖ₑ ∂μ) / t := by
            rw [div_eq_mul_inv, div_eq_mul_inv, mul_right_comm]
    have hTB : HasLinftyBoundOn (hlMaximalTrunc μ N) D 1 μ := by
      intro g _ s hs
      refine ae_of_all _ fun y => ?_
      have hs0 : 0 ≤ s := (norm_nonneg _).trans (hs y)
      have hMg : hlMaximal μ g y ≤ ENNReal.ofReal s :=
        hlMaximal_le_of_ae_enorm_le (ae_of_all _ fun z => by
          rw [← ofReal_norm]
          exact ENNReal.ofReal_le_ofReal (hs z)) y
      rw [hlMaximalTrunc, Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg, NNReal.coe_one,
        one_mul]
      exact ENNReal.toReal_le_of_le_ofReal hs0 ((min_le_left _ _).trans hMg)
    have hsub : IsSublinearOn (hlMaximalTrunc μ N) D μ := by
      intro g hg h _
      refine ae_of_all _ fun x => ?_
      simp only [hlMaximalTrunc, Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg]
      rw [← ENNReal.toReal_add (hne _ _) (hne _ _)]
      refine ENNReal.toReal_mono (ENNReal.add_ne_top.2 ⟨hne _ _, hne _ _⟩) ?_
      exact (min_le_min_right _ (hlMaximal_add_le hg x)).trans (min_add_le_add_min_enn _ _ _)
    have hTf : AEStronglyMeasurable (hlMaximalTrunc μ N f) μ :=
      (hM.min aemeasurable_const).ennreal_toReal.aestronglyMeasurable
    have := lintegral_rpow_le_of_hasWeakTypeOn_of_linfty (T := hlMaximalTrunc μ N) one_pos hp
      (by norm_num : (0 : ℝ) < 1 / 2) (by norm_num) hTA hTB hsub hD (show f ∈ D from hf) hf hTf
    simp only [enorm_hlMaximalTrunc] at this
    have hconst : marcinkiewiczBoundTop 1 p C (1 / 2) =
        ENNReal.ofReal (2 ^ p * p * C / (p - 1)) := by
      unfold marcinkiewiczBoundTop
      congr 1
      rw [Real.rpow_one, Real.rpow_one, one_div, Real.inv_rpow (by norm_num),
        ← Real.rpow_neg (by norm_num), neg_sub, Real.rpow_sub_one two_ne_zero]
      ring
    rwa [hconst] at this
  have hpt : ∀ x, hlMaximal μ f x ^ p = ⨆ N : ℕ, min (hlMaximal μ f x) N ^ p := fun x => by
    have h1 : ⨆ N : ℕ, min (hlMaximal μ f x) N = hlMaximal μ f x := by
      rw [← inf_iSup_eq, ENNReal.iSup_natCast]
      simp
    conv_lhs => rw [← h1]
    exact Monotone.map_iSup_of_continuousAt ENNReal.continuous_rpow_const.continuousAt
      (ENNReal.monotone_rpow_of_nonneg (by linarith)) (ENNReal.zero_rpow_of_pos (by linarith))
  simp_rw [hpt]
  rw [lintegral_iSup' (fun N => (hM.min aemeasurable_const).pow_const p)
    (ae_of_all _ fun x N N' hNN' => ENNReal.rpow_le_rpow
      (min_le_min_left _ (Nat.cast_le.2 hNN')) (by linarith))]
  exact iSup_le key

omit [OpensMeasurableSpace X] in
/-- **Strong type `(p, p)`, from the weak type `(1, 1)` bound**: if `M` satisfies the weak
`(1,1)` bound with constant `C` for all a.e. strongly measurable inputs, then
`‖M f‖_p ≤ C_p ‖f‖_p` for `1 < p < ∞`, `C_p = hlMaximalConst C p`. -/
theorem eLpNorm_hlMaximal_le_of_weak [SFinite μ] {C : ℝ≥0} {p : ℝ} (hp : 1 < p)
    (hweak : ∀ g : X → E, AEStronglyMeasurable g μ → ∀ t : ℝ≥0∞,
      μ {x | t < hlMaximal μ g x} ≤ C / t * ∫⁻ y, ‖g y‖ₑ ∂μ)
    {f : X → E} (hf : AEStronglyMeasurable f μ) (hM : AEMeasurable (hlMaximal μ f) μ) :
    eLpNorm (hlMaximal μ f) (ENNReal.ofReal p) μ ≤
      hlMaximalConst C p * eLpNorm f (ENNReal.ofReal p) μ := by
  have hp0 : 0 < p := by linarith
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by simpa using hp0) ENNReal.ofReal_ne_top
      hM.aestronglyMeasurable, ENNReal.toReal_ofReal hp0.le,
    eLpNorm_ofReal_eq_lintegral_rpow_enorm hf hp0, hlMaximalConst,
    ← ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]
  simp only [enorm_eq_self]
  exact ENNReal.rpow_le_rpow (lintegral_hlMaximal_rpow_le_of_weak hp hweak hf hM)
    (by positivity)

/-- **Hardy–Littlewood maximal theorem, strong type `(p, p)`, countable spaces** (Blueprint
Lemma 2.4 (`lem:maximal`), strong bound, the lattice case): on a countable space with measurable
singletons and an s-finite measure satisfying `μ(B(x,3r)) ≤ C μ(B(x,r))` (`r ≥ 0`), for
`1 < p < ∞` and every `f`, `‖M f‖_p ≤ C_p ‖f‖_p` with `C_p = (2^p p C/(p-1))^(1/p)`. -/
theorem eLpNorm_hlMaximal_le_of_countable [Countable X] [MeasurableSingletonClass X] [SFinite μ]
    {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    {p : ℝ} (hp : 1 < p) (f : X → E) :
    eLpNorm (hlMaximal μ f) (ENNReal.ofReal p) μ ≤
      hlMaximalConst C p * eLpNorm f (ENNReal.ofReal p) μ :=
  eLpNorm_hlMaximal_le_of_weak hp (fun g _ t => hlMaximal_weak_one_of_countable hC g t)
    AEStronglyMeasurable.of_discrete (measurable_of_countable _).aemeasurable

omit [OpensMeasurableSpace X] in
/-- **Hardy–Littlewood maximal theorem, `L^∞` bound, countable spaces** (Blueprint Lemma 2.4
(`lem:maximal`), `p = ∞`): `‖M f‖_∞ ≤ ‖f‖_∞`. -/
theorem eLpNorm_hlMaximal_top_le_of_countable [Countable X] [MeasurableSingletonClass X]
    (f : X → E) : eLpNorm (hlMaximal μ f) ∞ μ ≤ eLpNorm f ∞ μ :=
  eLpNorm_hlMaximal_top_le (measurable_of_countable _).aemeasurable

/-- **Hardy–Littlewood maximal theorem, strong type `(p, p)`** (Blueprint Lemma 2.4
(`lem:maximal`), strong bound, the Euclidean case): let `X` be second countable, `μ` s-finite
and inner regular, with balls of finite measure and `μ(B(x,3r)) ≤ C μ(B(x,r))` (`r ≥ 0`). For
`1 < p < ∞` and every a.e. strongly measurable `f`, `‖M f‖_p ≤ C_p ‖f‖_p` with
`C_p = (2^p p C/(p-1))^(1/p)`. -/
theorem eLpNorm_hlMaximal_le [SecondCountableTopology X] [SFinite μ] [μ.InnerRegular]
    (hfin : ∀ (x : X) (r : ℝ), μ (closedBall x r) ≠ ∞) {C : ℝ≥0}
    (hC : ∀ (x : X) (r : ℝ), 0 ≤ r → μ (closedBall x (3 * r)) ≤ C * μ (closedBall x r))
    {p : ℝ} (hp : 1 < p) {f : X → E} (hf : AEStronglyMeasurable f μ) :
    eLpNorm (hlMaximal μ f) (ENNReal.ofReal p) μ ≤
      hlMaximalConst C p * eLpNorm f (ENNReal.ofReal p) μ :=
  eLpNorm_hlMaximal_le_of_weak hp (fun _ hg t => hlMaximal_weak_one hfin hC hg t) hf
    (measurable_hlMaximal hfin hf).aemeasurable

end General

/-! ### Cubes in `ℝⁿ`: the sup metric on `Fin n → ℝ` and `E = EuclideanSpace ℝ (Fin n)` -/

section Euclidean

variable {E : Type*} [NormedAddCommGroup E] (n : ℕ)

/-- Doubling of Lebesgue measure for sup-metric balls (cubes) in `Fin n → ℝ`, constant `3ⁿ`. -/
theorem volume_closedBall_three_mul_le_pi (x : Fin n → ℝ) (r : ℝ) (hr : 0 ≤ r) :
    volume (closedBall x (3 * r)) ≤ ((3 ^ n : ℝ≥0) : ℝ≥0∞) * volume (closedBall x r) := by
  rw [Real.volume_pi_closedBall x (by positivity), Real.volume_pi_closedBall x hr,
    Fintype.card_fin, show (2 * (3 * r)) ^ n = 3 ^ n * (2 * r) ^ n by rw [← mul_pow]; ring,
    ENNReal.ofReal_mul (by positivity)]
  apply le_of_eq
  congr 1
  rw [ENNReal.ofReal_pow (by norm_num)]
  simp

/-- Weak type `(1,1)` of the cube maximal function on `Fin n → ℝ` (sup metric), constant `3ⁿ`. -/
theorem hlMaximal_weak_one_pi {f : (Fin n → ℝ) → E} (hf : AEStronglyMeasurable f volume)
    (t : ℝ≥0∞) :
    volume {x | t < hlMaximal volume f x} ≤
      ((3 ^ n : ℝ≥0) : ℝ≥0∞) / t * ∫⁻ y, ‖f y‖ₑ :=
  hlMaximal_weak_one (fun _ _ => measure_closedBall_lt_top.ne)
    (volume_closedBall_three_mul_le_pi n) hf t

/-- Strong type `(p,p)` of the cube maximal function on `Fin n → ℝ` (sup metric). -/
theorem eLpNorm_hlMaximal_le_pi {p : ℝ} (hp : 1 < p) {f : (Fin n → ℝ) → E}
    (hf : AEStronglyMeasurable f volume) :
    eLpNorm (hlMaximal volume f) (ENNReal.ofReal p) volume ≤
      hlMaximalConst (3 ^ n) p * eLpNorm f (ENNReal.ofReal p) volume :=
  eLpNorm_hlMaximal_le (fun _ _ => measure_closedBall_lt_top.ne)
    (volume_closedBall_three_mul_le_pi n) hp hf

/-- The closed axis-parallel cube `{y | ∀ i, |y i - x i| ≤ r}` of half side length `r` centered at
`x` in `E = EuclideanSpace ℝ (Fin n)`. -/
def euclideanCube {n : ℕ} (x : EuclideanSpace ℝ (Fin n)) (r : ℝ) :
    Set (EuclideanSpace ℝ (Fin n)) :=
  {y | ∀ i, |y i - x i| ≤ r}

/-- The blueprint's maximal function on `E = EuclideanSpace ℝ (Fin n)`: the supremum over all
radii `r ≥ 0` of the averages of `‖f‖` over the centered closed cubes
`{y | ∀ i, |y i - x i| ≤ r}` (with respect to Lebesgue measure), valued in `ℝ≥0∞`. -/
def cubeMaximalEuclidean (f : EuclideanSpace ℝ (Fin n) → E) (x : EuclideanSpace ℝ (Fin n)) :
    ℝ≥0∞ :=
  ⨆ (r : ℝ) (_ : 0 ≤ r),
    (volume (euclideanCube x r))⁻¹ * ∫⁻ y in euclideanCube x r, ‖f y‖ₑ

variable {X : Type*} [PseudoMetricSpace X] [MeasurableSpace X] in
/-- Averages over balls of negative radius vanish. -/
theorem hlBallAverage_of_neg (μ : Measure X) (f : X → E) (x : X) {r : ℝ} (hr : r < 0) :
    hlBallAverage μ f x r = 0 := by
  simp [hlBallAverage, closedBall_eq_empty.2 hr]

/-- The measure preserving identification `E ≃ᵐ (Fin n → ℝ)`. -/
abbrev euclideanEquivPi : EuclideanSpace ℝ (Fin n) ≃ᵐ (Fin n → ℝ) :=
  (MeasurableEquiv.toLp 2 (Fin n → ℝ)).symm

theorem measurePreserving_euclideanEquivPi :
    MeasurePreserving (euclideanEquivPi n) volume volume :=
  EuclideanSpace.volume_preserving_symm_measurableEquiv_toLp (Fin n)

/-- Cubes in `E` are sup-metric balls in `Fin n → ℝ`. -/
theorem euclideanCube_eq_preimage (x : EuclideanSpace ℝ (Fin n)) {r : ℝ} (hr : 0 ≤ r) :
    euclideanCube x r = euclideanEquivPi n ⁻¹' closedBall (euclideanEquivPi n x) r := by
  ext y
  simp only [euclideanCube, mem_ofPred_eq, mem_preimage, mem_closedBall, dist_pi_le_iff hr,
    Real.dist_eq]
  rfl

/-- The blueprint's cube maximal function on `E` is the sup-metric ball maximal function on
`Fin n → ℝ`, transported by `E ≃ᵐ (Fin n → ℝ)`. -/
theorem cubeMaximalEuclidean_eq (f : EuclideanSpace ℝ (Fin n) → E)
    (x : EuclideanSpace ℝ (Fin n)) :
    cubeMaximalEuclidean n f x =
      hlMaximal volume (f ∘ (euclideanEquivPi n).symm) (euclideanEquivPi n x) := by
  have he := measurePreserving_euclideanEquivPi n
  have havg : ∀ r : ℝ, 0 ≤ r →
      (volume (euclideanCube x r))⁻¹ * ∫⁻ y in euclideanCube x r, ‖f y‖ₑ =
        hlBallAverage volume (f ∘ (euclideanEquivPi n).symm) (euclideanEquivPi n x) r := by
    intro r hr
    rw [euclideanCube_eq_preimage n x hr, hlBallAverage, he.measure_preimage_equiv,
      ← he.setLIntegral_comp_preimage_emb (euclideanEquivPi n).measurableEmbedding]
    simp
  unfold cubeMaximalEuclidean hlMaximal
  refine le_antisymm (iSup₂_le fun r hr => (havg r hr).trans_le (le_iSup (fun r => _) r))
    (iSup_le fun r => ?_)
  rcases lt_or_ge r 0 with hr | hr
  · rw [hlBallAverage_of_neg _ _ _ hr]
    exact zero_le
  · rw [← havg r hr]
    exact le_iSup₂ (f := fun r (_ : 0 ≤ r) =>
      (volume (euclideanCube x r))⁻¹ * ∫⁻ y in euclideanCube x r, ‖f y‖ₑ) r hr

/-- The cube maximal function on `E` is measurable (for a.e. strongly measurable `f`). -/
theorem measurable_cubeMaximalEuclidean {f : EuclideanSpace ℝ (Fin n) → E}
    (hf : AEStronglyMeasurable f volume) : Measurable (cubeMaximalEuclidean n f) := by
  have he := measurePreserving_euclideanEquivPi n
  have hg : AEStronglyMeasurable (f ∘ (euclideanEquivPi n).symm) volume :=
    hf.comp_measurePreserving he.symm
  have : cubeMaximalEuclidean n f =
      hlMaximal volume (f ∘ (euclideanEquivPi n).symm) ∘ euclideanEquivPi n :=
    funext fun x => cubeMaximalEuclidean_eq n f x
  rw [this]
  exact (measurable_hlMaximal (fun _ _ => measure_closedBall_lt_top.ne) hg).comp
    (euclideanEquivPi n).measurable

/-- **Hardy–Littlewood maximal theorem on `E = ℝⁿ`, weak type `(1,1)`** (Blueprint Lemma 2.4
(`lem:maximal`), weak bound for `X = E`): for the maximal function over centered closed
axis-parallel cubes on `EuclideanSpace ℝ (Fin n)`, every a.e. strongly measurable `f` and every
`t`, `|{M f > t}| ≤ 3ⁿ t⁻¹ ‖f‖₁`. -/
theorem cubeMaximalEuclidean_weak_one {f : EuclideanSpace ℝ (Fin n) → E}
    (hf : AEStronglyMeasurable f volume) (t : ℝ≥0∞) :
    volume {x | t < cubeMaximalEuclidean n f x} ≤
      ((3 ^ n : ℝ≥0) : ℝ≥0∞) / t * ∫⁻ y, ‖f y‖ₑ := by
  have he := measurePreserving_euclideanEquivPi n
  have hg : AEStronglyMeasurable (f ∘ (euclideanEquivPi n).symm) volume :=
    hf.comp_measurePreserving he.symm
  have hset : {x | t < cubeMaximalEuclidean n f x} = euclideanEquivPi n ⁻¹'
      {z | t < hlMaximal volume (f ∘ (euclideanEquivPi n).symm) z} := by
    ext x
    simp [cubeMaximalEuclidean_eq n f x]
  have hint : ∫⁻ y, ‖f y‖ₑ = ∫⁻ z, ‖(f ∘ (euclideanEquivPi n).symm) z‖ₑ := by
    rw [← he.lintegral_comp_emb (euclideanEquivPi n).measurableEmbedding]
    simp
  rw [hset, he.measure_preimage_equiv, hint]
  exact hlMaximal_weak_one_pi n hg t

/-- **Hardy–Littlewood maximal theorem on `E = ℝⁿ`, strong type `(p,p)`** (Blueprint Lemma 2.4
(`lem:maximal`), strong bound for `X = E`, `1 < p < ∞`): for the maximal function over centered
closed axis-parallel cubes on `EuclideanSpace ℝ (Fin n)` and every a.e. strongly measurable `f`,
`‖M f‖_p ≤ C_{n,p} ‖f‖_p` with `C_{n,p} = (2^p p 3ⁿ/(p-1))^(1/p)`. -/
theorem eLpNorm_cubeMaximalEuclidean_le {p : ℝ} (hp : 1 < p)
    {f : EuclideanSpace ℝ (Fin n) → E} (hf : AEStronglyMeasurable f volume) :
    eLpNorm (cubeMaximalEuclidean n f) (ENNReal.ofReal p) volume ≤
      hlMaximalConst (3 ^ n) p * eLpNorm f (ENNReal.ofReal p) volume := by
  have he := measurePreserving_euclideanEquivPi n
  have hg : AEStronglyMeasurable (f ∘ (euclideanEquivPi n).symm) volume :=
    hf.comp_measurePreserving he.symm
  have h1 : cubeMaximalEuclidean n f =
      hlMaximal volume (f ∘ (euclideanEquivPi n).symm) ∘ euclideanEquivPi n :=
    funext fun x => cubeMaximalEuclidean_eq n f x
  have h2 : f = (f ∘ (euclideanEquivPi n).symm) ∘ euclideanEquivPi n := by
    funext x
    simp
  rw [h1, eLpNorm_comp_measurePreserving
      (measurable_hlMaximal (fun _ _ => measure_closedBall_lt_top.ne) hg).aestronglyMeasurable he,
    h2, eLpNorm_comp_measurePreserving hg he]
  exact eLpNorm_hlMaximal_le_pi n hp hg

/-- **Hardy–Littlewood maximal theorem on `E = ℝⁿ`, `L^∞` bound** (Blueprint Lemma 2.4
(`lem:maximal`), `p = ∞` for `X = E`, constant one): `‖M f‖_∞ ≤ ‖f‖_∞`. -/
theorem eLpNorm_cubeMaximalEuclidean_top_le {f : EuclideanSpace ℝ (Fin n) → E}
    (hf : AEStronglyMeasurable f volume) :
    eLpNorm (cubeMaximalEuclidean n f) ∞ volume ≤ eLpNorm f ∞ volume := by
  have he := measurePreserving_euclideanEquivPi n
  have hg : AEStronglyMeasurable (f ∘ (euclideanEquivPi n).symm) volume :=
    hf.comp_measurePreserving he.symm
  have h1 : cubeMaximalEuclidean n f =
      hlMaximal volume (f ∘ (euclideanEquivPi n).symm) ∘ euclideanEquivPi n :=
    funext fun x => cubeMaximalEuclidean_eq n f x
  have h2 : f = (f ∘ (euclideanEquivPi n).symm) ∘ euclideanEquivPi n := by
    funext x
    simp
  have hM := measurable_hlMaximal (fun _ _ => measure_closedBall_lt_top.ne) hg
  rw [h1, eLpNorm_comp_measurePreserving hM.aestronglyMeasurable he, h2,
    eLpNorm_comp_measurePreserving hg he]
  exact eLpNorm_hlMaximal_top_le hM.aemeasurable

end Euclidean

/-! ### Cubes in the lattice `G = ℤⁿ` -/

section Lattice

variable {E : Type*} [NormedAddCommGroup E] (n : ℕ)

/-- Sup-metric balls in `Fin n → ℤ` are integer cubes: for `r ≥ 0`,
`B(x,r) = ∏ᵢ [x i - ⌊r⌋, x i + ⌊r⌋]`. -/
theorem closedBall_int_eq_piFinset (x : Fin n → ℤ) {r : ℝ} (hr : 0 ≤ r) :
    closedBall x r =
      ↑(Fintype.piFinset fun i => Finset.Icc (x i - ⌊r⌋) (x i + ⌊r⌋)) := by
  ext y
  simp only [mem_closedBall, dist_pi_le_iff hr, Int.dist_eq, Fintype.coe_piFinset, Set.mem_pi,
    Set.mem_univ, true_implies, Finset.coe_Icc, Set.mem_Icc]
  refine forall_congr' fun i => ?_
  rw [abs_le]
  have hfl := Int.floor_le r
  constructor
  · rintro ⟨h1, h2⟩
    have h3 : x i - y i ≤ ⌊r⌋ := Int.le_floor.2 (by push_cast; linarith)
    have h4 : y i - x i ≤ ⌊r⌋ := Int.le_floor.2 (by push_cast; linarith)
    constructor <;> linarith
  · rintro ⟨h1, h2⟩
    have h3 : ((x i - y i : ℤ) : ℝ) ≤ ⌊r⌋ := by exact_mod_cast (by linarith : x i - y i ≤ ⌊r⌋)
    have h4 : ((y i - x i : ℤ) : ℝ) ≤ ⌊r⌋ := by exact_mod_cast (by linarith : y i - x i ≤ ⌊r⌋)
    push_cast at h3 h4
    constructor <;> linarith

/-- The number of lattice points of the cube of radius `r ≥ 0`: `(2⌊r⌋ + 1)ⁿ`. -/
theorem count_closedBall_int (x : Fin n → ℤ) {r : ℝ} (hr : 0 ≤ r) :
    Measure.count (closedBall x r) = (((2 * ⌊r⌋ + 1).toNat ^ n : ℕ) : ℝ≥0∞) := by
  classical
  rw [closedBall_int_eq_piFinset n x hr, Measure.count_apply_finset, Fintype.card_piFinset]
  congr 1
  rw [Finset.prod_congr rfl fun i _ => by
      rw [Int.card_Icc, show x i + ⌊r⌋ + 1 - (x i - ⌊r⌋) = 2 * ⌊r⌋ + 1 by ring],
    Finset.prod_const, Finset.card_univ, Fintype.card_fin]

/-- Doubling of counting measure for cubes in `ℤⁿ`, constant `5ⁿ` (all real radii `r ≥ 0`). -/
theorem count_closedBall_three_mul_le_int (x : Fin n → ℤ) (r : ℝ) (hr : 0 ≤ r) :
    Measure.count (closedBall x (3 * r)) ≤
      ((5 ^ n : ℝ≥0) : ℝ≥0∞) * Measure.count (closedBall x r) := by
  rw [count_closedBall_int n x hr, count_closedBall_int n x (by positivity)]
  have h1 : ⌊3 * r⌋ < 3 * ⌊r⌋ + 3 :=
    Int.floor_lt.2 (by push_cast; linarith [Int.lt_floor_add_one r])
  have h0 : 0 ≤ ⌊r⌋ := Int.floor_nonneg.2 hr
  have h2 : (2 * ⌊3 * r⌋ + 1).toNat ≤ 5 * (2 * ⌊r⌋ + 1).toNat := by omega
  have h3 : (2 * ⌊3 * r⌋ + 1).toNat ^ n ≤ 5 ^ n * (2 * ⌊r⌋ + 1).toNat ^ n := by
    rw [← mul_pow]
    exact Nat.pow_le_pow_left h2 n
  have h4 : ((5 ^ n : ℝ≥0) : ℝ≥0∞) = ((5 ^ n : ℕ) : ℝ≥0∞) := by push_cast; rfl
  rw [h4, ← Nat.cast_mul]
  exact_mod_cast h3

/-- The lattice cube `{y | ∀ i, |y i - x i| ≤ R}` of integer radius `R` centered at `x ∈ ℤⁿ`. -/
def intCube {n : ℕ} (x : Fin n → ℤ) (R : ℕ) : Set (Fin n → ℤ) :=
  {y | ∀ i, |y i - x i| ≤ R}

/-- The blueprint's maximal function on `G = ℤⁿ`: the supremum over integer radii `R ≥ 0`
(including `R = 0`) of the averages of `‖f‖` over the centered lattice cubes
`{y | ∀ i, |y i - x i| ≤ R}` with respect to counting measure, valued in `ℝ≥0∞`. -/
def cubeMaximalInt (f : (Fin n → ℤ) → E) (x : Fin n → ℤ) : ℝ≥0∞ :=
  ⨆ R : ℕ, (Measure.count (intCube x R))⁻¹ * ∫⁻ y in intCube x R, ‖f y‖ₑ ∂Measure.count

/-- Lattice cubes are sup-metric balls. -/
theorem intCube_eq_closedBall (x : Fin n → ℤ) (R : ℕ) : intCube x R = closedBall x R := by
  ext y
  simp only [intCube, mem_ofPred_eq, mem_closedBall, dist_pi_le_iff (Nat.cast_nonneg R),
    Int.dist_eq]
  refine forall_congr' fun i => ?_
  constructor
  · intro h
    exact_mod_cast h
  · intro h
    exact_mod_cast h

/-- The lattice cube maximal function is dominated by the ball maximal function. -/
theorem cubeMaximalInt_le_hlMaximal (f : (Fin n → ℤ) → E) (x : Fin n → ℤ) :
    cubeMaximalInt n f x ≤ hlMaximal Measure.count f x :=
  iSup_le fun R => by
    rw [intCube_eq_closedBall]
    exact hlBallAverage_le_hlMaximal _ f x R

/-- **Hardy–Littlewood maximal theorem on `G = ℤⁿ`, weak type `(1,1)`** (Blueprint Lemma 2.4
(`lem:maximal`), weak bound for `X = G`): for the maximal function over centered lattice cubes
of integer radii `R ≥ 0`, every `f` and every `t`, `#{M f > t} ≤ 5ⁿ t⁻¹ ‖f‖₁`. -/
theorem cubeMaximalInt_weak_one (f : (Fin n → ℤ) → E) (t : ℝ≥0∞) :
    Measure.count {x | t < cubeMaximalInt n f x} ≤
      ((5 ^ n : ℝ≥0) : ℝ≥0∞) / t * ∫⁻ y, ‖f y‖ₑ ∂Measure.count :=
  (measure_mono fun x hx => lt_of_lt_of_le hx (cubeMaximalInt_le_hlMaximal n f x)).trans
    (hlMaximal_weak_one_of_countable (count_closedBall_three_mul_le_int n) f t)

/-- **Hardy–Littlewood maximal theorem on `G = ℤⁿ`, strong type `(p,p)`** (Blueprint Lemma 2.4
(`lem:maximal`), strong bound for `X = G`, `1 < p < ∞`): `‖M f‖_p ≤ C_{n,p} ‖f‖_p` with
`C_{n,p} = (2^p p 5ⁿ/(p-1))^(1/p)`. -/
theorem eLpNorm_cubeMaximalInt_le {p : ℝ} (hp : 1 < p) (f : (Fin n → ℤ) → E) :
    eLpNorm (cubeMaximalInt n f) (ENNReal.ofReal p) Measure.count ≤
      hlMaximalConst (5 ^ n) p * eLpNorm f (ENNReal.ofReal p) Measure.count :=
  (eLpNorm_mono_enorm AEStronglyMeasurable.of_discrete fun x => by
      simpa only [enorm_eq_self] using cubeMaximalInt_le_hlMaximal n f x).trans
    (eLpNorm_hlMaximal_le_of_countable (count_closedBall_three_mul_le_int n) hp f)

/-- **Hardy–Littlewood maximal theorem on `G = ℤⁿ`, `L^∞` bound** (Blueprint Lemma 2.4
(`lem:maximal`), `p = ∞` for `X = G`, constant one): `‖M f‖_∞ ≤ ‖f‖_∞`. -/
theorem eLpNorm_cubeMaximalInt_top_le (f : (Fin n → ℤ) → E) :
    eLpNorm (cubeMaximalInt n f) ∞ Measure.count ≤ eLpNorm f ∞ Measure.count :=
  (eLpNorm_mono_enorm AEStronglyMeasurable.of_discrete fun x => by
      simpa only [enorm_eq_self] using cubeMaximalInt_le_hlMaximal n f x).trans
    (eLpNorm_hlMaximal_top_le_of_countable f)

end Lattice

end

end Auto
