/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Khintchine's inequality and the Marcinkiewicz–Zygmund `ℓ²`-valued extension

This file was automatically generated by Claude.

This file proves Khintchine's inequality for Rademacher sums of vectors in an inner product
space and the Marcinkiewicz–Zygmund `ℓ²`-valued extension of `L^p` bounds for additive
operators (Blueprint Lemma 2.6 (`lem:khintchine`, "Rademacher square functions")). It depends
on Mathlib only.

It was adapted from the user's project `lean-discretesw` (file
`DiscreteSW/Auto/KhintchineInequality.lean`); "Blueprint" in the docstrings refers to the
blueprint `blueprints/discrete-sw.tex` of that project.

## Formulation

Independent uniform signs `ε_i ∈ {-1, 1}`, `i ∈ s`, are encoded by the finite uniform
probability space of sign patterns `u ⊆ s` (`ε_i = 1` iff `i ∈ u`):

* `Auto.rademacherSum s u v = ∑_{i ∈ s} ε_i v_i`;
* `Auto.rademacherMean s F = 2^{-|s|} ∑_{u ⊆ s} F u` (the expectation over the signs).

Vectors `v : ι → H` live in a real or complex inner product space (`RCLike 𝕜`,
`InnerProductSpace 𝕜 H`); `S = ∑_{i ∈ s} ‖v_i‖²`. No completeness is needed.

## Main results

* `Auto.khintchine_upper` (upper Khintchine inequality): for `0 < p < ∞`,
  `(𝔼 ‖∑ ε_i v_i‖^p)^{1/p} ≤ C_p S^{1/2}` with `C_p = khintchineUpperConst p = √(4⌈p/2⌉)`.
* `Auto.khintchine_lower` (lower Khintchine inequality): for `0 < p < ∞`,
  `c_p S^{1/2} ≤ (𝔼 ‖∑ ε_i v_i‖^p)^{1/p}` with `c_p = khintchineLowerConst p = 100^{-1/p}/√2 > 0`.
* `Auto.marcinkiewicz_zygmund_square_function` (Marcinkiewicz–Zygmund extension): an additive
  operator `T` on an additive group `D` of functions `α → E` with
  `‖T g‖_{L^p(ν)} ≤ A ‖g‖_{L^p(μ)}` (`g ∈ D`, `0 < p < ∞`) satisfies, for finitely many
  `f_i ∈ D` with `f_i`, `T f_i` a.e.-strongly measurable,
  `‖(∑ |T f_i|²)^{1/2}‖_{L^p(ν)} ≤ (C_p / c_p) A ‖(∑ |f_i|²)^{1/2}‖_{L^p(μ)}`.
  `Auto.marcinkiewicz_zygmund_square_function_of_addMonoidHom` is the variant for `T` defined on
  all functions.

The upper bound is proved via a two-point inequality
`(‖x+a‖²+μ)^n + (‖x-a‖²+μ)^n ≤ 2(‖x‖²+μ+c‖a‖²)^n` (`1 ≤ c`, `4n ≤ c+3`) and induction on `s`,
giving even moments, then the power-mean inequality. The lower bound uses the exact second
moment, the fourth-moment bound `𝔼 ‖∑ ε_i v_i‖⁴ ≤ 25 S²` and a Paley–Zygmund argument.

## References

* A. Khintchine, "Über dyadische Brüche", Math. Z. 18 (1923) 109–116.
* J. Marcinkiewicz and A. Zygmund, "Quelques inégalités pour les opérations linéaires",
  Fund. Math. 32 (1939) 115–121.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., GTM 249, Appendix C and §5.5.
-/

@[expose] public section

namespace Auto

open scoped BigOperators ENNReal NNReal
open MeasureTheory

section Signs

variable {ι : Type*} [DecidableEq ι]

/-- The Rademacher signed sum `∑_{i ∈ s} ε_i v_i` attached to the sign pattern `u ⊆ s`:
`ε_i = 1` if `i ∈ u` and `ε_i = -1` otherwise. -/
def rademacherSum {G : Type*} [AddCommGroup G] (s u : Finset ι) (v : ι → G) : G :=
  ∑ i ∈ s, if i ∈ u then v i else -v i

/-- The uniform average `2^{-|s|} ∑_{u ⊆ s} F u` over all sign patterns on `s`. -/
noncomputable def rademacherMean (s : Finset ι) (F : Finset ι → ℝ) : ℝ :=
  (2 ^ s.card : ℝ)⁻¹ * ∑ u ∈ s.powerset, F u

/-- Additive maps commute with Rademacher signed sums. -/
theorem map_rademacherSum {G G' : Type*} [AddCommGroup G] [AddCommGroup G']
    (φ : G →+ G') (s u : Finset ι) (v : ι → G) :
    φ (rademacherSum s u v) = rademacherSum s u (fun i => φ (v i)) := by
  unfold rademacherSum
  rw [map_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  split_ifs <;> simp

/-- Adding a new index `a` with sign `-1`. -/
theorem rademacherSum_insert_of_subset {G : Type*} [AddCommGroup G] {s u : Finset ι} {a : ι}
    (ha : a ∉ s) (hu : u ⊆ s) (v : ι → G) :
    rademacherSum (insert a s) u v = -v a + rademacherSum s u v := by
  have hau : a ∉ u := fun h => ha (hu h)
  unfold rademacherSum
  rw [Finset.sum_insert ha]
  simp [hau]

/-- Adding a new index `a` with sign `+1`. -/
theorem rademacherSum_insert_insert {G : Type*} [AddCommGroup G] {s u : Finset ι} {a : ι}
    (ha : a ∉ s) (v : ι → G) :
    rademacherSum (insert a s) (insert a u) v = v a + rademacherSum s u v := by
  unfold rademacherSum
  rw [Finset.sum_insert ha]
  simp only [Finset.mem_insert_self, ↓reduceIte]
  congr 1
  refine Finset.sum_congr rfl fun i hi => ?_
  have hia : i ≠ a := fun h => ha (h ▸ hi)
  simp [Finset.mem_insert, hia]

end Signs

/-- Real two-point inequality driving the upper moment bound:
if `w² ≤ 4PA` and `4m ≤ c + 3`, `1 ≤ c`, then
`(P+A+w)^m + (P+A-w)^m ≤ 2 (P + cA)^m`. -/
theorem two_point_pow_aux {P A w c : ℝ} (hP : 0 ≤ P) (hA : 0 ≤ A) (hw : w ^ 2 ≤ 4 * P * A)
    (hc : 1 ≤ c) (hQ : 0 < P + c * A) :
    ∀ m : ℕ, 4 * (m : ℝ) ≤ c + 3 →
      (P + A + w) ^ m + (P + A - w) ^ m ≤ 2 * (P + c * A) ^ m ∧
        (P + c * A) * (w * ((P + A + w) ^ m - (P + A - w) ^ m)) ≤
          2 * m * w ^ 2 * (P + c * A) ^ m := by
  set Q := P + c * A with hQdef
  set u := P + A with hudef
  have huQ : u ≤ Q := by nlinarith
  have hu : 0 ≤ u := by positivity
  intro m
  induction m with
  | zero => intro _; norm_num
  | succ m ih =>
    intro hm
    have hm' : 4 * (m : ℝ) ≤ c + 3 := by push_cast at hm; linarith
    obtain ⟨hF, hG⟩ := ih hm'
    have hQm : 0 ≤ Q ^ m := pow_nonneg hQ.le m
    have hstep1 : (u + w) ^ (m + 1) + (u - w) ^ (m + 1) =
        u * ((u + w) ^ m + (u - w) ^ m) + w * ((u + w) ^ m - (u - w) ^ m) := by ring
    have hstep2 : (u + w) ^ (m + 1) - (u - w) ^ (m + 1) =
        u * ((u + w) ^ m - (u - w) ^ m) + w * ((u + w) ^ m + (u - w) ^ m) := by ring
    have hmc : 4 * (m : ℝ) + 1 ≤ c := by push_cast at hm; linarith
    have hm0 : (0 : ℝ) ≤ m := Nat.cast_nonneg m
    constructor
    · -- Q * F_{m+1} ≤ 2 Q^{m+2}
      have key : Q * ((u + w) ^ (m + 1) + (u - w) ^ (m + 1)) ≤ Q * (2 * Q ^ (m + 1)) := by
        rw [hstep1]
        have h1 : Q * (u * ((u + w) ^ m + (u - w) ^ m)) ≤ Q * (u * (2 * Q ^ m)) :=
          mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left hF hu) hQ.le
        have h2 : u * Q + m * w ^ 2 ≤ Q ^ 2 := by
          have : m * w ^ 2 ≤ m * (4 * P * A) := mul_le_mul_of_nonneg_left hw hm0
          have hPA : 0 ≤ P * A := mul_nonneg hP hA
          have hcc : c ≤ c * c := by nlinarith
          have hid : Q ^ 2 - u * Q - m * (4 * P * A) =
              (c - 4 * m - 1) * (P * A) + (c * c - c) * A ^ 2 := by
            rw [hQdef, hudef]; ring
          nlinarith [mul_le_mul_of_nonneg_left hmc hPA, mul_le_mul_of_nonneg_left hcc (sq_nonneg A)]
        have : Q * (u * ((u + w) ^ m + (u - w) ^ m)) + Q * (w * ((u + w) ^ m - (u - w) ^ m))
            ≤ Q * (u * (2 * Q ^ m)) + 2 * m * w ^ 2 * Q ^ m := by
          linarith
        calc Q * (u * ((u + w) ^ m + (u - w) ^ m) + w * ((u + w) ^ m - (u - w) ^ m))
            = Q * (u * ((u + w) ^ m + (u - w) ^ m)) + Q * (w * ((u + w) ^ m - (u - w) ^ m)) := by
              ring
          _ ≤ Q * (u * (2 * Q ^ m)) + 2 * m * w ^ 2 * Q ^ m := this
          _ = 2 * Q ^ m * (u * Q + m * w ^ 2) := by ring
          _ ≤ 2 * Q ^ m * (Q ^ 2) := by
              exact mul_le_mul_of_nonneg_left h2 (by positivity)
          _ = Q * (2 * Q ^ (m + 1)) := by ring
      exact le_of_mul_le_mul_left key hQ
    · rw [hstep2]
      have hw2 : 0 ≤ w ^ 2 := sq_nonneg w
      have h1 : u * (Q * (w * ((u + w) ^ m - (u - w) ^ m))) ≤ u * (2 * m * w ^ 2 * Q ^ m) :=
        mul_le_mul_of_nonneg_left hG hu
      have h2 : Q * w ^ 2 * ((u + w) ^ m + (u - w) ^ m) ≤ Q * w ^ 2 * (2 * Q ^ m) :=
        mul_le_mul_of_nonneg_left hF (mul_nonneg hQ.le hw2)
      have h3 : u * (2 * m * w ^ 2 * Q ^ m) ≤ Q * (2 * m * w ^ 2 * Q ^ m) :=
        mul_le_mul_of_nonneg_right huQ (by positivity)
      calc Q * (w * (u * ((u + w) ^ m - (u - w) ^ m) + w * ((u + w) ^ m + (u - w) ^ m)))
          = u * (Q * (w * ((u + w) ^ m - (u - w) ^ m))) +
              Q * w ^ 2 * ((u + w) ^ m + (u - w) ^ m) := by ring
        _ ≤ Q * (2 * m * w ^ 2 * Q ^ m) + Q * w ^ 2 * (2 * Q ^ m) := by linarith
        _ = 2 * ((m + 1 : ℕ) : ℝ) * w ^ 2 * Q ^ (m + 1) := by push_cast; ring

section Vectors

variable {ι : Type*} [DecidableEq ι]
variable (𝕜 : Type*) {H : Type*} [RCLike 𝕜] [NormedAddCommGroup H] [InnerProductSpace 𝕜 H]
include 𝕜

/-- Two-point inequality in an inner product space:
`(‖x+a‖²+μ)^n + (‖x-a‖²+μ)^n ≤ 2 (‖x‖²+μ+c‖a‖²)^n` whenever `1 ≤ c` and `4n ≤ c+3`. -/
theorem two_point_norm_pow (x a : H) {μ c : ℝ} (hμ : 0 ≤ μ) (hc : 1 ≤ c) (n : ℕ)
    (hn : 4 * (n : ℝ) ≤ c + 3) :
    (‖x + a‖ ^ 2 + μ) ^ n + (‖x - a‖ ^ 2 + μ) ^ n ≤ 2 * (‖x‖ ^ 2 + μ + c * ‖a‖ ^ 2) ^ n := by
  have hadd := norm_add_sq (𝕜 := 𝕜) x a
  have hsub := norm_sub_sq (𝕜 := 𝕜) x a
  set t := RCLike.re (inner 𝕜 x a) with ht
  have htle : t ^ 2 ≤ (‖x‖ * ‖a‖) ^ 2 := by
    have h1 : |t| ≤ ‖x‖ * ‖a‖ :=
      (RCLike.abs_re_le_norm _).trans (norm_inner_le_norm (𝕜 := 𝕜) x a)
    rw [← sq_abs]
    exact pow_le_pow_left₀ (abs_nonneg _) h1 2
  have hP : 0 ≤ ‖x‖ ^ 2 + μ := by positivity
  have hA : 0 ≤ ‖a‖ ^ 2 := by positivity
  have hw : (2 * t) ^ 2 ≤ 4 * (‖x‖ ^ 2 + μ) * ‖a‖ ^ 2 := by
    have : 0 ≤ μ * ‖a‖ ^ 2 := mul_nonneg hμ hA
    nlinarith
  rcases (show 0 ≤ ‖x‖ ^ 2 + μ + c * ‖a‖ ^ 2 by positivity).lt_or_eq with hQ | hQ
  · have := (two_point_pow_aux hP hA hw hc hQ n hn).1
    have e1 : ‖x + a‖ ^ 2 + μ = ‖x‖ ^ 2 + μ + ‖a‖ ^ 2 + 2 * t := by rw [hadd]; ring
    have e2 : ‖x - a‖ ^ 2 + μ = ‖x‖ ^ 2 + μ + ‖a‖ ^ 2 - 2 * t := by rw [hsub]; ring
    rw [e1, e2]
    exact this
  · have hx : ‖x‖ ^ 2 = 0 := by nlinarith [sq_nonneg ‖x‖, sq_nonneg ‖a‖]
    have ha : ‖a‖ ^ 2 = 0 := by nlinarith [sq_nonneg ‖x‖, sq_nonneg ‖a‖]
    have hμ0 : μ = 0 := by nlinarith [sq_nonneg ‖x‖, sq_nonneg ‖a‖]
    have hx0 : x = 0 := by simpa using hx
    have ha0 : a = 0 := by simpa using ha
    subst hx0 ha0 hμ0
    rcases n with _ | n <;> norm_num

/-- Even-moment bound with a free base point: for `1 ≤ c`, `4n ≤ c+3`, `μ ≥ 0`,
`∑_{u ⊆ s} (‖x + ∑ ε_i v_i‖² + μ)^n ≤ 2^{|s|} (‖x‖² + μ + c ∑ ‖v_i‖²)^n`. -/
theorem sum_powerset_norm_sq_add_pow_le (s : Finset ι) (v : ι → H) {c : ℝ} (hc : 1 ≤ c)
    (n : ℕ) (hn : 4 * (n : ℝ) ≤ c + 3) :
    ∀ (x : H) (μ : ℝ), 0 ≤ μ →
      ∑ u ∈ s.powerset, (‖x + rademacherSum s u v‖ ^ 2 + μ) ^ n ≤
        2 ^ s.card * (‖x‖ ^ 2 + μ + c * ∑ i ∈ s, ‖v i‖ ^ 2) ^ n := by
  induction s using Finset.induction_on with
  | empty => intro x μ _; simp [rademacherSum]
  | @insert a s ha ih =>
    intro x μ hμ
    rw [Finset.sum_powerset_insert ha]
    have e1 : ∀ u ∈ s.powerset, (‖x + rademacherSum (insert a s) u v‖ ^ 2 + μ) ^ n =
        (‖(x - v a) + rademacherSum s u v‖ ^ 2 + μ) ^ n := by
      intro u hu
      rw [rademacherSum_insert_of_subset ha (Finset.mem_powerset.mp hu)]
      rw [sub_eq_add_neg, add_assoc]
    have e2 : ∀ u ∈ s.powerset, (‖x + rademacherSum (insert a s) (insert a u) v‖ ^ 2 + μ) ^ n =
        (‖(x + v a) + rademacherSum s u v‖ ^ 2 + μ) ^ n := by
      intro u _
      rw [rademacherSum_insert_insert ha]
      rw [add_assoc]
    rw [Finset.sum_congr rfl e1, Finset.sum_congr rfl e2]
    set S := ∑ i ∈ s, ‖v i‖ ^ 2
    have hS : 0 ≤ S := Finset.sum_nonneg fun i _ => sq_nonneg _
    have hμ' : 0 ≤ μ + c * S := by nlinarith
    have htp := two_point_norm_pow 𝕜 x (v a) hμ' hc n hn
    calc _ ≤ 2 ^ s.card * (‖x - v a‖ ^ 2 + μ + c * S) ^ n +
          2 ^ s.card * (‖x + v a‖ ^ 2 + μ + c * S) ^ n := add_le_add (ih _ _ hμ) (ih _ _ hμ)
      _ = 2 ^ s.card * ((‖x + v a‖ ^ 2 + (μ + c * S)) ^ n +
          (‖x - v a‖ ^ 2 + (μ + c * S)) ^ n) := by ring
      _ ≤ 2 ^ s.card * (2 * (‖x‖ ^ 2 + (μ + c * S) + c * ‖v a‖ ^ 2) ^ n) :=
          mul_le_mul_of_nonneg_left htp (by positivity)
      _ = _ := by
          rw [Finset.card_insert_of_notMem ha, Finset.sum_insert ha, pow_succ]
          ring

/-- Exact second moment with a free base point:
`∑_{u ⊆ s} ‖x + ∑ ε_i v_i‖² = 2^{|s|} (‖x‖² + ∑ ‖v_i‖²)`. -/
theorem sum_powerset_norm_add_sq (s : Finset ι) (v : ι → H) :
    ∀ x : H, ∑ u ∈ s.powerset, ‖x + rademacherSum s u v‖ ^ 2 =
      2 ^ s.card * (‖x‖ ^ 2 + ∑ i ∈ s, ‖v i‖ ^ 2) := by
  induction s using Finset.induction_on with
  | empty => intro x; simp [rademacherSum]
  | @insert a s ha ih =>
    intro x
    rw [Finset.sum_powerset_insert ha]
    have e1 : ∀ u ∈ s.powerset, ‖x + rademacherSum (insert a s) u v‖ ^ 2 =
        ‖(x - v a) + rademacherSum s u v‖ ^ 2 := by
      intro u hu
      rw [rademacherSum_insert_of_subset ha (Finset.mem_powerset.mp hu)]
      rw [sub_eq_add_neg, add_assoc]
    have e2 : ∀ u ∈ s.powerset, ‖x + rademacherSum (insert a s) (insert a u) v‖ ^ 2 =
        ‖(x + v a) + rademacherSum s u v‖ ^ 2 := by
      intro u _
      rw [rademacherSum_insert_insert ha]
      rw [add_assoc]
    rw [Finset.sum_congr rfl e1, Finset.sum_congr rfl e2, ih, ih,
      Finset.card_insert_of_notMem ha, Finset.sum_insert ha, pow_succ]
    have hadd := norm_add_sq (𝕜 := 𝕜) x (v a)
    have hsub := norm_sub_sq (𝕜 := 𝕜) x (v a)
    linear_combination (2 : ℝ) ^ s.card * (hsub + hadd)

/-- Exact second moment: `∑_{u ⊆ s} ‖∑ ε_i v_i‖² = 2^{|s|} ∑ ‖v_i‖²`. -/
theorem sum_powerset_norm_rademacherSum_sq (s : Finset ι) (v : ι → H) :
    ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ ^ 2 = 2 ^ s.card * ∑ i ∈ s, ‖v i‖ ^ 2 := by
  simpa using sum_powerset_norm_add_sq 𝕜 s v 0

/-- Even moments: `∑_{u ⊆ s} ‖∑ ε_i v_i‖^{2n} ≤ 2^{|s|} (c ∑ ‖v_i‖²)^n` for `1 ≤ c`, `4n ≤ c+3`. -/
theorem sum_powerset_norm_rademacherSum_pow_le (s : Finset ι) (v : ι → H) {c : ℝ}
    (hc : 1 ≤ c) (n : ℕ) (hn : 4 * (n : ℝ) ≤ c + 3) :
    ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ ^ (2 * n) ≤
      2 ^ s.card * (c * ∑ i ∈ s, ‖v i‖ ^ 2) ^ n := by
  have := sum_powerset_norm_sq_add_pow_le 𝕜 s v hc n hn 0 0 le_rfl
  simpa [pow_mul] using this

/-- The explicit upper Khintchine constant `C_p = √(4 ⌈p/2⌉)`. -/
noncomputable def khintchineUpperConst (p : ℝ) : ℝ := Real.sqrt (4 * (⌈p / 2⌉₊ : ℝ))

/-- The explicit lower Khintchine constant `c_p = 100^{-1/p} / √2`. -/
noncomputable def khintchineLowerConst (p : ℝ) : ℝ := (1 / 100 : ℝ) ^ (1 / p) / Real.sqrt 2

omit 𝕜 in
/-- Positivity of the upper Khintchine constant. -/
theorem khintchineUpperConst_pos {p : ℝ} (hp : 0 < p) : 0 < khintchineUpperConst p := by
  unfold khintchineUpperConst
  have : (0 : ℝ) < ⌈p / 2⌉₊ := by exact_mod_cast Nat.ceil_pos.mpr (half_pos hp)
  positivity

omit 𝕜 in
/-- Positivity of the lower Khintchine constant. -/
theorem khintchineLowerConst_pos (p : ℝ) : 0 < khintchineLowerConst p := by
  unfold khintchineLowerConst
  positivity

/-- Upper Khintchine inequality, `p`-th power form:
`2^{-|s|} ∑_{u ⊆ s} ‖∑ ε_i v_i‖^p ≤ (C_p (∑ ‖v_i‖²)^{1/2})^p` for `0 < p`. -/
theorem khintchine_upper_rpow (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p) ≤
      (khintchineUpperConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)) ^ p := by
  set n := ⌈p / 2⌉₊ with hndef
  have hn1 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr (Nat.ceil_pos.mpr (half_pos hp)).ne'
  have hn1' : (1 : ℝ) ≤ n := by exact_mod_cast hn1
  set c : ℝ := 4 * (n : ℝ) with hcdef
  have hc : 1 ≤ c := by linarith
  have hnc : 4 * (n : ℝ) ≤ c + 3 := by linarith
  set S := ∑ i ∈ s, ‖v i‖ ^ 2 with hSdef
  have hS : 0 ≤ S := Finset.sum_nonneg fun i _ => sq_nonneg _
  set N : ℝ := 2 ^ s.card with hNdef
  have hN : 0 < N := by positivity
  have heven := sum_powerset_norm_rademacherSum_pow_le 𝕜 s v hc n hnc
  set q : ℝ := 2 * n / p with hqdef
  have hpn : p ≤ 2 * n := by
    have := Nat.le_ceil (p / 2)
    rw [← hndef] at this
    linarith
  have hq : 1 ≤ q := by rw [hqdef, le_div_iff₀ hp]; linarith
  have hq0 : 0 < q := by linarith
  have hw : ∑ _u ∈ s.powerset, N⁻¹ = 1 := by
    rw [Finset.sum_const, Finset.card_powerset, nsmul_eq_mul]
    push_cast
    exact mul_inv_cancel₀ hN.ne'
  have hpm := Real.rpow_arith_mean_le_arith_mean_rpow s.powerset (fun _ => N⁻¹)
    (fun u => ‖rademacherSum s u v‖ ^ p) (fun _ _ => (inv_pos.mpr hN).le) hw
    (fun _ _ => Real.rpow_nonneg (norm_nonneg _) _) hq
  have hzq : ∀ u : Finset ι,
      (‖rademacherSum s u v‖ ^ p) ^ q = ‖rademacherSum s u v‖ ^ (2 * n) := by
    intro u
    rw [← Real.rpow_mul (norm_nonneg _), hqdef, mul_div_cancel₀ _ hp.ne', ← Real.rpow_natCast]
    push_cast; ring_nf
  simp only [hzq] at hpm
  rw [← Finset.mul_sum, ← Finset.mul_sum] at hpm
  have hM : 0 ≤ rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p) := by
    unfold rademacherMean
    exact mul_nonneg (inv_nonneg.mpr (by positivity))
      (Finset.sum_nonneg fun _ _ => Real.rpow_nonneg (norm_nonneg _) _)
  have hMq : (rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)) ^ q ≤ (c * S) ^ n := by
    unfold rademacherMean
    refine hpm.trans ?_
    rw [inv_mul_le_iff₀ hN]
    exact heven
  have hcS : 0 ≤ c * S := by positivity
  calc rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)
      = ((rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)) ^ q) ^ q⁻¹ :=
        (Real.rpow_rpow_inv hM hq0.ne').symm
    _ ≤ ((c * S) ^ n) ^ q⁻¹ :=
        Real.rpow_le_rpow (Real.rpow_nonneg hM _) hMq (inv_nonneg.mpr hq0.le)
    _ = (khintchineUpperConst p * Real.sqrt S) ^ p := by
        unfold khintchineUpperConst
        rw [← hndef, ← hcdef, ← Real.sqrt_mul (by positivity), Real.sqrt_eq_rpow,
          ← Real.rpow_mul hcS, ← Real.rpow_natCast, ← Real.rpow_mul hcS, hqdef]
        congr 1
        field_simp

/-- Upper Khintchine inequality (Blueprint Lemma 2.6 (`lem:khintchine`), upper bound):
for vectors `v_i` in a real or complex inner product space and `0 < p < ∞`,
`(𝔼_ε ‖∑_{i ∈ s} ε_i v_i‖^p)^{1/p} ≤ C_p (∑_{i ∈ s} ‖v_i‖²)^{1/2}`, where the expectation is the
uniform average over the `2^{|s|}` sign patterns and `C_p = khintchineUpperConst p` depends
only on `p`. -/
theorem khintchine_upper (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    (rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)) ^ (1 / p) ≤
      khintchineUpperConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2) := by
  have hC := (khintchineUpperConst_pos hp).le
  have hM : 0 ≤ rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p) := by
    unfold rademacherMean
    exact mul_nonneg (inv_nonneg.mpr (by positivity))
      (Finset.sum_nonneg fun _ _ => Real.rpow_nonneg (norm_nonneg _) _)
  calc _ ≤ ((khintchineUpperConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)) ^ p) ^ (1 / p) :=
        Real.rpow_le_rpow hM (khintchine_upper_rpow 𝕜 s v hp) (by positivity)
    _ = _ := by rw [one_div, Real.rpow_rpow_inv (by positivity) hp.ne']

/-- Finite Paley–Zygmund lower moment estimate:
`2^{|s|}/100 · (S/2)^{p/2} ≤ ∑_{u ⊆ s} ‖∑ ε_i v_i‖^p`, `S = ∑ ‖v_i‖²`, for `p ≥ 0`. -/
theorem sum_powerset_norm_rademacherSum_rpow_ge (s : Finset ι) (v : ι → H) {p : ℝ}
    (hp : 0 ≤ p) :
    (2 ^ s.card : ℝ) / 100 * ((∑ i ∈ s, ‖v i‖ ^ 2) / 2) ^ (p / 2) ≤
      ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ ^ p := by
  classical
  let X : Finset ι → ℝ := fun u => ‖rademacherSum s u v‖ ^ 2
  set S : ℝ := ∑ i ∈ s, ‖v i‖ ^ 2 with hSdef
  set n : ℝ := 2 ^ s.card with hndef
  let good : Finset (Finset ι) := s.powerset.filter (fun u => S / 2 ≤ X u)
  let bad : Finset (Finset ι) := s.powerset.filter (fun u => ¬ S / 2 ≤ X u)
  have hXnonneg (u : Finset ι) : 0 ≤ X u := sq_nonneg _
  have hS : 0 ≤ S := Finset.sum_nonneg fun i _ => sq_nonneg _
  have hn : 0 < n := by positivity
  have hcardpow : ((s.powerset.card : ℕ) : ℝ) = n := by
    rw [Finset.card_powerset]; push_cast; rfl
  have hgoodsub : good ⊆ s.powerset := Finset.filter_subset _ _
  have hbadsub : bad ⊆ s.powerset := Finset.filter_subset _ _
  have hbadbound : (∑ u ∈ bad, X u) ≤ n * (S / 2) := by
    calc (∑ u ∈ bad, X u) ≤ ∑ _u ∈ bad, S / 2 := by
          apply Finset.sum_le_sum
          intro u hu
          exact le_of_lt (lt_of_not_ge (Finset.mem_filter.mp hu).2)
      _ = (bad.card : ℝ) * (S / 2) := by rw [Finset.sum_const, nsmul_eq_mul]
      _ ≤ n * (S / 2) := by
          apply mul_le_mul_of_nonneg_right _ (by positivity)
          rw [← hcardpow]
          exact_mod_cast Finset.card_le_card hbadsub
  have htotal : (∑ u ∈ s.powerset, X u) = n * S :=
    sum_powerset_norm_rademacherSum_sq 𝕜 s v
  have hsplit : (∑ u ∈ good, X u) + (∑ u ∈ bad, X u) = ∑ u ∈ s.powerset, X u :=
    Finset.sum_filter_add_sum_filter_not _ _ _
  have hgoodsum : n * S / 2 ≤ ∑ u ∈ good, X u := by
    nlinarith [hbadbound, hsplit, htotal]
  have hfour : (∑ u ∈ s.powerset, X u ^ 2) ≤ 25 * n * S ^ 2 := by
    have h := sum_powerset_norm_rademacherSum_pow_le 𝕜 s v (c := 5) (by norm_num) 2
      (by norm_num)
    calc (∑ u ∈ s.powerset, X u ^ 2)
        = ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ ^ (2 * 2) := by
          refine Finset.sum_congr rfl fun u _ => ?_
          simp only [X, ← pow_mul]
      _ ≤ n * (5 * S) ^ 2 := h
      _ = 25 * n * S ^ 2 := by ring
  have hgoodfour : (∑ u ∈ good, X u ^ 2) ≤ 25 * n * S ^ 2 :=
    (Finset.sum_le_sum_of_subset_of_nonneg hgoodsub fun u _ _ => sq_nonneg _).trans hfour
  have hgoodcard : n / 100 ≤ (good.card : ℝ) := by
    by_cases hSzero : S = 0
    · have hgoodeq : good = s.powerset := by
        apply Finset.Subset.antisymm hgoodsub
        intro u hu
        refine Finset.mem_filter.mpr ⟨hu, ?_⟩
        simpa [hSzero] using hXnonneg u
      rw [hgoodeq, hcardpow]
      linarith
    · have hSpos : 0 < S := lt_of_le_of_ne hS (Ne.symm hSzero)
      have hGnonneg : 0 ≤ ∑ u ∈ good, X u := Finset.sum_nonneg fun u _ => hXnonneg u
      have hsquare : (n * S / 2) ^ 2 ≤ (∑ u ∈ good, X u) ^ 2 :=
        (sq_le_sq₀ (by positivity) hGnonneg).mpr hgoodsum
      have hcs := sq_sum_le_card_mul_sum_sq (s := good) (f := X)
      have hcs' : (∑ u ∈ good, X u) ^ 2 ≤ (good.card : ℝ) * (25 * n * S ^ 2) :=
        hcs.trans (mul_le_mul_of_nonneg_left hgoodfour (Nat.cast_nonneg _))
      have hfactor : (n * S ^ 2) * (n / 4) ≤ (n * S ^ 2) * (25 * (good.card : ℝ)) := by
        calc (n * S ^ 2) * (n / 4) = (n * S / 2) ^ 2 := by ring
          _ ≤ (∑ u ∈ good, X u) ^ 2 := hsquare
          _ ≤ (good.card : ℝ) * (25 * n * S ^ 2) := hcs'
          _ = (n * S ^ 2) * (25 * (good.card : ℝ)) := by ring
      have hlinear : n / 4 ≤ 25 * (good.card : ℝ) :=
        le_of_mul_le_mul_left hfactor (mul_pos hn (pow_pos hSpos 2))
      linarith
  have hpoint (u : Finset ι) (hu : u ∈ good) :
      (S / 2) ^ (p / 2) ≤ ‖rademacherSum s u v‖ ^ p := by
    have hthreshold : S / 2 ≤ X u := (Finset.mem_filter.mp hu).2
    calc (S / 2) ^ (p / 2) ≤ (X u) ^ (p / 2) :=
          Real.rpow_le_rpow (by positivity) hthreshold (by positivity)
      _ = ‖rademacherSum s u v‖ ^ p := by
          simp only [X]
          rw [← Real.rpow_natCast, ← Real.rpow_mul (norm_nonneg _)]
          congr 1
          push_cast; ring
  calc n / 100 * (S / 2) ^ (p / 2) ≤ (good.card : ℝ) * (S / 2) ^ (p / 2) :=
        mul_le_mul_of_nonneg_right hgoodcard (Real.rpow_nonneg (by positivity) _)
    _ = ∑ _u ∈ good, (S / 2) ^ (p / 2) := by rw [Finset.sum_const, nsmul_eq_mul]
    _ ≤ ∑ u ∈ good, ‖rademacherSum s u v‖ ^ p := Finset.sum_le_sum hpoint
    _ ≤ ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ ^ p :=
        Finset.sum_le_sum_of_subset_of_nonneg hgoodsub fun _ _ _ =>
          Real.rpow_nonneg (norm_nonneg _) _

/-- Lower Khintchine inequality, `p`-th power form:
`(c_p (∑ ‖v_i‖²)^{1/2})^p ≤ 2^{-|s|} ∑_{u ⊆ s} ‖∑ ε_i v_i‖^p` for `0 < p`. -/
theorem khintchine_lower_rpow (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    (khintchineLowerConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)) ^ p ≤
      rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p) := by
  set S := ∑ i ∈ s, ‖v i‖ ^ 2 with hSdef
  have hS : 0 ≤ S := Finset.sum_nonneg fun i _ => sq_nonneg _
  have h := sum_powerset_norm_rademacherSum_rpow_ge 𝕜 s v hp.le
  rw [← hSdef] at h
  have hN : (0 : ℝ) < 2 ^ s.card := by positivity
  have hid : (khintchineLowerConst p * Real.sqrt S) ^ p = 1 / 100 * (S / 2) ^ (p / 2) := by
    unfold khintchineLowerConst
    rw [div_mul_eq_mul_div, mul_div_assoc, ← Real.sqrt_div hS,
      Real.mul_rpow (by positivity) (by positivity), ← Real.rpow_mul (by norm_num),
      one_div_mul_cancel hp.ne', Real.rpow_one, Real.sqrt_eq_rpow,
      ← Real.rpow_mul (by positivity)]
    congr 2
    ring
  rw [hid]
  unfold rademacherMean
  rw [le_inv_mul_iff₀ hN]
  calc (2 : ℝ) ^ s.card * (1 / 100 * (S / 2) ^ (p / 2))
      = 2 ^ s.card / 100 * (S / 2) ^ (p / 2) := by ring
    _ ≤ _ := h

/-- Lower Khintchine inequality (Blueprint Lemma 2.6 (`lem:khintchine`), lower bound):
for vectors `v_i` in a real or complex inner product space and `0 < p < ∞`,
`c_p (∑_{i ∈ s} ‖v_i‖²)^{1/2} ≤ (𝔼_ε ‖∑_{i ∈ s} ε_i v_i‖^p)^{1/p}`, where the expectation is the
uniform average over the `2^{|s|}` sign patterns and `c_p = khintchineLowerConst p > 0` depends
only on `p`. -/
theorem khintchine_lower (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    khintchineLowerConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2) ≤
      (rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)) ^ (1 / p) := by
  have hc := (khintchineLowerConst_pos p).le
  calc _ = ((khintchineLowerConst p * Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)) ^ p) ^ (1 / p) := by
        rw [one_div, Real.rpow_rpow_inv (by positivity) hp.ne']
    _ ≤ _ := Real.rpow_le_rpow (by positivity) (khintchine_lower_rpow 𝕜 s v hp) (by positivity)

end Vectors

section Extended

variable {ι : Type*} [DecidableEq ι]

/-- Rewriting the extended-real Rademacher average as `ENNReal.ofReal` of the real one. -/
theorem rademacher_enorm_avg_eq {H : Type*} [NormedAddCommGroup H] (s : Finset ι) (v : ι → H)
    {p : ℝ} (hp : 0 ≤ p) :
    (2 ^ s.card : ℝ≥0∞)⁻¹ * ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ₑ ^ p =
      ENNReal.ofReal (rademacherMean s (fun u => ‖rademacherSum s u v‖ ^ p)) := by
  unfold rademacherMean
  rw [ENNReal.ofReal_mul (inv_nonneg.mpr (by positivity)),
    ENNReal.ofReal_inv_of_pos (by positivity), ENNReal.ofReal_sum_of_nonneg
      (fun _ _ => Real.rpow_nonneg (norm_nonneg _) _)]
  congr 1
  · rw [ENNReal.ofReal_pow (by norm_num)]; simp
  · refine Finset.sum_congr rfl fun u _ => ?_
    rw [← ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) hp, ofReal_norm]

/-- Rewriting `(ofReal c · ‖√S‖ₑ)^p` as `ofReal ((c √S)^p)`. -/
theorem rademacher_enorm_sqrt_eq {c S p : ℝ} (hc : 0 ≤ c) (hp : 0 ≤ p) :
    (ENNReal.ofReal c * ‖Real.sqrt S‖ₑ) ^ p = ENNReal.ofReal ((c * Real.sqrt S) ^ p) := by
  rw [Real.enorm_eq_ofReal (Real.sqrt_nonneg _), ← ENNReal.ofReal_mul hc,
    ENNReal.ofReal_rpow_of_nonneg (mul_nonneg hc (Real.sqrt_nonneg _)) hp]

variable (𝕜 : Type*) {H : Type*} [RCLike 𝕜] [NormedAddCommGroup H] [InnerProductSpace 𝕜 H]
include 𝕜

/-- Pointwise lower Khintchine inequality in `ℝ≥0∞` form, used for the vector extension. -/
theorem khintchine_lower_enorm (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    (ENNReal.ofReal (khintchineLowerConst p) * ‖Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)‖ₑ) ^ p ≤
      (2 ^ s.card : ℝ≥0∞)⁻¹ * ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ₑ ^ p := by
  rw [rademacher_enorm_avg_eq s v hp.le,
    rademacher_enorm_sqrt_eq (khintchineLowerConst_pos p).le hp.le]
  exact ENNReal.ofReal_le_ofReal (khintchine_lower_rpow 𝕜 s v hp)

/-- Pointwise upper Khintchine inequality in `ℝ≥0∞` form, used for the vector extension. -/
theorem khintchine_upper_enorm (s : Finset ι) (v : ι → H) {p : ℝ} (hp : 0 < p) :
    (2 ^ s.card : ℝ≥0∞)⁻¹ * ∑ u ∈ s.powerset, ‖rademacherSum s u v‖ₑ ^ p ≤
      (ENNReal.ofReal (khintchineUpperConst p) * ‖Real.sqrt (∑ i ∈ s, ‖v i‖ ^ 2)‖ₑ) ^ p := by
  rw [rademacher_enorm_avg_eq s v hp.le,
    rademacher_enorm_sqrt_eq (khintchineUpperConst_pos hp).le hp.le]
  exact ENNReal.ofReal_le_ofReal (khintchine_upper_rpow 𝕜 s v hp)

end Extended

section MarcinkiewiczZygmund

variable {ι : Type*}

/-- A.e.-strong measurability of a Rademacher signed sum of a.e.-strongly measurable functions. -/
theorem aestronglyMeasurable_rademacherSum [DecidableEq ι] {α E : Type*} [MeasurableSpace α]
    {μ : Measure α}
    [NormedAddCommGroup E] (s u : Finset ι) (f : ι → α → E)
    (hf : ∀ i ∈ s, AEStronglyMeasurable (f i) μ) :
    AEStronglyMeasurable (fun x => rademacherSum s u (fun i => f i x)) μ := by
  unfold rademacherSum
  refine Finset.aestronglyMeasurable_fun_sum s fun i hi => ?_
  by_cases h : i ∈ u
  · simpa [h] using hf i hi
  · simp only [h, ↓reduceIte]
    exact (hf i hi).neg

/-- A.e.-strong measurability of the square function `x ↦ (∑_{i∈s} ‖f_i x‖²)^{1/2}`. -/
theorem aestronglyMeasurable_sqrt_sum_norm_sq {α E : Type*} [MeasurableSpace α]
    {μ : Measure α} [NormedAddCommGroup E] (s : Finset ι) (f : ι → α → E)
    (hf : ∀ i ∈ s, AEStronglyMeasurable (f i) μ) :
    AEStronglyMeasurable (fun x => Real.sqrt (∑ i ∈ s, ‖f i x‖ ^ 2)) μ :=
  Real.continuous_sqrt.comp_aestronglyMeasurable
    (Finset.aestronglyMeasurable_fun_sum s fun i hi => (hf i hi).norm.pow 2)

/-- `x^{1/p} ≤ A · y^{1/p}` implies `x ≤ A^p · y` in `ℝ≥0∞`, for `0 < p`. -/
theorem ennreal_le_rpow_mul_of_rpow_le {x y A : ℝ≥0∞} {p : ℝ} (hp : 0 < p)
    (h : x ^ (1 / p) ≤ A * y ^ (1 / p)) : x ≤ A ^ p * y := by
  have h' := ENNReal.rpow_le_rpow h hp.le
  rwa [ENNReal.mul_rpow_of_nonneg _ _ hp.le, one_div, ENNReal.rpow_inv_rpow hp.ne',
    ENNReal.rpow_inv_rpow hp.ne'] at h'

/-- Marcinkiewicz–Zygmund `ℓ²`-valued extension (Blueprint Lemma 2.6 (`lem:khintchine`),
operator assertion). Let `D` be an additive group of functions `α → E` and `T : D → (β → F)`
additive (in particular any linear operator on a space of functions), where `E`, `F` are real
or complex inner product spaces, and let `0 < p < ∞`. If `‖T g‖_{L^p(ν)} ≤ A ‖g‖_{L^p(μ)}` for
all `g ∈ D`, then for every finite family `f_i ∈ D` (`i ∈ s`) with each `f_i` and each `T f_i`
a.e.-strongly measurable,
`‖(∑_{i∈s} |T f_i|²)^{1/2}‖_{L^p(ν)} ≤ (C_p / c_p) · A · ‖(∑_{i∈s} |f_i|²)^{1/2}‖_{L^p(μ)}`,
where `C_p = khintchineUpperConst p` and `c_p = khintchineLowerConst p` depend only on `p`. -/
theorem marcinkiewicz_zygmund_square_function
    (𝕜 𝕜' : Type*) [RCLike 𝕜] [RCLike 𝕜']
    {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ : Measure α} {ν : Measure β}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [NormedAddCommGroup F] [InnerProductSpace 𝕜' F]
    (D : AddSubgroup (α → E)) (T : D →+ (β → F)) {p : ℝ} (hp : 0 < p) (A : ℝ≥0)
    (hT : ∀ g : D, eLpNorm (T g) (ENNReal.ofReal p) ν ≤
      A * eLpNorm (g : α → E) (ENNReal.ofReal p) μ)
    (s : Finset ι) (f : ι → D)
    (hf : ∀ i ∈ s, AEStronglyMeasurable (f i : α → E) μ)
    (hTf : ∀ i ∈ s, AEStronglyMeasurable (T (f i)) ν) :
    eLpNorm (fun y => Real.sqrt (∑ i ∈ s, ‖T (f i) y‖ ^ 2)) (ENNReal.ofReal p) ν ≤
      ENNReal.ofReal (khintchineUpperConst p / khintchineLowerConst p) * A *
        eLpNorm (fun x => Real.sqrt (∑ i ∈ s, ‖(f i : α → E) x‖ ^ 2)) (ENNReal.ofReal p) μ := by
  classical
  set P := ENNReal.ofReal p with hPdef
  have hP0 : P ≠ 0 := (ENNReal.ofReal_pos.mpr hp).ne'
  have hPtop : P ≠ ∞ := ENNReal.ofReal_ne_top
  have hPr : P.toReal = p := ENNReal.toReal_ofReal hp.le
  let g : Finset ι → D := fun u => rademacherSum s u f
  have hg : ∀ u x, (g u : α → E) x = rademacherSum s u (fun i => (f i : α → E) x) := by
    intro u x
    have := map_rademacherSum ((Pi.evalAddMonoidHom (fun _ : α => E) x).comp D.subtype) s u f
    simpa [g] using this
  have hTg : ∀ u y, T (g u) y = rademacherSum s u (fun i => T (f i) y) := by
    intro u y
    have := map_rademacherSum ((Pi.evalAddMonoidHom (fun _ : β => F) y).comp T) s u f
    simpa [g] using this
  have hgm : ∀ u, AEStronglyMeasurable (g u : α → E) μ := by
    intro u
    have h := aestronglyMeasurable_rademacherSum s u (fun i => (f i : α → E)) hf
    have he : (g u : α → E) = fun x => rademacherSum s u (fun i => (f i : α → E) x) :=
      funext (hg u)
    rwa [he]
  have hTgm : ∀ u, AEStronglyMeasurable (T (g u)) ν := by
    intro u
    have h := aestronglyMeasurable_rademacherSum s u (fun i => T (f i)) hTf
    have he : T (g u) = fun y => rademacherSum s u (fun i => T (f i) y) := funext (hTg u)
    rwa [he]
  -- the scalar bound for every sign pattern, raised to the power `p`
  have hstep : ∀ u, ∫⁻ y, ‖T (g u) y‖ₑ ^ p ∂ν ≤
      (A : ℝ≥0∞) ^ p * ∫⁻ x, ‖(g u : α → E) x‖ₑ ^ p ∂μ := by
    intro u
    have h := hT (g u)
    rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hP0 hPtop (hTgm u),
      eLpNorm_eq_lintegral_rpow_enorm_toReal hP0 hPtop (hgm u), hPr] at h
    exact ennreal_le_rpow_mul_of_rpow_le hp h
  set cL := ENNReal.ofReal (khintchineLowerConst p) with hcL
  set CU := ENNReal.ofReal (khintchineUpperConst p) with hCU
  set N : ℝ≥0∞ := (2 ^ s.card : ℝ≥0∞)⁻¹ with hN
  have hNtop : N ≠ ∞ := ENNReal.inv_ne_top.mpr (by positivity)
  set G := fun y => Real.sqrt (∑ i ∈ s, ‖T (f i) y‖ ^ 2) with hG
  set Fsq := fun x => Real.sqrt (∑ i ∈ s, ‖(f i : α → E) x‖ ^ 2) with hFsq
  have hGm : AEStronglyMeasurable G ν := aestronglyMeasurable_sqrt_sum_norm_sq s _ hTf
  have hFm : AEStronglyMeasurable Fsq μ := aestronglyMeasurable_sqrt_sum_norm_sq s _ hf
  have hmain : cL ^ p * ∫⁻ y, ‖G y‖ₑ ^ p ∂ν ≤
      (A : ℝ≥0∞) ^ p * CU ^ p * ∫⁻ x, ‖Fsq x‖ₑ ^ p ∂μ := by
    calc cL ^ p * ∫⁻ y, ‖G y‖ₑ ^ p ∂ν = ∫⁻ y, (cL * ‖G y‖ₑ) ^ p ∂ν := by
          rw [← lintegral_const_mul' _ _ (ENNReal.rpow_ne_top_of_nonneg hp.le
            ENNReal.ofReal_ne_top)]
          refine lintegral_congr fun y => ?_
          rw [ENNReal.mul_rpow_of_nonneg _ _ hp.le]
      _ ≤ ∫⁻ y, N * ∑ u ∈ s.powerset, ‖T (g u) y‖ₑ ^ p ∂ν := by
          refine lintegral_mono fun y => ?_
          simp only [hTg]
          exact khintchine_lower_enorm 𝕜' s (fun i => T (f i) y) hp
      _ = N * ∑ u ∈ s.powerset, ∫⁻ y, ‖T (g u) y‖ₑ ^ p ∂ν := by
          rw [lintegral_const_mul' _ _ hNtop, lintegral_finsetSum']
          intro u _
          exact ((hTgm u).enorm.pow_const p)
      _ ≤ N * ∑ u ∈ s.powerset, (A : ℝ≥0∞) ^ p * ∫⁻ x, ‖(g u : α → E) x‖ₑ ^ p ∂μ := by
          gcongr with u
          exact hstep u
      _ = (A : ℝ≥0∞) ^ p * ∫⁻ x, N * ∑ u ∈ s.powerset, ‖(g u : α → E) x‖ₑ ^ p ∂μ := by
          rw [lintegral_const_mul' _ _ hNtop, lintegral_finsetSum', ← Finset.mul_sum]
          · ring
          intro u _
          exact ((hgm u).enorm.pow_const p)
      _ ≤ (A : ℝ≥0∞) ^ p * ∫⁻ x, (CU * ‖Fsq x‖ₑ) ^ p ∂μ := by
          gcongr with x
          simp only [hg]
          exact khintchine_upper_enorm 𝕜 s (fun i => (f i : α → E) x) hp
      _ = (A : ℝ≥0∞) ^ p * CU ^ p * ∫⁻ x, ‖Fsq x‖ₑ ^ p ∂μ := by
          rw [mul_assoc, ← lintegral_const_mul' _ _ (ENNReal.rpow_ne_top_of_nonneg hp.le
            ENNReal.ofReal_ne_top)]
          congr 1
          refine lintegral_congr fun x => ?_
          rw [ENNReal.mul_rpow_of_nonneg _ _ hp.le]
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hP0 hPtop hGm,
    eLpNorm_eq_lintegral_rpow_enorm_toReal hP0 hPtop hFm, hPr]
  have hcLpos : 0 < khintchineLowerConst p := khintchineLowerConst_pos p
  have hcL0 : cL ≠ 0 := (ENNReal.ofReal_pos.mpr hcLpos).ne'
  have hcLtop : cL ≠ ∞ := ENNReal.ofReal_ne_top
  have h1 := ENNReal.rpow_le_rpow hmain (by positivity : 0 ≤ 1 / p)
  rw [ENNReal.mul_rpow_of_nonneg _ _ (by positivity : 0 ≤ 1 / p),
    ENNReal.mul_rpow_of_nonneg _ _ (by positivity : 0 ≤ 1 / p),
    ENNReal.mul_rpow_of_nonneg _ _ (by positivity : 0 ≤ 1 / p), one_div,
    ENNReal.rpow_rpow_inv hp.ne', ENNReal.rpow_rpow_inv hp.ne',
    ENNReal.rpow_rpow_inv hp.ne'] at h1
  rw [ENNReal.ofReal_div_of_pos hcLpos, ← hcL, ← hCU, one_div]
  set a := (∫⁻ y, ‖G y‖ₑ ^ p ∂ν) ^ p⁻¹
  set b := (∫⁻ x, ‖Fsq x‖ₑ ^ p ∂μ) ^ p⁻¹
  calc a = cL⁻¹ * (cL * a) := by
        rw [← mul_assoc, ENNReal.inv_mul_cancel hcL0 hcLtop, one_mul]
    _ ≤ cL⁻¹ * (A * CU * b) := by gcongr
    _ = CU / cL * A * b := by rw [div_eq_mul_inv]; ring

/-- Marcinkiewicz–Zygmund `ℓ²`-valued extension for an additive operator defined on all
functions (Blueprint Lemma 2.6 (`lem:khintchine`), operator assertion, globally defined form). -/
theorem marcinkiewicz_zygmund_square_function_of_addMonoidHom
    (𝕜 𝕜' : Type*) [RCLike 𝕜] [RCLike 𝕜']
    {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ : Measure α} {ν : Measure β}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [NormedAddCommGroup F] [InnerProductSpace 𝕜' F]
    (T : (α → E) →+ (β → F)) {p : ℝ} (hp : 0 < p) (A : ℝ≥0)
    (hT : ∀ g : α → E, eLpNorm (T g) (ENNReal.ofReal p) ν ≤ A * eLpNorm g (ENNReal.ofReal p) μ)
    (s : Finset ι) (f : ι → α → E)
    (hf : ∀ i ∈ s, AEStronglyMeasurable (f i) μ)
    (hTf : ∀ i ∈ s, AEStronglyMeasurable (T (f i)) ν) :
    eLpNorm (fun y => Real.sqrt (∑ i ∈ s, ‖T (f i) y‖ ^ 2)) (ENNReal.ofReal p) ν ≤
      ENNReal.ofReal (khintchineUpperConst p / khintchineLowerConst p) * A *
        eLpNorm (fun x => Real.sqrt (∑ i ∈ s, ‖f i x‖ ^ 2)) (ENNReal.ofReal p) μ :=
  marcinkiewicz_zygmund_square_function 𝕜 𝕜' ⊤ (T.comp (⊤ : AddSubgroup (α → E)).subtype) hp A
    (fun g => hT g) s (fun i => ⟨f i, AddSubgroup.mem_top _⟩) hf hTf

end MarcinkiewiczZygmund

end Auto
