/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import VariationalSW.Auto.CalderonZygmund
public import VariationalSW.Auto.VectorValuedCalderonZygmund

/-!
# The Littlewood–Paley inequality

This file was automatically generated by Claude.

This file proves the **Littlewood–Paley square function inequality** for the dyadic dilates
of a mean-zero Schwartz function on `ℝⁿ`, together with a vector-valued version and Stein's
pointwise bound of convolutions with radially decreasing kernels by the maximal function. The
statements depend on Mathlib only (and on the local definitions `lpDilate`, `lpMaximal`).

## Statements

Let `n ≥ 1`, `1 < p < ∞`, `ψ ∈ 𝓢(ℝⁿ)` with `∫ ψ = 0`, and `ψ_j(x) = 2^{jn} ψ(2^j x)`
(`lpDilate n ψ j`, `j ∈ ℤ`). There are constants `C` (depending on `n`, `p`, `ψ`) such that,
for every finite set of scales `s ⊆ ℤ`:
* `littlewood_paley`: `‖(∑_{j ∈ s} |ψ_j * f|²)^{1/2}‖_p ≤ C ‖f‖_p` for `f ∈ L^p`;
* `littlewood_paley_vector`: `‖(∑_{j ∈ s} |ψ_j * f_j|²)^{1/2}‖_p ≤ C ‖(∑_{j ∈ s} |f_j|²)^{1/2}‖_p`
  for `f_j ∈ L^p`.
Here `ψ_j * f (x) = ∫ ψ_j(x - y) f(y) dy` (the Bochner integral).

* `norm_conv_le_maximal`: if `|h(z)| ≤ Φ(|z|)` with `Φ ≥ 0` nonincreasing on `[0, ∞)`, then
  `|∫ h(x - y) f(y) dy| ≤ (∫ Φ(|z|) dz) · M f(x)` for every `x`, where `M f = lpMaximal f` is
  the centered Hardy–Littlewood maximal function over closed balls
  (`norm_conv_le_maximal_of_integrable` is the form with `A = ∫ Φ(|z|) dz < ∞`).

## Proof

* The square function is the norm of the `ℓ²(s)`-valued convolution operator with kernel
  `x ↦ (ψ_j(x))_{j ∈ s}`, and the bound follows from the **Benedek–Calderón–Panzone theorem**
  (`ℓ²`-valued Calderón–Zygmund theory, `vcz_eLpNorm_sqFun_le`), once its two hypotheses are
  checked with constants independent of `s`:
* **`L²` bound** (`lp_L2`), via **Plancherel**: `𝓕 ψ_j(ξ) = 𝓕 ψ(2^{-j} ξ)`
  (`fourier_lpDilate`), and `|𝓕 ψ(ξ)| ≤ D min(|ξ|, |ξ|⁻¹)` since `𝓕 ψ` is a Schwartz function
  vanishing at `0` (`lp_norm_fourier_le`), so `∑_j |𝓕 ψ_j(ξ)|² ≤ M` uniformly in `ξ` by the
  elementary dyadic sum `∑_j min(2^j t, (2^j t)⁻¹) ≤ B` (`lp_sum_min_le`). The identity
  `‖k * g‖₂ ≤ ‖𝓕 k · 𝓕 g‖₂` is proved for Schwartz `g` by duality and Parseval
  (`lp_eLpNorm_conv_le_fourier`); summing and extending to `g ∈ L²` by density of Schwartz
  functions gives `∑_j ‖ψ_j * g‖₂² ≤ 2 M ‖g‖₂²` (`lp_sum_eLpNorm_conv_le`).
* **Hörmander condition** (`lp_hormander`): by the mean value theorem and the decay of
  `∇ψ`, `|ψ_j(x - y) - ψ_j(x)| ≤ K |y| |x|^{-n-1} min(2^j|x|, (2^j|x|)⁻¹)` for `|x| > 2|y|`
  (`lp_dilate_sub_le`); summing over `j`, `(∑_j |ψ_j(x - y) - ψ_j(x)|²)^{1/2} ≤ ∑_j |…| ≲
  |y| |x|^{-n-1}`, whose integral over `|x| > 2|y|` is bounded (comparison with the envelope of
  `VariationalSW.Auto.CalderonZygmund`).
* The vector-valued version applies the Hilbert-space Benedek–Calderón–Panzone theorem
  (`vcz_eLpNorm_le_of_innerProductSpace`) to the diagonal kernel `diag(ψ_j(x))_{j ∈ s}` on
  `ℓ²(s)` (`lpDiagKernel`), whose `L²` bound follows from the scalar Plancherel bound
  `|𝓕 ψ_j| ≤ D` and whose Hörmander condition follows from the same pointwise estimate.
* The maximal function bound is proved by the layer-cake formula: the superlevel sets of
  `z ↦ Φ(|z|)` are centered balls `S_t`, and `∫_{x - S_t} |f| ≤ |S_t| M f(x)`.

## References

* E. M. Stein, *Singular Integrals and Differentiability Properties of Functions*, Princeton
  University Press, 1970, Ch. IV §5 (the Littlewood–Paley theorem) and Ch. III §2.2 (the
  maximal function bound for radially decreasing kernels).
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, §6.1.
-/

@[expose] public section

namespace Auto

open MeasureTheory Metric Set Filter Topology FourierTransform
open scoped ENNReal NNReal Convolution ComplexConjugate

noncomputable section

/-! ## Dilates and an elementary dyadic sum -/

/-- The `L¹`-normalized dyadic dilate `ψ_j(x) = 2^{jn} ψ(2^j x)`, `j ∈ ℤ`. -/
def lpDilate (n : ℕ) (ψ : EuclideanSpace ℝ (Fin n) → ℂ) (j : ℤ)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  (2 : ℝ) ^ (j * n) * ψ ((2 : ℝ) ^ j • x)

/-- The weight `(1/2)^{|k|}` on `ℤ`. -/
def lpGeom (k : ℤ) : ℝ := (1 / 2 : ℝ) ^ k.natAbs

lemma lpGeom_nonneg (k : ℤ) : 0 ≤ lpGeom k := by unfold lpGeom; positivity

lemma summable_lpGeom : Summable lpGeom := by
  refine Summable.of_nat_of_neg ?_ ?_
  · simpa [lpGeom] using summable_geometric_two
  · simpa [lpGeom] using summable_geometric_two

/-- `min(2^j t, (2^j t)⁻¹) ≤ 2 · 2^{-|j + N|}` when `2^N ≤ t < 2^{N+1}`. -/
lemma lp_min_le_lpGeom {t : ℝ} {N : ℤ} (h1 : (2 : ℝ) ^ N ≤ t) (h2 : t < (2 : ℝ) ^ (N + 1))
    (j : ℤ) : min ((2 : ℝ) ^ j * t) ((2 : ℝ) ^ j * t)⁻¹ ≤ 2 * lpGeom (j + N) := by
  have h2pos : (0 : ℝ) < 2 := two_pos
  have hpos : 0 < (2 : ℝ) ^ (j + N) := zpow_pos h2pos _
  have hlow : (2 : ℝ) ^ (j + N) ≤ 2 ^ j * t := by
    rw [zpow_add₀ h2pos.ne']; exact mul_le_mul_of_nonneg_left h1 (zpow_pos h2pos _).le
  have hup : 2 ^ j * t < (2 : ℝ) ^ (j + N + 1) := by
    rw [add_assoc, zpow_add₀ h2pos.ne']; exact mul_lt_mul_of_pos_left h2 (zpow_pos h2pos _)
  rcases le_or_gt 0 (j + N) with hk | hk
  · obtain ⟨m, hm⟩ := Int.eq_ofNat_of_zero_le hk
    have hg : lpGeom (j + N) = ((2 : ℝ) ^ (j + N))⁻¹ := by
      rw [lpGeom, hm, Int.natAbs_natCast, zpow_natCast, one_div, inv_pow]
    refine (min_le_right _ _).trans ?_
    rw [hg]
    calc (2 ^ j * t)⁻¹ ≤ ((2 : ℝ) ^ (j + N))⁻¹ := inv_anti₀ hpos hlow
      _ ≤ 2 * ((2 : ℝ) ^ (j + N))⁻¹ := by linarith [inv_pos.2 hpos]
  · obtain ⟨m, hm⟩ := Int.exists_eq_neg_ofNat hk.le
    have hg : lpGeom (j + N) = (2 : ℝ) ^ (j + N) := by
      rw [lpGeom, hm, Int.natAbs_neg, Int.natAbs_natCast, zpow_neg, zpow_natCast, one_div,
        inv_pow]
    refine (min_le_left _ _).trans ?_
    rw [hg]
    calc 2 ^ j * t ≤ (2 : ℝ) ^ (j + N + 1) := hup.le
      _ = 2 * (2 : ℝ) ^ (j + N) := by rw [zpow_add_one₀ h2pos.ne']; ring

/-- The basic dyadic sum: `∑_{j ∈ s} min(2^j t, (2^j t)⁻¹) ≤ B` uniformly in the finite set
`s ⊆ ℤ` and `t ≥ 0`. -/
lemma lp_sum_min_le : ∃ B : ℝ, 0 ≤ B ∧ ∀ (s : Finset ℤ) (t : ℝ), 0 ≤ t →
    ∑ j ∈ s, min ((2 : ℝ) ^ j * t) ((2 : ℝ) ^ j * t)⁻¹ ≤ B := by
  have hS0 : 0 ≤ ∑' k, lpGeom k := tsum_nonneg lpGeom_nonneg
  refine ⟨2 * ∑' k, lpGeom k, by positivity, fun s t ht => ?_⟩
  rcases ht.eq_or_lt with rfl | ht
  · simp only [mul_zero, inv_zero, min_self, Finset.sum_const_zero]; positivity
  obtain ⟨N, hN1, hN2⟩ := exists_mem_Ico_zpow ht one_lt_two
  have hsum : Summable fun j => lpGeom (j + N) :=
    ((Equiv.addRight N).summable_iff (f := lpGeom)).2 summable_lpGeom
  calc ∑ j ∈ s, min ((2 : ℝ) ^ j * t) ((2 : ℝ) ^ j * t)⁻¹
      ≤ ∑ j ∈ s, 2 * lpGeom (j + N) := Finset.sum_le_sum fun j _ => lp_min_le_lpGeom hN1 hN2 j
    _ = 2 * ∑ j ∈ s, lpGeom (j + N) := by rw [Finset.mul_sum]
    _ ≤ 2 * ∑' j, lpGeom (j + N) := by
        gcongr; exact hsum.sum_le_tsum s fun j _ => lpGeom_nonneg _
    _ = 2 * ∑' k, lpGeom k := congrArg (2 * ·) ((Equiv.addRight N).tsum_eq lpGeom)

/-- The same sum with the reflected scales `2^{-j}`. -/
lemma lp_sum_min_neg_le {B : ℝ} (hB : ∀ (s : Finset ℤ) (t : ℝ), 0 ≤ t →
    ∑ j ∈ s, min ((2 : ℝ) ^ j * t) ((2 : ℝ) ^ j * t)⁻¹ ≤ B) (s : Finset ℤ) {t : ℝ}
    (ht : 0 ≤ t) : ∑ j ∈ s, min ((2 : ℝ) ^ (-j) * t) ((2 : ℝ) ^ (-j) * t)⁻¹ ≤ B := by
  have h := hB (s.image Neg.neg) t ht
  rwa [Finset.sum_image fun a _ b _ hab => neg_injective hab] at h

/-- `min(u, u⁻¹) ≤ 1`. -/
lemma lp_min_inv_le_one (u : ℝ) : min u u⁻¹ ≤ 1 := by
  rcases le_or_gt u 1 with h | h
  · exact (min_le_left _ _).trans h
  · exact (min_le_right _ _).trans (inv_le_one_of_one_le₀ h.le)

/-- `u^{n+1} (1 + u)^{-n-2} ≤ min(u, u⁻¹)` for `u ≥ 0`. -/
lemma lp_pow_div_le_min (n : ℕ) {u : ℝ} (hu : 0 ≤ u) :
    u ^ (n + 1) / (1 + u) ^ (n + 2) ≤ min u u⁻¹ := by
  have h1 : 0 < 1 + u := by linarith
  have hq : (u / (1 + u)) ^ n ≤ 1 :=
    pow_le_one₀ (by positivity) ((div_le_one h1).2 (by linarith))
  have he : u ^ (n + 1) / (1 + u) ^ (n + 2) = (u / (1 + u)) ^ n * (u / (1 + u) ^ 2) := by
    rw [div_pow]; field_simp; ring
  have hr : u / (1 + u) ^ 2 ≤ min u u⁻¹ := by
    refine le_min ?_ ?_
    · rw [div_le_iff₀ (by positivity)]
      nlinarith [mul_nonneg hu (by positivity : (0 : ℝ) ≤ 2 * u + u ^ 2)]
    · rcases hu.eq_or_lt with rfl | hu'
      · simp
      · rw [div_le_iff₀ (by positivity), inv_mul_eq_div, le_div_iff₀ hu']; nlinarith
  rw [he]
  calc (u / (1 + u)) ^ n * (u / (1 + u) ^ 2) ≤ 1 * (u / (1 + u) ^ 2) :=
        mul_le_mul_of_nonneg_right hq (by positivity)
    _ ≤ min u u⁻¹ := by rw [one_mul]; exact hr

/-! ## Decay of Schwartz functions and the Hörmander condition -/

section Hormander

variable {n : ℕ}

/-- Polynomial decay of the derivatives of a Schwartz function. -/
lemma lp_schwartz_decay {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup F] [NormedSpace ℝ F] (g : SchwartzMap E F) (k m : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ x, (1 + ‖x‖) ^ k * ‖iteratedFDeriv ℝ m g x‖ ≤ C :=
  ⟨2 ^ k * ((Finset.Iic (k, m)).sup fun q => SchwartzMap.seminorm ℝ q.1 q.2) g,
    mul_nonneg (by positivity) (apply_nonneg _ _),
    fun x => SchwartzMap.one_add_le_sup_seminorm_apply (m := (k, m)) le_rfl le_rfl g x⟩

/-- Mean value estimate with decay: if `(1 + |w|)^{n+2} |∇φ(w)| ≤ C` everywhere and
`2|b| ≤ |a|`, then `|φ(a - b) - φ(a)| ≤ 2^{n+2} C |b| (1 + |a|)^{-n-2}`. -/
lemma lp_norm_sub_le_of_decay {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {φ : E → ℂ} (hφ : Differentiable ℝ φ) {C : ℝ}
    (hd : ∀ w, (1 + ‖w‖) ^ (n + 2) * ‖fderiv ℝ φ w‖ ≤ C) {a b : E} (hab : 2 * ‖b‖ ≤ ‖a‖) :
    ‖φ (a - b) - φ a‖ ≤ 2 ^ (n + 2) * C * ‖b‖ / (1 + ‖a‖) ^ (n + 2) := by
  have hbound : ∀ w ∈ closedBall a ‖b‖,
      ‖fderiv ℝ φ w‖ ≤ 2 ^ (n + 2) * C / (1 + ‖a‖) ^ (n + 2) := by
    intro w hw
    have hw' : ‖a‖ / 2 ≤ ‖w‖ := by
      rw [mem_closedBall_iff_norm] at hw
      have := norm_sub_norm_le a w
      rw [norm_sub_rev] at this
      linarith
    have h2 : (1 + ‖a‖) / 2 ≤ 1 + ‖w‖ := by linarith
    have h3 : ((1 + ‖a‖) / 2) ^ (n + 2) ≤ (1 + ‖w‖) ^ (n + 2) :=
      pow_le_pow_left₀ (by positivity) h2 _
    rw [le_div_iff₀ (by positivity)]
    calc ‖fderiv ℝ φ w‖ * (1 + ‖a‖) ^ (n + 2)
        = 2 ^ (n + 2) * (((1 + ‖a‖) / 2) ^ (n + 2) * ‖fderiv ℝ φ w‖) := by
          rw [div_pow]; field_simp
      _ ≤ 2 ^ (n + 2) * ((1 + ‖w‖) ^ (n + 2) * ‖fderiv ℝ φ w‖) := by gcongr
      _ ≤ 2 ^ (n + 2) * C := by gcongr; exact hd w
  have hmem : a - b ∈ closedBall a ‖b‖ := by
    rw [mem_closedBall_iff_norm]; simp
  have h := (convex_closedBall a ‖b‖).norm_image_sub_le_of_norm_fderiv_le
    (fun w _ => hφ w) hbound (mem_closedBall_self (norm_nonneg b)) hmem
  calc ‖φ (a - b) - φ a‖ ≤ 2 ^ (n + 2) * C / (1 + ‖a‖) ^ (n + 2) * ‖a - b - a‖ := h
    _ = 2 ^ (n + 2) * C * ‖b‖ / (1 + ‖a‖) ^ (n + 2) := by
        rw [sub_sub_cancel_left, norm_neg]; ring

/-- The scaling computation: `c^n K c Y (1 + c X)^{-n-2} ≤ K Y X^{-n-1} min(cX, (cX)⁻¹)`. -/
lemma lp_scale_bound {c X Y K : ℝ} (hc : 0 < c) (hX : 0 < X) (hY : 0 ≤ Y) (hK : 0 ≤ K) :
    c ^ n * (K * (c * Y) / (1 + c * X) ^ (n + 2)) ≤
      K * Y / X ^ (n + 1) * min (c * X) (c * X)⁻¹ := by
  have h := lp_pow_div_le_min n (u := c * X) (by positivity)
  have he : c ^ n * (K * (c * Y) / (1 + c * X) ^ (n + 2)) =
      K * Y / X ^ (n + 1) * ((c * X) ^ (n + 1) / (1 + c * X) ^ (n + 2)) := by
    field_simp; ring
  rw [he]
  exact mul_le_mul_of_nonneg_left h (by positivity)

/-- The pointwise smoothness estimate for one dilate. -/
lemma lp_dilate_sub_le {ψ : EuclideanSpace ℝ (Fin n) → ℂ} (hψ : Differentiable ℝ ψ) {C : ℝ}
    (hC : 0 ≤ C) (hd : ∀ w, (1 + ‖w‖) ^ (n + 2) * ‖fderiv ℝ ψ w‖ ≤ C) (j : ℤ)
    {x y : EuclideanSpace ℝ (Fin n)} (hxy : 2 * ‖y‖ < ‖x‖) :
    ‖lpDilate n ψ j (x - y) - lpDilate n ψ j x‖ ≤
      2 ^ (n + 2) * C * ‖y‖ / ‖x‖ ^ (n + 1) *
        min ((2 : ℝ) ^ j * ‖x‖) ((2 : ℝ) ^ j * ‖x‖)⁻¹ := by
  have hc : 0 < (2 : ℝ) ^ j := zpow_pos two_pos j
  have hX : 0 < ‖x‖ := by linarith [norm_nonneg y]
  have hab : 2 * ‖(2 : ℝ) ^ j • y‖ ≤ ‖(2 : ℝ) ^ j • x‖ := by
    rw [norm_smul, norm_smul, Real.norm_of_nonneg hc.le]; nlinarith
  have hpow : (2 : ℝ) ^ (j * (n : ℤ)) = ((2 : ℝ) ^ j) ^ n := by rw [zpow_mul, zpow_natCast]
  have h1 : lpDilate n ψ j (x - y) - lpDilate n ψ j x =
      ((((2 : ℝ) ^ j) ^ n : ℝ) : ℂ) *
        (ψ ((2 : ℝ) ^ j • x - (2 : ℝ) ^ j • y) - ψ ((2 : ℝ) ^ j • x)) := by
    simp only [lpDilate, smul_sub, mul_sub]
    rw [show ((2 : ℝ) : ℂ) ^ (j * (n : ℤ)) = ((((2 : ℝ) ^ j) ^ n : ℝ) : ℂ) by
      rw [← hpow, Complex.ofReal_zpow]]
  rw [h1, norm_mul, Complex.norm_real, Real.norm_of_nonneg (by positivity)]
  have h2 := lp_norm_sub_le_of_decay hψ hd hab
  rw [norm_smul, norm_smul, Real.norm_of_nonneg hc.le] at h2
  calc ((2 : ℝ) ^ j) ^ n * ‖ψ ((2 : ℝ) ^ j • x - (2 : ℝ) ^ j • y) - ψ ((2 : ℝ) ^ j • x)‖
      ≤ ((2 : ℝ) ^ j) ^ n * (2 ^ (n + 2) * C * ((2 : ℝ) ^ j * ‖y‖) /
          (1 + (2 : ℝ) ^ j * ‖x‖) ^ (n + 2)) :=
        mul_le_mul_of_nonneg_left h2 (by positivity)
    _ ≤ _ := lp_scale_bound hc hX (norm_nonneg y) (by positivity)

/-- The pointwise bound `∑_j |ψ_j(x - y) - ψ_j(x)| ≤ K |y| |x|^{-n-1}` for `|x| > 2|y|`,
uniformly in the finite set of scales. -/
lemma lp_sum_dilate_sub_le (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    ∃ K : ℝ, 0 ≤ K ∧ ∀ (s : Finset ℤ) (x y : EuclideanSpace ℝ (Fin n)), 2 * ‖y‖ < ‖x‖ →
      ∑ j ∈ s, ‖lpDilate n ψ j (x - y) - lpDilate n ψ j x‖ ≤ K * ‖y‖ / ‖x‖ ^ (n + 1) := by
  obtain ⟨C, hC, hd⟩ := lp_schwartz_decay ψ (n + 2) 1
  obtain ⟨B, hB, hsum⟩ := lp_sum_min_le
  refine ⟨2 ^ (n + 2) * C * B, by positivity, fun s x y hxy => ?_⟩
  have hd' : ∀ w, (1 + ‖w‖) ^ (n + 2) * ‖fderiv ℝ ψ w‖ ≤ C := fun w => by
    rw [← norm_iteratedFDeriv_one]; exact hd w
  calc ∑ j ∈ s, ‖lpDilate n ψ j (x - y) - lpDilate n ψ j x‖
      ≤ ∑ j ∈ s, 2 ^ (n + 2) * C * ‖y‖ / ‖x‖ ^ (n + 1) *
          min ((2 : ℝ) ^ j * ‖x‖) ((2 : ℝ) ^ j * ‖x‖)⁻¹ :=
        Finset.sum_le_sum fun j _ => lp_dilate_sub_le ψ.differentiable hC hd' j hxy
    _ = 2 ^ (n + 2) * C * ‖y‖ / ‖x‖ ^ (n + 1) *
          ∑ j ∈ s, min ((2 : ℝ) ^ j * ‖x‖) ((2 : ℝ) ^ j * ‖x‖)⁻¹ := by rw [Finset.mul_sum]
    _ ≤ 2 ^ (n + 2) * C * ‖y‖ / ‖x‖ ^ (n + 1) * B :=
        mul_le_mul_of_nonneg_left (hsum s _ (norm_nonneg x)) (by positivity)
    _ = 2 ^ (n + 2) * C * B * ‖y‖ / ‖x‖ ^ (n + 1) := by ring

/-- Comparison with the envelope: `δ |u|^{-n-1} ≤ 2^n B_{2δ}(u)` for `|u| ≥ 2δ > 0`. -/
lemma lp_div_pow_le_envelope {δ : ℝ} (hδ : 0 < δ) {u : EuclideanSpace ℝ (Fin n)}
    (hu : 2 * δ ≤ ‖u‖) : δ / ‖u‖ ^ (n + 1) ≤ 2 ^ n * envelope n (2 * δ) u := by
  have hu0 : 0 < ‖u‖ := by linarith
  rw [envelope_eq_div (by positivity), mul_div_assoc', div_le_div_iff₀ (by positivity)
    (by positivity)]
  calc δ * (2 * δ + ‖u‖) ^ (n + 1) ≤ δ * (2 * ‖u‖) ^ (n + 1) :=
        mul_le_mul_of_nonneg_left (pow_le_pow_left₀ (by positivity) (by linarith) _) hδ.le
    _ = 2 ^ n * (2 * δ) * ‖u‖ ^ (n + 1) := by rw [mul_pow, pow_succ]; ring

/-- Integration of the pointwise bound `F(x) ≤ K |y| |x|^{-n-1}` over `|x| > 2|y|`. -/
lemma lp_lintegral_le_of_le_div {K : ℝ} (hK : 0 ≤ K) (y : EuclideanSpace ℝ (Fin n))
    {F : EuclideanSpace ℝ (Fin n) → ℝ≥0∞}
    (hF : ∀ x, 2 * ‖y‖ < ‖x‖ → F x ≤ ENNReal.ofReal (K * ‖y‖ / ‖x‖ ^ (n + 1))) :
    ∫⁻ x in {x | 2 * ‖y‖ < ‖x‖}, F x ≤ ENNReal.ofReal (K * 2 ^ n * envelopeConst n) := by
  have hmeas : MeasurableSet {x : EuclideanSpace ℝ (Fin n) | 2 * ‖y‖ < ‖x‖} :=
    measurableSet_lt measurable_const measurable_norm
  rcases (norm_nonneg y).eq_or_lt with hy | hy
  · calc _ ≤ ∫⁻ x in {x | 2 * ‖y‖ < ‖x‖}, (0 : ℝ≥0∞) := by
          refine setLIntegral_mono' hmeas fun x hx => (hF x hx).trans_eq ?_
          rw [← hy]; simp
      _ ≤ _ := by simp
  · calc _ ≤ ∫⁻ x in {x | 2 * ‖y‖ < ‖x‖},
          ENNReal.ofReal (K * 2 ^ n * envelope n (2 * ‖y‖) x) := by
          refine setLIntegral_mono' hmeas fun x hx => (hF x hx).trans ?_
          refine ENNReal.ofReal_le_ofReal ?_
          have h := lp_div_pow_le_envelope hy (le_of_lt hx)
          calc K * ‖y‖ / ‖x‖ ^ (n + 1) = K * (‖y‖ / ‖x‖ ^ (n + 1)) := by ring
            _ ≤ K * (2 ^ n * envelope n (2 * ‖y‖) x) := mul_le_mul_of_nonneg_left h hK
            _ = K * 2 ^ n * envelope n (2 * ‖y‖) x := by ring
      _ ≤ ∫⁻ x, ENNReal.ofReal (K * 2 ^ n * envelope n (2 * ‖y‖) x) :=
          setLIntegral_le_lintegral _ _
      _ = ENNReal.ofReal (K * 2 ^ n) * ∫⁻ x, ENNReal.ofReal (envelope n (2 * ‖y‖) x) := by
          simp_rw [ENNReal.ofReal_mul (by positivity : (0 : ℝ) ≤ K * 2 ^ n)]
          rw [lintegral_const_mul' _ _ ENNReal.ofReal_ne_top]
      _ ≤ ENNReal.ofReal (K * 2 ^ n) * ENNReal.ofReal (envelopeConst n) :=
          mul_le_mul_right (lintegral_envelope_le (by positivity)) _
      _ = ENNReal.ofReal (K * 2 ^ n * envelopeConst n) := by
          rw [← ENNReal.ofReal_mul (by positivity)]

/-- **The `ℓ²`-Hörmander condition** for the dilates of a Schwartz function, uniformly in the
finite set of scales. -/
theorem lp_hormander (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    ∃ A : ℝ, 0 ≤ A ∧ ∀ (s : Finset ℤ) (y : EuclideanSpace ℝ (Fin n)),
      ∫⁻ x in {x | 2 * ‖y‖ < ‖x‖},
        ENNReal.ofReal √(∑ j ∈ s, ‖lpDilate n ψ j (x - y) - lpDilate n ψ j x‖ ^ 2) ≤
          ENNReal.ofReal A := by
  obtain ⟨K, hK, hpt⟩ := lp_sum_dilate_sub_le ψ
  refine ⟨K * 2 ^ n * envelopeConst n, by unfold envelopeConst; positivity, fun s y => ?_⟩
  refine lp_lintegral_le_of_le_div hK y fun x hx => ENNReal.ofReal_le_ofReal ?_
  refine le_trans ?_ (hpt s x y hx)
  rw [Real.sqrt_le_left (Finset.sum_nonneg fun j _ => norm_nonneg _)]
  exact Finset.sum_sq_le_sq_sum_of_nonneg fun j _ => norm_nonneg _

end Hormander

/-! ## The Fourier transform of the dilates and the `L²` estimate -/

section Fourier

variable {n : ℕ}

/-- The dilates of an integrable function are integrable. -/
lemma integrable_lpDilate {ψ : EuclideanSpace ℝ (Fin n) → ℂ} (hψ : Integrable ψ) (j : ℤ) :
    Integrable (lpDilate n ψ j) :=
  (hψ.comp_smul (zpow_ne_zero j two_ne_zero)).const_mul _

/-- The Fourier transform of a dilate: `𝓕 ψ_j (ξ) = 𝓕 ψ (2^{-j} ξ)`. -/
lemma fourier_lpDilate (ψ : EuclideanSpace ℝ (Fin n) → ℂ) (j : ℤ)
    (ξ : EuclideanSpace ℝ (Fin n)) :
    𝓕 (lpDilate n ψ j) ξ = 𝓕 ψ (((2 : ℝ) ^ j)⁻¹ • ξ) := by
  have hc : 0 < (2 : ℝ) ^ j := zpow_pos two_pos j
  have hpow : ((2 : ℝ) : ℂ) ^ (j * (n : ℤ)) = ((((2 : ℝ) ^ j) ^ n : ℝ) : ℂ) := by
    rw [← zpow_natCast, ← zpow_mul, Complex.ofReal_zpow]
  have hpt : ∀ v : EuclideanSpace ℝ (Fin n), 𝐞 (-inner ℝ v ξ) • lpDilate n ψ j v =
      ((((2 : ℝ) ^ j) ^ n : ℝ) : ℂ) * (fun w => 𝐞 (-inner ℝ w (((2 : ℝ) ^ j)⁻¹ • ξ)) • ψ w)
        ((2 : ℝ) ^ j • v) := by
    intro v
    have hin : inner ℝ ((2 : ℝ) ^ j • v) (((2 : ℝ) ^ j)⁻¹ • ξ) = inner ℝ v ξ := by
      rw [real_inner_smul_left, real_inner_smul_right, ← mul_assoc, mul_inv_cancel₀ hc.ne',
        one_mul]
    simp only [lpDilate, hin, Circle.smul_def, hpow]
    ring
  rw [Real.fourier_eq, Real.fourier_eq]
  simp_rw [hpt]
  have key := Measure.integral_comp_smul volume
    (fun w => 𝐞 (-inner ℝ w (((2 : ℝ) ^ j)⁻¹ • ξ)) • ψ w) ((2 : ℝ) ^ j)
  rw [integral_const_mul, key, finrank_euclideanSpace_fin,
    abs_of_pos (by positivity), Complex.real_smul, ← mul_assoc, ← Complex.ofReal_mul,
    mul_inv_cancel₀ (by positivity), Complex.ofReal_one, one_mul]

/-- Since `ψ` has mean zero and `𝓕 ψ` is a Schwartz function,
`|𝓕 ψ(ξ)| ≤ D min(|ξ|, |ξ|⁻¹)`. -/
lemma lp_norm_fourier_le (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) (hψ : ∫ x, ψ x = 0) :
    ∃ D : ℝ, 0 ≤ D ∧ ∀ ξ, ‖𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ ≤ D * min ‖ξ‖ ‖ξ‖⁻¹ := by
  obtain ⟨C0, hC0, h0⟩ := lp_schwartz_decay (𝓕 ψ) 1 0
  obtain ⟨C1, hC1, h1⟩ := lp_schwartz_decay (𝓕 ψ) 0 1
  have hcoe := SchwartzMap.fourier_coe ψ
  have hz : 𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) 0 = 0 := by
    rw [Real.fourier_eq]; simpa using hψ
  have hdiff : Differentiable ℝ (𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ)) := by
    rw [← hcoe]; exact SchwartzMap.differentiable _
  refine ⟨max C0 C1, le_max_of_le_left hC0, fun ξ => ?_⟩
  have hA : ‖𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ ≤ C1 * ‖ξ‖ := by
    have hb : ∀ w ∈ (univ : Set (EuclideanSpace ℝ (Fin n))),
        ‖fderiv ℝ (𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ)) w‖ ≤ C1 := fun w _ => by
      have := h1 w
      rwa [pow_zero, one_mul, norm_iteratedFDeriv_one, hcoe] at this
    have := convex_univ.norm_image_sub_le_of_norm_fderiv_le (fun w _ => hdiff w) hb
      (mem_univ 0) (mem_univ ξ)
    rwa [hz, sub_zero, sub_zero] at this
  have hB : ‖𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ ≤ C0 * ‖ξ‖⁻¹ := by
    have := h0 ξ
    rw [pow_one, norm_iteratedFDeriv_zero, hcoe] at this
    rcases (norm_nonneg ξ).eq_or_lt with h | h
    · rw [eq_comm, norm_eq_zero] at h
      rw [h, hz]; simp
    · rw [← div_eq_mul_inv, le_div_iff₀ h]
      nlinarith [norm_nonneg (𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) ξ)]
  rw [mul_min_of_nonneg _ _ (le_max_of_le_left hC0)]
  exact le_min (hA.trans (by gcongr; exact le_max_right _ _))
    (hB.trans (by gcongr; exact le_max_left _ _))

/-- The multiplier bound `∑_{j ∈ s} |𝓕 ψ_j(ξ)|² ≤ M`, uniformly in `s` and `ξ`. -/
lemma lp_sum_fourier_sq_le (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ)
    (hψ : ∫ x, ψ x = 0) :
    ∃ M : ℝ, 0 ≤ M ∧ ∀ (s : Finset ℤ) (ξ : EuclideanSpace ℝ (Fin n)),
      ∑ j ∈ s, ‖𝓕 (lpDilate n ψ j) ξ‖ ^ 2 ≤ M := by
  obtain ⟨D, hD, hF⟩ := lp_norm_fourier_le ψ hψ
  obtain ⟨B, hB, hsum⟩ := lp_sum_min_le
  refine ⟨D ^ 2 * B, by positivity, fun s ξ => ?_⟩
  have hterm : ∀ j : ℤ, ‖𝓕 (lpDilate n ψ j) ξ‖ ^ 2 ≤
      D ^ 2 * min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ := by
    intro j
    rw [fourier_lpDilate]
    have hn : ‖((2 : ℝ) ^ j)⁻¹ • ξ‖ = (2 : ℝ) ^ (-j) * ‖ξ‖ := by
      rw [norm_smul, Real.norm_of_nonneg (by positivity), zpow_neg]
    have h := hF (((2 : ℝ) ^ j)⁻¹ • ξ)
    rw [hn] at h
    have hu : 0 ≤ (2 : ℝ) ^ (-j) * ‖ξ‖ := by positivity
    have hm0 : 0 ≤ min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ :=
      le_min hu (inv_nonneg.2 hu)
    have hm1 := lp_min_inv_le_one ((2 : ℝ) ^ (-j) * ‖ξ‖)
    calc ‖𝓕 (ψ : EuclideanSpace ℝ (Fin n) → ℂ) (((2 : ℝ) ^ j)⁻¹ • ξ)‖ ^ 2
        ≤ (D * min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹) ^ 2 :=
          pow_le_pow_left₀ (norm_nonneg _) h 2
      _ = D ^ 2 * (min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ *
            min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹) := by ring
      _ ≤ D ^ 2 * (min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ * 1) := by gcongr
      _ = D ^ 2 * min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ := by ring
  calc ∑ j ∈ s, ‖𝓕 (lpDilate n ψ j) ξ‖ ^ 2
      ≤ ∑ j ∈ s, D ^ 2 * min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ :=
        Finset.sum_le_sum fun j _ => hterm j
    _ = D ^ 2 * ∑ j ∈ s, min ((2 : ℝ) ^ (-j) * ‖ξ‖) ((2 : ℝ) ^ (-j) * ‖ξ‖)⁻¹ := by
        rw [Finset.mul_sum]
    _ ≤ D ^ 2 * B := by gcongr; exact lp_sum_min_neg_le hsum s (norm_nonneg ξ)

/-- `‖u‖₂² = ∫ |u|²`. -/
lemma lp_eLpNorm_two_sq {α E : Type*} [MeasurableSpace α] [NormedAddCommGroup E] {μ : Measure α}
    {u : α → E}
    (hu : AEStronglyMeasurable u μ) : eLpNorm u 2 μ ^ 2 = ∫⁻ x, ‖u x‖ₑ ^ 2 ∂μ := by
  have h := eLpNorm_two_rpow_two hu
  simp only [ENNReal.rpow_two] at h
  exact h

/-- `(a + b)² ≤ 2 (a² + b²)` in `[0, ∞]`. -/
lemma lp_add_sq_le (a b : ℝ≥0∞) : (a + b) ^ 2 ≤ 2 * (a ^ 2 + b ^ 2) := by
  have h := ENNReal.rpow_add_le_mul_rpow_add_rpow a b (p := 2) one_le_two
  rw [show (2 : ℝ) - 1 = 1 by norm_num, ENNReal.rpow_one] at h
  simpa only [ENNReal.rpow_two] using h

/-- Plancherel, in the form `‖H * g‖₂ ≤ ‖𝓕 H · 𝓕 g‖₂` for `H ∈ L¹` and Schwartz `g`
(by duality against Schwartz test functions and Parseval). -/
lemma lp_eLpNorm_conv_le_fourier {H : EuclideanSpace ℝ (Fin n) → ℂ} (hH : Integrable H)
    (g : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g : EuclideanSpace ℝ (Fin n) → ℂ)) 2
      volume ≤
      eLpNorm (fun ξ => 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2 volume := by
  have h22 : (2 : ℝ).HolderConjugate 2 := Real.HolderConjugate.two_two
  have e2 : ENNReal.ofReal 2 = 2 := ENNReal.ofReal_ofNat 2
  have hHi := memLp_one_iff_integrable.2 hH
  have hu2 : MemLp (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g : EuclideanSpace ℝ (Fin n) → ℂ))
      (ENNReal.ofReal 2) volume := by
    rw [e2]; exact memLp_convolution_of_memLp one_le_two hHi (g.memLp 2 volume)
  have hui : Integrable (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
      (g : EuclideanSpace ℝ (Fin n) → ℂ)) :=
    memLp_one_iff_integrable.1 (memLp_convolution_of_memLp le_rfl hHi (g.memLp 1 volume))
  have hHF : AEStronglyMeasurable (𝓕 H) volume :=
    (VectorFourier.fourierIntegral_continuous Real.continuous_fourierChar continuous_inner
      hH).aestronglyMeasurable
  have hgF : AEStronglyMeasurable (𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ)) volume :=
    (𝓕 g).continuous.aestronglyMeasurable
  have key := eLpNorm_le_of_smooth_dual_test h22 hu2
    (A := eLpNorm (fun ξ => 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2 volume)
    (fun φ hφs hφc hφ2 => ?_)
  · rwa [e2] at key
  set S := hφc.toSchwartzMap hφs
  have hSφ : (S : EuclideanSpace ℝ (Fin n) → ℂ) = φ := rfl
  rw [e2] at hφ2
  rw [← hSφ, integral_mul_conj_eq_fourier hui S]
  have hconv : ∀ ξ, 𝓕 (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
      (g : EuclideanSpace ℝ (Fin n) → ℂ)) ξ = 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ :=
    Real.fourier_mul_convolution_eq hH g.integrable
  simp_rw [hconv]
  have hSF : AEStronglyMeasurable (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ)) volume :=
    (𝓕 S).continuous.aestronglyMeasurable
  calc ‖∫ ξ, 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ *
        conj (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ)‖ₑ
      ≤ ∫⁻ ξ, ‖𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ *
          conj (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ)‖ₑ := enorm_integral_le_lintegral_enorm _
    _ = ∫⁻ ξ, ‖𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ *
          ‖𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ := by
        congr 1; funext ξ; rw [enorm_mul _ (conj _), RCLike.enorm_conj]
    _ ≤ eLpNorm (fun ξ => 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2 volume *
          eLpNorm (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume :=
        lintegral_enorm_mul_le_eLpNorm_two (hHF.mul hgF) hSF
    _ = eLpNorm (fun ξ => 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2 volume *
          eLpNorm φ 2 volume := by rw [eLpNorm_fourier_schwartz, hSφ]
    _ ≤ eLpNorm (fun ξ => 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2 volume * 1 := by
        gcongr
    _ = _ := mul_one _

/-- The summed `L²` bound for Schwartz inputs: if `∑_{i ∈ s} |𝓕 k_i|² ≤ M`, then
`∑_{i ∈ s} ‖k_i * g‖₂² ≤ M ‖g‖₂²`. -/
lemma lp_sum_eLpNorm_conv_schwartz_le {ι : Type*} (s : Finset ι)
    {k : ι → EuclideanSpace ℝ (Fin n) → ℂ} (hk : ∀ i ∈ s, Integrable (k i)) {M : ℝ}
    (hM : ∀ ξ, ∑ i ∈ s, ‖𝓕 (k i) ξ‖ ^ 2 ≤ M) (g : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
      (g : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume ^ 2 ≤
      ENNReal.ofReal M * eLpNorm g 2 volume ^ 2 := by
  have hgF : AEStronglyMeasurable (𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ)) volume :=
    (𝓕 g).continuous.aestronglyMeasurable
  have hkF : ∀ i ∈ s, AEStronglyMeasurable (𝓕 (k i)) volume := fun i hi =>
    (VectorFourier.fourierIntegral_continuous Real.continuous_fourierChar continuous_inner
      (hk i hi)).aestronglyMeasurable
  calc ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
        (g : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume ^ 2
      ≤ ∑ i ∈ s, eLpNorm (fun ξ => 𝓕 (k i) ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ) 2
          volume ^ 2 :=
        Finset.sum_le_sum fun i hi =>
          pow_le_pow_left₀ zero_le (lp_eLpNorm_conv_le_fourier (hk i hi) g) 2
    _ = ∑ i ∈ s, ∫⁻ ξ, ‖𝓕 (k i) ξ‖ₑ ^ 2 *
          ‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ ^ 2 := by
        refine Finset.sum_congr rfl fun i hi => ?_
        rw [lp_eLpNorm_two_sq (u := fun ξ => 𝓕 (k i) ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ)
          ((hkF i hi).mul hgF)]
        simp_rw [enorm_mul, mul_pow]
    _ = ∫⁻ ξ, (∑ i ∈ s, ‖𝓕 (k i) ξ‖ₑ ^ 2) *
          ‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ ^ 2 := by
        rw [← lintegral_finsetSum' (f := fun i ξ => ‖𝓕 (k i) ξ‖ₑ ^ 2 *
          ‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ ^ 2) _ (fun i hi =>
          ((hkF i hi).enorm.pow_const 2).mul (hgF.enorm.pow_const 2))]
        simp_rw [Finset.sum_mul]
    _ ≤ ∫⁻ ξ, ENNReal.ofReal M * ‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ ^ 2 := by
        refine lintegral_mono fun ξ => ?_
        gcongr
        calc ∑ i ∈ s, ‖𝓕 (k i) ξ‖ₑ ^ 2 = ENNReal.ofReal (∑ i ∈ s, ‖𝓕 (k i) ξ‖ ^ 2) := by
              rw [ENNReal.ofReal_sum_of_nonneg fun i _ => by positivity]
              refine Finset.sum_congr rfl fun i _ => ?_
              rw [← ofReal_norm, ENNReal.ofReal_pow (norm_nonneg _)]
          _ ≤ ENNReal.ofReal M := ENNReal.ofReal_le_ofReal (hM ξ)
    _ = ENNReal.ofReal M * eLpNorm g 2 volume ^ 2 := by
        rw [lintegral_const_mul' _ _ ENNReal.ofReal_ne_top, ← lp_eLpNorm_two_sq hgF,
          eLpNorm_fourier_schwartz]

/-- The summed `L²` bound for all `g ∈ L²` (by density of Schwartz functions, with a loss of
a factor `2`): if `∑_{i ∈ s} |𝓕 k_i|² ≤ M`, then `∑_{i ∈ s} ‖k_i * g‖₂² ≤ 2 M ‖g‖₂²`. -/
lemma lp_sum_eLpNorm_conv_le {ι : Type*} (s : Finset ι)
    {k : ι → EuclideanSpace ℝ (Fin n) → ℂ} (hk : ∀ i ∈ s, Integrable (k i)) {M : ℝ}
    (hM : ∀ ξ, ∑ i ∈ s, ‖𝓕 (k i) ξ‖ ^ 2 ≤ M) {g : EuclideanSpace ℝ (Fin n) → ℂ}
    (hg : MemLp g 2 volume) :
    ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ^ 2 ≤
      2 * ENNReal.ofReal M * eLpNorm g 2 volume ^ 2 := by
  set G := eLpNorm g 2 volume with hG_def
  set N := ∑ i ∈ s, eLpNorm (k i) 1 volume ^ 2 with hN_def
  have hN : N ≠ ∞ := ENNReal.sum_ne_top.2 fun i hi =>
    ENNReal.pow_ne_top (memLp_one_iff_integrable.2 (hk i hi)).eLpNorm_ne_top
  set F : ℝ → ℝ≥0∞ := fun δ =>
    2 * ENNReal.ofReal M * (G + ENNReal.ofReal δ) ^ 2 + 2 * N * ENNReal.ofReal δ ^ 2 with hF_def
  have hF : Continuous F := by
    refine Continuous.add ?_ ?_
    · exact (ENNReal.continuous_const_mul (by finiteness)).comp
        ((ENNReal.continuous_pow 2).comp (continuous_const.add ENNReal.continuous_ofReal))
    · exact (ENNReal.continuous_const_mul (by finiteness)).comp
        ((ENNReal.continuous_pow 2).comp ENNReal.continuous_ofReal)
  have hF0 : F 0 = 2 * ENNReal.ofReal M * G ^ 2 := by simp [F]
  have hle : ∀ δ : ℝ, 0 < δ →
      ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ^ 2 ≤ F δ := by
    intro δ hδ
    obtain ⟨g₀, hg₀c, hg₀s, hg₀⟩ :=
      hg.exist_eLpNorm_sub_le (by norm_num : (2 : ℝ≥0∞) ≠ ∞) one_le_two hδ
    set S := hg₀c.toSchwartzMap hg₀s
    have hSg : (S : EuclideanSpace ℝ (Fin n) → ℂ) = g₀ := rfl
    have hS2 : MemLp g₀ 2 volume := S.memLp 2 volume
    have hdiff2 : MemLp (g - g₀) 2 volume := hg.sub hS2
    have hterm : ∀ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume +
          eLpNorm (k i) 1 volume * ENNReal.ofReal δ := by
      intro i hi
      have hHi := memLp_one_iff_integrable.2 (hk i hi)
      have hae : k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g =ᵐ[volume]
          k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀ +
            k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀) := by
        filter_upwards [ae_convolutionExistsAt_of_memLp one_le_two hHi hS2,
          ae_convolutionExistsAt_of_memLp one_le_two hHi hdiff2] with x h1 h2
        rw [Pi.add_apply, ← h1.distrib_add h2, add_sub_cancel]
      calc eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume
          = eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀ +
              k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀)) 2 volume :=
            eLpNorm_congr_ae hae
        _ ≤ eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume +
              eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀)) 2 volume :=
            eLpNorm_add_le one_le_two
        _ ≤ _ := by
            gcongr
            exact (eLpNorm_convolution_le_mul one_le_two (hk i hi).1
              hdiff2.aestronglyMeasurable).trans (by gcongr)
    have hsch := lp_sum_eLpNorm_conv_schwartz_le s hk hM S
    rw [hSg] at hsch
    have hg₀le : eLpNorm g₀ 2 volume ≤ G + ENNReal.ofReal δ := by
      calc eLpNorm g₀ 2 volume = eLpNorm (g - (g - g₀)) 2 volume := by rw [sub_sub_cancel]
        _ ≤ eLpNorm g 2 volume + eLpNorm (g - g₀) 2 volume := eLpNorm_sub_le one_le_two
        _ ≤ G + ENNReal.ofReal δ := add_le_add le_rfl hg₀
    calc ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ^ 2
        ≤ ∑ i ∈ s, (eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume +
            eLpNorm (k i) 1 volume * ENNReal.ofReal δ) ^ 2 :=
          Finset.sum_le_sum fun i hi => pow_le_pow_left₀ zero_le (hterm i hi) 2
      _ ≤ ∑ i ∈ s, 2 * (eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume ^ 2 +
            (eLpNorm (k i) 1 volume * ENNReal.ofReal δ) ^ 2) :=
          Finset.sum_le_sum fun i _ => lp_add_sq_le _ _
      _ = 2 * ∑ i ∈ s, eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume ^ 2 +
            2 * N * ENNReal.ofReal δ ^ 2 := by
          rw [← Finset.mul_sum, Finset.sum_add_distrib, mul_add]
          congr 1
          rw [hN_def, mul_assoc, Finset.sum_mul]
          simp_rw [mul_pow]
      _ ≤ 2 * (ENNReal.ofReal M * (G + ENNReal.ofReal δ) ^ 2) + 2 * N * ENNReal.ofReal δ ^ 2 := by
          gcongr
          exact hsch.trans (by gcongr)
      _ = F δ := by simp only [F]; ring
  rw [← hF0]
  exact ge_of_tendsto ((hF.tendsto 0).mono_left nhdsWithin_le_nhds)
    (eventually_nhdsWithin_of_forall (s := Ioi 0) fun δ hδ => hle δ hδ)

/-- **The `L²` estimate** for the dilates of a mean-zero Schwartz function, in the form of the
hypothesis of the square-function theorem `vcz_eLpNorm_sqFun_le`. -/
theorem lp_L2 (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) (hψ : ∫ x, ψ x = 0) :
    ∃ A : ℝ, 0 ≤ A ∧ ∀ (s : Finset ℤ) (g : EuclideanSpace ℝ (Fin n) → ℂ), MemLp g 2 volume →
      ∑ j ∈ s, eLpNorm (fun x => ∫ y, lpDilate n ψ j (x - y) * g y) 2 volume ^ 2 ≤
        ENNReal.ofReal A ^ 2 * eLpNorm g 2 volume ^ 2 := by
  obtain ⟨M, hM0, hM⟩ := lp_sum_fourier_sq_le ψ hψ
  refine ⟨√(2 * M), Real.sqrt_nonneg _, fun s g hg => ?_⟩
  have hconv : ∀ j, (fun x => ∫ y, lpDilate n ψ j (x - y) * g y) =
      lpDilate n ψ j ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g := fun j =>
    funext fun x => (convolution_eq_integral_sub _ _ x).symm
  simp_rw [hconv]
  rw [← ENNReal.ofReal_pow (Real.sqrt_nonneg _), Real.sq_sqrt (by positivity),
    ENNReal.ofReal_mul zero_le_two, ENNReal.ofReal_ofNat]
  exact lp_sum_eLpNorm_conv_le s (fun j _ => integrable_lpDilate ψ.integrable j) (hM s) hg

end Fourier

/-! ## The Littlewood–Paley inequality -/

/-- **The Littlewood–Paley inequality.** Let `n ≥ 1`, `1 < p < ∞`, and let `ψ` be a Schwartz
function on `ℝⁿ` with `∫ ψ = 0`; write `ψ_j(x) = 2^{jn} ψ(2^j x)`. Then there is `C` such that
for every finite set of scales `s ⊆ ℤ` and every `f ∈ L^p`,
`‖(∑_{j ∈ s} |ψ_j * f|²)^{1/2}‖_p ≤ C ‖f‖_p`. -/
theorem littlewood_paley {n : ℕ} (hn : 0 < n) (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ)
    (hψ : ∫ x, ψ x = 0) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (s : Finset ℤ) (f : EuclideanSpace ℝ (Fin n) → ℂ),
      MemLp f (ENNReal.ofReal p) volume →
      eLpNorm (fun x => √(∑ j ∈ s, ‖∫ y, lpDilate n ψ j (x - y) * f y‖ ^ 2))
        (ENNReal.ofReal p) volume ≤ ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) volume := by
  obtain ⟨A₁, hA₁, hL2⟩ := lp_L2 ψ hψ
  obtain ⟨A₂, hA₂, hH⟩ := lp_hormander ψ
  have hA : 0 ≤ max A₁ A₂ := le_max_of_le_left hA₁
  refine ⟨vczConst n p * max A₁ A₂, mul_nonneg (vczConst_nonneg n p) hA, fun s f hf => ?_⟩
  refine vcz_eLpNorm_sqFun_le hn hp s (lpDilate n ψ) hA
    (fun j _ => integrable_lpDilate ψ.integrable j) (fun g hg => (hL2 s g hg).trans ?_)
    (fun y => (hH s y).trans ?_) hf
  · gcongr; exact le_max_left _ _
  · exact ENNReal.ofReal_le_ofReal (le_max_right _ _)

/-! ## Convolution with a radially decreasing majorant and the maximal function -/

section Maximal

variable {n : ℕ}

/-- The centered Hardy–Littlewood maximal function over closed balls,
`M f(x) = sup_{r > 0} |B(x, r)|⁻¹ ∫_{B(x, r)} |f|`, as an element of `[0, ∞]`. -/
def lpMaximal (f : EuclideanSpace ℝ (Fin n) → ℂ) (x : EuclideanSpace ℝ (Fin n)) : ℝ≥0∞ :=
  ⨆ (r : ℝ) (_ : 0 < r), (volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ

/-- `∫_{B(x, r)} |f| ≤ |B(x, r)| M f(x)` for `r > 0`. -/
lemma lp_setLIntegral_closedBall_le (f : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) {r : ℝ} (hr : 0 < r) :
    ∫⁻ y in closedBall x r, ‖f y‖ₑ ≤ volume (closedBall x r) * lpMaximal f x := by
  have h0 : volume (closedBall x r) ≠ 0 := (measure_closedBall_pos volume x hr).ne'
  have ht : volume (closedBall x r) ≠ ∞ := measure_closedBall_lt_top.ne
  calc ∫⁻ y in closedBall x r, ‖f y‖ₑ = volume (closedBall x r) *
        ((volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ) :=
        (ENNReal.mul_inv_cancel_left h0 ht).symm
    _ ≤ volume (closedBall x r) * lpMaximal f x := by
        gcongr
        exact le_iSup₂ (f := fun r (_ : 0 < r) =>
          (volume (closedBall x r))⁻¹ * ∫⁻ y in closedBall x r, ‖f y‖ₑ) r hr

/-- For a set `S` which is radially decreasing (`z ∈ S`, `|w| ≤ |z|` imply `w ∈ S`), i.e. a
centered ball (open or closed), `∅` or `ℝⁿ`: `∫_{x - S} |f| ≤ |S| M f(x)`. -/
lemma lp_setLIntegral_le_of_radial (hn : 0 < n) (f : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) {S : Set (EuclideanSpace ℝ (Fin n))}
    (hS : ∀ z ∈ S, ∀ w : EuclideanSpace ℝ (Fin n), ‖w‖ ≤ ‖z‖ → w ∈ S) :
    ∫⁻ y in {y | x - y ∈ S}, ‖f y‖ₑ ≤ volume S * lpMaximal f x := by
  have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
  rcases S.eq_empty_or_nonempty with hSe | ⟨z₀, hz₀⟩
  · simp [hSe]
  by_cases hbdd : BddAbove (norm '' S)
  · set a := sSup (norm '' S) with ha_def
    have hsub : {y | x - y ∈ S} ⊆ closedBall x a := fun y hy => by
      rw [mem_closedBall, dist_eq_norm, ← norm_neg, neg_sub]
      exact le_csSup hbdd ⟨_, hy, rfl⟩
    have hball : ball (0 : EuclideanSpace ℝ (Fin n)) a ⊆ S := fun z hz => by
      rw [mem_ball_zero_iff] at hz
      obtain ⟨_, ⟨w, hw, rfl⟩, hlt⟩ :=
        exists_lt_of_lt_csSup (⟨‖z₀‖, z₀, hz₀, rfl⟩ : (norm '' S).Nonempty) hz
      exact hS w hw z hlt.le
    have ha0 : 0 ≤ a := (norm_nonneg z₀).trans (le_csSup hbdd ⟨z₀, hz₀, rfl⟩)
    calc ∫⁻ y in {y | x - y ∈ S}, ‖f y‖ₑ ≤ ∫⁻ y in closedBall x a, ‖f y‖ₑ :=
          lintegral_mono_set hsub
      _ ≤ volume (closedBall x a) * lpMaximal f x := by
          rcases ha0.eq_or_lt with ha | ha
          · have hvol0 : volume (closedBall x a) = 0 := by
              rw [EuclideanSpace.volume_closedBall, ← ha]
              simp [Fintype.card_fin, zero_pow hn.ne']
            rw [setLIntegral_measure_zero _ _ hvol0]
            exact zero_le
          · exact lp_setLIntegral_closedBall_le f x ha
      _ = volume (ball (0 : EuclideanSpace ℝ (Fin n)) a) * lpMaximal f x := by
          rw [EuclideanSpace.volume_closedBall, EuclideanSpace.volume_ball]
      _ ≤ volume S * lpMaximal f x := by gcongr
  · have huniv : S = univ := eq_univ_of_forall fun w => by
      rw [not_bddAbove_iff] at hbdd
      obtain ⟨_, ⟨z, hz, rfl⟩, hlt⟩ := hbdd ‖w‖
      exact hS z hz w hlt.le
    have hvol : volume S = ∞ := by
      rw [huniv]; exact measure_univ_of_isAddLeftInvariant volume
    rw [hvol]
    by_cases hM : lpMaximal f x = 0
    · have hk : ∀ k : ℕ, ∫⁻ y in closedBall x (k + 1), ‖f y‖ₑ = 0 := fun k => by
        have := lp_setLIntegral_closedBall_le f x (r := k + 1) (by positivity)
        rw [hM, mul_zero] at this
        exact le_antisymm this zero_le
      have hU : {y | x - y ∈ S} ⊆ ⋃ k : ℕ, closedBall x (k + 1) := fun y _ => by
        obtain ⟨k, hk⟩ := exists_nat_gt (dist y x)
        exact mem_iUnion.2 ⟨k, mem_closedBall.2 (by linarith)⟩
      calc ∫⁻ y in {y | x - y ∈ S}, ‖f y‖ₑ
          ≤ ∫⁻ y in ⋃ k : ℕ, closedBall x (k + 1), ‖f y‖ₑ := lintegral_mono_set hU
        _ ≤ ∑' k : ℕ, ∫⁻ y in closedBall x (k + 1), ‖f y‖ₑ := lintegral_iUnion_le _ _
        _ = 0 := by simp [hk]
        _ ≤ _ := zero_le
    · rw [ENNReal.top_mul hM]; exact le_top

/-- **Convolution with a radially decreasing integrable majorant is controlled by the maximal
function** (Stein's lemma). Let `n ≥ 1` and let `Φ : [0, ∞) → [0, ∞)` be nonincreasing with
`|h(z)| ≤ Φ(|z|)`. Then `|∫ h(x - y) f(y) dy| ≤ (∫ Φ(|z|) dz) · M f(x)`, with `M` the centered
maximal function `lpMaximal` over closed balls. -/
theorem norm_conv_le_maximal (hn : 0 < n) {Φ : ℝ → ℝ} (hΦ : AntitoneOn Φ (Ici 0))
    (hΦ0 : ∀ r, 0 ≤ r → 0 ≤ Φ r) {h f : EuclideanSpace ℝ (Fin n) → ℂ}
    (hh : ∀ z, ‖h z‖ ≤ Φ ‖z‖) (hf : AEStronglyMeasurable f volume)
    (x : EuclideanSpace ℝ (Fin n)) :
    ‖∫ y, h (x - y) * f y‖ₑ ≤
      (∫⁻ z : EuclideanSpace ℝ (Fin n), ENNReal.ofReal (Φ ‖z‖)) * lpMaximal f x := by
  set Φ' : ℝ → ℝ := fun r => Φ (max r 0) with hΦ'_def
  have hΦ' : Antitone Φ' := fun r s hrs =>
    hΦ (mem_Ici.2 (le_max_right _ _)) (mem_Ici.2 (le_max_right _ _)) (max_le_max hrs le_rfl)
  have hΦ'n : ∀ z : EuclideanSpace ℝ (Fin n), Φ' ‖z‖ = Φ ‖z‖ := fun z => by
    simp only [Φ', max_eq_left (norm_nonneg z)]
  have hφm : Measurable fun z : EuclideanSpace ℝ (Fin n) => Φ' ‖z‖ :=
    hΦ'.measurable.comp measurable_norm
  have hφ0 : ∀ z : EuclideanSpace ℝ (Fin n), 0 ≤ Φ' ‖z‖ := fun z => hΦ0 _ (le_max_right _ _)
  have hmx : Measurable fun y : EuclideanSpace ℝ (Fin n) => Φ' ‖x - y‖ :=
    hφm.comp (measurable_const.sub measurable_id)
  have hmt : Measurable fun t : ℝ => volume {z : EuclideanSpace ℝ (Fin n) | t < Φ' ‖z‖} := by
    refine Antitone.measurable fun t t' htt => measure_mono fun z hz => ?_
    exact lt_of_le_of_lt htt hz
  calc ‖∫ y, h (x - y) * f y‖ₑ ≤ ∫⁻ y, ‖h (x - y) * f y‖ₑ := enorm_integral_le_lintegral_enorm _
    _ ≤ ∫⁻ y, ‖f y‖ₑ * ENNReal.ofReal (Φ' ‖x - y‖) := lintegral_mono fun y => by
        rw [enorm_mul, mul_comm, hΦ'n]
        gcongr
        rw [← ofReal_norm]
        exact ENNReal.ofReal_le_ofReal (hh _)
    _ = ∫⁻ y, ENNReal.ofReal (Φ' ‖x - y‖) ∂(volume.withDensity fun y => ‖f y‖ₑ) :=
        (lintegral_withDensity_eq_lintegral_mul₀ hf.enorm
          hmx.ennreal_ofReal.aemeasurable).symm
    _ = ∫⁻ t in Ioi 0, (volume.withDensity fun y => ‖f y‖ₑ) {y | t < Φ' ‖x - y‖} :=
        lintegral_eq_lintegral_meas_lt _ (ae_of_all _ fun y => hφ0 _) hmx.aemeasurable
    _ ≤ ∫⁻ t in Ioi 0, volume {z : EuclideanSpace ℝ (Fin n) | t < Φ' ‖z‖} * lpMaximal f x := by
        refine lintegral_mono fun t => ?_
        rw [withDensity_apply _ (measurableSet_lt measurable_const hmx)]
        exact lp_setLIntegral_le_of_radial hn f x (S := {z | t < Φ' ‖z‖})
          fun z hz w hw => lt_of_lt_of_le hz (hΦ' hw)
    _ = (∫⁻ t in Ioi 0, volume {z : EuclideanSpace ℝ (Fin n) | t < Φ' ‖z‖}) * lpMaximal f x :=
        lintegral_mul_const _ hmt
    _ = (∫⁻ z : EuclideanSpace ℝ (Fin n), ENNReal.ofReal (Φ ‖z‖)) * lpMaximal f x := by
        rw [← lintegral_eq_lintegral_meas_lt volume (ae_of_all _ hφ0) hφm.aemeasurable]
        simp_rw [hΦ'n]

/-- The form of `norm_conv_le_maximal` with an integrable majorant:
`|∫ h(x - y) f(y) dy| ≤ A · M f(x)` with `A = ∫ Φ(|z|) dz`. -/
theorem norm_conv_le_maximal_of_integrable (hn : 0 < n) {Φ : ℝ → ℝ} (hΦ : AntitoneOn Φ (Ici 0))
    (hΦ0 : ∀ r, 0 ≤ r → 0 ≤ Φ r)
    (hΦi : Integrable fun z : EuclideanSpace ℝ (Fin n) => Φ ‖z‖)
    {h f : EuclideanSpace ℝ (Fin n) → ℂ} (hh : ∀ z, ‖h z‖ ≤ Φ ‖z‖)
    (hf : AEStronglyMeasurable f volume) (x : EuclideanSpace ℝ (Fin n)) :
    ‖∫ y, h (x - y) * f y‖ₑ ≤
      ENNReal.ofReal (∫ z : EuclideanSpace ℝ (Fin n), Φ ‖z‖) * lpMaximal f x := by
  rw [ofReal_integral_eq_lintegral_ofReal hΦi (ae_of_all _ fun z => hΦ0 _ (norm_nonneg z))]
  exact norm_conv_le_maximal hn hΦ hΦ0 hh hf x

end Maximal

/-! ## Vector-valued inputs -/

section Vector

variable {n : ℕ} {ι : Type*} (s : Finset ι)

open Classical in
/-- The rank-one operator `v ↦ v_i e_i` on `ℓ²(s)`. -/
def lpDiagUnit (i : s) : EuclideanSpace ℂ s →L[ℂ] EuclideanSpace ℂ s :=
  (ContinuousLinearMap.toSpanSingleton ℂ (EuclideanSpace.single i (1 : ℂ))).comp
    (EuclideanSpace.proj i)

/-- The diagonal operator-valued kernel `x ↦ diag(k_i(x))_{i ∈ s}` on `ℓ²(s)`. -/
def lpDiagKernel (k : ι → EuclideanSpace ℝ (Fin n) → ℂ) (x : EuclideanSpace ℝ (Fin n)) :
    EuclideanSpace ℂ s →L[ℂ] EuclideanSpace ℂ s :=
  ∑ i : s, k i x • lpDiagUnit s i

variable {s}

lemma lpDiagKernel_apply (k : ι → EuclideanSpace ℝ (Fin n) → ℂ) (x : EuclideanSpace ℝ (Fin n))
    (v : EuclideanSpace ℂ s) (j : s) : lpDiagKernel s k x v j = k j x * v j := by
  classical
  simp [lpDiagKernel, lpDiagUnit, Pi.single_apply, Finset.sum_ite_eq]

lemma norm_lpDiagUnit_le (i : s) : ‖lpDiagUnit s i‖ ≤ 1 := by
  classical
  refine ContinuousLinearMap.opNorm_le_bound _ zero_le_one fun v => ?_
  simp only [lpDiagUnit, ContinuousLinearMap.comp_apply, ContinuousLinearMap.toSpanSingleton_apply,
    norm_smul]
  simp only [PiLp.proj_apply, PiLp.norm_single, norm_one, mul_one, one_mul]
  exact PiLp.norm_apply_le v i

lemma integrable_lpDiagKernel {k : ι → EuclideanSpace ℝ (Fin n) → ℂ}
    (hk : ∀ i ∈ s, Integrable (k i)) : Integrable (lpDiagKernel s k) := by
  have : lpDiagKernel s k = fun x => ∑ i : s, k i x • lpDiagUnit s i := rfl
  rw [this]
  exact integrable_finsetSum (f := fun (i : s) x => k i x • lpDiagUnit s i) _
    fun i _ => (hk i i.2).smul_const _

lemma norm_lpDiagKernel_sub_le (k : ι → EuclideanSpace ℝ (Fin n) → ℂ)
    (x y : EuclideanSpace ℝ (Fin n)) :
    ‖lpDiagKernel s k x - lpDiagKernel s k y‖ ≤ ∑ i ∈ s, ‖k i x - k i y‖ := by
  have h : lpDiagKernel s k x - lpDiagKernel s k y =
      ∑ i : s, (k i x - k i y) • lpDiagUnit s i := by
    simp only [lpDiagKernel, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => (sub_smul _ _ _).symm
  rw [h]
  calc ‖∑ i : s, (k i x - k i y) • lpDiagUnit s i‖
      ≤ ∑ i : s, ‖(k i x - k i y) • lpDiagUnit s i‖ := norm_sum_le _ _
    _ ≤ ∑ i : s, ‖k i x - k i y‖ := Finset.sum_le_sum fun i _ => by
        rw [norm_smul]; exact mul_le_of_le_one_right (norm_nonneg _) (norm_lpDiagUnit_le i)
    _ = ∑ i ∈ s, ‖k i x - k i y‖ := Finset.sum_coe_sort s (fun i => ‖k i x - k i y‖)

/-- The norm of `v ∈ ℓ²(s)` with coordinates `v_j = w_j`. -/
lemma lp_norm_euclidean {v : EuclideanSpace ℂ s} {w : ι → ℂ} (h : ∀ j : s, v j = w j) :
    ‖v‖ = √(∑ j ∈ s, ‖w j‖ ^ 2) := by
  rw [EuclideanSpace.norm_eq, ← Finset.sum_coe_sort s (fun j => ‖w j‖ ^ 2)]
  simp_rw [h]

/-- `‖u‖₂² = ∑_j ‖u_j‖₂²` for `ℓ²(s)`-valued `u`. -/
lemma lp_eLpNorm_euclidean_sq {u : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ s}
    (hu : AEStronglyMeasurable u volume) :
    eLpNorm u 2 volume ^ 2 = ∑ j : s, eLpNorm (fun x => u x j) 2 volume ^ 2 := by
  have hj : ∀ j : s, AEStronglyMeasurable (fun x => u x j) volume := fun j =>
    (EuclideanSpace.proj j).continuous.comp_aestronglyMeasurable hu
  have hpt : ∀ x, ‖u x‖ₑ ^ 2 = ∑ j : s, ‖u x j‖ₑ ^ 2 := fun x => by
    rw [← ofReal_norm, ← ENNReal.ofReal_pow (norm_nonneg _), EuclideanSpace.norm_sq_eq,
      ENNReal.ofReal_sum_of_nonneg fun j _ => by positivity]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [← ofReal_norm, ENNReal.ofReal_pow (norm_nonneg _)]
  rw [lp_eLpNorm_two_sq hu]
  simp_rw [hpt]
  rw [lintegral_finsetSum' _ fun j _ => (hj j).enorm.pow_const 2]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [lp_eLpNorm_two_sq (hj j)]

/-- The coordinates of the diagonal convolution are the scalar convolutions, a.e. -/
lemma lp_diag_component_ae {k : ι → EuclideanSpace ℝ (Fin n) → ℂ}
    (hk : ∀ i ∈ s, Integrable (k i)) {p : ℝ≥0∞} (hp : 1 ≤ p)
    {g : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ s} (hg : MemLp g p volume) :
    ∀ᵐ x, ∀ j : s, (∫ y, lpDiagKernel s k (x - y) (g y)) j = ∫ y, k j (x - y) * g y j := by
  filter_upwards [vcz_ae_convolutionExistsAt hp (integrable_lpDiagKernel hk) hg] with x hx j
  have hG := vcz_integrable_of_convolutionExistsAt hx
  change EuclideanSpace.proj j (∫ y, lpDiagKernel s k (x - y) (g y)) = _
  rw [← (EuclideanSpace.proj j).integral_comp_comm hG]
  congr 1
  funext y
  exact lpDiagKernel_apply k (x - y) (g y) j

/-- The `L²` bound of the diagonal kernel from uniform `L²` bounds of its entries. -/
lemma lp_diag_L2 {k : ι → EuclideanSpace ℝ (Fin n) → ℂ} (hk : ∀ i ∈ s, Integrable (k i))
    {A : ℝ} (hkA : ∀ i ∈ s, ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (k i ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume)
    (g : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ s) (hg : MemLp g 2 volume) :
    eLpNorm (fun x => ∫ y, lpDiagKernel s k (x - y) (g y)) 2 volume ≤
      ENNReal.ofReal A * eLpNorm g 2 volume := by
  have hgj : ∀ j : s, MemLp (fun y => g y j) 2 volume := fun j =>
    (EuclideanSpace.proj (𝕜 := ℂ) j : EuclideanSpace ℂ s →L[ℂ] ℂ).comp_memLp' hg
  have hT : AEStronglyMeasurable (fun x => ∫ y, lpDiagKernel s k (x - y) (g y)) volume := by
    rw [vcz_fun_eq_convolution]
    exact AEStronglyMeasurable.convolution _ (integrable_lpDiagKernel hk).1 hg.aestronglyMeasurable
  have hae := lp_diag_component_ae hk one_le_two hg
  rw [← ENNReal.pow_le_pow_left_iff two_ne_zero, lp_eLpNorm_euclidean_sq hT, mul_pow,
    lp_eLpNorm_euclidean_sq hg.aestronglyMeasurable, Finset.mul_sum]
  refine Finset.sum_le_sum fun j _ => ?_
  have hc : (fun x => (∫ y, lpDiagKernel s k (x - y) (g y)) j) =ᵐ[volume]
      k j ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (fun y => g y j) := by
    filter_upwards [hae] with x hx
    rw [hx j, convolution_eq_integral_sub]
  rw [eLpNorm_congr_ae hc, ← mul_pow]
  exact pow_le_pow_left₀ zero_le (hkA j j.2 _ (hgj j)) 2

/-- **The Littlewood–Paley inequality for vector-valued inputs.** Under the hypotheses of
`littlewood_paley`, there is `C` such that for every finite set of scales `s ⊆ ℤ` and all
`f_j ∈ L^p` (`j ∈ s`),
`‖(∑_{j ∈ s} |ψ_j * f_j|²)^{1/2}‖_p ≤ C ‖(∑_{j ∈ s} |f_j|²)^{1/2}‖_p`. -/
theorem littlewood_paley_vector {n : ℕ} (hn : 0 < n)
    (ψ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) (hψ : ∫ x, ψ x = 0) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (s : Finset ℤ) (F : ℤ → EuclideanSpace ℝ (Fin n) → ℂ),
      (∀ j ∈ s, MemLp (F j) (ENNReal.ofReal p) volume) →
      eLpNorm (fun x => √(∑ j ∈ s, ‖∫ y, lpDilate n ψ j (x - y) * F j y‖ ^ 2))
        (ENNReal.ofReal p) volume ≤
        ENNReal.ofReal C *
          eLpNorm (fun x => √(∑ j ∈ s, ‖F j x‖ ^ 2)) (ENNReal.ofReal p) volume := by
  classical
  obtain ⟨D, hD, hF⟩ := lp_norm_fourier_le ψ hψ
  obtain ⟨K, hK, hpt⟩ := lp_sum_dilate_sub_le ψ
  have hA : 0 ≤ max D (K * 2 ^ n * envelopeConst n) := le_max_of_le_left hD
  refine ⟨vczConst n p * max D (K * 2 ^ n * envelopeConst n),
    mul_nonneg (vczConst_nonneg n p) hA, fun s F hFp => ?_⟩
  have hp1 : 1 ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have hk : ∀ j ∈ s, Integrable (lpDilate n ψ j) := fun j _ =>
    integrable_lpDilate ψ.integrable j
  have hkA : ∀ j ∈ s, ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (lpDilate n ψ j ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal (max D (K * 2 ^ n * envelopeConst n)) * eLpNorm g 2 volume := by
    intro j hj g hg
    refine eLpNorm_convolution_two_le_of_norm_fourier_le (hk j hj) (fun ξ => ?_) g hg
    rw [fourier_lpDilate]
    refine (hF _).trans ?_
    calc D * min ‖((2 : ℝ) ^ j)⁻¹ • ξ‖ ‖((2 : ℝ) ^ j)⁻¹ • ξ‖⁻¹ ≤ D * 1 :=
          mul_le_mul_of_nonneg_left (lp_min_inv_le_one _) hD
      _ ≤ max D (K * 2 ^ n * envelopeConst n) := by rw [mul_one]; exact le_max_left _ _
  set G : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℂ s :=
    fun y => WithLp.toLp 2 (fun j : s => F j y) with hG_def
  have hGeq : G = fun y => ∑ j : s,
      (ContinuousLinearMap.toSpanSingleton ℂ (EuclideanSpace.single j (1 : ℂ))) (F j y) := by
    funext y
    ext j
    simp [G, Pi.single_apply, Finset.sum_ite_eq]
  have hGp : MemLp G (ENNReal.ofReal p) volume := by
    rw [hGeq]
    exact memLp_finsetSum _ fun j _ =>
      (ContinuousLinearMap.toSpanSingleton ℂ (EuclideanSpace.single j (1 : ℂ))).comp_memLp'
        (hFp j j.2)
  have hmain := vcz_eLpNorm_le_of_innerProductSpace hn hp hA (integrable_lpDiagKernel hk)
    (lp_diag_L2 hk hkA)
    (fun y => (lp_lintegral_le_of_le_div hK y fun x hx => by
      rw [← ofReal_norm]
      exact ENNReal.ofReal_le_ofReal
        ((norm_lpDiagKernel_sub_le _ _ _).trans (hpt s x y hx))).trans
      (ENNReal.ofReal_le_ofReal (le_max_right _ _))) hGp
  have hL : eLpNorm (fun x => √(∑ j ∈ s, ‖∫ y, lpDilate n ψ j (x - y) * F j y‖ ^ 2))
      (ENNReal.ofReal p) volume = eLpNorm (fun x => ∫ y, lpDiagKernel s (lpDilate n ψ) (x - y)
        (G y)) (ENNReal.ofReal p) volume := by
    rw [← eLpNorm_norm (fun x => ∫ y, lpDiagKernel s (lpDilate n ψ) (x - y) (G y)) (by
      rw [vcz_fun_eq_convolution]
      exact AEStronglyMeasurable.convolution _ (integrable_lpDiagKernel hk).1
        hGp.aestronglyMeasurable)]
    refine eLpNorm_congr_ae ?_
    filter_upwards [lp_diag_component_ae hk hp1 hGp] with x hx
    exact (lp_norm_euclidean fun j => hx j).symm
  have hR : eLpNorm G (ENNReal.ofReal p) volume =
      eLpNorm (fun x => √(∑ j ∈ s, ‖F j x‖ ^ 2)) (ENNReal.ofReal p) volume := by
    rw [← eLpNorm_norm G hGp.aestronglyMeasurable]
    congr 1
    funext x
    exact lp_norm_euclidean fun j => rfl
  rw [hL, ← hR]
  exact hmain

end Vector

end

end Auto
