/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# The Marcinkiewicz interpolation theorem

This file was automatically generated by Claude.

This file proves the **Marcinkiewicz (real) interpolation theorem** for subadditive operators,
in textbook generality and with explicit constants. It depends on Mathlib only.

It was adapted from the user's project `lean-discretesw` (file
`DiscreteSW/Auto/MarcinkiewiczInterpolation.lean`), where it is Blueprint Lemma 2.3
(`lem:interpolation`); "Blueprint" in the docstrings below refers to the blueprint
`blueprints/discrete-sw.tex` of that project.

## Setting

* Inputs are functions `f : α → E` on a measure space `(α, μ)` (`μ` s-finite), outputs are
  functions `T f : β → F` on a possibly different measure space `(β, ν)`; `E` and `F` are
  arbitrary normed additive groups (so vector-valued inputs and outputs, e.g.
  `EuclideanSpace ℂ (Fin k)`, are covered).
* `T : (α → E) → β → F` is only required to behave well on a class `D` of inputs:
  * `IsSublinearOn T D ν`: `‖T (f + g)‖ ≤ ‖T f‖ + ‖T g‖` `ν`-a.e. for `f, g ∈ D`;
  * `IsTruncationClosed D`: `f 𝟙_{‖f‖ > s}` and `f 𝟙_{‖f‖ ≤ s}` lie in `D` for `f ∈ D`, `s > 0`
    (e.g. `D = univ`, `isTruncationClosed_univ`, or `D = L^q`, `isTruncationClosed_memLp`).
  Homogeneity is not needed.
* `distributionFunction g t ν = ν {x | t < ‖g x‖ₑ}`;
  `HasWeakTypeOn T D a A μ ν`: `ν {‖T f‖ > t} ≤ (A ‖f‖_{L^a} / t)^a` for `f ∈ D`, `t > 0`;
  `HasStrongTypeOn T D a A μ ν`: `‖T f‖_{L^a} ≤ A ‖f‖_{L^a}` for `f ∈ D`;
  `HasLinftyBoundOn T D B ν`: `‖f‖ ≤ s` everywhere implies `‖T f‖ ≤ B s` `ν`-a.e.
  Constants `A B : ℝ≥0`, exponents are real and enter `eLpNorm` via `ENNReal.ofReal`.
* Measurability of the particular output `T f` is an explicit hypothesis of the main theorems
  (`eLpNorm` of a non-a.e.-strongly-measurable function is `∞`).

## Main results

* `eLpNorm_rpow_eq_lintegral_distributionFunction`: layer-cake formula
  `‖g‖_p^p = p ∫_0^∞ t^(p-1) ν{‖g‖ > t} dt`.
* `HasStrongTypeOn.hasWeakTypeOn`: Chebyshev, strong `(a,a)` implies weak `(a,a)`, same constant.
* `lintegral_rpow_le_of_hasWeakTypeOn`, `eLpNorm_le_of_hasWeakTypeOn_of_pos`: for weak types
  `(a,a)`, `(b,b)` with constants `A`, `B`, `0 < a < p < b < ∞`, and **every** truncation
  parameter `c > 0`,
  `‖T f‖_p^p ≤ p (2^a A^a c^(a-p)/(p-a) + 2^b B^b c^(b-p)/(b-p)) ‖f‖_p^p`
  (`marcinkiewiczBound`).
* `eLpNorm_le_of_hasWeakTypeOn`: the Marcinkiewicz interpolation theorem
  `‖T f‖_p ≤ C(a,b,p) A^(1-θ) B^θ ‖f‖_p`, `1/p = (1-θ)/a + θ/b`, with the explicit finite constant
  `C(a,b,p) = marcinkiewiczConst a b p = (p (2^a/(p-a) + 2^b/(b-p)))^(1/p)`
  (the case `A = 0` or `B = 0` is included).
* `lintegral_rpow_le_of_hasWeakTypeOn_of_linfty`, `eLpNorm_le_of_hasWeakTypeOn_of_linfty_of_pos`,
  `eLpNorm_le_of_hasWeakTypeOn_of_linfty`: the endpoint `b = ∞`,
  `‖T f‖_p ≤ C(a,p) A^(a/p) B^(1-a/p) ‖f‖_p` for `0 < a < p < ∞`, with
  `C(a,p) = marcinkiewiczConstTop a p = 2 (p/(p-a))^(1/p)`.

## Proof

Split `f = f 𝟙_{‖f‖ > c t} + f 𝟙_{‖f‖ ≤ c t}`, use subadditivity and the two weak-type bounds at
height `t/2`, insert into the layer-cake formula and exchange the integrals (Tonelli); the inner
integrals are `∫_0^{‖f‖/c} t^(p-a-1) dt` and `∫_{‖f‖/c}^∞ t^(p-b-1) dt`. Finally optimize `c`.

## References

* J. Marcinkiewicz, *Sur l'interpolation d'opérations*, C. R. Acad. Sci. Paris **208** (1939),
  1272–1273.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, Theorem 1.3.2.
* E. M. Stein and G. Weiss, *Introduction to Fourier Analysis on Euclidean Spaces*, Chapter V,
  §2.
-/

@[expose] public section

namespace Auto

open MeasureTheory Set Filter Topology
open scoped ENNReal NNReal

noncomputable section

/-! ### Elementary power integrals on the half-line -/

/-- `∫_0^u t^(r-1) dt = u^r / r` for `r > 0`, written with an indicator on `(0, ∞)`. -/
theorem lintegral_Ioi_indicator_Iio_rpow {u r : ℝ} (hu : 0 ≤ u) (hr : 0 < r) :
    ∫⁻ t in Ioi (0 : ℝ), (Iio u).indicator (fun t => ENNReal.ofReal (t ^ (r - 1))) t =
      ENNReal.ofReal (u ^ r / r) := by
  rw [lintegral_indicator measurableSet_Iio, Measure.restrict_restrict measurableSet_Iio,
    Set.inter_comm, Ioi_inter_Iio, setLIntegral_congr Ioo_ae_eq_Ioc]
  have hpow : -1 < r - 1 := by linarith
  have hinterval : IntervalIntegrable (fun t : ℝ => t ^ (r - 1)) volume 0 u :=
    intervalIntegral.intervalIntegrable_rpow' hpow
  have hIoc : IntegrableOn (fun t : ℝ => t ^ (r - 1)) (Ioc 0 u) volume :=
    (intervalIntegrable_iff_integrableOn_Ioc_of_le hu).mp hinterval
  have hnonneg : 0 ≤ᵐ[volume.restrict (Ioc 0 u)] (fun t : ℝ => t ^ (r - 1)) := by
    filter_upwards [ae_restrict_mem measurableSet_Ioc] with t ht
    exact Real.rpow_nonneg ht.1.le _
  rw [← ofReal_integral_eq_lintegral_ofReal hIoc hnonneg, ← intervalIntegral.integral_of_le hu,
    integral_rpow (Or.inl hpow)]
  rw [show r - 1 + 1 = r by ring, Real.zero_rpow hr.ne']
  simp

/-- `∫_u^∞ t^(-r-1) dt = u^(-r) / r` for `u > 0`, `r > 0`, written with an indicator on
`(0, ∞)`. -/
theorem lintegral_Ioi_indicator_Ici_rpow {u r : ℝ} (hu : 0 < u) (hr : 0 < r) :
    ∫⁻ t in Ioi (0 : ℝ), (Ici u).indicator (fun t => ENNReal.ofReal (t ^ (-r - 1))) t =
      ENNReal.ofReal (u ^ (-r) / r) := by
  rw [lintegral_indicator measurableSet_Ici, Measure.restrict_restrict measurableSet_Ici]
  have hinter : Ici u ∩ Ioi (0 : ℝ) = Ici u :=
    inter_eq_left.mpr fun t ht => hu.trans_le ht
  rw [hinter, ← setLIntegral_congr Ioi_ae_eq_Ici]
  have hpow : -r - 1 < -1 := by linarith
  have hIoi : IntegrableOn (fun t : ℝ => t ^ (-r - 1)) (Ioi u) volume :=
    integrableOn_Ioi_rpow_of_lt hpow hu
  have hnonneg : 0 ≤ᵐ[volume.restrict (Ioi u)] (fun t : ℝ => t ^ (-r - 1)) := by
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    exact Real.rpow_nonneg (hu.trans ht).le _
  rw [← ofReal_integral_eq_lintegral_ofReal hIoi hnonneg, integral_Ioi_rpow_of_lt hpow hu]
  rw [show -r - 1 + 1 = -r by ring]
  congr 1
  field_simp

/-! ### Tonelli for the truncation integrals -/

section Tonelli

variable {α : Type*} [MeasurableSpace α] {μ : Measure α}

/-- Exchange of the `t`-integral over `(0, ∞)` and the space integral for integrands supported
on a measurable subset `S` of `ℝ × α` (Tonelli). -/
theorem lintegral_Ioi_mul_lintegral_indicator_swap [SFinite μ] (S : Set (ℝ × α))
    (hS : MeasurableSet S) (w : ℝ → ℝ≥0∞) (hw : Measurable w) (v : α → ℝ≥0∞)
    (hv : Measurable v) :
    ∫⁻ t in Ioi (0 : ℝ), w t * ∫⁻ x, S.indicator (fun z => v z.2) (t, x) ∂μ =
      ∫⁻ x, v x * (∫⁻ t in Ioi (0 : ℝ), S.indicator (fun z => w z.1) (t, x)) ∂μ := by
  have hF : Measurable (S.indicator (fun z : ℝ × α => w z.1 * v z.2)) :=
    ((hw.comp measurable_fst).mul (hv.comp measurable_snd)).indicator hS
  have h1 : ∀ t, w t * ∫⁻ x, S.indicator (fun z => v z.2) (t, x) ∂μ =
      ∫⁻ x, S.indicator (fun z : ℝ × α => w z.1 * v z.2) (t, x) ∂μ := by
    intro t
    have hm : Measurable fun x => S.indicator (fun z : ℝ × α => v z.2) (t, x) :=
      ((hv.comp measurable_snd).indicator hS).comp measurable_prodMk_left
    rw [← lintegral_const_mul _ hm]
    congr 1
    funext x
    by_cases h : (t, x) ∈ S <;> simp [h]
  have h2 : ∀ x, v x * ∫⁻ t in Ioi (0 : ℝ), S.indicator (fun z => w z.1) (t, x) =
      ∫⁻ t in Ioi (0 : ℝ), S.indicator (fun z : ℝ × α => w z.1 * v z.2) (t, x) := by
    intro x
    have hm : Measurable fun t => S.indicator (fun z : ℝ × α => w z.1) (t, x) :=
      ((hw.comp measurable_fst).indicator hS).comp measurable_prodMk_right
    rw [← lintegral_const_mul _ hm]
    congr 1
    funext t
    by_cases h : (t, x) ∈ S <;> simp [h, mul_comm]
  simp_rw [h1, h2]
  exact lintegral_lintegral_swap hF.aemeasurable

/-- Measurability in `t` of the truncated space integrals. -/
theorem measurable_lintegral_indicator_section [SFinite μ] (S : Set (ℝ × α))
    (hS : MeasurableSet S) (v : α → ℝ≥0∞) (hv : Measurable v) :
    Measurable fun t : ℝ => ∫⁻ x, S.indicator (fun z => v z.2) (t, x) ∂μ :=
  ((hv.comp measurable_snd).indicator hS).lintegral_prod_right'

/-- The low-truncation Tonelli identity:
`∫_0^∞ t^(r-1) ∫_{c t < φ} φ^q dμ dt = (c^(-r)/r) ∫ φ^(q+r) dμ`. -/
theorem lintegral_Ioi_rpow_mul_lintegral_indicator_lt [SFinite μ] (φ : α → ℝ)
    (hφ : Measurable φ) (hφ0 : ∀ x, 0 ≤ φ x) {c q r : ℝ} (hc : 0 < c) (hq : 0 ≤ q)
    (hr : 0 < r) :
    ∫⁻ t in Ioi (0 : ℝ), ENNReal.ofReal (t ^ (r - 1)) *
        ∫⁻ x, {x | c * t < φ x}.indicator (fun x => ENNReal.ofReal (φ x) ^ q) x ∂μ =
      ENNReal.ofReal (c ^ (-r) / r) * ∫⁻ x, ENNReal.ofReal (φ x) ^ (q + r) ∂μ := by
  have hS : MeasurableSet {z : ℝ × α | c * z.1 < φ z.2} :=
    measurableSet_lt (measurable_const.mul measurable_fst) (hφ.comp measurable_snd)
  have hw : Measurable fun t : ℝ => ENNReal.ofReal (t ^ (r - 1)) :=
    (measurable_id.pow_const _).ennreal_ofReal
  have hv : Measurable fun x => ENNReal.ofReal (φ x) ^ q := hφ.ennreal_ofReal.pow_const q
  have key := lintegral_Ioi_mul_lintegral_indicator_swap (μ := μ) _ hS _ hw _ hv
  refine key.trans ?_
  rw [← lintegral_const_mul _ (hφ.ennreal_ofReal.pow_const _)]
  refine lintegral_congr fun x => ?_
  have hsec : (fun t => {z : ℝ × α | c * z.1 < φ z.2}.indicator
      (fun z => ENNReal.ofReal (z.1 ^ (r - 1))) (t, x)) =
      (Iio (φ x / c)).indicator (fun t => ENNReal.ofReal (t ^ (r - 1))) := by
    funext t
    simp only [Set.indicator_apply, mem_ofPred_eq, mem_Iio, lt_div_iff₀ hc, mul_comm c]
  rw [hsec, lintegral_Ioi_indicator_Iio_rpow (div_nonneg (hφ0 x) hc.le) hr]
  have hreal : (φ x / c) ^ r / r = c ^ (-r) / r * φ x ^ r := by
    rw [Real.div_rpow (hφ0 x) hc.le, Real.rpow_neg hc.le]
    field_simp
  rw [hreal, ENNReal.ofReal_mul (div_nonneg (Real.rpow_nonneg hc.le _) hr.le),
    ← ENNReal.ofReal_rpow_of_nonneg (hφ0 x) hr.le,
    ENNReal.rpow_add_of_nonneg _ _ hq hr.le]
  ring

/-- The high-truncation Tonelli identity:
`∫_0^∞ t^(-r-1) ∫_{φ ≤ c t} φ^q dμ dt = (c^r/r) ∫ φ^(q-r) dμ` for `0 < r < q`. -/
theorem lintegral_Ioi_rpow_mul_lintegral_indicator_le [SFinite μ] (φ : α → ℝ)
    (hφ : Measurable φ) (hφ0 : ∀ x, 0 ≤ φ x) {c q r : ℝ} (hc : 0 < c) (hq : 0 < q)
    (hr : 0 < r) (hrq : r < q) :
    ∫⁻ t in Ioi (0 : ℝ), ENNReal.ofReal (t ^ (-r - 1)) *
        ∫⁻ x, {x | φ x ≤ c * t}.indicator (fun x => ENNReal.ofReal (φ x) ^ q) x ∂μ =
      ENNReal.ofReal (c ^ r / r) * ∫⁻ x, ENNReal.ofReal (φ x) ^ (q - r) ∂μ := by
  have hS : MeasurableSet {z : ℝ × α | φ z.2 ≤ c * z.1} :=
    measurableSet_le (hφ.comp measurable_snd) (measurable_const.mul measurable_fst)
  have hw : Measurable fun t : ℝ => ENNReal.ofReal (t ^ (-r - 1)) :=
    (measurable_id.pow_const _).ennreal_ofReal
  have hv : Measurable fun x => ENNReal.ofReal (φ x) ^ q := hφ.ennreal_ofReal.pow_const q
  have key := lintegral_Ioi_mul_lintegral_indicator_swap (μ := μ) _ hS _ hw _ hv
  refine key.trans ?_
  rw [← lintegral_const_mul _ (hφ.ennreal_ofReal.pow_const _)]
  refine lintegral_congr fun x => ?_
  rcases (hφ0 x).eq_or_lt with h0 | hpos
  · rw [← h0]
    simp [ENNReal.zero_rpow_of_pos hq, ENNReal.zero_rpow_of_pos (sub_pos.mpr hrq)]
  have hsec : (fun t => {z : ℝ × α | φ z.2 ≤ c * z.1}.indicator
      (fun z => ENNReal.ofReal (z.1 ^ (-r - 1))) (t, x)) =
      (Ici (φ x / c)).indicator (fun t => ENNReal.ofReal (t ^ (-r - 1))) := by
    funext t
    simp only [Set.indicator_apply, mem_ofPred_eq, mem_Ici, div_le_iff₀ hc, mul_comm c]
  rw [hsec, lintegral_Ioi_indicator_Ici_rpow (div_pos hpos hc) hr]
  have hreal : (φ x / c) ^ (-r) / r = c ^ r / r * φ x ^ (-r) := by
    rw [Real.div_rpow (hφ0 x) hc.le, Real.rpow_neg hc.le]
    field_simp
  have hne : ENNReal.ofReal (φ x) ≠ 0 := by simpa using hpos
  rw [hreal, ENNReal.ofReal_mul (div_nonneg (Real.rpow_nonneg hc.le _) hr.le),
    ← ENNReal.ofReal_rpow_of_pos hpos, sub_eq_add_neg,
    ENNReal.rpow_add _ _ hne ENNReal.ofReal_ne_top]
  ring

end Tonelli

/-! ### From a split distributional bound to an `Lᵖ` bound -/

section Split

variable {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ : Measure α}
  {ν : Measure β} [NormedAddCommGroup E] [NormedAddCommGroup F]

/-- The core of the real interpolation argument. If the distribution function of `g` at every
height `t > 0` is controlled by `K₁ t^(-a) ∫_{‖f‖ > c t} ‖f‖^a + K₂ t^(-b) ∫_{‖f‖ ≤ c t} ‖f‖^b`,
then `∫ ‖g‖^p ≤ p (K₁ c^(a-p)/(p-a) + K₂ c^(b-p)/(b-p)) ∫ ‖f‖^p` for `0 < a < p < b`
(layer-cake formula followed by Tonelli). -/
theorem lintegral_rpow_enorm_le_of_distribution_split [SFinite μ] {g : β → F}
    (hg : AEStronglyMeasurable g ν) {f : α → E} (hf : AEStronglyMeasurable f μ)
    {a b p c K₁ K₂ : ℝ} (ha : 0 < a) (hap : a < p) (hpb : p < b) (hc : 0 < c)
    (hK₁ : 0 ≤ K₁) (hK₂ : 0 ≤ K₂)
    (hsplit : ∀ t : ℝ, 0 < t → ν {x | t < ‖g x‖} ≤
      ENNReal.ofReal K₁ * ENNReal.ofReal (t ^ (-a)) *
          ∫⁻ x, ‖{y | c * t < ‖f y‖}.indicator f x‖ₑ ^ a ∂μ +
        ENNReal.ofReal K₂ * ENNReal.ofReal (t ^ (-b)) *
          ∫⁻ x, ‖{y | ‖f y‖ ≤ c * t}.indicator f x‖ₑ ^ b ∂μ) :
    ∫⁻ x, ‖g x‖ₑ ^ p ∂ν ≤
      ENNReal.ofReal (p * (K₁ * c ^ (a - p) / (p - a) + K₂ * c ^ (b - p) / (b - p))) *
        ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  have hp : 0 < p := ha.trans hap
  have hb : 0 < b := hp.trans hpb
  -- a measurable nonnegative version `φ` of `‖f‖`
  have ψ : AEMeasurable (fun x => ‖f x‖) μ := hf.norm.aemeasurable
  set φ : α → ℝ := fun x => max (ψ.mk _ x) 0 with hφdef
  have hφm : Measurable φ := ψ.measurable_mk.max measurable_const
  have hφ0 : ∀ x, 0 ≤ φ x := fun x => le_max_right _ _
  have hφae : ∀ᵐ x ∂μ, φ x = ‖f x‖ := by
    filter_upwards [ψ.ae_eq_mk] with x hx
    simp only [hφdef, ← hx, max_eq_left (norm_nonneg _)]
  have hJ₁ : ∀ t : ℝ, ∫⁻ x, ‖{y | c * t < ‖f y‖}.indicator f x‖ₑ ^ a ∂μ =
      ∫⁻ x, {x | c * t < φ x}.indicator (fun x => ENNReal.ofReal (φ x) ^ a) x ∂μ := by
    intro t
    refine lintegral_congr_ae ?_
    filter_upwards [hφae] with x hx
    by_cases h : c * t < ‖f x‖
    · have h' : c * t < φ x := hx ▸ h
      simp [h, hx]
    · have h' : ¬ c * t < φ x := hx ▸ h
      simp [h, h', ENNReal.zero_rpow_of_pos ha]
  have hJ₂ : ∀ t : ℝ, ∫⁻ x, ‖{y | ‖f y‖ ≤ c * t}.indicator f x‖ₑ ^ b ∂μ =
      ∫⁻ x, {x | φ x ≤ c * t}.indicator (fun x => ENNReal.ofReal (φ x) ^ b) x ∂μ := by
    intro t
    refine lintegral_congr_ae ?_
    filter_upwards [hφae] with x hx
    by_cases h : ‖f x‖ ≤ c * t
    · have h' : φ x ≤ c * t := hx ▸ h
      simp [h, hx]
    · have h' : ¬ φ x ≤ c * t := hx ▸ h
      simp [h, h', ENNReal.zero_rpow_of_pos hb]
  have hIf : ∫⁻ x, ENNReal.ofReal (φ x) ^ p ∂μ = ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
    refine lintegral_congr_ae ?_
    filter_upwards [hφae] with x hx
    simp [hx]
  -- measurability of the two truncated integrals in `t`
  have hS₁ : MeasurableSet {z : ℝ × α | c * z.1 < φ z.2} :=
    measurableSet_lt (measurable_const.mul measurable_fst) (hφm.comp measurable_snd)
  have hS₂ : MeasurableSet {z : ℝ × α | φ z.2 ≤ c * z.1} :=
    measurableSet_le (hφm.comp measurable_snd) (measurable_const.mul measurable_fst)
  have hm₁ : Measurable fun t : ℝ =>
      ∫⁻ x, {x | c * t < φ x}.indicator (fun x => ENNReal.ofReal (φ x) ^ a) x ∂μ :=
    measurable_lintegral_indicator_section (μ := μ) _ hS₁ _ (hφm.ennreal_ofReal.pow_const a)
  have hm₂ : Measurable fun t : ℝ =>
      ∫⁻ x, {x | φ x ≤ c * t}.indicator (fun x => ENNReal.ofReal (φ x) ^ b) x ∂μ :=
    measurable_lintegral_indicator_section (μ := μ) _ hS₂ _ (hφm.ennreal_ofReal.pow_const b)
  -- layer cake
  have hlc := lintegral_rpow_eq_lintegral_meas_lt_mul ν (f := fun x => ‖g x‖)
    (ae_of_all _ fun x => norm_nonneg _) hg.norm.aemeasurable hp
  have hlhs : ∫⁻ x, ‖g x‖ₑ ^ p ∂ν = ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ p) ∂ν := by
    refine lintegral_congr fun x => ?_
    rw [← ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) hp.le, ofReal_norm]
  rw [hlhs, hlc]
  calc ENNReal.ofReal p * ∫⁻ t in Ioi (0 : ℝ), ν {x | t < ‖g x‖} * ENNReal.ofReal (t ^ (p - 1))
      ≤ ENNReal.ofReal p * ∫⁻ t in Ioi (0 : ℝ),
          (ENNReal.ofReal K₁ * (ENNReal.ofReal (t ^ ((p - a) - 1)) *
            ∫⁻ x, {x | c * t < φ x}.indicator (fun x => ENNReal.ofReal (φ x) ^ a) x ∂μ) +
          ENNReal.ofReal K₂ * (ENNReal.ofReal (t ^ (-(b - p) - 1)) *
            ∫⁻ x, {x | φ x ≤ c * t}.indicator (fun x => ENNReal.ofReal (φ x) ^ b) x ∂μ)) := by
        gcongr ENNReal.ofReal p * ?_
        refine setLIntegral_mono' measurableSet_Ioi fun t ht => ?_
        have ht : (0 : ℝ) < t := ht
        have e₁ : ENNReal.ofReal (t ^ (-a)) * ENNReal.ofReal (t ^ (p - 1)) =
            ENNReal.ofReal (t ^ ((p - a) - 1)) := by
          rw [← ENNReal.ofReal_mul (Real.rpow_nonneg ht.le _), ← Real.rpow_add ht]
          ring_nf
        have e₂ : ENNReal.ofReal (t ^ (-b)) * ENNReal.ofReal (t ^ (p - 1)) =
            ENNReal.ofReal (t ^ (-(b - p) - 1)) := by
          rw [← ENNReal.ofReal_mul (Real.rpow_nonneg ht.le _), ← Real.rpow_add ht]
          ring_nf
        calc ν {x | t < ‖g x‖} * ENNReal.ofReal (t ^ (p - 1))
            ≤ (ENNReal.ofReal K₁ * ENNReal.ofReal (t ^ (-a)) *
                  ∫⁻ x, ‖{y | c * t < ‖f y‖}.indicator f x‖ₑ ^ a ∂μ +
                ENNReal.ofReal K₂ * ENNReal.ofReal (t ^ (-b)) *
                  ∫⁻ x, ‖{y | ‖f y‖ ≤ c * t}.indicator f x‖ₑ ^ b ∂μ) *
                ENNReal.ofReal (t ^ (p - 1)) := by
              gcongr
              exact hsplit t ht
          _ = _ := by
              rw [hJ₁, hJ₂, ← e₁, ← e₂]
              ring
    _ = ENNReal.ofReal p * (ENNReal.ofReal K₁ * (ENNReal.ofReal (c ^ (-(p - a)) / (p - a)) *
            ∫⁻ x, ENNReal.ofReal (φ x) ^ (a + (p - a)) ∂μ) +
          ENNReal.ofReal K₂ * (ENNReal.ofReal (c ^ (b - p) / (b - p)) *
            ∫⁻ x, ENNReal.ofReal (φ x) ^ (b - (b - p)) ∂μ)) := by
        rw [lintegral_add_left, lintegral_const_mul, lintegral_const_mul,
          lintegral_Ioi_rpow_mul_lintegral_indicator_lt φ hφm hφ0 hc ha.le (sub_pos.mpr hap),
          lintegral_Ioi_rpow_mul_lintegral_indicator_le φ hφm hφ0 hc hb (sub_pos.mpr hpb)
            (by linarith)]
        · exact ((measurable_id.pow_const _).ennreal_ofReal).mul hm₂
        · exact ((measurable_id.pow_const _).ennreal_ofReal).mul hm₁
        · exact measurable_const.mul (((measurable_id.pow_const _).ennreal_ofReal).mul hm₁)
    _ = _ := by
        rw [add_sub_cancel, sub_sub_cancel, hIf, ENNReal.ofReal_mul hp.le,
          ENNReal.ofReal_add (div_nonneg (mul_nonneg hK₁ (Real.rpow_nonneg hc.le _))
            (sub_pos.mpr hap).le) (div_nonneg (mul_nonneg hK₂ (Real.rpow_nonneg hc.le _))
            (sub_pos.mpr hpb).le),
          mul_div_assoc, mul_div_assoc, ENNReal.ofReal_mul hK₁, ENNReal.ofReal_mul hK₂, neg_sub]
        ring

end Split

/-! ### Distribution functions, weak type, sublinearity -/

section Defs

variable {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] [NormedAddCommGroup E]
  [NormedAddCommGroup F]

/-- The distribution function `t ↦ ν {x | t < ‖g x‖}` of `g : β → F`, with `t : ℝ≥0∞`. -/
def distributionFunction (g : β → F) (t : ℝ≥0∞) (ν : Measure β) : ℝ≥0∞ :=
  ν {x | t < ‖g x‖ₑ}

/-- `T` is of weak type `(a, a)` with constant `A` on the class of inputs `D`:
`ν {‖T f‖ > t} ≤ (A ‖f‖_{L^a(μ)} / t)^a` for all `f ∈ D` and all `t > 0`. -/
def HasWeakTypeOn (T : (α → E) → β → F) (D : Set (α → E)) (a : ℝ) (A : ℝ≥0)
    (μ : Measure α) (ν : Measure β) : Prop :=
  ∀ f ∈ D, ∀ t : ℝ≥0∞, 0 < t →
    distributionFunction (T f) t ν ≤ ((A : ℝ≥0∞) * eLpNorm f (ENNReal.ofReal a) μ / t) ^ a

/-- `T` is of strong type `(a, a)` with constant `A` on `D`:
`‖T f‖_{L^a(ν)} ≤ A ‖f‖_{L^a(μ)}` for all `f ∈ D`. -/
def HasStrongTypeOn (T : (α → E) → β → F) (D : Set (α → E)) (a : ℝ) (A : ℝ≥0)
    (μ : Measure α) (ν : Measure β) : Prop :=
  ∀ f ∈ D, eLpNorm (T f) (ENNReal.ofReal a) ν ≤ (A : ℝ≥0∞) * eLpNorm f (ENNReal.ofReal a) μ

/-- The `L^∞` endpoint hypothesis with constant `B`: if `‖f x‖ ≤ s` for every `x`, then
`‖T f y‖ ≤ B s` for `ν`-almost every `y` (for `f ∈ D`). -/
def HasLinftyBoundOn (T : (α → E) → β → F) (D : Set (α → E)) (B : ℝ≥0) (ν : Measure β) :
    Prop :=
  ∀ f ∈ D, ∀ s : ℝ, (∀ x, ‖f x‖ ≤ s) → ∀ᵐ y ∂ν, ‖T f y‖ ≤ B * s

/-- `T` is subadditive in pointwise norm on `D`: `‖T (f + g)‖ ≤ ‖T f‖ + ‖T g‖` `ν`-a.e. -/
def IsSublinearOn (T : (α → E) → β → F) (D : Set (α → E)) (ν : Measure β) : Prop :=
  ∀ f ∈ D, ∀ g ∈ D, ∀ᵐ x ∂ν, ‖T (f + g) x‖ ≤ ‖T f x‖ + ‖T g x‖

/-- `D` is closed under the two truncations `f 𝟙_{‖f‖ > s}` and `f 𝟙_{‖f‖ ≤ s}`, `s > 0`, used
in the proof of the Marcinkiewicz interpolation theorem. -/
def IsTruncationClosed (D : Set (α → E)) : Prop :=
  ∀ f ∈ D, ∀ s : ℝ, 0 < s →
    {x | s < ‖f x‖}.indicator f ∈ D ∧ {x | ‖f x‖ ≤ s}.indicator f ∈ D

omit [MeasurableSpace α] in
/-- The class of all functions is truncation closed. -/
theorem isTruncationClosed_univ : IsTruncationClosed (Set.univ : Set (α → E)) :=
  fun _ _ _ _ => ⟨Set.mem_univ _, Set.mem_univ _⟩

/-- The class `L^q(μ)` is truncation closed. -/
theorem isTruncationClosed_memLp {q : ℝ≥0∞} {μ : Measure α} :
    IsTruncationClosed {f : α → E | MemLp f q μ} := by
  intro f hf s _
  have hf' : MemLp f q μ := hf
  have hm := hf'.aestronglyMeasurable
  refine ⟨?_, ?_⟩
  · refine MemLp.mono hf' (hm.indicator₀
      (nullMeasurableSet_lt aemeasurable_const hm.norm.aemeasurable)) (ae_of_all _ fun x => ?_)
    by_cases h : s < ‖f x‖ <;> simp [h]
  · refine MemLp.mono hf' (hm.indicator₀
      (nullMeasurableSet_le hm.norm.aemeasurable aemeasurable_const)) (ae_of_all _ fun x => ?_)
    by_cases h : ‖f x‖ ≤ s <;> simp [h]

variable {μ : Measure α} {ν : Measure β}

/-- The distribution function at a real height. -/
theorem distributionFunction_ofReal (g : β → F) {t : ℝ} (ht : 0 ≤ t) :
    distributionFunction g (ENNReal.ofReal t) ν = ν {x | t < ‖g x‖} := by
  unfold distributionFunction
  congr 1
  ext x
  simp only [mem_ofPred_eq, ← ofReal_norm, ENNReal.ofReal_lt_ofReal_iff_of_nonneg ht]

/-- `‖f‖_{L^p}^p = ∫ ‖f‖^p` for `0 < p < ∞` and a.e. strongly measurable `f`. -/
theorem eLpNorm_ofReal_rpow_eq_lintegral {f : α → E} (hf : AEStronglyMeasurable f μ) {p : ℝ}
    (hp : 0 < p) :
    eLpNorm f (ENNReal.ofReal p) μ ^ p = ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by simpa using hp) ENNReal.ofReal_ne_top hf,
    ENNReal.toReal_ofReal hp.le, ← ENNReal.rpow_mul, one_div, inv_mul_cancel₀ hp.ne',
    ENNReal.rpow_one]

/-- `‖f‖_{L^p} = (∫ ‖f‖^p)^(1/p)` for `0 < p < ∞` and a.e. strongly measurable `f`. -/
theorem eLpNorm_ofReal_eq_lintegral_rpow_enorm {f : α → E} (hf : AEStronglyMeasurable f μ) {p : ℝ}
    (hp : 0 < p) :
    eLpNorm f (ENNReal.ofReal p) μ = (∫⁻ x, ‖f x‖ₑ ^ p ∂μ) ^ (1 / p) := by
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal (by simpa using hp) ENNReal.ofReal_ne_top hf,
    ENNReal.toReal_ofReal hp.le]

/-- **Layer-cake formula**: `‖g‖_p^p = p ∫_0^∞ t^(p-1) ν{‖g‖ > t} dt` for `0 < p < ∞`. -/
theorem eLpNorm_rpow_eq_lintegral_distributionFunction {g : β → F}
    (hg : AEStronglyMeasurable g ν) {p : ℝ} (hp : 0 < p) :
    eLpNorm g (ENNReal.ofReal p) ν ^ p =
      ENNReal.ofReal p * ∫⁻ t in Ioi (0 : ℝ),
        ENNReal.ofReal (t ^ (p - 1)) * distributionFunction g (ENNReal.ofReal t) ν := by
  rw [eLpNorm_ofReal_rpow_eq_lintegral hg hp]
  have hlhs : ∫⁻ x, ‖g x‖ₑ ^ p ∂ν = ∫⁻ x, ENNReal.ofReal (‖g x‖ ^ p) ∂ν := by
    refine lintegral_congr fun x => ?_
    rw [← ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) hp.le, ofReal_norm]
  rw [hlhs, lintegral_rpow_eq_lintegral_meas_lt_mul ν (f := fun x => ‖g x‖)
    (ae_of_all _ fun x => norm_nonneg _) hg.norm.aemeasurable hp]
  congr 1
  refine setLIntegral_congr_fun measurableSet_Ioi fun t ht => ?_
  rw [distributionFunction_ofReal g (le_of_lt ht), mul_comm]

/-- **Chebyshev's inequality**: strong type `(a, a)` implies weak type `(a, a)` with the same
constant. -/
theorem HasStrongTypeOn.hasWeakTypeOn {T : (α → E) → β → F} {D : Set (α → E)} {a : ℝ}
    {A : ℝ≥0} (ha : 0 < a) (h : HasStrongTypeOn T D a A μ ν) : HasWeakTypeOn T D a A μ ν := by
  intro f hf t ht
  by_cases htop : t = ∞
  · simp [distributionFunction, htop]
  have ha' : ENNReal.ofReal a ≠ 0 := by simpa using ha
  have hcheb := meas_ge_le_mul_pow_eLpNorm_enorm ν ha' ENNReal.ofReal_ne_top (f := T f)
    ht.ne' (fun h => absurd h htop)
  rw [ENNReal.toReal_ofReal ha.le] at hcheb
  calc distributionFunction (T f) t ν ≤ ν {x | t ≤ ‖T f x‖ₑ} :=
        measure_mono fun x (hx : t < ‖T f x‖ₑ) => (le_of_lt hx : t ≤ ‖T f x‖ₑ)
    _ ≤ t⁻¹ ^ a * eLpNorm (T f) (ENNReal.ofReal a) ν ^ a := hcheb
    _ ≤ t⁻¹ ^ a * ((A : ℝ≥0∞) * eLpNorm f (ENNReal.ofReal a) μ) ^ a := by
        gcongr
        exact h f hf
    _ = ((A : ℝ≥0∞) * eLpNorm f (ENNReal.ofReal a) μ / t) ^ a := by
        simp only [div_eq_mul_inv, ENNReal.mul_rpow_of_nonneg _ _ ha.le]
        ring

/-- A weak-type `(a, a)` bound may be checked at real heights `t > 0` only. -/
theorem hasWeakTypeOn_of_forall_real {T : (α → E) → β → F} {D : Set (α → E)} {a : ℝ}
    {A : ℝ≥0} (h : ∀ f ∈ D, ∀ t : ℝ, 0 < t → ν {x | t < ‖T f x‖} ≤
      ((A : ℝ≥0∞) * eLpNorm f (ENNReal.ofReal a) μ / ENNReal.ofReal t) ^ a) :
    HasWeakTypeOn T D a A μ ν := by
  intro f hf t ht
  by_cases htop : t = ∞
  · simp [distributionFunction, htop]
  have ht' : 0 < t.toReal := ENNReal.toReal_pos ht.ne' htop
  have := h f hf t.toReal ht'
  rwa [← distributionFunction_ofReal _ ht'.le, ENNReal.ofReal_toReal htop] at this

/-- A weak-type bound with constant `0` forces `T f = 0` almost everywhere. -/
theorem HasWeakTypeOn.ae_eq_zero_of_const_eq_zero {T : (α → E) → β → F} {D : Set (α → E)}
    {a : ℝ} (ha : 0 < a) (h : HasWeakTypeOn T D a 0 μ ν) {f : α → E} (hf : f ∈ D) :
    T f =ᵐ[ν] 0 := by
  have hnull : ν {x | 0 < ‖T f x‖ₑ} = 0 := by
    have hsub : {x | 0 < ‖T f x‖ₑ} ⊆ ⋃ n : ℕ, {x | ((n : ℝ≥0∞))⁻¹ < ‖T f x‖ₑ} := by
      intro x hx
      obtain ⟨n, hn⟩ := ENNReal.exists_inv_nat_lt (ne_of_gt (show 0 < ‖T f x‖ₑ from hx))
      exact mem_iUnion.mpr ⟨n, hn⟩
    refine measure_mono_null hsub (measure_iUnion_null fun n => ?_)
    have := h f hf ((n : ℝ≥0∞))⁻¹ (ENNReal.inv_pos.mpr (ENNReal.natCast_ne_top n))
    simpa [distributionFunction, ENNReal.zero_rpow_of_pos ha] using this
  rw [Filter.EventuallyEq, ae_iff]
  refine measure_mono_null (fun x hx => ?_) hnull
  simpa [pos_iff_ne_zero] using hx

end Defs

/-! ### Truncation and the split of the distribution function -/

section Truncation

variable {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] [NormedAddCommGroup E]
  [NormedAddCommGroup F] {μ : Measure α} {ν : Measure β}

/-- The upper truncation `f 𝟙_{‖f‖ > s}` of an a.e. strongly measurable function is a.e.
strongly measurable. -/
theorem aestronglyMeasurable_indicator_lt_norm {f : α → E} (hf : AEStronglyMeasurable f μ)
    (s : ℝ) : AEStronglyMeasurable ({x | s < ‖f x‖}.indicator f) μ :=
  hf.indicator₀ (nullMeasurableSet_lt aemeasurable_const hf.norm.aemeasurable)

/-- The lower truncation `f 𝟙_{‖f‖ ≤ s}` of an a.e. strongly measurable function is a.e.
strongly measurable. -/
theorem aestronglyMeasurable_indicator_norm_le {f : α → E} (hf : AEStronglyMeasurable f μ)
    (s : ℝ) : AEStronglyMeasurable ({x | ‖f x‖ ≤ s}.indicator f) μ :=
  hf.indicator₀ (nullMeasurableSet_le hf.norm.aemeasurable aemeasurable_const)

omit [MeasurableSpace α] in
/-- The two truncations at height `s` add up to `f`. -/
theorem indicator_lt_norm_add_indicator_norm_le (f : α → E) (s : ℝ) :
    {x | s < ‖f x‖}.indicator f + {x | ‖f x‖ ≤ s}.indicator f = f := by
  funext x
  by_cases h : s < ‖f x‖
  · simp [h, not_le.mpr h]
  · simp [h, le_of_not_gt h]

omit [MeasurableSpace α] in
/-- Subadditivity splits the distribution function of `T f` at height `t` into those of the
truncations of `f` at height `s`, each at height `t / 2`. -/
theorem measure_lt_norm_le_of_isSublinearOn {T : (α → E) → β → F} {D : Set (α → E)}
    (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D) {f : α → E} (hfD : f ∈ D)
    {s : ℝ} (hs : 0 < s) (t : ℝ) :
    ν {x | t < ‖T f x‖} ≤ ν {x | t / 2 < ‖T ({y | s < ‖f y‖}.indicator f) x‖} +
      ν {x | t / 2 < ‖T ({y | ‖f y‖ ≤ s}.indicator f) x‖} := by
  obtain ⟨h₁, h₂⟩ := hD f hfD s hs
  have hae := hsub _ h₁ _ h₂
  rw [indicator_lt_norm_add_indicator_norm_le] at hae
  refine (measure_mono_ae (hae.mono fun x hx hxt => ?_)).trans (measure_union_le _ _)
  have hxt' : t < ‖T f x‖ := hxt
  by_contra hc
  simp only [mem_union, mem_ofPred_eq, not_or, not_lt] at hc
  linarith [hc.1, hc.2]

/-- A weak-type `(a, a)` bound at height `t / 2`, written in the normalized form used in the
interpolation argument. -/
theorem HasWeakTypeOn.measure_half_lt_le {T : (α → E) → β → F} {D : Set (α → E)} {a : ℝ}
    {A : ℝ≥0} (h : HasWeakTypeOn T D a A μ ν) (ha : 0 < a) {g : α → E} (hgD : g ∈ D)
    (hg : AEStronglyMeasurable g μ) {t : ℝ} (ht : 0 < t) :
    ν {x | t / 2 < ‖T g x‖} ≤
      ENNReal.ofReal (2 ^ a * (A : ℝ) ^ a) * ENNReal.ofReal (t ^ (-a)) *
        ∫⁻ x, ‖g x‖ₑ ^ a ∂μ := by
  have ht2 : 0 < t / 2 := half_pos ht
  have hw := h g hgD (ENNReal.ofReal (t / 2)) (ENNReal.ofReal_pos.mpr ht2)
  rw [distributionFunction_ofReal _ ht2.le] at hw
  refine hw.trans (le_of_eq ?_)
  have e : (t / 2)⁻¹ ^ a = 2 ^ a * t ^ (-a) := by
    rw [inv_div, Real.div_rpow two_pos.le ht.le, Real.rpow_neg ht.le, div_eq_mul_inv]
  rw [div_eq_mul_inv, ← ENNReal.ofReal_inv_of_pos ht2, ENNReal.mul_rpow_of_nonneg _ _ ha.le,
    ENNReal.mul_rpow_of_nonneg _ _ ha.le, eLpNorm_ofReal_rpow_eq_lintegral hg ha,
    ENNReal.ofReal_rpow_of_nonneg (inv_nonneg.mpr ht2.le) ha.le, ← ENNReal.ofReal_coe_nnreal,
    ENNReal.ofReal_rpow_of_nonneg A.coe_nonneg ha.le, e,
    ENNReal.ofReal_mul (Real.rpow_nonneg two_pos.le _),
    ENNReal.ofReal_mul (Real.rpow_nonneg two_pos.le _)]
  ring

omit [MeasurableSpace α] in
/-- The `L^∞` endpoint hypothesis makes the distribution function of `T g` vanish at heights
above `B s`, for `‖g‖ ≤ s` everywhere. -/
theorem HasLinftyBoundOn.measure_lt_eq_zero {T : (α → E) → β → F} {D : Set (α → E)}
    {B : ℝ≥0} (h : HasLinftyBoundOn T D B ν) {g : α → E} (hgD : g ∈ D) {s t : ℝ}
    (hbound : ∀ x, ‖g x‖ ≤ s) (hBs : (B : ℝ) * s ≤ t) :
    ν {x | t < ‖T g x‖} = 0 := by
  refine measure_mono_null (fun x hx => ?_) (ae_iff.mp (h g hgD s hbound))
  have hx' : t < ‖T g x‖ := hx
  change ¬ ‖T g x‖ ≤ B * s
  intro hle
  linarith

end Truncation

/-! ### Constants -/

/-- The free-parameter interpolation constant
`p (2^a A^a c^(a-p)/(p-a) + 2^b B^b c^(b-p)/(b-p))`, which bounds `‖T f‖_p^p / ‖f‖_p^p` for
every truncation parameter `c > 0`. -/
def marcinkiewiczBound (a b p : ℝ) (A B : ℝ≥0) (c : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal (p * (2 ^ a * (A : ℝ) ^ a * c ^ (a - p) / (p - a) +
    2 ^ b * (B : ℝ) ^ b * c ^ (b - p) / (b - p)))

/-- The Marcinkiewicz constant `C(a, b, p) = (p (2^a/(p-a) + 2^b/(b-p)))^(1/p)`. -/
def marcinkiewiczConst (a b p : ℝ) : ℝ≥0 :=
  Real.toNNReal ((p * (2 ^ a / (p - a) + 2 ^ b / (b - p))) ^ (1 / p))

/-- The free-parameter constant `p 2^a A^a c^(a-p)/(p-a)` of the endpoint case `b = ∞`. -/
def marcinkiewiczBoundTop (a p : ℝ) (A : ℝ≥0) (c : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal (p * (2 ^ a * (A : ℝ) ^ a * c ^ (a - p) / (p - a)))

/-- The Marcinkiewicz constant of the endpoint case `b = ∞`: `C(a, p) = 2 (p/(p-a))^(1/p)`. -/
def marcinkiewiczConstTop (a p : ℝ) : ℝ≥0 :=
  Real.toNNReal (2 * (p / (p - a)) ^ (1 / p))

/-- `marcinkiewiczBound` is finite. -/
theorem marcinkiewiczBound_ne_top (a b p : ℝ) (A B : ℝ≥0) (c : ℝ) :
    marcinkiewiczBound a b p A B c ≠ ∞ := ENNReal.ofReal_ne_top

/-- `marcinkiewiczBoundTop` is finite. -/
theorem marcinkiewiczBoundTop_ne_top (a p : ℝ) (A : ℝ≥0) (c : ℝ) :
    marcinkiewiczBoundTop a p A c ≠ ∞ := ENNReal.ofReal_ne_top

/-- The Marcinkiewicz constant `C(a, b, p)` is finite. -/
theorem marcinkiewiczConst_ne_top (a b p : ℝ) : (marcinkiewiczConst a b p : ℝ≥0∞) ≠ ∞ :=
  ENNReal.coe_ne_top

/-- The endpoint Marcinkiewicz constant `C(a, p)` is finite. -/
theorem marcinkiewiczConstTop_ne_top (a p : ℝ) : (marcinkiewiczConstTop a p : ℝ≥0∞) ≠ ∞ :=
  ENNReal.coe_ne_top

/-- Optimization of the truncation parameter: with `c = (A^a/B^b)^(1/(b-a))`,
`(p (2^a A^a c^(a-p)/(p-a) + 2^b B^b c^(b-p)/(b-p)))^(1/p) = C(a,b,p) A^(1-θ) B^θ`. -/
theorem marcinkiewicz_real_identity {a b p A B : ℝ} (ha : 0 < a) (hap : a < p) (hpb : p < b)
    (hA : 0 < A) (hB : 0 < B) :
    (p * (2 ^ a * A ^ a * ((A ^ a / B ^ b) ^ (1 / (b - a))) ^ (a - p) / (p - a) +
        2 ^ b * B ^ b * ((A ^ a / B ^ b) ^ (1 / (b - a))) ^ (b - p) / (b - p))) ^ (1 / p) =
      (p * (2 ^ a / (p - a) + 2 ^ b / (b - p))) ^ (1 / p) *
        A ^ (a * (b - p) / (p * (b - a))) * B ^ (b * (p - a) / (p * (b - a))) := by
  have hp : 0 < p := ha.trans hap
  have hba : b - a ≠ 0 := by linarith
  have hpa : 0 < p - a := by linarith
  have hbp : 0 < b - p := by linarith
  set M := A ^ (a * (b - p) / (b - a)) * B ^ (b * (p - a) / (b - a)) with hM
  have key₁ : A ^ a * ((A ^ a / B ^ b) ^ (1 / (b - a))) ^ (a - p) = M := by
    rw [hM, ← Real.exp_log hA, ← Real.exp_log hB]
    simp only [← Real.exp_mul, ← Real.exp_sub, ← Real.exp_add]
    congr 1
    field_simp
    ring
  have key₂ : B ^ b * ((A ^ a / B ^ b) ^ (1 / (b - a))) ^ (b - p) = M := by
    rw [hM, ← Real.exp_log hA, ← Real.exp_log hB]
    simp only [← Real.exp_mul, ← Real.exp_sub, ← Real.exp_add]
    congr 1
    field_simp
    ring
  rw [mul_assoc (2 ^ a), key₁, mul_assoc (2 ^ b), key₂,
    show p * (2 ^ a * M / (p - a) + 2 ^ b * M / (b - p)) =
      p * (2 ^ a / (p - a) + 2 ^ b / (b - p)) * M by ring,
    Real.mul_rpow (by positivity) (by positivity), mul_assoc]
  congr 1
  rw [hM, ← Real.exp_log hA, ← Real.exp_log hB]
  simp only [← Real.exp_mul, ← Real.exp_add]
  congr 1
  field_simp

/-- Optimization of the truncation parameter in the endpoint case: with `c = 1/(2B)`,
`(p 2^a A^a c^(a-p)/(p-a))^(1/p) = C(a,p) A^(a/p) B^(1-a/p)`. -/
theorem marcinkiewicz_real_identity_top {a p A B : ℝ} (ha : 0 < a) (hap : a < p) (hA : 0 < A)
    (hB : 0 < B) :
    (p * (2 ^ a * A ^ a * (1 / (2 * B)) ^ (a - p) / (p - a))) ^ (1 / p) =
      2 * (p / (p - a)) ^ (1 / p) * A ^ (a / p) * B ^ (1 - a / p) := by
  have hp : 0 < p := ha.trans hap
  have hpa : 0 < p - a := by linarith
  have hX : 0 < p / (p - a) := div_pos hp hpa
  rw [show p * (2 ^ a * A ^ a * (1 / (2 * B)) ^ (a - p) / (p - a)) =
    p / (p - a) * (2 ^ a * A ^ a * (1 / (2 * B)) ^ (a - p)) by ring]
  rw [← Real.exp_log hA, ← Real.exp_log hB, ← Real.exp_log hX,
    ← Real.exp_log (two_pos : (0 : ℝ) < 2)]
  simp only [← Real.exp_mul, ← Real.exp_add, one_div, ← Real.exp_neg]
  congr 1
  field_simp
  ring

/-! ### The Marcinkiewicz interpolation theorem -/

section Interpolation

variable {α β E F : Type*} [MeasurableSpace α] [MeasurableSpace β] [NormedAddCommGroup E]
  [NormedAddCommGroup F] {μ : Measure α} {ν : Measure β}

/-- From `∫ ‖g‖^p ≤ K ∫ ‖f‖^p` to `‖g‖_p ≤ K^(1/p) ‖f‖_p`. -/
theorem eLpNorm_le_of_lintegral_rpow_le {g : β → F} (hg : AEStronglyMeasurable g ν)
    {f : α → E} (hf : AEStronglyMeasurable f μ) {p : ℝ} (hp : 0 < p) {K : ℝ≥0∞}
    (h : ∫⁻ x, ‖g x‖ₑ ^ p ∂ν ≤ K * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ) :
    eLpNorm g (ENNReal.ofReal p) ν ≤ K ^ (1 / p) * eLpNorm f (ENNReal.ofReal p) μ := by
  rw [eLpNorm_ofReal_eq_lintegral_rpow_enorm hg hp, eLpNorm_ofReal_eq_lintegral_rpow_enorm hf hp,
    ← ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]
  exact ENNReal.rpow_le_rpow h (by positivity)

/-- **Marcinkiewicz interpolation, free truncation parameter** (the displayed estimate in the
proof of Blueprint Lemma 2.3 (`lem:interpolation`)): if `T` is subadditive on a truncation
closed class `D`, of weak type `(a, a)` with constant `A` and of weak type `(b, b)` with
constant `B` on `D`, where `0 < a < p < b < ∞`, then for every `c > 0` and every
`f ∈ D`,
`∫ ‖T f‖^p ≤ p (2^a A^a c^(a-p)/(p-a) + 2^b B^b c^(b-p)/(b-p)) ∫ ‖f‖^p`. -/
theorem lintegral_rpow_le_of_hasWeakTypeOn [SFinite μ] {T : (α → E) → β → F}
    {D : Set (α → E)} {a b p c : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p) (hpb : p < b)
    (hc : 0 < c) (hTA : HasWeakTypeOn T D a A μ ν) (hTB : HasWeakTypeOn T D b B μ ν)
    (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D) {f : α → E} (hfD : f ∈ D)
    (hf : AEStronglyMeasurable f μ) (hTf : AEStronglyMeasurable (T f) ν) :
    ∫⁻ x, ‖T f x‖ₑ ^ p ∂ν ≤ marcinkiewiczBound a b p A B c * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  have hb : 0 < b := (ha.trans hap).trans hpb
  refine lintegral_rpow_enorm_le_of_distribution_split hTf hf ha hap hpb hc (by positivity)
    (by positivity) fun t ht => ?_
  have hs : 0 < c * t := mul_pos hc ht
  obtain ⟨h₁, h₂⟩ := hD f hfD _ hs
  exact (measure_lt_norm_le_of_isSublinearOn hsub hD hfD hs t).trans (add_le_add
    (hTA.measure_half_lt_le ha h₁ (aestronglyMeasurable_indicator_lt_norm hf _) ht)
    (hTB.measure_half_lt_le hb h₂ (aestronglyMeasurable_indicator_norm_le hf _) ht))

/-- **Marcinkiewicz interpolation, free truncation parameter, `Lᵖ` form**: under the hypotheses
of `lintegral_rpow_le_of_hasWeakTypeOn`, for every `c > 0`,
`‖T f‖_p ≤ (p (2^a A^a c^(a-p)/(p-a) + 2^b B^b c^(b-p)/(b-p)))^(1/p) ‖f‖_p`. -/
theorem eLpNorm_le_of_hasWeakTypeOn_of_pos [SFinite μ] {T : (α → E) → β → F}
    {D : Set (α → E)} {a b p c : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p) (hpb : p < b)
    (hc : 0 < c) (hTA : HasWeakTypeOn T D a A μ ν) (hTB : HasWeakTypeOn T D b B μ ν)
    (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D) {f : α → E} (hfD : f ∈ D)
    (hf : AEStronglyMeasurable f μ) (hTf : AEStronglyMeasurable (T f) ν) :
    eLpNorm (T f) (ENNReal.ofReal p) ν ≤
      marcinkiewiczBound a b p A B c ^ (1 / p) * eLpNorm f (ENNReal.ofReal p) μ :=
  eLpNorm_le_of_lintegral_rpow_le hTf hf (ha.trans hap)
    (lintegral_rpow_le_of_hasWeakTypeOn ha hap hpb hc hTA hTB hsub hD hfD hf hTf)

/-- **Marcinkiewicz interpolation theorem** (Blueprint Lemma 2.3 (`lem:interpolation`), first
assertion): let `T` be subadditive in pointwise norm on a truncation closed class `D` of inputs
(e.g. all functions, or `L^q`), of weak type `(a, a)` with constant `A` and of weak type `(b, b)`
with constant `B` on `D`, where `0 < a < p < b < ∞` (in particular `1 ≤ a < p < b < ∞`).
Then for every a.e. strongly measurable `f ∈ D` with `T f` a.e. strongly measurable,
`‖T f‖_p ≤ C(a,b,p) A^(1-θ) B^θ ‖f‖_p`, where `1/p = (1-θ)/a + θ/b` and
`C(a,b,p) = (p (2^a/(p-a) + 2^b/(b-p)))^(1/p) < ∞`. Strong endpoint bounds may be used via
`HasStrongTypeOn.hasWeakTypeOn`. -/
theorem eLpNorm_le_of_hasWeakTypeOn [SFinite μ] {T : (α → E) → β → F} {D : Set (α → E)}
    {a b p θ : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p) (hpb : p < b)
    (hθ : 1 / p = (1 - θ) / a + θ / b) (hTA : HasWeakTypeOn T D a A μ ν)
    (hTB : HasWeakTypeOn T D b B μ ν) (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D)
    {f : α → E} (hfD : f ∈ D) (hf : AEStronglyMeasurable f μ)
    (hTf : AEStronglyMeasurable (T f) ν) :
    eLpNorm (T f) (ENNReal.ofReal p) ν ≤
      (marcinkiewiczConst a b p : ℝ≥0∞) * (A : ℝ≥0∞) ^ (1 - θ) * (B : ℝ≥0∞) ^ θ *
        eLpNorm f (ENNReal.ofReal p) μ := by
  have hp : 0 < p := ha.trans hap
  have hb : 0 < b := hp.trans hpb
  have hba : 0 < b - a := by linarith
  have hθ' : θ = b * (p - a) / (p * (b - a)) := by
    field_simp at hθ
    rw [eq_div_iff (by positivity)]
    linear_combination hθ
  have h1θ : 1 - θ = a * (b - p) / (p * (b - a)) := by
    rw [hθ']
    field_simp
    ring
  have hθ0 : 0 ≤ θ := by rw [hθ']; exact div_nonneg (by nlinarith) (by positivity)
  have h1θ0 : 0 ≤ 1 - θ := by rw [h1θ]; exact div_nonneg (by nlinarith) (by positivity)
  rcases eq_or_ne A 0 with rfl | hA0
  · rw [eLpNorm_congr_ae (hTA.ae_eq_zero_of_const_eq_zero ha hfD), eLpNorm_zero]
    exact zero_le
  rcases eq_or_ne B 0 with rfl | hB0
  · rw [eLpNorm_congr_ae (hTB.ae_eq_zero_of_const_eq_zero hb hfD), eLpNorm_zero]
    exact zero_le
  have hA : 0 < (A : ℝ) := NNReal.coe_pos.mpr (pos_iff_ne_zero.mpr hA0)
  have hB : 0 < (B : ℝ) := NNReal.coe_pos.mpr (pos_iff_ne_zero.mpr hB0)
  set c : ℝ := ((A : ℝ) ^ a / (B : ℝ) ^ b) ^ (1 / (b - a)) with hcdef
  have hc : 0 < c := by positivity
  refine (eLpNorm_le_of_hasWeakTypeOn_of_pos ha hap hpb hc hTA hTB hsub hD hfD hf hTf).trans
    (le_of_eq ?_)
  congr 1
  have hX : 0 ≤ p * (2 ^ a * (A : ℝ) ^ a * c ^ (a - p) / (p - a) +
      2 ^ b * (B : ℝ) ^ b * c ^ (b - p) / (b - p)) := by
    have hpa : 0 < p - a := by linarith
    have hbp : 0 < b - p := by linarith
    positivity
  rw [marcinkiewiczBound, ENNReal.ofReal_rpow_of_nonneg hX (by positivity), hcdef,
    marcinkiewicz_real_identity ha hap hpb hA hB, ← h1θ, ← hθ',
    ENNReal.ofReal_mul (by positivity), ENNReal.ofReal_mul (by positivity),
    ← ENNReal.ofReal_rpow_of_nonneg A.coe_nonneg h1θ0,
    ← ENNReal.ofReal_rpow_of_nonneg B.coe_nonneg hθ0,
    ENNReal.ofReal_coe_nnreal, ENNReal.ofReal_coe_nnreal]
  rfl

/-- **Marcinkiewicz interpolation with an `L^∞` endpoint, free truncation parameter** (the
endpoint estimate in the proof of Blueprint Lemma 2.3 (`lem:interpolation`)): if `T` is
subadditive on a truncation closed class `D`, of weak type `(a, a)` with constant `A`, and
`‖f‖ ≤ s` implies `‖T f‖ ≤ B s` a.e. (for `f ∈ D`), then for `0 < a < p`, every `c > 0` with
`B c ≤ 1/2` and every `f ∈ D`, `∫ ‖T f‖^p ≤ p 2^a A^a c^(a-p)/(p-a) ∫ ‖f‖^p`. -/
theorem lintegral_rpow_le_of_hasWeakTypeOn_of_linfty [SFinite μ] {T : (α → E) → β → F}
    {D : Set (α → E)} {a p c : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p) (hc : 0 < c)
    (hBc : (B : ℝ) * c ≤ 1 / 2) (hTA : HasWeakTypeOn T D a A μ ν)
    (hTB : HasLinftyBoundOn T D B ν) (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D)
    {f : α → E} (hfD : f ∈ D) (hf : AEStronglyMeasurable f μ)
    (hTf : AEStronglyMeasurable (T f) ν) :
    ∫⁻ x, ‖T f x‖ₑ ^ p ∂ν ≤ marcinkiewiczBoundTop a p A c * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  have hsplit : ∀ t : ℝ, 0 < t → ν {x | t < ‖T f x‖} ≤
      ENNReal.ofReal (2 ^ a * (A : ℝ) ^ a) * ENNReal.ofReal (t ^ (-a)) *
          ∫⁻ x, ‖{y | c * t < ‖f y‖}.indicator f x‖ₑ ^ a ∂μ +
        ENNReal.ofReal 0 * ENNReal.ofReal (t ^ (-(p + 1))) *
          ∫⁻ x, ‖{y | ‖f y‖ ≤ c * t}.indicator f x‖ₑ ^ (p + 1) ∂μ := by
    intro t ht
    have hs : 0 < c * t := mul_pos hc ht
    obtain ⟨h₁, h₂⟩ := hD f hfD _ hs
    have hbound : ∀ x, ‖{y | ‖f y‖ ≤ c * t}.indicator f x‖ ≤ c * t := by
      intro x
      by_cases h : ‖f x‖ ≤ c * t
      · simp [h]
      · simp [h, hs.le]
    have hBs : (B : ℝ) * (c * t) ≤ t / 2 := by
      calc (B : ℝ) * (c * t) = (B * c) * t := by ring
        _ ≤ 1 / 2 * t := mul_le_mul_of_nonneg_right hBc ht.le
        _ = t / 2 := by ring
    have hz := hTB.measure_lt_eq_zero h₂ hbound hBs
    rw [ENNReal.ofReal_zero, zero_mul, zero_mul, add_zero]
    refine (measure_lt_norm_le_of_isSublinearOn hsub hD hfD hs t).trans ?_
    rw [hz, add_zero]
    exact hTA.measure_half_lt_le ha h₁ (aestronglyMeasurable_indicator_lt_norm hf _) ht
  refine (lintegral_rpow_enorm_le_of_distribution_split hTf hf ha hap (by linarith) hc
    (by positivity) le_rfl hsplit).trans_eq ?_
  rw [marcinkiewiczBoundTop, zero_mul, zero_div, add_zero]

/-- **Marcinkiewicz interpolation with an `L^∞` endpoint, free truncation parameter, `Lᵖ` form**:
under the hypotheses of `lintegral_rpow_le_of_hasWeakTypeOn_of_linfty`,
`‖T f‖_p ≤ (p 2^a A^a c^(a-p)/(p-a))^(1/p) ‖f‖_p`. -/
theorem eLpNorm_le_of_hasWeakTypeOn_of_linfty_of_pos [SFinite μ] {T : (α → E) → β → F}
    {D : Set (α → E)} {a p c : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p) (hc : 0 < c)
    (hBc : (B : ℝ) * c ≤ 1 / 2) (hTA : HasWeakTypeOn T D a A μ ν)
    (hTB : HasLinftyBoundOn T D B ν) (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D)
    {f : α → E} (hfD : f ∈ D) (hf : AEStronglyMeasurable f μ)
    (hTf : AEStronglyMeasurable (T f) ν) :
    eLpNorm (T f) (ENNReal.ofReal p) ν ≤
      marcinkiewiczBoundTop a p A c ^ (1 / p) * eLpNorm f (ENNReal.ofReal p) μ :=
  eLpNorm_le_of_lintegral_rpow_le hTf hf (ha.trans hap)
    (lintegral_rpow_le_of_hasWeakTypeOn_of_linfty ha hap hc hBc hTA hTB hsub hD hfD hf hTf)

/-- **Marcinkiewicz interpolation theorem with an `L^∞` endpoint** (Blueprint Lemma 2.3
(`lem:interpolation`), second assertion): let `T` be subadditive in pointwise norm on a
truncation closed class `D`, of weak type `(a, a)` with constant `A` on `D`, and strong type
`(∞, ∞)` with constant `B` in the form `‖f‖ ≤ s ⇒ ‖T f‖ ≤ B s` a.e. (for `f ∈ D`). Then for
`0 < a < p < ∞` and every a.e. strongly measurable `f ∈ D` with `T f` a.e. strongly measurable,
`‖T f‖_p ≤ C(a,p) A^(a/p) B^(1-a/p) ‖f‖_p` with `C(a,p) = 2 (p/(p-a))^(1/p) < ∞`.
(If `B = 0` we additionally assume `‖f‖_p < ∞`.) -/
theorem eLpNorm_le_of_hasWeakTypeOn_of_linfty [SFinite μ] {T : (α → E) → β → F}
    {D : Set (α → E)} {a p : ℝ} {A B : ℝ≥0} (ha : 0 < a) (hap : a < p)
    (hTA : HasWeakTypeOn T D a A μ ν) (hTB : HasLinftyBoundOn T D B ν)
    (hsub : IsSublinearOn T D ν) (hD : IsTruncationClosed D) {f : α → E} (hfD : f ∈ D)
    (hf : AEStronglyMeasurable f μ) (hTf : AEStronglyMeasurable (T f) ν)
    (hB : 0 < B ∨ eLpNorm f (ENNReal.ofReal p) μ ≠ ∞) :
    eLpNorm (T f) (ENNReal.ofReal p) ν ≤
      (marcinkiewiczConstTop a p : ℝ≥0∞) * (A : ℝ≥0∞) ^ (a / p) * (B : ℝ≥0∞) ^ (1 - a / p) *
        eLpNorm f (ENNReal.ofReal p) μ := by
  have hp : 0 < p := ha.trans hap
  have hpa : 0 < p - a := by linarith
  have hap' : 0 < 1 - a / p := by
    rw [sub_pos, div_lt_one hp]
    exact hap
  rcases eq_or_ne A 0 with rfl | hA0
  · rw [eLpNorm_congr_ae (hTA.ae_eq_zero_of_const_eq_zero ha hfD), eLpNorm_zero]
    exact zero_le
  have hA : 0 < (A : ℝ) := NNReal.coe_pos.mpr (pos_iff_ne_zero.mpr hA0)
  rcases eq_or_ne B 0 with rfl | hB0
  · -- `B = 0`: let the truncation parameter tend to infinity
    have hfp : eLpNorm f (ENNReal.ofReal p) μ ≠ ∞ := by
      rcases hB with hB | hB
      · exact absurd hB (lt_irrefl _)
      · exact hB
    have hI : ∫⁻ x, ‖f x‖ₑ ^ p ∂μ ≠ ∞ := by
      rw [← eLpNorm_ofReal_rpow_eq_lintegral hf hp]
      exact ENNReal.rpow_ne_top_of_nonneg hp.le hfp
    have hlim : Tendsto (fun c : ℝ => marcinkiewiczBoundTop a p A c * ∫⁻ x, ‖f x‖ₑ ^ p ∂μ)
        atTop (𝓝 0) := by
      have h1 : Tendsto (fun c : ℝ => p * 2 ^ a * (A : ℝ) ^ a / (p - a) * c ^ (-(p - a)))
          atTop (𝓝 (p * 2 ^ a * (A : ℝ) ^ a / (p - a) * 0)) :=
        (tendsto_rpow_neg_atTop hpa).const_mul _
      rw [mul_zero] at h1
      have h2 := ENNReal.Tendsto.mul_const (ENNReal.tendsto_ofReal h1)
        (b := ∫⁻ x, ‖f x‖ₑ ^ p ∂μ) (Or.inr hI)
      rw [ENNReal.ofReal_zero, zero_mul] at h2
      refine h2.congr' (Eventually.of_forall fun c => ?_)
      unfold marcinkiewiczBoundTop
      rw [neg_sub]
      congr 2
      ring
    have hle : ∫⁻ x, ‖T f x‖ₑ ^ p ∂ν ≤ 0 := by
      refine ge_of_tendsto hlim ((eventually_gt_atTop 0).mono fun c hc => ?_)
      exact lintegral_rpow_le_of_hasWeakTypeOn_of_linfty ha hap hc (by simp) hTA hTB hsub hD
        hfD hf hTf
    have h0 : eLpNorm (T f) (ENNReal.ofReal p) ν = 0 := by
      rw [eLpNorm_ofReal_eq_lintegral_rpow_enorm hTf hp, nonpos_iff_eq_zero.mp hle,
        ENNReal.zero_rpow_of_pos (by positivity)]
    rw [h0]
    exact zero_le
  have hB' : 0 < (B : ℝ) := NNReal.coe_pos.mpr (pos_iff_ne_zero.mpr hB0)
  have hc : 0 < 1 / (2 * (B : ℝ)) := by positivity
  have hBc : (B : ℝ) * (1 / (2 * B)) ≤ 1 / 2 := by
    rw [show (B : ℝ) * (1 / (2 * B)) = 1 / 2 by field_simp]
  refine (eLpNorm_le_of_hasWeakTypeOn_of_linfty_of_pos ha hap hc hBc hTA hTB hsub hD hfD hf
    hTf).trans (le_of_eq ?_)
  congr 1
  have hX : 0 ≤ p * (2 ^ a * (A : ℝ) ^ a * (1 / (2 * (B : ℝ))) ^ (a - p) / (p - a)) := by
    positivity
  rw [marcinkiewiczBoundTop, ENNReal.ofReal_rpow_of_nonneg hX (by positivity),
    marcinkiewicz_real_identity_top ha hap hA hB',
    ENNReal.ofReal_mul (by positivity), ENNReal.ofReal_mul (by positivity),
    ← ENNReal.ofReal_rpow_of_nonneg A.coe_nonneg (by positivity),
    ← ENNReal.ofReal_rpow_of_nonneg B.coe_nonneg hap'.le,
    ENNReal.ofReal_coe_nnreal, ENNReal.ofReal_coe_nnreal]
  rfl

end Interpolation

end

end Auto
