/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Decay estimates for oscillatory integrals

This file was automatically generated by Claude.

We prove two classical decay estimates for oscillatory integrals `∫ e^{iΦ(x)} a(x) dx` on
`ℝⁿ = EuclideanSpace ℝ (Fin n)`, with constants that are uniform in the phase and the amplitude
(see E. M. Stein, *Harmonic Analysis* (1993), Ch. VIII, §1 (nonstationary phase) and §2
(nondegenerate critical points)).

## Main results

* `Auto.norm_integral_exp_mul_le_of_nonstationary` (nonstationary phase): for `N : ℕ` and
  `M : ℝ` there is `C = C(n, N, M)` such that, whenever `Φ` is smooth on an open set
  `U ⊇ tsupport a`, `a` is smooth with compact support, `‖DΦ‖ ≥ μ > 0` and
  `‖D^k Φ‖ ≤ M μ` for `2 ≤ k ≤ N + 1` on `tsupport a`,
  `‖∫ e^{iΦ} a‖ ≤ C μ^{-N} ∑_{k ≤ N} ∫ ‖D^k a‖`.
* `Auto.norm_integral_exp_mul_le_of_strongMono` (strongly convex phase): if `Φ` is smooth on the
  `δ`-neighbourhood `K_δ` of `K = tsupport a`, `‖D^k Φ‖ ≤ B λ` on `K_δ` for `2 ≤ k ≤ n + 3`,
  and `⟪∇Φ(x) - ∇Φ(y), x - y⟫ ≥ c λ ‖x - y‖²` on `K`, then `‖∫ e^{iΦ} a‖ ≤ C λ^{-n/2}` with
  `C` depending only on `n, c, δ, B`, a bound `A` for the derivatives of `a` up to order `n + 1`
  and a bound `R` for the volume of `K`.
* `Auto.norm_integral_exp_radial_le`: the typical application
  `Φ(t) = λ u ‖t‖^α - ⟪t, ξ⟫` (`α > 1`, `u ∈ [1, U]`) with `a` supported in the annulus
  `1/2 ≤ ‖t‖ ≤ 2`: `‖∫ e^{iΦ} a‖ ≤ C λ^{-n/2}` uniformly in `ξ`, `u` and `λ > 0`.
* `Auto.norm_integral_exp_radial_le_of_nonstationary`: for the same phases, if
  `‖ξ‖ ≥ 2 α U 2^{|α-1|} λ` or `‖ξ‖ ≤ α 2^{-|α-1|} λ / 2` (no critical point), then
  `‖∫ e^{iΦ} a‖ ≤ C (λ + ‖ξ‖)^{-N} ∑_{k ≤ N} ∫ ‖D^k a‖`.

## Proof outline

The nonstationary phase estimate is proved by `N` integrations by parts with the transposed
operator `g ↦ i ∑ᵢ ∂ᵢ(wᵢ g)`, `w = ∇Φ/|∇Φ|²` (`Auto.oscStep`, `Auto.osc_integral_oscStep`).
The derivatives of `w` are controlled by Faà di Bruno's formula
(`norm_iteratedFDerivWithin_comp_le`) applied to the `(-1)`-homogeneous map
`L ↦ L(eᵢ)/∑ⱼ L(eⱼ)²` at the unit vector `DΦ(x)/‖DΦ(x)‖` (where its derivatives are bounded by
compactness of the unit sphere), giving `‖D^l w‖ ≲ μ⁻¹`; the Leibniz rule then gives the
pointwise bounds `‖D^j (oscStep^[m] a)‖ ≲ μ^{-m} ∑_{l ≤ N} ‖D^l a‖` for `j + m ≤ N`.

The strongly convex estimate uses the `|m|²` trick:
`|∫ e^{iΦ} a|² ≤ ∫_w |∫_t e^{i(Φ(t) - Φ(t - w))} a(t) conj a(t - w) dt| dw`. For each `w` the
phase `ψ_w(t) = Φ(t) - Φ(t - w)` satisfies `|∇ψ_w| ≥ c λ |w|` (strong monotonicity) and
`‖D^k ψ_w‖ ≲ λ |w|` (mean value theorem for `|w| < δ`, the trivial bound otherwise) on the
support of the amplitude, so the nonstationary phase estimate with `N = n + 1` gives
`≲ (λ |w|)^{-(n+1)}`; together with the trivial bound this is `≲ (1 + λ |w|)^{-(n+1)}`, whose
integral is `≲ λ^{-n}`.

For the radial corollary the strong monotonicity of `x ↦ α ‖x‖^{α-2} x` on the annulus follows
from the identity
`2⟪h(x) x - h(y) y, x - y⟫ = (h(x) + h(y)) (‖x - y‖² - (‖x‖ - ‖y‖)²)
  + 2 (‖x‖ - ‖y‖)(‖x‖ h(x) - ‖y‖ h(y))`, `h(x) = α ‖x‖^{α-2}`.

The integration-by-parts mechanism is adapted from the lemma
`norm_integral_eC_mul_le_of_nonstationary` of the user's project `lean-discretesw`
(file `DiscreteSW/Auto/Sec2_4_2_5MultiplierApproximations.lean`), made quantitative here.
-/

@[expose] public section
namespace Auto

open MeasureTheory Set Filter Metric
open scoped ContDiff Topology ComplexConjugate Nat

variable {n : ℕ}

/-- The standard basis vector `e_i` of `ℝⁿ`. -/
noncomputable def oscBasis (i : Fin n) : EuclideanSpace ℝ (Fin n) := EuclideanSpace.single i 1

lemma osc_norm_oscBasis (i : Fin n) : ‖oscBasis i‖ = 1 := by
  simp [oscBasis]

/-- The sum of squares `∑ⱼ L(eⱼ)²` of a linear functional; it equals `‖L‖²`. -/
noncomputable def oscSq (L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) : ℝ := ∑ j, L (oscBasis j) ^ 2

lemma osc_eq_zero_of_oscSq {L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ} (h : oscSq L = 0) : L = 0 := by
  have hj : ∀ j, L (oscBasis j) = 0 := by
    intro j
    have := (Finset.sum_eq_zero_iff_of_nonneg (fun j _ => sq_nonneg (L (oscBasis j)))).1 h j
      (Finset.mem_univ _)
    exact pow_eq_zero_iff (two_ne_zero) |>.1 this
  ext v
  have hv : v = ∑ j, v j • oscBasis j := by
    have := (EuclideanSpace.basisFun (Fin n) ℝ).sum_repr v
    conv_lhs => rw [← this]
    simp [oscBasis]
  rw [hv, map_sum]; simp [hj]

lemma osc_oscSq_ne_zero {L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ} (h : L ≠ 0) : oscSq L ≠ 0 :=
  fun h' => h (osc_eq_zero_of_oscSq h')

/-- The `i`-th component `L(eᵢ)/∑ⱼ L(eⱼ)²` of the vector field `∇Φ/|∇Φ|²`, as a function of
`L = DΦ(x)`. -/
noncomputable def oscG (i : Fin n) (L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) : ℂ :=
  ((L (oscBasis i) / oscSq L : ℝ) : ℂ)

lemma osc_contDiffOn_oscG (i : Fin n) :
    ContDiffOn ℝ ∞ (oscG i) {L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ | L ≠ 0} := by
  have h1 : ContDiff ℝ ∞ fun L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ => L (oscBasis i) :=
    (ContinuousLinearMap.apply ℝ ℝ (oscBasis i)).contDiff
  have h2 : ContDiff ℝ ∞ fun L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ => oscSq L := by
    unfold oscSq
    exact ContDiff.sum fun j _ => ((ContinuousLinearMap.apply ℝ ℝ (oscBasis j)).contDiff).pow 2
  exact Complex.ofRealCLM.contDiff.comp_contDiffOn
    (h1.contDiffOn.div h2.contDiffOn fun L hL => osc_oscSq_ne_zero hL)

lemma osc_sum_oscG {L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ} (hL : L ≠ 0) :
    ∑ i, (L (oscBasis i) : ℂ) * oscG i L = 1 := by
  have h := osc_oscSq_ne_zero hL
  simp only [oscG, Complex.ofReal_div]
  simp_rw [← mul_div_assoc]
  rw [← Finset.sum_div]
  have : ∑ i, (L (oscBasis i) : ℂ) * (L (oscBasis i) : ℂ) = (oscSq L : ℂ) := by
    simp [oscSq, sq]
  rw [this, div_self (by exact_mod_cast h)]

lemma osc_oscG_smul (i : Fin n) (L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) {c : ℝ} (hc : c ≠ 0) :
    oscG i (c • L) = ((c⁻¹ : ℝ) : ℂ) * oscG i L := by
  have hsq : oscSq (c • L) = c ^ 2 * oscSq L := by
    simp only [oscSq, smul_apply, smul_eq_mul, mul_pow, Finset.mul_sum]
  simp only [oscG, hsq, smul_apply, smul_eq_mul]
  rw [← Complex.ofReal_mul]
  congr 1
  rcases eq_or_ne (oscSq L) 0 with h | h
  · simp [h]
  · field_simp

/-- The derivatives of `oscG i` up to order `N` are uniformly bounded on the unit sphere. -/
lemma osc_oscG_bound (N : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (i : Fin n) (l : ℕ), l ≤ N → ∀ L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ,
      ‖L‖ = 1 → ‖iteratedFDerivWithin ℝ l (oscG i) {L | L ≠ 0} L‖ ≤ C := by
  set t : Set (EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) := {L | L ≠ 0} with ht
  have hto : IsOpen t := isOpen_ne
  have hcont : ContinuousOn (fun L => ∑ i : Fin n, ∑ l ∈ Finset.range (N + 1),
      ‖iteratedFDerivWithin ℝ l (oscG i) t L‖) t := by
    refine continuousOn_finsetSum _ fun i _ => continuousOn_finsetSum _ fun l _ => ?_
    exact ((osc_contDiffOn_oscG i).continuousOn_iteratedFDerivWithin (by simp)
      hto.uniqueDiffOn).norm
  have hsub : sphere (0 : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) 1 ⊆ t := by
    intro L hL
    have : ‖L‖ = 1 := by simpa using hL
    intro h0; rw [h0, norm_zero] at this; exact zero_ne_one this
  obtain ⟨C, hC⟩ :=
    (isCompact_sphere (0 : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) 1).exists_bound_of_continuousOn
    (hcont.mono hsub)
  refine ⟨max C 0, le_max_right _ _, fun i l hl L hL => ?_⟩
  have hLs : L ∈ sphere (0 : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) 1 := by simpa using hL
  have h1 := hC L hLs
  rw [Real.norm_of_nonneg (by positivity)] at h1
  refine le_trans ?_ (le_trans h1 (le_max_left _ _))
  refine le_trans ?_ (Finset.single_le_sum (f := fun i : Fin n => ∑ l ∈ Finset.range (N + 1),
      ‖iteratedFDerivWithin ℝ l (oscG i) t L‖) (fun _ _ => by positivity) (Finset.mem_univ i))
  exact Finset.single_le_sum (f := fun l => ‖iteratedFDerivWithin ℝ l (oscG i) t L‖)
    (fun _ _ => norm_nonneg _) (Finset.mem_range.2 (by omega))

/-- The open set where `Φ` is smooth (`U`) and nonstationary. -/
def oscO (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (U : Set (EuclideanSpace ℝ (Fin n))) :
    Set (EuclideanSpace ℝ (Fin n)) :=
  U ∩ {x | fderiv ℝ Φ x ≠ 0}

/-- The `i`-th component of the vector field `∇Φ/|∇Φ|²`. -/
noncomputable def oscW (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (i : Fin n)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  oscG i (fderiv ℝ Φ x)

section W

variable {Φ : EuclideanSpace ℝ (Fin n) → ℝ} {U : Set (EuclideanSpace ℝ (Fin n))}

lemma osc_isOpen_oscO (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U) : IsOpen (oscO Φ U) :=
  (hΦ.continuousOn_fderiv_of_isOpen hU (by simp)).isOpen_inter_preimage hU isOpen_ne

lemma osc_contDiffOn_fderiv (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U) :
    ContDiffOn ℝ ∞ (fun y => fderiv ℝ Φ y) U :=
  hΦ.fderiv_of_isOpen hU (by simp)

lemma osc_contDiffOn_oscW (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U) (i : Fin n) :
    ContDiffOn ℝ ∞ (oscW Φ i) (oscO Φ U) :=
  (osc_contDiffOn_oscG i).comp ((osc_contDiffOn_fderiv hU hΦ).mono inter_subset_left)
    (fun _ hy => hy.2)

/-- Pointwise bounds for the derivatives of the vector field `∇Φ/|∇Φ|²`. -/
lemma osc_oscW_bound (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U) (N : ℕ) {C : ℝ}
    (hC : ∀ (i : Fin n) (l : ℕ), l ≤ N → ∀ L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ,
      ‖L‖ = 1 → ‖iteratedFDerivWithin ℝ l (oscG i) {L | L ≠ 0} L‖ ≤ C)
    {M μ : ℝ} (hμ : 0 < μ) {x : EuclideanSpace ℝ (Fin n)} (hxU : x ∈ U)
    (hx : μ ≤ ‖fderiv ℝ Φ x‖)
    (hM : ∀ k, 2 ≤ k → k ≤ N + 1 → ‖iteratedFDeriv ℝ k Φ x‖ ≤ M * μ) (i : Fin n) (l : ℕ)
    (hl : l ≤ N) :
    ‖iteratedFDerivWithin ℝ l (oscW Φ i) (oscO Φ U) x‖ ≤ (N ! * C * max M 1 ^ N) * μ⁻¹ := by
  set ρ := ‖fderiv ℝ Φ x‖ with hρ
  have hρ0 : 0 < ρ := lt_of_lt_of_le hμ hx
  have hO := osc_isOpen_oscO hU hΦ
  have hxO : x ∈ oscO Φ U := ⟨hxU, fun h => by rw [h, norm_zero] at hρ; linarith⟩
  set f : EuclideanSpace ℝ (Fin n) → (EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ) :=
    fun y => ρ⁻¹ • fderiv ℝ Φ y with hf
  have hW : oscW Φ i = ρ⁻¹ • (oscG i ∘ f) := by
    funext y
    simp only [oscW, hf, Pi.smul_apply, Function.comp_apply]
    rw [osc_oscG_smul i _ (inv_ne_zero hρ0.ne'), inv_inv, Complex.real_smul,
      ← mul_assoc, ← Complex.ofReal_mul, inv_mul_cancel₀ hρ0.ne']
    simp
  have hfd : ContDiffOn ℝ ∞ (fun y => fderiv ℝ Φ y) (oscO Φ U) :=
    (osc_contDiffOn_fderiv hU hΦ).mono inter_subset_left
  have hfc : ContDiffOn ℝ ∞ f (oscO Φ U) := hfd.const_smul _
  have hgf : ContDiffOn ℝ ∞ (oscG i ∘ f) (oscO Φ U) :=
    (osc_contDiffOn_oscG i).comp hfc (fun y hy => smul_ne_zero (inv_ne_zero hρ0.ne') hy.2)
  rw [hW, iteratedFDerivWithin_const_smul_apply (hgf.of_le (by simp) x hxO) hO.uniqueDiffOn hxO,
    norm_smul, Real.norm_of_nonneg (by positivity), mul_comm]
  have hM0 : ∀ j, 1 ≤ j → j ≤ l → ‖iteratedFDerivWithin ℝ j f (oscO Φ U) x‖ ≤ max M 1 ^ j := by
    intro j hj1 hjl
    rw [hf, show (fun y => ρ⁻¹ • fderiv ℝ Φ y) = ρ⁻¹ • (fun y => fderiv ℝ Φ y) from rfl,
      iteratedFDerivWithin_const_smul_apply ((hfd.of_le (by simp)) x hxO) hO.uniqueDiffOn hxO,
      iteratedFDerivWithin_of_isOpen j hO hxO, norm_smul, norm_iteratedFDeriv_fderiv,
      Real.norm_of_nonneg (by positivity)]
    have h1 := hM (j + 1) (by omega) (by omega)
    have hM0 : 0 ≤ M := by
      by_contra h; push Not at h
      have := norm_nonneg (iteratedFDeriv ℝ (j + 1) Φ x)
      nlinarith
    calc ρ⁻¹ * ‖iteratedFDeriv ℝ (j + 1) Φ x‖ ≤ ρ⁻¹ * (M * ρ) := by gcongr; nlinarith
      _ = M := by field_simp
      _ ≤ max M 1 := le_max_left _ _
      _ ≤ max M 1 ^ j := le_self_pow₀ (le_max_right _ _) (by omega)
  have hCl : ∀ j, j ≤ l → ‖iteratedFDerivWithin ℝ j (oscG i) {L | L ≠ 0} (f x)‖ ≤ C := by
    intro j hj
    refine hC i j (by omega) _ ?_
    simp only [hf, norm_smul, norm_inv, Real.norm_of_nonneg hρ0.le]
    exact inv_mul_cancel₀ hρ0.ne'
  have hfdb := norm_iteratedFDerivWithin_comp_le (osc_contDiffOn_oscG i) hfc (n := l)
    (by simp) isOpen_ne.uniqueDiffOn hO.uniqueDiffOn
    (fun y hy => smul_ne_zero (inv_ne_zero hρ0.ne') hy.2) hxO hCl hM0
  have hC0 : 0 ≤ C := le_trans (norm_nonneg _) (hCl 0 (Nat.zero_le _))
  have h1 : (l ! : ℝ) * C * max M 1 ^ l ≤ N ! * C * max M 1 ^ N := by
    gcongr
    exact le_max_right _ _
  calc ‖iteratedFDerivWithin ℝ l (oscG i ∘ f) (oscO Φ U) x‖ * ρ⁻¹
      ≤ (N ! * C * max M 1 ^ N) * ρ⁻¹ := by gcongr; exact hfdb.trans h1
    _ ≤ (N ! * C * max M 1 ^ N) * μ⁻¹ := by gcongr

end W

section Support

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [NormedRing F] [NormedAlgebra ℝ F]

/-- A function smooth on an open set `O`, times a smooth function supported in `O`, is smooth. -/
lemma osc_contDiff_mul_of_tsupport {k : ℕ∞ω} {O : Set E} (hO : IsOpen O) {h g : E → F}
    (hh : ContDiffOn ℝ k h O) (hg : ContDiff ℝ k g) (hgO : tsupport g ⊆ O) :
    ContDiff ℝ k (fun x => h x * g x) := by
  refine contDiff_iff_contDiffAt.2 fun x => ?_
  by_cases hx : x ∈ O
  · exact (hh.contDiffAt (hO.mem_nhds hx)).mul hg.contDiffAt
  · have hx' : x ∉ tsupport g := fun h' => hx (hgO h')
    rw [notMem_tsupport_iff_eventuallyEq] at hx'
    refine contDiffAt_const (c := (0 : F)).congr_of_eventuallyEq ?_
    filter_upwards [hx'] with y hy
    simp [hy]

/-- Continuity version of `osc_contDiff_mul_of_tsupport`. -/
lemma osc_continuous_mul_of_tsupport {O : Set E} (hO : IsOpen O) {h g : E → F}
    (hh : ContinuousOn h O) (hg : Continuous g) (hgO : tsupport g ⊆ O) :
    Continuous (fun x => h x * g x) := by
  have := osc_contDiff_mul_of_tsupport (k := 0) hO (contDiffOn_zero.2 hh) (contDiff_zero.2 hg) hgO
  exact contDiff_zero.1 this

/-- Integrability version of `osc_contDiff_mul_of_tsupport`. -/
lemma osc_integrable_mul_of_tsupport [MeasurableSpace E] [BorelSpace E] {μ : Measure E}
    [IsFiniteMeasureOnCompacts μ] {O : Set E} (hO : IsOpen O) {h g : E → F}
    (hh : ContinuousOn h O) (hg : Continuous g) (hgc : HasCompactSupport g)
    (hgO : tsupport g ⊆ O) : Integrable (fun x => h x * g x) μ :=
  (osc_continuous_mul_of_tsupport hO hh hg hgO).integrable_of_hasCompactSupport hgc.mul_left

omit [NormedAlgebra ℝ F] in
lemma osc_support_fderiv_apply {G : Type*} [NormedAddCommGroup G] [NormedSpace ℝ G] {f : E → G}
    (v : E) : Function.support (fun x => fderiv ℝ f x v) ⊆ tsupport f := fun x hx =>
  support_fderiv_subset ℝ (fun h => hx (by simp [h]))

end Support

/-- The oscillatory factor `e^{iΦ}`. -/
noncomputable def oscE (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  Complex.exp (Complex.I * (Φ x : ℂ))

lemma osc_norm_oscE (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (x : EuclideanSpace ℝ (Fin n)) :
    ‖oscE Φ x‖ = 1 := by
  rw [oscE, mul_comm]; exact Complex.norm_exp_ofReal_mul_I _

/-- The transposed integration-by-parts operator `g ↦ i ∑ᵢ ∂ᵢ(wᵢ g)`, `w = ∇Φ/|∇Φ|²`. -/
noncomputable def oscStep (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (g : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  ∑ i, Complex.I * fderiv ℝ (fun y => oscW Φ i y * g y) x (oscBasis i)

section Step

variable {Φ : EuclideanSpace ℝ (Fin n) → ℝ} {U : Set (EuclideanSpace ℝ (Fin n))}

lemma osc_contDiffOn_oscE (hΦ : ContDiffOn ℝ ∞ Φ U) : ContDiffOn ℝ ∞ (oscE Φ) U :=
  Complex.contDiff_exp.comp_contDiffOn
    (contDiffOn_const.mul (Complex.ofRealCLM.contDiff.comp_contDiffOn hΦ))

lemma osc_hasFDerivAt_oscE (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ U) (v : EuclideanSpace ℝ (Fin n)) :
    fderiv ℝ (oscE Φ) x v = oscE Φ x * (Complex.I * (fderiv ℝ Φ x v : ℂ)) := by
  have hΦx : HasFDerivAt Φ (fderiv ℝ Φ x) x :=
    ((hΦ.contDiffAt (hU.mem_nhds hx)).differentiableAt (by simp)).hasFDerivAt
  have h1 := ((Complex.ofRealCLM.hasFDerivAt.comp x hΦx).const_mul Complex.I).cexp
  have h2 : HasFDerivAt (oscE Φ) _ x := h1
  rw [h2.fderiv]
  simp [oscE]

lemma osc_contDiff_oscW_mul (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U) (i : Fin n)
    {g : EuclideanSpace ℝ (Fin n) → ℂ} (hg : ContDiff ℝ ∞ g) (hgO : tsupport g ⊆ oscO Φ U) :
    ContDiff ℝ ∞ (fun y => oscW Φ i y * g y) :=
  osc_contDiff_mul_of_tsupport (osc_isOpen_oscO hU hΦ) (osc_contDiffOn_oscW hU hΦ i) hg hgO

lemma osc_contDiff_oscStep (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {g : EuclideanSpace ℝ (Fin n) → ℂ} (hg : ContDiff ℝ ∞ g) (hgO : tsupport g ⊆ oscO Φ U) :
    ContDiff ℝ ∞ (oscStep Φ g) := by
  unfold oscStep
  refine ContDiff.sum fun i _ => contDiff_const.mul ?_
  exact ((osc_contDiff_oscW_mul hU hΦ i hg hgO).fderiv_right (m := ∞) (by simp)).clm_apply
    contDiff_const

lemma osc_tsupport_oscStep (g : EuclideanSpace ℝ (Fin n) → ℂ) :
    tsupport (oscStep Φ g) ⊆ tsupport g := by
  refine closure_minimal (fun x hx => ?_) isClosed_closure
  by_contra h
  apply hx
  unfold oscStep
  refine Finset.sum_eq_zero fun i _ => ?_
  have : x ∉ tsupport (fun y => oscW Φ i y * g y) := fun h' => h (tsupport_mul_subset_right h')
  rw [fderiv_of_notMem_tsupport ℝ this]
  simp

/-- One integration by parts: `∫ e^{iΦ} g = ∫ e^{iΦ} (oscStep Φ g)`. -/
lemma osc_integral_oscStep (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {g : EuclideanSpace ℝ (Fin n) → ℂ} (hg : ContDiff ℝ ∞ g) (hgc : HasCompactSupport g)
    (hgO : tsupport g ⊆ oscO Φ U) :
    ∫ x, oscE Φ x * g x = ∫ x, oscE Φ x * oscStep Φ g x := by
  have hO := osc_isOpen_oscO hU hΦ
  have hOU : oscO Φ U ⊆ U := inter_subset_left
  set G : Fin n → EuclideanSpace ℝ (Fin n) → ℂ := fun i y => oscW Φ i y * g y with hGdef
  have hG : ∀ i, ContDiff ℝ ∞ (G i) := fun i => osc_contDiff_oscW_mul hU hΦ i hg hgO
  have hGc : ∀ i, HasCompactSupport (G i) := fun i => hgc.mul_left
  have hGO : ∀ i, tsupport (G i) ⊆ oscO Φ U := fun i => tsupport_mul_subset_right.trans hgO
  have hEc : ContinuousOn (oscE Φ) (oscO Φ U) := ((osc_contDiffOn_oscE hΦ).continuousOn).mono hOU
  have hdEc : ∀ v, ContinuousOn (fun x => fderiv ℝ (oscE Φ) x v) (oscO Φ U) := fun v =>
    (((osc_contDiffOn_oscE hΦ).continuousOn_fderiv_of_isOpen hU (by simp)).clm_apply
      continuousOn_const).mono hOU
  have hdG : ∀ i v, Continuous (fun x => fderiv ℝ (G i) x v) := fun i v =>
    ((hG i).continuous_fderiv (by simp)).clm_apply continuous_const
  have hdGc : ∀ i v, HasCompactSupport (fun x => fderiv ℝ (G i) x v) := fun i v =>
    (hGc i).mono' (osc_support_fderiv_apply v)
  have hdGO : ∀ i v, tsupport (fun x => fderiv ℝ (G i) x v) ⊆ oscO Φ U := fun i v =>
    (closure_minimal (osc_support_fderiv_apply v) isClosed_closure).trans (hGO i)
  have hint1 : ∀ i, Integrable (fun x => fderiv ℝ (oscE Φ) x (oscBasis i) * G i x) := fun i =>
    osc_integrable_mul_of_tsupport hO (hdEc _) (hG i).continuous (hGc i) (hGO i)
  have hint2 : ∀ i, Integrable (fun x => oscE Φ x * fderiv ℝ (G i) x (oscBasis i)) := fun i =>
    osc_integrable_mul_of_tsupport hO hEc (hdG i _) (hdGc i _) (hdGO i _)
  have hibp : ∀ i, ∫ x, oscE Φ x * fderiv ℝ (G i) x (oscBasis i) =
      -∫ x, fderiv ℝ (oscE Φ) x (oscBasis i) * G i x := fun i =>
    integral_mul_fderiv_eq_neg_fderiv_mul_of_integrable (hint1 i) (hint2 i)
      (osc_integrable_mul_of_tsupport hO hEc (hG i).continuous (hGc i) (hGO i))
      (fun x hx => ((osc_contDiffOn_oscE hΦ).contDiffAt
        (hU.mem_nhds (hOU (hGO i hx)))).differentiableAt (by simp))
      (fun x _ => (hG i).differentiable (by simp) x)
  have hpt : ∀ x, ∑ i, fderiv ℝ (oscE Φ) x (oscBasis i) * G i x =
      Complex.I * (oscE Φ x * g x) := by
    intro x
    by_cases hx : x ∈ tsupport g
    · have hxO := hgO hx
      simp only [hGdef, osc_hasFDerivAt_oscE hU hΦ (hOU hxO)]
      have h1 := osc_sum_oscG hxO.2
      calc ∑ i, oscE Φ x * (Complex.I * (fderiv ℝ Φ x (oscBasis i) : ℂ)) * (oscW Φ i x * g x)
          = Complex.I * (oscE Φ x * g x) *
            ∑ i, (fderiv ℝ Φ x (oscBasis i) : ℂ) * oscG i (fderiv ℝ Φ x) := by
            rw [Finset.mul_sum]
            refine Finset.sum_congr rfl fun i _ => ?_
            simp only [oscW]; ring
        _ = _ := by rw [h1, mul_one]
    · simp [hGdef, image_eq_zero_of_notMem_tsupport hx]
  have hL : Complex.I * ∫ x, oscE Φ x * g x =
      -∑ i, ∫ x, oscE Φ x * fderiv ℝ (G i) x (oscBasis i) := by
    rw [← integral_const_mul]
    simp_rw [← hpt]
    rw [integral_finsetSum _ fun i _ => hint1 i, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [hibp, neg_neg]
  have hR : ∫ x, oscE Φ x * oscStep Φ g x =
      Complex.I * ∑ i, ∫ x, oscE Φ x * fderiv ℝ (G i) x (oscBasis i) := by
    unfold oscStep
    simp_rw [Finset.mul_sum]
    rw [integral_finsetSum _ fun i _ => ?_]
    · refine Finset.sum_congr rfl fun i _ => ?_
      rw [← integral_const_mul]
      congr 1; funext x; simp only [hGdef]; ring
    · simpa [mul_left_comm] using (hint2 i).const_mul Complex.I
  rw [hR]
  linear_combination (-Complex.I) * hL + (∫ x, oscE Φ x * g x) * Complex.I_sq

/-- Pointwise bound for the derivatives of `oscStep Φ g` in terms of those of `g` and `w`. -/
lemma osc_oscStep_bound (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {g : EuclideanSpace ℝ (Fin n) → ℂ} (hg : ContDiff ℝ ∞ g) (hgO : tsupport g ⊆ oscO Φ U)
    {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ oscO Φ U) (j : ℕ) {W B : ℝ}
    (hW : ∀ (i : Fin n) (l : ℕ), l ≤ j + 1 →
      ‖iteratedFDerivWithin ℝ l (oscW Φ i) (oscO Φ U) x‖ ≤ W)
    (hB : ∀ l, l ≤ j + 1 → ‖iteratedFDeriv ℝ l g x‖ ≤ B) :
    ‖iteratedFDeriv ℝ j (oscStep Φ g) x‖ ≤ n * 2 ^ (j + 1) * W * B := by
  have hO := osc_isOpen_oscO hU hΦ
  set G : Fin n → EuclideanSpace ℝ (Fin n) → ℂ := fun i y => oscW Φ i y * g y with hGdef
  have hG : ∀ i, ContDiff ℝ ∞ (G i) := fun i => osc_contDiff_oscW_mul hU hΦ i hg hgO
  have hdG : ∀ i, ContDiff ℝ ∞ (fun y => fderiv ℝ (G i) y (oscBasis i)) := fun i =>
    ((hG i).fderiv_right (m := ∞) (by simp)).clm_apply contDiff_const
  have hB0 : 0 ≤ B := le_trans (norm_nonneg _) (hB 0 (Nat.zero_le _))
  have hGi : ∀ i, ‖iteratedFDeriv ℝ (j + 1) (G i) x‖ ≤ 2 ^ (j + 1) * W * B := by
    intro i
    have hW0 : 0 ≤ W := le_trans (norm_nonneg _) (hW i 0 (Nat.zero_le _))
    rw [← iteratedFDerivWithin_of_isOpen (j + 1) hO hx]
    refine (norm_iteratedFDerivWithin_mul_le (osc_contDiffOn_oscW hU hΦ i) hg.contDiffOn
      hO.uniqueDiffOn hx (n := j + 1) (by simp)).trans ?_
    calc ∑ l ∈ Finset.range (j + 1 + 1), ((j + 1).choose l : ℝ) *
          ‖iteratedFDerivWithin ℝ l (oscW Φ i) (oscO Φ U) x‖ *
          ‖iteratedFDerivWithin ℝ (j + 1 - l) g (oscO Φ U) x‖
        ≤ ∑ l ∈ Finset.range (j + 1 + 1), ((j + 1).choose l : ℝ) * W * B := by
          refine Finset.sum_le_sum fun l hl => ?_
          have hl' := Finset.mem_range.1 hl
          rw [iteratedFDerivWithin_of_isOpen (j + 1 - l) hO hx]
          gcongr
          · exact hW i l (by omega)
          · exact hB _ (by omega)
      _ = 2 ^ (j + 1) * W * B := by
          rw [← Finset.sum_mul, ← Finset.sum_mul]
          congr 2
          exact_mod_cast Nat.sum_range_choose (j + 1)
  have hsum : oscStep Φ g = ∑ i, fun y => Complex.I • fderiv ℝ (G i) y (oscBasis i) := by
    funext y; simp [oscStep, hGdef]
  rw [hsum, iteratedFDeriv_sum_apply
    (fun i _ => (((hdG i).const_smul Complex.I).of_le (by simp)).contDiffAt)]
  refine (norm_sum_le _ _).trans ?_
  calc ∑ i, ‖iteratedFDeriv ℝ j (fun y => Complex.I • fderiv ℝ (G i) y (oscBasis i)) x‖
      ≤ ∑ _i : Fin n, 2 ^ (j + 1) * W * B := by
        refine Finset.sum_le_sum fun i _ => ?_
        rw [show (fun y => Complex.I • fderiv ℝ (G i) y (oscBasis i)) =
          Complex.I • (fun y => fderiv ℝ (G i) y (oscBasis i)) from rfl,
          iteratedFDeriv_const_smul_apply ((hdG i).of_le (by simp)).contDiffAt, norm_smul,
          Complex.norm_I, one_mul]
        refine (norm_iteratedFDeriv_clm_apply_const
          ((hG i).fderiv_right (m := ∞) (by simp)).contDiffAt (n := j) (by simp)).trans ?_
        rw [osc_norm_oscBasis, one_mul, norm_iteratedFDeriv_fderiv]
        exact hGi i
    _ = n * 2 ^ (j + 1) * W * B := by simp; ring

lemma osc_iterate_props (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {a : EuclideanSpace ℝ (Fin n) → ℂ} (ha : ContDiff ℝ ∞ a) (haO : tsupport a ⊆ oscO Φ U)
    (m : ℕ) : ContDiff ℝ ∞ ((oscStep Φ)^[m] a) ∧ tsupport ((oscStep Φ)^[m] a) ⊆ tsupport a := by
  induction m with
  | zero => exact ⟨ha, subset_rfl⟩
  | succ m ih =>
    rw [Function.iterate_succ_apply']
    exact ⟨osc_contDiff_oscStep hU hΦ ih.1 (ih.2.trans haO),
      (osc_tsupport_oscStep _).trans ih.2⟩

lemma osc_integral_iterate (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {a : EuclideanSpace ℝ (Fin n) → ℂ} (ha : ContDiff ℝ ∞ a) (hac : HasCompactSupport a)
    (haO : tsupport a ⊆ oscO Φ U) (m : ℕ) :
    ∫ x, oscE Φ x * a x = ∫ x, oscE Φ x * (oscStep Φ)^[m] a x := by
  induction m with
  | zero => rfl
  | succ m ih =>
    obtain ⟨h1, h2⟩ := osc_iterate_props hU hΦ ha haO m
    rw [ih, Function.iterate_succ_apply', osc_integral_oscStep hU hΦ h1
      (hac.mono' (subset_tsupport _ |>.trans h2)) (h2.trans haO)]

/-- The pointwise bound for the iterated amplitudes `(oscStep Φ)^[m] a`. -/
lemma osc_iterate_bound (hU : IsOpen U) (hΦ : ContDiffOn ℝ ∞ Φ U)
    {a : EuclideanSpace ℝ (Fin n) → ℂ} (ha : ContDiff ℝ ∞ a) (haU : tsupport a ⊆ U)
    (N : ℕ) {C M μ : ℝ}
    (hC : ∀ (i : Fin n) (l : ℕ), l ≤ N → ∀ L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ,
      ‖L‖ = 1 → ‖iteratedFDerivWithin ℝ l (oscG i) {L | L ≠ 0} L‖ ≤ C) (hC0 : 0 ≤ C)
    (hμ : 0 < μ) (hlow : ∀ x ∈ tsupport a, μ ≤ ‖fderiv ℝ Φ x‖)
    (hM : ∀ x ∈ tsupport a, ∀ k, 2 ≤ k → k ≤ N + 1 → ‖iteratedFDeriv ℝ k Φ x‖ ≤ M * μ)
    (m : ℕ) : ∀ j, j + m ≤ N → ∀ x, ‖iteratedFDeriv ℝ j ((oscStep Φ)^[m] a) x‖ ≤
      (n * 2 ^ N * (N ! * C * max M 1 ^ N)) ^ m * μ⁻¹ ^ m *
        ∑ l ∈ Finset.range (N + 1), ‖iteratedFDeriv ℝ l a x‖ := by
  have haO : tsupport a ⊆ oscO Φ U := fun x hx =>
    ⟨haU hx, fun h => by have := hlow x hx; rw [h, norm_zero] at this; linarith⟩
  have hK0 : 0 ≤ (n * 2 ^ N * (N ! * C * max M 1 ^ N) : ℝ) := by
    have : (0 : ℝ) ≤ max M 1 := le_trans zero_le_one (le_max_right _ _)
    positivity
  induction m with
  | zero =>
    intro j hj x
    simp only [Function.iterate_zero, id_eq, pow_zero, one_mul]
    exact Finset.single_le_sum (f := fun l => ‖iteratedFDeriv ℝ l a x‖)
      (fun _ _ => norm_nonneg _) (Finset.mem_range.2 (by omega))
  | succ m ih =>
    intro j hj x
    obtain ⟨h1, h2⟩ := osc_iterate_props hU hΦ ha haO m
    by_cases hx : x ∈ tsupport a
    · rw [Function.iterate_succ_apply']
      have hS0 : 0 ≤ ∑ l ∈ Finset.range (N + 1), ‖iteratedFDeriv ℝ l a x‖ :=
        Finset.sum_nonneg fun _ _ => norm_nonneg _
      refine (osc_oscStep_bound hU hΦ h1 (h2.trans haO) (haO hx) j
        (W := (N ! * C * max M 1 ^ N) * μ⁻¹)
        (fun i l hl => osc_oscW_bound hU hΦ N hC hμ (haU hx) (hlow x hx) (hM x hx) i l
          (by omega))
        (fun l hl => ih l (by omega) x)).trans ?_
      have h2N : (2 : ℝ) ^ (j + 1) ≤ 2 ^ N := pow_le_pow_right₀ (by norm_num) (by omega)
      have : (0 : ℝ) ≤ max M 1 := le_trans zero_le_one (le_max_right _ _)
      calc (n : ℝ) * 2 ^ (j + 1) * (N ! * C * max M 1 ^ N * μ⁻¹) *
            ((n * 2 ^ N * (N ! * C * max M 1 ^ N)) ^ m * μ⁻¹ ^ m *
              ∑ l ∈ Finset.range (N + 1), ‖iteratedFDeriv ℝ l a x‖)
          ≤ (n : ℝ) * 2 ^ N * (N ! * C * max M 1 ^ N * μ⁻¹) *
            ((n * 2 ^ N * (N ! * C * max M 1 ^ N)) ^ m * μ⁻¹ ^ m *
              ∑ l ∈ Finset.range (N + 1), ‖iteratedFDeriv ℝ l a x‖) := by gcongr
        _ = _ := by ring
    · have hx' : x ∉ tsupport ((oscStep Φ)^[m + 1] a) := fun h =>
        hx ((osc_iterate_props hU hΦ ha haO (m + 1)).2 h)
      rw [show iteratedFDeriv ℝ j ((oscStep Φ)^[m + 1] a) x = 0 from
        Function.notMem_support.1 (fun h => hx' (support_iteratedFDeriv_subset j h)), norm_zero]
      have : (0 : ℝ) ≤ max M 1 := le_trans zero_le_one (le_max_right _ _)
      have hS0 : 0 ≤ ∑ l ∈ Finset.range (N + 1), ‖iteratedFDeriv ℝ l a x‖ :=
        Finset.sum_nonneg fun _ _ => norm_nonneg _
      positivity

end Step

/-- **Nonstationary phase** (quantitative and uniform; see E. M. Stein, *Harmonic Analysis*
(1993), Ch. VIII, §1). For every `n, N` and `M` there is a constant `C` such that for every
phase `Φ` smooth on an open set `U ⊇ tsupport a` and every smooth compactly supported amplitude
`a` with `|∇Φ| ≥ μ > 0` and `‖D^k Φ‖ ≤ M μ` (`2 ≤ k ≤ N + 1`) on `tsupport a`,
`|∫ e^{iΦ} a| ≤ C μ^{-N} ∑_{k ≤ N} ∫ ‖D^k a‖`. -/
theorem norm_integral_exp_mul_le_of_nonstationary (n N : ℕ) (M : ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (a : EuclideanSpace ℝ (Fin n) → ℂ)
      (U : Set (EuclideanSpace ℝ (Fin n))) (μ : ℝ), IsOpen U → ContDiffOn ℝ ∞ Φ U →
      ContDiff ℝ ∞ a → HasCompactSupport a → tsupport a ⊆ U → 0 < μ →
      (∀ x ∈ tsupport a, μ ≤ ‖fderiv ℝ Φ x‖) →
      (∀ x ∈ tsupport a, ∀ k, 2 ≤ k → k ≤ N + 1 → ‖iteratedFDeriv ℝ k Φ x‖ ≤ M * μ) →
      ‖∫ x, Complex.exp (Complex.I * Φ x) * a x‖ ≤
        C * μ ^ (-(N : ℝ)) * ∑ k ∈ Finset.range (N + 1), ∫ x, ‖iteratedFDeriv ℝ k a x‖ := by
  obtain ⟨C, hC0, hC⟩ := osc_oscG_bound (n := n) N
  have hM1 : (0 : ℝ) ≤ max M 1 := le_trans zero_le_one (le_max_right _ _)
  refine ⟨(n * 2 ^ N * (N ! * C * max M 1 ^ N)) ^ N, by positivity, ?_⟩
  intro Φ a U μ hU hΦ ha hac haU hμ hlow hM
  have haO : tsupport a ⊆ oscO Φ U := fun x hx =>
    ⟨haU hx, fun h => by have := hlow x hx; rw [h, norm_zero] at this; linarith⟩
  have hb := osc_iterate_bound hU hΦ ha haU N hC hC0 hμ hlow hM N 0 (by omega)
  have hint : ∀ l, Integrable (fun x => ‖iteratedFDeriv ℝ l a x‖) := fun l =>
    ((ha.continuous_iteratedFDeriv (by simp)).norm).integrable_of_hasCompactSupport
      (hac.iteratedFDeriv l).norm
  change ‖∫ x, oscE Φ x * a x‖ ≤ _
  rw [osc_integral_iterate hU hΦ ha hac haO N]
  refine (norm_integral_le_integral_norm _).trans ?_
  have hrpow : μ ^ (-(N : ℝ)) = μ⁻¹ ^ N := by
    rw [Real.rpow_neg hμ.le, Real.rpow_natCast, inv_pow]
  rw [hrpow, ← integral_finsetSum _ fun l _ => hint l, ← integral_const_mul]
  refine integral_mono_of_nonneg (Eventually.of_forall fun x => norm_nonneg _)
    ((integrable_finsetSum _ fun l _ => hint l).const_mul _) (Eventually.of_forall fun x => ?_)
  simp only [norm_mul, osc_norm_oscE, one_mul]
  have := hb x
  rw [norm_iteratedFDeriv_zero] at this
  simpa [Finset.sum_apply] using this


/-! ### The `|m|²` trick -/

section Square

/-- `|∫ f|² ≤ ∫_w |∫_t f(t) conj f(t - w) dt| dw` for continuous compactly supported `f`. -/
lemma osc_norm_integral_sq_le {f : EuclideanSpace ℝ (Fin n) → ℂ} (hf : Continuous f)
    (hfc : HasCompactSupport f) :
    ‖∫ x, f x‖ ^ 2 ≤ ∫ w, ‖∫ t, f t * conj (f (t - w))‖ := by
  set F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n) → ℂ :=
    fun t w => f t * conj (f (t - w)) with hF
  have hFc : Continuous (Function.uncurry F) := by
    simp only [hF]
    exact (hf.comp continuous_fst).mul
      (Complex.continuous_conj.comp (hf.comp (continuous_fst.sub continuous_snd)))
  have hFs : HasCompactSupport (Function.uncurry F) := by
    refine HasCompactSupport.intro ((hfc.prod hfc).image
      (continuous_fst.prodMk (continuous_fst.sub continuous_snd))) ?_
    rintro ⟨t, w⟩ hp
    by_contra h
    apply hp
    have h1 : f t ≠ 0 := fun h' => h (by simp [hF, h'])
    have h2 : f (t - w) ≠ 0 := fun h' => h (by simp [hF, h'])
    exact ⟨(t, t - w), ⟨subset_tsupport _ h1, subset_tsupport _ h2⟩, by simp⟩
  have hFi : Integrable (Function.uncurry F) (volume.prod volume) :=
    hFc.integrable_of_hasCompactSupport hFs
  have heq : (∫ x, f x) * conj (∫ x, f x) = ∫ w, ∫ t, F t w := by
    rw [← integral_integral_swap hFi, ← integral_conj, ← integral_mul_const]
    refine integral_congr_ae (Eventually.of_forall fun t => ?_)
    simp only [hF]
    rw [integral_const_mul]
    congr 1
    exact (integral_sub_left_eq_self (fun s => conj (f s)) volume t).symm
  calc ‖∫ x, f x‖ ^ 2 = ‖(∫ x, f x) * conj (∫ x, f x)‖ := by
        rw [norm_mul, Complex.norm_conj, sq]
    _ = ‖∫ w, ∫ t, F t w‖ := by rw [heq]
    _ ≤ ∫ w, ‖∫ t, F t w‖ := norm_integral_le_integral_norm _

/-- Elementary: a bound `min(X₀, X₁ s^{-(n+1)})` is dominated by `2^{n+1}(X₀+X₁)(1+s)^{-(n+1)}`. -/
lemma osc_elem_bound (m : ℕ) {s y X₀ X₁ : ℝ} (hs : 0 ≤ s) (hX₀ : 0 ≤ X₀) (hX₁ : 0 ≤ X₁)
    (h0 : y ≤ X₀) (h1 : 1 < s → y ≤ X₁ * (s ^ m)⁻¹) :
    y ≤ 2 ^ m * (X₀ + X₁) * ((1 + s) ^ m)⁻¹ := by
  rcases le_or_gt s 1 with hs1 | hs1
  · have : (1 + s) ^ m ≤ 2 ^ m := pow_le_pow_left₀ (by linarith) (by linarith) m
    calc y ≤ X₀ := h0
      _ ≤ 2 ^ m * (X₀ + X₁) * ((1 + s) ^ m)⁻¹ := by
        rw [le_mul_inv_iff₀ (by positivity)]
        nlinarith [pow_pos (show (0 : ℝ) < 1 + s by linarith) m]
  · have hs0 : 0 < s := by linarith
    have : (1 + s) ^ m ≤ 2 ^ m * s ^ m := by
      rw [← mul_pow]; exact pow_le_pow_left₀ (by linarith) (by linarith) m
    calc y ≤ X₁ * (s ^ m)⁻¹ := h1 hs1
      _ ≤ 2 ^ m * (X₀ + X₁) * ((1 + s) ^ m)⁻¹ := by
        rw [mul_inv_le_iff₀ (by positivity), mul_assoc, mul_comm, mul_assoc,
          inv_mul_eq_div, le_div_iff₀ (by positivity)]
        have hsp := pow_pos hs0 m
        nlinarith [pow_pos (show (0 : ℝ) < 1 + s by linarith) m]

/-- `∫ (1 + λ|w|)^{-(n+1)} dw = λ^{-n} ∫ (1 + |u|)^{-(n+1)} du`, and the integrand is integrable. -/
lemma osc_integral_decay {lam : ℝ} (hlam : 0 < lam) :
    Integrable (fun w : EuclideanSpace ℝ (Fin n) => ((1 + lam * ‖w‖) ^ (n + 1))⁻¹) ∧
    ∫ w : EuclideanSpace ℝ (Fin n), ((1 + lam * ‖w‖) ^ (n + 1))⁻¹ =
      (lam ^ n)⁻¹ * ∫ u : EuclideanSpace ℝ (Fin n), ((1 + ‖u‖) ^ (n + 1))⁻¹ := by
  set g : EuclideanSpace ℝ (Fin n) → ℝ := fun u => ((1 + ‖u‖) ^ (n + 1))⁻¹ with hg
  have hgi : Integrable g := by
    have := integrable_one_add_norm (E := EuclideanSpace ℝ (Fin n)) (μ := volume)
      (r := ((n + 1 : ℕ) : ℝ)) (by simp)
    refine this.congr (Eventually.of_forall fun u => ?_)
    simp only [hg]
    rw [Real.rpow_neg (by positivity), Real.rpow_natCast]
  have hcomp : (fun w : EuclideanSpace ℝ (Fin n) => ((1 + lam * ‖w‖) ^ (n + 1))⁻¹) =
      fun w => g (lam • w) := by
    funext w; simp [hg, norm_smul, abs_of_pos hlam]
  rw [hcomp]
  refine ⟨hgi.comp_smul hlam.ne', ?_⟩
  rw [Measure.integral_comp_smul, finrank_euclideanSpace_fin, abs_of_pos (by positivity),
    smul_eq_mul]

/-- Derivative bounds for the amplitude `a(t) conj a(t - w)`. -/
lemma osc_norm_iteratedFDeriv_b_le {a : EuclideanSpace ℝ (Fin n) → ℂ} (ha : ContDiff ℝ ∞ a)
    {m : ℕ} {A : ℝ} (hA : ∀ j, j ≤ m → ∀ x, ‖iteratedFDeriv ℝ j a x‖ ≤ A)
    (w : EuclideanSpace ℝ (Fin n)) {k : ℕ} (hk : k ≤ m) (t : EuclideanSpace ℝ (Fin n)) :
    ‖iteratedFDeriv ℝ k (fun t => a t * conj (a (t - w))) t‖ ≤ 2 ^ k * A ^ 2 := by
  have hA0 : 0 ≤ A := le_trans (norm_nonneg _) (hA 0 (Nat.zero_le _) t)
  have hcw : ContDiff ℝ ∞ (fun t => conj (a (t - w))) :=
    Complex.conjCLE.contDiff.comp (ha.comp (contDiff_id.sub contDiff_const))
  have hconj : ∀ j, ‖iteratedFDeriv ℝ j (fun t => conj (a (t - w))) t‖ =
      ‖iteratedFDeriv ℝ j a (t - w)‖ := by
    intro j
    rw [show (fun t => conj (a (t - w))) = fun t => (Complex.conjLIE ∘ a) (t - w) from rfl,
      iteratedFDeriv_comp_sub, LinearIsometryEquiv.norm_iteratedFDeriv_comp_left]
  refine (norm_iteratedFDeriv_mul_le ha hcw t (n := k) (by simp)).trans ?_
  calc ∑ i ∈ Finset.range (k + 1), (k.choose i : ℝ) * ‖iteratedFDeriv ℝ i a t‖ *
        ‖iteratedFDeriv ℝ (k - i) (fun t => conj (a (t - w))) t‖
      ≤ ∑ i ∈ Finset.range (k + 1), (k.choose i : ℝ) * A * A := by
        refine Finset.sum_le_sum fun i hi => ?_
        have hi' := Finset.mem_range.1 hi
        rw [hconj]
        gcongr
        · exact hA i (by omega) t
        · exact hA _ (by omega) _
    _ = 2 ^ k * A ^ 2 := by
        rw [← Finset.sum_mul, ← Finset.sum_mul]
        have := Nat.sum_range_choose k
        rw [show (∑ i ∈ Finset.range (k + 1), (k.choose i : ℝ)) = 2 ^ k by exact_mod_cast this]
        ring

lemma osc_integral_norm_iteratedFDeriv_b_le {a : EuclideanSpace ℝ (Fin n) → ℂ}
    (ha : ContDiff ℝ ∞ a) (hac : HasCompactSupport a) {R : ℝ}
    (hR : volume.real (tsupport a) ≤ R)
    {m : ℕ} {A : ℝ} (hA : ∀ j, j ≤ m → ∀ x, ‖iteratedFDeriv ℝ j a x‖ ≤ A)
    (w : EuclideanSpace ℝ (Fin n)) {k : ℕ} (hk : k ≤ m) :
    ∫ t, ‖iteratedFDeriv ℝ k (fun t => a t * conj (a (t - w))) t‖ ≤ 2 ^ k * A ^ 2 * R := by
  have hvan : ∀ t, t ∉ tsupport a →
      ‖iteratedFDeriv ℝ k (fun t => a t * conj (a (t - w))) t‖ = 0 := by
    intro t ht
    rw [norm_eq_zero]
    exact Function.notMem_support.1 fun h => ht (tsupport_mul_subset_left
      (support_iteratedFDeriv_subset k h))
  rw [← setIntegral_eq_integral_of_forall_compl_eq_zero hvan]
  refine (le_abs_self _).trans ?_
  rw [← Real.norm_eq_abs]
  refine (norm_setIntegral_le_of_norm_le_const (C := 2 ^ k * A ^ 2)
    hac.isCompact.measure_lt_top (fun t _ => ?_)).trans ?_
  · rw [norm_norm]; exact osc_norm_iteratedFDeriv_b_le ha hA w hk t
  · gcongr

/-- The phase `ψ_w(t) = Φ(t) - Φ(t - w)` of the `|m|²` trick: smoothness, lower bound for the
gradient (from strong monotonicity) and upper bounds for the higher derivatives. -/
lemma osc_phase_facts {Φ : EuclideanSpace ℝ (Fin n) → ℝ} {K : Set (EuclideanSpace ℝ (Fin n))}
    {δ lam c B : ℝ} (hδ : 0 < δ) (hlam : 0 < lam) (m : ℕ)
    (hΦ : ContDiffOn ℝ ∞ Φ (thickening δ K))
    (hB : ∀ x ∈ thickening δ K, ∀ k, 2 ≤ k → k ≤ m + 1 → ‖iteratedFDeriv ℝ k Φ x‖ ≤ B * lam)
    (hmono : ∀ x ∈ K, ∀ y ∈ K, c * lam * ‖x - y‖ ^ 2 ≤ (fderiv ℝ Φ x - fderiv ℝ Φ y) (x - y))
    (w : EuclideanSpace ℝ (Fin n)) :
    IsOpen (thickening δ K ∩ (fun t => t - w) ⁻¹' thickening δ K) ∧
    ContDiffOn ℝ ∞ (fun t => Φ t - Φ (t - w))
      (thickening δ K ∩ (fun t => t - w) ⁻¹' thickening δ K) ∧
    (∀ t ∈ K, t - w ∈ K → c * lam * ‖w‖ ≤ ‖fderiv ℝ (fun t => Φ t - Φ (t - w)) t‖) ∧
    (∀ t ∈ K, t - w ∈ K → ∀ k, 2 ≤ k → k ≤ m →
      ‖iteratedFDeriv ℝ k (fun t => Φ t - Φ (t - w)) t‖ ≤ (|B| + 2 * |B| / δ) * lam * ‖w‖) := by
  have hT : IsOpen (thickening δ K) := isOpen_thickening
  have hKT : K ⊆ thickening δ K := self_subset_thickening hδ K
  have hsub : Continuous fun t : EuclideanSpace ℝ (Fin n) => t - w :=
    continuous_id.sub continuous_const
  have hcd : ∀ x ∈ thickening δ K, ContDiffAt ℝ ∞ Φ x := fun x hx =>
    hΦ.contDiffAt (hT.mem_nhds hx)
  have hcd' : ∀ t, t - w ∈ thickening δ K → ContDiffAt ℝ ∞ (fun t => Φ (t - w)) t := fun t ht =>
    (hcd _ ht).comp t (contDiff_id.sub contDiff_const).contDiffAt
  refine ⟨hT.inter (hT.preimage hsub), ?_, ?_, ?_⟩
  · exact (hΦ.mono inter_subset_left).sub
      (hΦ.comp (contDiff_id.sub contDiff_const).contDiffOn (fun t ht => ht.2))
  · intro t ht htw
    rcases eq_or_ne w 0 with rfl | hw
    · simp
    have hfd : fderiv ℝ (fun t => Φ t - Φ (t - w)) t = fderiv ℝ Φ t - fderiv ℝ Φ (t - w) := by
      rw [fderiv_fun_sub ((hcd t (hKT ht)).differentiableAt (by simp))
        ((hcd' t (hKT htw)).differentiableAt (by simp)), fderiv_comp_sub]
    rw [hfd]
    have h1 := hmono t ht (t - w) htw
    rw [sub_sub_cancel] at h1
    have h2 := (le_abs_self _).trans
      (((fderiv ℝ Φ t - fderiv ℝ Φ (t - w)).le_opNorm w).trans_eq' (Real.norm_eq_abs _).symm)
    have hw0 : 0 < ‖w‖ := norm_pos_iff.2 hw
    have : c * lam * ‖w‖ * ‖w‖ ≤ ‖fderiv ℝ Φ t - fderiv ℝ Φ (t - w)‖ * ‖w‖ := by nlinarith
    exact le_of_mul_le_mul_right this hw0
  · intro t ht htw k hk2 hkm
    have hiter : iteratedFDeriv ℝ k (fun t => Φ t - Φ (t - w)) t =
        iteratedFDeriv ℝ k Φ t - iteratedFDeriv ℝ k Φ (t - w) := by
      rw [show (fun t => Φ t - Φ (t - w)) = Φ - fun t => Φ (t - w) from rfl,
        iteratedFDeriv_sub_apply ((hcd t (hKT ht)).of_le (by simp))
        ((hcd' t (hKT htw)).of_le (by simp)), iteratedFDeriv_comp_sub]
    rw [hiter]
    have hB' : ∀ x ∈ thickening δ K, ∀ j, 2 ≤ j → j ≤ m + 1 →
        ‖iteratedFDeriv ℝ j Φ x‖ ≤ |B| * lam := fun x hx j h1 h2 =>
      (hB x hx j h1 h2).trans (by gcongr; exact le_abs_self B)
    have hB0 : 0 ≤ |B| * lam := by positivity
    rcases lt_or_ge ‖w‖ δ with hwδ | hwδ
    · have hball : ball t δ ⊆ thickening δ K := ball_subset_thickening ht δ
      have hmvt := (convex_ball t δ).norm_image_sub_le_of_norm_fderiv_le
        (f := iteratedFDeriv ℝ k Φ) (C := |B| * lam)
        (fun y hy => (hcd y (hball hy)).differentiableAt_iteratedFDeriv
          (by exact_mod_cast ENat.natCast_lt_top k))
        (fun y hy => by
          rw [norm_fderiv_iteratedFDeriv]; exact hB' y (hball hy) (k + 1) (by omega) (by omega))
        (mem_ball_self hδ) (show t - w ∈ ball t δ by simpa [dist_eq_norm] using hwδ)
      rw [norm_sub_rev, sub_sub_cancel_left, norm_neg] at hmvt
      calc ‖iteratedFDeriv ℝ k Φ t - iteratedFDeriv ℝ k Φ (t - w)‖ ≤ |B| * lam * ‖w‖ := hmvt
        _ ≤ (|B| + 2 * |B| / δ) * lam * ‖w‖ := by
          gcongr
          have : 0 ≤ 2 * |B| / δ := by positivity
          linarith
    · calc ‖iteratedFDeriv ℝ k Φ t - iteratedFDeriv ℝ k Φ (t - w)‖
          ≤ ‖iteratedFDeriv ℝ k Φ t‖ + ‖iteratedFDeriv ℝ k Φ (t - w)‖ := norm_sub_le _ _
        _ ≤ |B| * lam + |B| * lam := by
          gcongr
          · exact hB' t (hKT ht) k hk2 (by omega)
          · exact hB' _ (hKT htw) k hk2 (by omega)
        _ ≤ 2 * |B| / δ * lam * ‖w‖ := by
          rw [div_mul_eq_mul_div, div_mul_eq_mul_div, le_div_iff₀ hδ]
          have : 0 ≤ |B| * lam := hB0
          nlinarith
        _ ≤ (|B| + 2 * |B| / δ) * lam * ‖w‖ := by
          gcongr
          linarith [abs_nonneg B]

lemma osc_tsupport_conj_sub_subset (a : EuclideanSpace ℝ (Fin n) → ℂ)
    (w : EuclideanSpace ℝ (Fin n)) :
    tsupport (fun t => conj (a (t - w))) ⊆ (fun t => t - w) ⁻¹' tsupport a :=
  closure_minimal (fun t ht => subset_tsupport _ (fun h => ht (by simp [h])))
    (isClosed_tsupport _ |>.preimage (continuous_id.sub continuous_const))

lemma osc_conj_oscE (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (s : EuclideanSpace ℝ (Fin n)) :
    conj (oscE Φ s) = Complex.exp (-(Complex.I * Φ s)) := by
  simp [oscE, ← Complex.exp_conj]

/-- **Oscillatory integrals with strongly convex phase** (sharp decay `λ^{-n/2}`, see
E. M. Stein, *Harmonic Analysis* (1993), Ch. VIII, §2). Let `K = tsupport a` and let `K_δ` be its
open `δ`-neighbourhood. Suppose `Φ` is smooth on `K_δ` with `‖D^k Φ‖ ≤ B λ` on `K_δ` for
`2 ≤ k ≤ n + 3`, and that `∇Φ` is strongly monotone on `K`:
`⟪∇Φ(x) - ∇Φ(y), x - y⟫ ≥ c λ ‖x - y‖²` (written as `(DΦ(x) - DΦ(y))(x - y)`). If the derivatives
of `a` up to order `n + 1` are bounded by `A` and `|K| ≤ R`, then `|∫ e^{iΦ} a| ≤ C λ^{-n/2}`,
where `C` depends only on `n, c, δ, B, A, R`. -/
theorem norm_integral_exp_mul_le_of_strongMono (n : ℕ) {c δ : ℝ} (hc : 0 < c) (hδ : 0 < δ)
    (B A R : ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (Φ : EuclideanSpace ℝ (Fin n) → ℝ) (a : EuclideanSpace ℝ (Fin n) → ℂ)
      (lam : ℝ), 0 < lam → ContDiff ℝ ∞ a → HasCompactSupport a →
      volume.real (tsupport a) ≤ R →
      (∀ j, j ≤ n + 1 → ∀ x, ‖iteratedFDeriv ℝ j a x‖ ≤ A) →
      ContDiffOn ℝ ∞ Φ (thickening δ (tsupport a)) →
      (∀ x ∈ thickening δ (tsupport a), ∀ k, 2 ≤ k → k ≤ n + 3 →
        ‖iteratedFDeriv ℝ k Φ x‖ ≤ B * lam) →
      (∀ x ∈ tsupport a, ∀ y ∈ tsupport a,
        c * lam * ‖x - y‖ ^ 2 ≤ (fderiv ℝ Φ x - fderiv ℝ Φ y) (x - y)) →
      ‖∫ x, Complex.exp (Complex.I * Φ x) * a x‖ ≤ C * lam ^ (-(n : ℝ) / 2) := by
  set B' := |B| + 2 * |B| / δ with hB'
  obtain ⟨CA, hCA0, hCA⟩ := norm_integral_exp_mul_le_of_nonstationary n (n + 1) (B' / c)
  set X₀ := |A| ^ 2 * |R| with hX₀
  set S := ((n + 2 : ℕ) : ℝ) * 2 ^ (n + 1) * |A| ^ 2 * |R| with hS
  set X₁ := CA * (c ^ (n + 1))⁻¹ * S with hX₁
  set C₂ := 2 ^ (n + 1) * (X₀ + X₁) with hC₂
  set J₀ := ∫ u : EuclideanSpace ℝ (Fin n), ((1 + ‖u‖) ^ (n + 1))⁻¹ with hJ₀
  have hX₀0 : 0 ≤ X₀ := by positivity
  have hX₁0 : 0 ≤ X₁ := by positivity
  have hC₂0 : 0 ≤ C₂ := by positivity
  have hJ₀0 : 0 ≤ J₀ := integral_nonneg fun u => by positivity
  refine ⟨Real.sqrt (C₂ * J₀), Real.sqrt_nonneg _, ?_⟩
  intro Φ a lam hlam ha hac hR hA hΦ hB hmono
  set K := tsupport a with hK
  set f : EuclideanSpace ℝ (Fin n) → ℂ := fun t => oscE Φ t * a t with hfdef
  have hf : Continuous f := osc_continuous_mul_of_tsupport isOpen_thickening
    ((osc_contDiffOn_oscE hΦ).continuousOn) ha.continuous (self_subset_thickening hδ _)
  have hfc : HasCompactSupport f := hac.mul_left
  have hsq := osc_norm_integral_sq_le hf hfc
  have hA0 : 0 ≤ A := le_trans (norm_nonneg _) (hA 0 (Nat.zero_le _) 0)
  have hR0 : 0 ≤ R := le_trans measureReal_nonneg hR
  -- the bound for the inner integrals
  have hI : ∀ w, ‖∫ t, f t * conj (f (t - w))‖ ≤ C₂ * ((1 + lam * ‖w‖) ^ (n + 1))⁻¹ := by
    intro w
    set b : EuclideanSpace ℝ (Fin n) → ℂ := fun t => a t * conj (a (t - w)) with hb
    set ψ : EuclideanSpace ℝ (Fin n) → ℝ := fun t => Φ t - Φ (t - w) with hψ
    have hrw : (fun t => f t * conj (f (t - w))) = fun t => oscE ψ t * b t := by
      funext t
      simp only [hfdef, hb, hψ, map_mul, osc_conj_oscE]
      have : oscE (fun t => Φ t - Φ (t - w)) t =
          oscE Φ t * Complex.exp (-(Complex.I * Φ (t - w))) := by
        simp only [oscE]
        rw [← Complex.exp_add]
        congr 1; push_cast; ring
      rw [this]; ring
    rw [hrw]
    have hbs : ContDiff ℝ ∞ b :=
      ha.mul (Complex.conjCLE.contDiff.comp (ha.comp (contDiff_id.sub contDiff_const)))
    have hbc : HasCompactSupport b := hac.mul_right
    have hbint : ∀ k, k ≤ n + 1 → ∫ t, ‖iteratedFDeriv ℝ k b t‖ ≤ 2 ^ k * A ^ 2 * R :=
      fun k hk => osc_integral_norm_iteratedFDeriv_b_le ha hac hR hA w hk
    have h0 : ‖∫ t, oscE ψ t * b t‖ ≤ X₀ := by
      refine (norm_integral_le_integral_norm _).trans ?_
      have := hbint 0 (Nat.zero_le _)
      simp only [norm_iteratedFDeriv_zero, pow_zero, one_mul] at this
      simp only [norm_mul, osc_norm_oscE, one_mul]
      refine this.trans ?_
      rw [hX₀, sq_abs, abs_of_nonneg hR0]
    have h1 : 1 < lam * ‖w‖ → ‖∫ t, oscE ψ t * b t‖ ≤ X₁ * ((lam * ‖w‖) ^ (n + 1))⁻¹ := by
      intro hlw
      have hw : 0 < ‖w‖ := by
        by_contra h; push Not at h
        have : ‖w‖ = 0 := le_antisymm h (norm_nonneg _)
        rw [this, mul_zero] at hlw; linarith
      obtain ⟨hUo, hψs, hlow, hup⟩ := osc_phase_facts hδ hlam (n + 2) hΦ hB hmono w
      have hmem : ∀ t ∈ tsupport b, t ∈ K ∧ t - w ∈ K := fun t ht =>
        ⟨tsupport_mul_subset_left (f := a) (g := fun t => conj (a (t - w))) ht,
          osc_tsupport_conj_sub_subset a w
            (tsupport_mul_subset_right (f := a) (g := fun t => conj (a (t - w))) ht)⟩
      have hbU : tsupport b ⊆ thickening δ K ∩ (fun t => t - w) ⁻¹' thickening δ K :=
        fun t ht => ⟨self_subset_thickening hδ _ (hmem t ht).1,
          self_subset_thickening hδ K (hmem t ht).2⟩
      have hμ : 0 < c * lam * ‖w‖ := by positivity
      have hmain := hCA ψ b _ (c * lam * ‖w‖) hUo hψs hbs hbc hbU hμ
        (fun t ht => hlow t (hmem t ht).1 (hmem t ht).2)
        (fun t ht k hk2 hk => by
          refine (hup t (hmem t ht).1 (hmem t ht).2 k hk2 (by omega)).trans_eq ?_
          rw [hB']; field_simp)
      change ‖∫ t, oscE ψ t * b t‖ ≤ _ at hmain
      refine hmain.trans ?_
      have hsum : ∑ k ∈ Finset.range (n + 1 + 1), ∫ t, ‖iteratedFDeriv ℝ k b t‖ ≤ S := by
        calc ∑ k ∈ Finset.range (n + 1 + 1), ∫ t, ‖iteratedFDeriv ℝ k b t‖
            ≤ ∑ _k ∈ Finset.range (n + 1 + 1), (2 : ℝ) ^ (n + 1) * |A| ^ 2 * |R| := by
              refine Finset.sum_le_sum fun k hk => ?_
              have hk' := Finset.mem_range.1 hk
              refine (hbint k (by omega)).trans ?_
              rw [sq_abs, abs_of_nonneg hR0]
              gcongr
              · norm_num
              · omega
          _ = S := by simp [hS]; ring
      have hrp : (c * lam * ‖w‖) ^ (-((n + 1 : ℕ) : ℝ)) =
          (c ^ (n + 1))⁻¹ * ((lam * ‖w‖) ^ (n + 1))⁻¹ := by
        rw [Real.rpow_neg hμ.le, Real.rpow_natCast, mul_assoc, mul_pow, mul_inv]
      rw [hrp, hX₁]
      have hS0 : 0 ≤ ∑ k ∈ Finset.range (n + 1 + 1), ∫ t, ‖iteratedFDeriv ℝ k b t‖ :=
        Finset.sum_nonneg fun k _ => integral_nonneg fun t => norm_nonneg _
      calc CA * ((c ^ (n + 1))⁻¹ * ((lam * ‖w‖) ^ (n + 1))⁻¹) *
            ∑ k ∈ Finset.range (n + 1 + 1), ∫ t, ‖iteratedFDeriv ℝ k b t‖
          ≤ CA * ((c ^ (n + 1))⁻¹ * ((lam * ‖w‖) ^ (n + 1))⁻¹) * S := by gcongr
        _ = CA * (c ^ (n + 1))⁻¹ * S * ((lam * ‖w‖) ^ (n + 1))⁻¹ := by ring
    exact osc_elem_bound (n + 1) (by positivity) hX₀0 hX₁0 h0 h1
  obtain ⟨hint, heq⟩ := osc_integral_decay (n := n) hlam
  have hsq2 : ‖∫ x, f x‖ ^ 2 ≤ C₂ * J₀ * lam ^ (-(n : ℝ)) := by
    refine hsq.trans ?_
    calc ∫ w, ‖∫ t, f t * conj (f (t - w))‖
        ≤ ∫ w, C₂ * ((1 + lam * ‖w‖) ^ (n + 1))⁻¹ :=
          integral_mono_of_nonneg (Eventually.of_forall fun w => norm_nonneg _)
            (hint.const_mul _) (Eventually.of_forall hI)
      _ = C₂ * J₀ * lam ^ (-(n : ℝ)) := by
          rw [integral_const_mul, heq, Real.rpow_neg hlam.le, Real.rpow_natCast]; ring
  change ‖∫ x, f x‖ ≤ _
  have hlp : 0 ≤ lam ^ (-(n : ℝ) / 2) := by positivity
  rw [← Real.sqrt_sq (norm_nonneg _)]
  calc Real.sqrt (‖∫ x, f x‖ ^ 2) ≤ Real.sqrt (C₂ * J₀ * lam ^ (-(n : ℝ))) :=
        Real.sqrt_le_sqrt hsq2
    _ = Real.sqrt (C₂ * J₀) * lam ^ (-(n : ℝ) / 2) := by
        rw [Real.sqrt_mul (by positivity), Real.sqrt_eq_rpow (lam ^ _), ← Real.rpow_mul hlam.le]
        congr 2; ring

end Square

/-! ### The radial phase `‖t‖^α` on the annulus `1/2 ≤ ‖t‖ ≤ 2` -/

section Radial

open scoped RealInnerProductSpace

lemma osc_rpow_lower {r : ℝ} (hr1 : 1 / 2 ≤ r) (hr2 : r ≤ 2) (β : ℝ) :
    (2 : ℝ) ^ (-|β|) ≤ r ^ β := by
  rw [Real.rpow_def_of_pos (by norm_num), Real.rpow_def_of_pos (by linarith)]
  apply Real.exp_le_exp.2
  have h1 : Real.log r ≤ Real.log 2 := Real.log_le_log (by linarith) hr2
  have h2 : -Real.log 2 ≤ Real.log r := by
    rw [← Real.log_inv]; exact Real.log_le_log (by norm_num) (by linarith)
  have h3 := Real.log_pos one_lt_two
  rcases abs_cases β with ⟨hb, _⟩ | ⟨hb, _⟩ <;> rw [hb] <;> nlinarith

lemma osc_slope {α : ℝ} (hα : 1 < α) {r s : ℝ} (hr : r ∈ Icc (1 / 2 : ℝ) 2)
    (hs : s ∈ Icc (1 / 2 : ℝ) 2) :
    (α - 1) * 2 ^ (-|α - 2|) * (r - s) ^ 2 ≤ (r - s) * (r ^ (α - 1) - s ^ (α - 1)) := by
  have hpos : ∀ x ∈ Icc (1 / 2 : ℝ) 2, x ≠ 0 := fun x hx => by linarith [hx.1]
  have key := (convex_Icc (1 / 2 : ℝ) 2).mul_sub_le_image_sub_of_le_deriv
    (f := fun x => x ^ (α - 1)) (C := (α - 1) * 2 ^ (-|α - 2|))
    (fun x hx => (Real.continuousAt_rpow_const x (α - 1)
      (Or.inl (hpos x hx))).continuousWithinAt)
    (fun x hx => by
      rw [interior_Icc] at hx
      exact (Real.hasDerivAt_rpow_const (Or.inl (hpos x (Ioo_subset_Icc_self hx)))
        ).differentiableAt.differentiableWithinAt)
    (fun x hx => by
      rw [interior_Icc] at hx
      rw [(Real.hasDerivAt_rpow_const (Or.inl (hpos x (Ioo_subset_Icc_self hx)))).deriv,
        show α - 1 - 1 = α - 2 by ring]
      exact mul_le_mul_of_nonneg_left (osc_rpow_lower hx.1.le hx.2.le _) (by linarith))
  rcases le_total s r with h | h
  · have := key s hs r hr h
    have h0 : 0 ≤ r - s := by linarith
    nlinarith
  · have := key r hr s hs h
    have h0 : 0 ≤ s - r := by linarith
    nlinarith

lemma osc_fderiv_rad {α : ℝ} {x : EuclideanSpace ℝ (Fin n)} (hx : x ≠ 0)
    (v : EuclideanSpace ℝ (Fin n)) :
    fderiv ℝ (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) x v = α * ‖x‖ ^ (α - 2) * ⟪x, v⟫ := by
  have heq : (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) =
      fun t => (‖t‖ ^ 2) ^ (α / 2) := by
    funext t
    rw [← Real.rpow_two, ← Real.rpow_mul (norm_nonneg _)]
    congr 1; ring
  have hx2 : ‖x‖ ^ 2 ≠ 0 := by positivity
  have h1 := ((hasStrictFDerivAt_norm_sq x).hasFDerivAt).rpow_const (p := α / 2) (Or.inl hx2)
  rw [heq, h1.fderiv]
  simp only [smul_apply, innerSL_apply_apply, smul_eq_mul]
  rw [← Real.rpow_two, ← Real.rpow_mul (norm_nonneg _), show 2 * (α / 2 - 1) = α - 2 by ring]
  ring

lemma osc_rad_mono {α : ℝ} (hα : 1 < α) {x y : EuclideanSpace ℝ (Fin n)}
    (hx : 1 / 2 ≤ ‖x‖ ∧ ‖x‖ ≤ 2) (hy : 1 / 2 ≤ ‖y‖ ∧ ‖y‖ ≤ 2) :
    α * 2 ^ (-|α - 2|) * min 1 (α - 1) * ‖x - y‖ ^ 2 ≤
      (fderiv ℝ (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) x -
        fderiv ℝ (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) y) (x - y) := by
  have hx0 : x ≠ 0 := fun h => by rw [h, norm_zero] at hx; linarith [hx.1]
  have hy0 : y ≠ 0 := fun h => by rw [h, norm_zero] at hy; linarith [hy.1]
  rw [sub_apply, osc_fderiv_rad hx0, osc_fderiv_rad hy0]
  set r := ‖x‖ with hr
  set s := ‖y‖ with hs
  set d := ‖x - y‖ with hd
  set p := r ^ (α - 2) with hp
  set q := s ^ (α - 2) with hq
  set ε : ℝ := 2 ^ (-|α - 2|) with hε
  have hε0 : 0 < ε := by positivity
  have hpε : ε ≤ p := osc_rpow_lower hx.1 hx.2 _
  have hqε : ε ≤ q := osc_rpow_lower hy.1 hy.2 _
  have hrp : r * p = r ^ (α - 1) := by
    rw [hp, mul_comm, ← Real.rpow_add_one (by positivity)]; congr 1; ring
  have hsq : s * q = s ^ (α - 1) := by
    rw [hq, mul_comm, ← Real.rpow_add_one (by positivity)]; congr 1; ring
  have hslope := osc_slope hα ⟨hx.1, hx.2⟩ ⟨hy.1, hy.2⟩
  rw [← hrp, ← hsq, ← hε] at hslope
  have hxx : ⟪x, x - y⟫ = (r ^ 2 - s ^ 2 + d ^ 2) / 2 := by
    rw [hd, norm_sub_sq_real, inner_sub_right, real_inner_self_eq_norm_sq]; ring
  have hyy : ⟪y, x - y⟫ = (r ^ 2 - s ^ 2 - d ^ 2) / 2 := by
    rw [hd, norm_sub_sq_real, inner_sub_right, real_inner_self_eq_norm_sq, real_inner_comm]; ring
  rw [hxx, hyy]
  have hrs : (r - s) ^ 2 ≤ d ^ 2 := by
    rw [hd, hr, hs, ← sq_abs]
    exact pow_le_pow_left₀ (abs_nonneg _) (abs_norm_sub_norm_le x y) 2
  have hm1 : min 1 (α - 1) ≤ 1 := min_le_left _ _
  have hm2 : min 1 (α - 1) ≤ α - 1 := min_le_right _ _
  have hm0 : 0 < min 1 (α - 1) := lt_min one_pos (by linarith)
  have hid : α * p * ((r ^ 2 - s ^ 2 + d ^ 2) / 2) - α * q * ((r ^ 2 - s ^ 2 - d ^ 2) / 2) =
      α / 2 * ((p + q) * (d ^ 2 - (r - s) ^ 2) + 2 * ((r - s) * (r * p - s * q))) := by ring
  rw [hid]
  have h1 : 2 * ε * min 1 (α - 1) * (d ^ 2 - (r - s) ^ 2) ≤ (p + q) * (d ^ 2 - (r - s) ^ 2) := by
    apply mul_le_mul_of_nonneg_right _ (by linarith)
    nlinarith
  have h2 : 2 * ε * min 1 (α - 1) * (r - s) ^ 2 ≤ 2 * ((r - s) * (r * p - s * q)) := by
    have : ε * min 1 (α - 1) * (r - s) ^ 2 ≤ (α - 1) * ε * (r - s) ^ 2 := by
      have := sq_nonneg (r - s)
      nlinarith [mul_nonneg (mul_nonneg (sub_nonneg.2 hm2) hε0.le) this]
    linarith
  have h3 : α * ε * min 1 (α - 1) * d ^ 2 =
      α / 2 * (2 * ε * min 1 (α - 1) * (d ^ 2 - (r - s) ^ 2) +
        2 * ε * min 1 (α - 1) * (r - s) ^ 2) := by ring
  rw [h3]
  exact mul_le_mul_of_nonneg_left (add_le_add h1 h2) (by linarith)

lemma osc_contDiffOn_rad (α : ℝ) :
    ContDiffOn ℝ ∞ (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) {t | t ≠ 0} := fun _ hx =>
  ((contDiffAt_norm ℝ hx).rpow_const_of_ne (norm_ne_zero_iff.2 hx)).contDiffWithinAt

/-- The derivatives of `‖t‖^α` are bounded on the shell `1/4 ≤ ‖t‖ ≤ 9/4`. -/
lemma osc_rad_bound (α : ℝ) (m : ℕ) :
    ∃ G : ℝ, 0 ≤ G ∧ ∀ k, k ≤ m → ∀ t : EuclideanSpace ℝ (Fin n), 1 / 4 ≤ ‖t‖ → ‖t‖ ≤ 9 / 4 →
      ‖iteratedFDeriv ℝ k (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) t‖ ≤ G := by
  set O : Set (EuclideanSpace ℝ (Fin n)) := {t | t ≠ 0} with hO
  have hOo : IsOpen O := isOpen_ne
  set S : Set (EuclideanSpace ℝ (Fin n)) := closedBall 0 (9 / 4) ∩ {t | 1 / 4 ≤ ‖t‖} with hS
  have hSc : IsCompact S :=
    (isCompact_closedBall _ _).inter_right (isClosed_le continuous_const continuous_norm)
  have hSO : S ⊆ O := fun t ht h => by
    have := ht.2; simp only [Set.mem_ofPred_eq, h, norm_zero] at this; linarith
  have hcont : ContinuousOn (fun t => ∑ k ∈ Finset.range (m + 1),
      ‖iteratedFDeriv ℝ k (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) t‖) O := by
    refine continuousOn_finsetSum _ fun k _ => ?_
    refine (((osc_contDiffOn_rad α).continuousOn_iteratedFDerivWithin (m := k) (by simp)
      hOo.uniqueDiffOn).congr fun t ht => ?_).norm
    exact (iteratedFDerivWithin_of_isOpen k hOo ht).symm
  obtain ⟨G, hG⟩ := hSc.exists_bound_of_continuousOn (hcont.mono hSO)
  refine ⟨max G 0, le_max_right _ _, fun k hk t ht1 ht2 => ?_⟩
  have htS : t ∈ S := ⟨by simpa using ht2, ht1⟩
  have h1 := hG t htS
  rw [Real.norm_of_nonneg (Finset.sum_nonneg fun _ _ => norm_nonneg _)] at h1
  refine le_trans ?_ (h1.trans (le_max_left _ _))
  exact Finset.single_le_sum
    (f := fun k => ‖iteratedFDeriv ℝ k (fun t : EuclideanSpace ℝ (Fin n) => ‖t‖ ^ α) t‖)
    (fun _ _ => norm_nonneg _) (Finset.mem_range.2 (by omega))

lemma osc_thickening_annulus {K : Set (EuclideanSpace ℝ (Fin n))}
    (hK : K ⊆ {t | 1 / 2 ≤ ‖t‖ ∧ ‖t‖ ≤ 2}) {x : EuclideanSpace ℝ (Fin n)}
    (hx : x ∈ thickening (1 / 4) K) : 1 / 4 ≤ ‖x‖ ∧ ‖x‖ ≤ 9 / 4 := by
  obtain ⟨z, hz, hd⟩ := mem_thickening_iff.1 hx
  rw [dist_eq_norm] at hd
  have h1 := norm_sub_norm_le x z
  have h2 := norm_sub_norm_le z x
  rw [norm_sub_rev] at h2
  have := hK hz
  constructor <;> linarith [this.1, this.2]

lemma osc_iteratedFDeriv_inner_eq_zero (ξ : EuclideanSpace ℝ (Fin n)) {k : ℕ} (hk : 2 ≤ k)
    (x : EuclideanSpace ℝ (Fin n)) :
    iteratedFDeriv ℝ k (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) x = 0 := by
  have heq : (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) = fun t => innerSL ℝ ξ t := by
    funext t; simp [real_inner_comm]
  obtain ⟨j, rfl⟩ : ∃ j, k = j + 1 := ⟨k - 1, by omega⟩
  rw [← norm_eq_zero, ← norm_iteratedFDeriv_fderiv, heq]
  have : fderiv ℝ (fun t => innerSL ℝ ξ t) = fun _ => innerSL ℝ ξ := by
    funext y; exact (innerSL ℝ ξ).fderiv
  rw [this, iteratedFDeriv_const_of_ne (by omega), Pi.zero_apply, norm_zero]

lemma osc_fderiv_inner (ξ x : EuclideanSpace ℝ (Fin n)) :
    fderiv ℝ (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) x = innerSL ℝ ξ := by
  have heq : (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) = fun t => innerSL ℝ ξ t := by
    funext t; simp [real_inner_comm]
  rw [heq]; exact (innerSL ℝ ξ).fderiv

/-- **Corollary: the radial phase** `Φ(t) = λ u ‖t‖^α - ⟪t, ξ⟫` (`α > 1`, `1 ≤ u ≤ U`). For
amplitudes supported in the annulus `1/2 ≤ ‖t‖ ≤ 2` with derivatives up to order `n + 1`
bounded by `A`, `|∫ e^{i(λ u ‖t‖^α - ⟪t, ξ⟫)} a(t) dt| ≤ C λ^{-n/2}`, uniformly in `ξ ∈ ℝⁿ`,
`u ∈ [1, U]` and `λ > 0`. -/
theorem norm_integral_exp_radial_le (n : ℕ) {α : ℝ} (hα : 1 < α) (U A : ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (a : EuclideanSpace ℝ (Fin n) → ℂ) (lam u : ℝ)
      (ξ : EuclideanSpace ℝ (Fin n)), 0 < lam → 1 ≤ u → u ≤ U → ContDiff ℝ ∞ a →
      tsupport a ⊆ {t | 1 / 2 ≤ ‖t‖ ∧ ‖t‖ ≤ 2} →
      (∀ j, j ≤ n + 1 → ∀ x, ‖iteratedFDeriv ℝ j a x‖ ≤ A) →
      ‖∫ x, Complex.exp (Complex.I * ((lam * u * ‖x‖ ^ α - ⟪x, ξ⟫ : ℝ) : ℂ)) * a x‖ ≤
        C * lam ^ (-(n : ℝ) / 2) := by
  obtain ⟨G, hG0, hG⟩ := osc_rad_bound (n := n) α (n + 3)
  set c := α * 2 ^ (-|α - 2|) * min 1 (α - 1) with hc
  have hc0 : 0 < c := by
    have : 0 < min 1 (α - 1) := lt_min one_pos (by linarith)
    positivity
  obtain ⟨C, hC0, hC⟩ :=
    norm_integral_exp_mul_le_of_strongMono n hc0 (by norm_num : (0 : ℝ) < 1 / 4)
      (|U| * G) A (volume.real (closedBall (0 : EuclideanSpace ℝ (Fin n)) 2))
  refine ⟨C, hC0, fun a lam u ξ hlam hu1 huU ha hsupp hA => ?_⟩
  set g : EuclideanSpace ℝ (Fin n) → ℝ := fun t => ‖t‖ ^ α with hg
  set Φ : EuclideanSpace ℝ (Fin n) → ℝ := fun t => lam * u * ‖t‖ ^ α - ⟪t, ξ⟫ with hΦ
  have hball : tsupport a ⊆ closedBall 0 2 := fun t ht => by
    simpa using (hsupp ht).2
  have hac : HasCompactSupport a :=
    (isCompact_closedBall (0 : EuclideanSpace ℝ (Fin n)) 2).of_isClosed_subset
      (isClosed_tsupport a) hball
  have hvol : volume.real (tsupport a) ≤
      volume.real (closedBall (0 : EuclideanSpace ℝ (Fin n)) 2) :=
    measureReal_mono hball measure_closedBall_lt_top.ne
  have hne : ∀ x ∈ thickening (1 / 4) (tsupport a), x ≠ 0 := fun x hx h => by
    have := (osc_thickening_annulus hsupp hx).1; rw [h, norm_zero] at this; linarith
  have hinner : ContDiff ℝ ∞ (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) :=
    contDiff_id.inner ℝ contDiff_const
  have hgO : ContDiffOn ℝ ∞ g {t | t ≠ 0} := osc_contDiffOn_rad α
  have hΦs : ContDiffOn ℝ ∞ Φ (thickening (1 / 4) (tsupport a)) :=
    ((contDiffOn_const.mul hgO).sub hinner.contDiffOn).mono fun x hx => hne x hx
  have hgat : ∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ContDiffAt ℝ ∞ g x := fun x hx =>
    hgO.contDiffAt (isOpen_ne.mem_nhds hx)
  have hlu : 0 < lam * u := by positivity
  have hB : ∀ x ∈ thickening (1 / 4) (tsupport a), ∀ k, 2 ≤ k → k ≤ n + 3 →
      ‖iteratedFDeriv ℝ k Φ x‖ ≤ |U| * G * lam := by
    intro x hx k hk2 hk
    have hx0 := hne x hx
    have h1 : iteratedFDeriv ℝ k Φ x = (lam * u) • iteratedFDeriv ℝ k g x := by
      rw [show Φ = (lam * u) • g - fun t => ⟪t, ξ⟫ from rfl,
        iteratedFDeriv_sub_apply
          ((show ContDiffAt ℝ ∞ ((lam * u) • g) x by
            exact (hgat x hx0).const_smul (lam * u)).of_le (by simp))
          (hinner.contDiffAt.of_le (by simp)),
        osc_iteratedFDeriv_inner_eq_zero ξ hk2, sub_zero,
        iteratedFDeriv_const_smul_apply ((hgat x hx0).of_le (by simp))]
    rw [h1, norm_smul, Real.norm_of_nonneg hlu.le]
    have := osc_thickening_annulus hsupp hx
    have hgk := hG k (by omega) x this.1 this.2
    calc lam * u * ‖iteratedFDeriv ℝ k g x‖ ≤ lam * |U| * G := by
          rw [mul_assoc, mul_assoc]
          exact mul_le_mul_of_nonneg_left (mul_le_mul (huU.trans (le_abs_self U)) hgk
            (norm_nonneg _) (abs_nonneg _)) hlam.le
      _ = |U| * G * lam := by ring
  have hmono : ∀ x ∈ tsupport a, ∀ y ∈ tsupport a,
      c * lam * ‖x - y‖ ^ 2 ≤ (fderiv ℝ Φ x - fderiv ℝ Φ y) (x - y) := by
    intro x hx y hy
    have hx0 : x ≠ 0 := fun h => by have := (hsupp hx).1; rw [h, norm_zero] at this; linarith
    have hy0 : y ≠ 0 := fun h => by have := (hsupp hy).1; rw [h, norm_zero] at this; linarith
    have hfd : ∀ z : EuclideanSpace ℝ (Fin n), z ≠ 0 →
        fderiv ℝ Φ z = (lam * u) • fderiv ℝ g z - innerSL ℝ ξ := by
      intro z hz
      rw [show Φ = fun t => (lam * u) * g t - ⟪t, ξ⟫ from rfl,
        fderiv_fun_sub (((hgat z hz).differentiableAt (by simp)).const_mul _)
          (hinner.differentiable (by simp) z),
        fderiv_const_mul ((hgat z hz).differentiableAt (by simp)), osc_fderiv_inner]
    rw [hfd x hx0, hfd y hy0]
    have hm := osc_rad_mono (n := n) hα (hsupp hx) (hsupp hy)
    simp only [sub_apply, smul_apply, smul_eq_mul] at hm ⊢
    have hd : 0 ≤ c * ‖x - y‖ ^ 2 := by positivity
    calc c * lam * ‖x - y‖ ^ 2 ≤ lam * u * (c * ‖x - y‖ ^ 2) := by
          have : lam * (c * ‖x - y‖ ^ 2) ≤ lam * u * (c * ‖x - y‖ ^ 2) := by
            rw [mul_assoc lam u]
            exact mul_le_mul_of_nonneg_left (le_mul_of_one_le_left hd hu1) hlam.le
          linarith
      _ ≤ lam * u * ((fderiv ℝ g x) (x - y) - (fderiv ℝ g y) (x - y)) := by
          gcongr
      _ = _ := by ring
  exact hC Φ a lam hlam ha hac (hvol.trans le_rfl) hA hΦs hB hmono

lemma osc_rpow_upper {r : ℝ} (hr1 : 1 / 2 ≤ r) (hr2 : r ≤ 2) (β : ℝ) :
    r ^ β ≤ (2 : ℝ) ^ |β| := by
  rw [Real.rpow_def_of_pos (by linarith), Real.rpow_def_of_pos (by norm_num)]
  apply Real.exp_le_exp.2
  have h1 : Real.log r ≤ Real.log 2 := Real.log_le_log (by linarith) hr2
  have h2 : -Real.log 2 ≤ Real.log r := by
    rw [← Real.log_inv]; exact Real.log_le_log (by norm_num) (by linarith)
  have h3 := Real.log_pos one_lt_two
  rcases abs_cases β with ⟨hb, _⟩ | ⟨hb, _⟩ <;> rw [hb] <;> nlinarith

lemma osc_norm_le_opNorm_of_apply (L : EuclideanSpace ℝ (Fin n) →L[ℝ] ℝ)
    (v : EuclideanSpace ℝ (Fin n)) (h : ‖v‖ ^ 2 ≤ L v) : ‖v‖ ≤ ‖L‖ := by
  rcases eq_or_ne v 0 with rfl | hv
  · simp
  have hv0 : 0 < ‖v‖ := norm_pos_iff.2 hv
  have h1 := (le_abs_self (L v)).trans (L.le_opNorm v |>.trans_eq' (Real.norm_eq_abs _).symm)
  nlinarith

/-- **Corollary: the radial phase without critical points.** If `‖ξ‖ ≥ 2 α U 2^{|α-1|} λ` or
`‖ξ‖ ≤ α 2^{-|α-1|} λ / 2`, then the phase `λ u ‖t‖^α - ⟪t, ξ⟫` has no critical point on the
annulus `1/2 ≤ ‖t‖ ≤ 2`, and for amplitudes supported there
`|∫ e^{i(λ u ‖t‖^α - ⟪t, ξ⟫)} a(t) dt| ≤ C (λ + ‖ξ‖)^{-N} ∑_{k ≤ N} ∫ ‖D^k a‖`. -/
theorem norm_integral_exp_radial_le_of_nonstationary (n N : ℕ) {α : ℝ} (hα : 1 < α) (U : ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (a : EuclideanSpace ℝ (Fin n) → ℂ) (lam u : ℝ)
      (ξ : EuclideanSpace ℝ (Fin n)), 0 < lam → 1 ≤ u → u ≤ U → ContDiff ℝ ∞ a →
      tsupport a ⊆ {t | 1 / 2 ≤ ‖t‖ ∧ ‖t‖ ≤ 2} →
      (2 * α * U * 2 ^ |α - 1| * lam ≤ ‖ξ‖ ∨ ‖ξ‖ ≤ α * 2 ^ (-|α - 1|) * lam / 2) →
      ‖∫ x, Complex.exp (Complex.I * ((lam * u * ‖x‖ ^ α - ⟪x, ξ⟫ : ℝ) : ℂ)) * a x‖ ≤
        C * (lam + ‖ξ‖) ^ (-(N : ℝ)) *
          ∑ k ∈ Finset.range (N + 1), ∫ x, ‖iteratedFDeriv ℝ k a x‖ := by
  obtain ⟨G, hG0, hG⟩ := osc_rad_bound (n := n) α (N + 1)
  set m := α * 2 ^ (-|α - 1|) / 2 with hm
  have hm0 : 0 < m := by
    have : 0 < α := by linarith
    positivity
  set κ := min (1 / 3) (m / (1 + m)) with hκ
  have hκ0 : 0 < κ := lt_min (by norm_num) (by positivity)
  obtain ⟨CA, hCA0, hCA⟩ := norm_integral_exp_mul_le_of_nonstationary n N (|U| * G / κ)
  refine ⟨CA * (κ ^ N)⁻¹, by positivity, ?_⟩
  intro a lam u ξ hlam hu1 huU ha hsupp hξ
  set g : EuclideanSpace ℝ (Fin n) → ℝ := fun t => ‖t‖ ^ α with hg
  set Φ : EuclideanSpace ℝ (Fin n) → ℝ := fun t => lam * u * ‖t‖ ^ α - ⟪t, ξ⟫ with hΦ
  have hball : tsupport a ⊆ closedBall 0 2 := fun t ht => by
    simpa using (hsupp ht).2
  have hac : HasCompactSupport a :=
    (isCompact_closedBall (0 : EuclideanSpace ℝ (Fin n)) 2).of_isClosed_subset
      (isClosed_tsupport a) hball
  have hne : ∀ x ∈ tsupport a, x ≠ 0 := fun x hx h => by
    have := (hsupp hx).1; rw [h, norm_zero] at this; linarith
  have hinner : ContDiff ℝ ∞ (fun t : EuclideanSpace ℝ (Fin n) => ⟪t, ξ⟫) :=
    contDiff_id.inner ℝ contDiff_const
  have hgO : ContDiffOn ℝ ∞ g {t | t ≠ 0} := osc_contDiffOn_rad α
  have hΦs : ContDiffOn ℝ ∞ Φ {t | t ≠ 0} := (contDiffOn_const.mul hgO).sub hinner.contDiffOn
  have hgat : ∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ContDiffAt ℝ ∞ g x := fun x hx =>
    hgO.contDiffAt (isOpen_ne.mem_nhds hx)
  have hlu : 0 < lam * u := by positivity
  set μ := κ * (lam + ‖ξ‖) with hμ
  have hμ0 : 0 < μ := by positivity
  -- the gradient lower bound
  have hlow : ∀ x ∈ tsupport a, μ ≤ ‖fderiv ℝ Φ x‖ := by
    intro x hx
    have hx0 := hne x hx
    set P : EuclideanSpace ℝ (Fin n) := (lam * u * α * ‖x‖ ^ (α - 2)) • x with hP
    have hfd : ∀ v, fderiv ℝ Φ x v = ⟪P - ξ, v⟫ := by
      intro v
      rw [show Φ = fun t => (lam * u) * g t - ⟪t, ξ⟫ from rfl,
        fderiv_fun_sub (((hgat x hx0).differentiableAt (by simp)).const_mul _)
          (hinner.differentiable (by simp) x),
        fderiv_const_mul ((hgat x hx0).differentiableAt (by simp)), osc_fderiv_inner]
      simp only [sub_apply, smul_apply, smul_eq_mul, innerSL_apply_apply, hg,
        osc_fderiv_rad hx0, hP, inner_sub_left, inner_smul_left, RCLike.conj_to_real]
      ring
    have hge : ‖P - ξ‖ ≤ ‖fderiv ℝ Φ x‖ :=
      osc_norm_le_opNorm_of_apply _ _ (by rw [hfd, real_inner_self_eq_norm_sq])
    refine le_trans ?_ hge
    have hr := hsupp hx
    have hPn : ‖P‖ = lam * u * α * ‖x‖ ^ (α - 1) := by
      rw [hP, norm_smul, Real.norm_of_nonneg (by positivity), mul_assoc,
        ← Real.rpow_add_one (norm_ne_zero_iff.2 hx0)]
      congr 2; ring
    have hup := osc_rpow_upper hr.1 hr.2 (α - 1)
    have hlo := osc_rpow_lower hr.1 hr.2 (α - 1)
    have hα0 : 0 < α := by linarith
    have h2p : (1 : ℝ) ≤ 2 ^ |α - 1| := Real.one_le_rpow (by norm_num) (abs_nonneg _)
    rcases hξ with hξ | hξ
    · -- `‖ξ‖` large
      have hPle : ‖P‖ ≤ ‖ξ‖ / 2 := by
        rw [hPn]
        have : lam * u * α * ‖x‖ ^ (α - 1) ≤ lam * U * α * 2 ^ |α - 1| := by
          have h1 : lam * u ≤ lam * U := mul_le_mul_of_nonneg_left huU hlam.le
          have h2 : 0 ≤ ‖x‖ ^ (α - 1) := by positivity
          calc lam * u * α * ‖x‖ ^ (α - 1) ≤ lam * U * α * ‖x‖ ^ (α - 1) := by gcongr
            _ ≤ lam * U * α * 2 ^ |α - 1| := by
              have : 0 ≤ lam * U * α := by
                have : 0 ≤ U := by linarith
                positivity
              gcongr
        linarith
      have hlamξ : lam ≤ ‖ξ‖ / 2 := by
        have : lam ≤ α * U * 2 ^ |α - 1| * lam := by
          have h1 : 1 ≤ α * U := by nlinarith
          have h2 : 1 ≤ α * U * 2 ^ |α - 1| := by nlinarith
          nlinarith
        linarith
      have h1 : ‖ξ‖ - ‖P‖ ≤ ‖P - ξ‖ := by
        have := norm_sub_norm_le ξ P; rw [norm_sub_rev] at this; linarith
      have : μ ≤ (lam + ‖ξ‖) / 3 := by
        rw [hμ]; exact mul_le_mul_of_nonneg_right (min_le_left _ _) (by positivity) |>.trans_eq
          (by ring)
      linarith
    · -- `‖ξ‖` small
      have hPge : 2 * m * lam ≤ ‖P‖ := by
        rw [hPn, hm]
        have h1 : lam ≤ lam * u := le_mul_of_one_le_right hlam.le hu1
        calc 2 * (α * 2 ^ (-|α - 1|) / 2) * lam = lam * α * 2 ^ (-|α - 1|) := by ring
          _ ≤ lam * u * α * ‖x‖ ^ (α - 1) := by gcongr
      have h1 : ‖P‖ - ‖ξ‖ ≤ ‖P - ξ‖ := norm_sub_norm_le P ξ
      have hξm : ‖ξ‖ ≤ m * lam := by rw [hm]; linarith
      have : μ ≤ m * lam := by
        rw [hμ]
        calc κ * (lam + ‖ξ‖) ≤ m / (1 + m) * (lam + ‖ξ‖) :=
              mul_le_mul_of_nonneg_right (min_le_right _ _) (by positivity)
          _ ≤ m / (1 + m) * (lam + m * lam) := by gcongr
          _ = m * lam := by field_simp
      linarith
  have hB : ∀ x ∈ tsupport a, ∀ k, 2 ≤ k → k ≤ N + 1 →
      ‖iteratedFDeriv ℝ k Φ x‖ ≤ |U| * G / κ * μ := by
    intro x hx k hk2 hk
    have hx0 := hne x hx
    have h1 : iteratedFDeriv ℝ k Φ x = (lam * u) • iteratedFDeriv ℝ k g x := by
      rw [show Φ = (lam * u) • g - fun t => ⟪t, ξ⟫ from rfl,
        iteratedFDeriv_sub_apply
          ((show ContDiffAt ℝ ∞ ((lam * u) • g) x by exact (hgat x hx0).const_smul (lam * u)).of_le
            (by simp))
          (hinner.contDiffAt.of_le (by simp)),
        osc_iteratedFDeriv_inner_eq_zero ξ hk2, sub_zero,
        iteratedFDeriv_const_smul_apply ((hgat x hx0).of_le (by simp))]
    rw [h1, norm_smul, Real.norm_of_nonneg hlu.le]
    have hr := hsupp hx
    have hgk := hG k hk x (by linarith [hr.1]) (by linarith [hr.2])
    have hUG : 0 ≤ |U| * G := by positivity
    calc lam * u * ‖iteratedFDeriv ℝ k g x‖ ≤ lam * (|U| * G) := by
          rw [mul_assoc]
          exact mul_le_mul_of_nonneg_left
            (mul_le_mul (huU.trans (le_abs_self U)) hgk (norm_nonneg _) (abs_nonneg _)) hlam.le
      _ ≤ (lam + ‖ξ‖) * (|U| * G) := by gcongr; linarith [norm_nonneg ξ]
      _ = |U| * G / κ * μ := by rw [hμ]; field_simp
  have hmain := hCA Φ a {t | t ≠ 0} μ isOpen_ne hΦs ha hac (fun x hx => hne x hx) hμ0 hlow hB
  refine hmain.trans_eq ?_
  rw [hμ, Real.mul_rpow hκ0.le (by positivity), Real.rpow_neg hκ0.le, Real.rpow_natCast]
  ring

end Radial

end Auto
