/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Interpolation of operators of restricted strong type

This file was automatically generated by Claude.

It proves an interpolation theorem of Marcinkiewicz–Stein–Weiss type for operators of
restricted strong type. It depends on Mathlib only.

## Setting

* `(X, μ)`, `(Y, ν)` are arbitrary measure spaces (no σ-finiteness is needed); inputs are functions
  `f : X → E` with values in a normed additive group `E` (e.g. `E = ℂ`), and
  `T : (X → E) → Y → ℝ≥0∞` takes nonnegative extended real values.
* `D : Set (X → E)` is a class of a.e. strongly measurable functions which is
  `IsLevelTruncationClosed`: `f 𝟙_{s < ‖f‖ ≤ t} ∈ D` for `f ∈ D`, `0 ≤ s < t`.
* `IsDisjointSublinearOn T D ν`: if `f ∈ D`, `f_k ∈ D` (`k ∈ ℤ`) have pairwise disjoint supports
  and `f = ∑_k f_k` pointwise, then `T f ≤ ∑_k T f_k` `ν`-a.e.
* `HasRestrictedStrongTypeOn T D q M μ ν`: for every measurable `S` with `μ S < ∞`, every `c ≥ 0`
  and every `g ∈ D` with `‖g‖ ≤ c 𝟙_S`, `‖T g‖_{L^q(ν)} ≤ M c μ(S)^(1/q)`.

## Main result

* `eLpNorm_le_of_restrictedType`: if `T` is of restricted strong type `(p₀, p₀)` and `(p₁, p₁)`
  on `D` with constants `M₀, M₁ > 0`, where `0 < p₀ < p < p₁ < ∞` (in particular for
  `1 ≤ p₀`), then for every `f ∈ D` with `T f` a.e. strongly measurable,
  `‖T f‖_{L^p(ν)} ≤ C(p₀,p₁,p) M₀^(1-θ) M₁^θ ‖f‖_{L^p(μ)}`, `1/p = (1-θ)/p₀ + θ/p₁`,
  with the explicit constant `C(p₀,p₁,p) = rtiConst p₀ p₁ p` depending only on `p₀, p₁, p`
  (geometric mean of the constants).
* `rti_lintegral_tsum_rpow_le`: the underlying abstract summation estimate for a family
  `(g_k)_{k ∈ ℤ}` of nonnegative functions with distributional bounds at two exponents.

## Proof

Decompose `f = ∑_k f_k`, `f_k = f 𝟙_{E_k}`, `E_k = {2^k < ‖f‖ ≤ 2^(k+1)}`, so that
`T f ≤ G := ∑_k T f_k` a.e. and, by the restricted strong-type bounds and Chebyshev,
`ν{T f_k > t} ≤ t^(-pᵢ) (2Mᵢ)^(pᵢ) 2^(k pᵢ) μ(E_k)` for `i = 0, 1`. A discrete layer-cake
inequality gives `∫ G^p ≤ 2^p ∑_j τ_j^p ν{G > τ_j}`, `τ_j = λ 2^j`. At height `τ_j` the
threshold is split among the levels with geometric weights, `t_{jk} = W⁻¹ 2^(-γ|k-j|) τ_j`
(`∑_k t_{jk} = τ_j`), so that `ν{G > τ_j} ≤ ∑_k ν{T f_k > t_{jk}}`; the `p₁`-bound is used for
`k ≤ j` and the `p₀`-bound for `k > j`. Each term is at most
`K 2^(-δ|k-j|) 2^(k p) μ(E_k)`, and summing first over `j` (a discrete Schur-type estimate)
leaves `2^p Ψ K ∑_k 2^(k p) μ(E_k) ≤ 2^p Ψ K ∫ ‖f‖^p`. Finally the scaling `λ` is chosen to
balance the two contributions, which yields the geometric mean `M₀^(1-θ) M₁^θ`.
In fact only the weak-type consequence of the restricted strong-type hypotheses is used.

## References

* E. M. Stein, G. Weiss, *Introduction to Fourier Analysis on Euclidean Spaces*, Princeton
  University Press, 1971, Chapter V, §3 (restricted weak type and the Marcinkiewicz theorem).
* L. Grafakos, *Classical Fourier Analysis*, Graduate Texts in Mathematics 249, Springer,
  §1.4 (interpolation for operators of restricted weak type).
-/

@[expose] public section

namespace Auto

open MeasureTheory Set Real
open scoped ENNReal NNReal

noncomputable section

/-! ### Two-sided geometric series -/

/-- The two-sided geometric series `∑_{n ∈ ℤ} 2^(-η |n|)`. -/
def rtiSeries (η : ℝ) : ℝ := ∑' n : ℤ, (2 : ℝ) ^ (-(η * |(n : ℝ)|))

theorem rti_summable {η : ℝ} (hη : 0 < η) :
    Summable fun n : ℤ => (2 : ℝ) ^ (-(η * |(n : ℝ)|)) := by
  have hr0 : (0 : ℝ) ≤ 2 ^ (-η) := rpow_nonneg (by norm_num) _
  have hr1 : (2 : ℝ) ^ (-η) < 1 := rpow_lt_one_of_one_lt_of_neg one_lt_two (neg_neg_of_pos hη)
  have key : ∀ n : ℕ, (2 : ℝ) ^ (-(η * (n : ℝ))) = ((2 : ℝ) ^ (-η)) ^ n := by
    intro n
    rw [← rpow_natCast, ← rpow_mul (by norm_num)]
    ring_nf
  apply Summable.of_nat_of_neg
  · refine (summable_geometric_of_lt_one hr0 hr1).congr fun n => ?_
    simp only [Int.cast_natCast, abs_of_nonneg (Nat.cast_nonneg (α := ℝ) n), key]
  · refine (summable_geometric_of_lt_one hr0 hr1).congr fun n => ?_
    simp only [Int.cast_neg, Int.cast_natCast, abs_neg,
      abs_of_nonneg (Nat.cast_nonneg (α := ℝ) n), key]

theorem rtiSeries_pos {η : ℝ} (hη : 0 < η) : 0 < rtiSeries η :=
  (rti_summable hη).tsum_pos (fun _ => rpow_nonneg (by norm_num) _) 0 (rpow_pos_of_pos two_pos _)

/-- Shift invariance of the two-sided geometric series. -/
theorem rti_tsum_ofReal_shift {η : ℝ} (hη : 0 < η) (j : ℤ) :
    ∑' k : ℤ, ENNReal.ofReal ((2 : ℝ) ^ (-(η * |(k : ℝ) - j|))) =
      ENNReal.ofReal (rtiSeries η) := by
  rw [rtiSeries, ENNReal.ofReal_tsum_of_nonneg (fun _ => rpow_nonneg (by norm_num) _)
    (rti_summable hη)]
  have := (Equiv.subRight j).tsum_eq
    (fun n : ℤ => ENNReal.ofReal ((2 : ℝ) ^ (-(η * |(n : ℝ)|))))
  simpa only [Equiv.subRight_apply, Int.cast_sub] using this

/-! ### A discrete layer-cake inequality -/

section LayerCake

variable {Y : Type*} [MeasurableSpace Y]

theorem rti_lintegral_tsum_indicator_le (ν : Measure Y) (A : ℤ → Set Y) (c : ℤ → ℝ≥0∞) :
    ∫⁻ y, ∑' j, (A j).indicator (fun _ => c j) y ∂ν ≤ ∑' j, c j * ν (A j) := by
  calc ∫⁻ y, ∑' j, (A j).indicator (fun _ => c j) y ∂ν
      ≤ ∫⁻ y, ∑' j, (toMeasurable ν (A j)).indicator (fun _ => c j) y ∂ν := by
        refine lintegral_mono fun y => ENNReal.tsum_le_tsum fun j => ?_
        exact indicator_le_indicator_of_subset (subset_toMeasurable _ _) (fun _ => zero_le) y
    _ = ∑' j, c j * ν (A j) := by
        rw [lintegral_tsum fun j =>
          (measurable_const.indicator (measurableSet_toMeasurable _ _)).aemeasurable]
        congr 1
        funext j
        rw [lintegral_indicator_const (measurableSet_toMeasurable _ _), measure_toMeasurable]

/-- Pointwise discrete layer cake: `G^p ≤ 2^p ∑_j τ_j^p 1{τ_j < G}`, `τ_j = λ 2^j`. -/
theorem rti_rpow_le_tsum (G : ℝ≥0∞) {lam p : ℝ} (hlam : 0 < lam) (hp : 0 < p) :
    G ^ p ≤ ENNReal.ofReal (2 ^ p) * ∑' j : ℤ,
      (if ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < G then
        ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) else 0) := by
  rcases eq_or_ne G 0 with rfl | h0
  · simp [ENNReal.zero_rpow_of_pos hp]
  have h2p : ENNReal.ofReal (2 ^ p) ≠ 0 := by
    rw [ne_eq, ENNReal.ofReal_eq_zero, not_le]; positivity
  rcases eq_or_ne G ⊤ with rfl | htop
  · have hsum : ∑' j : ℤ, (if ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < ⊤ then
        ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) else 0) = ⊤ := by
      simp only [ENNReal.ofReal_lt_top, ↓reduceIte]
      refine top_unique ?_
      have hl : ENNReal.ofReal (lam ^ p) ≠ 0 := by
        rw [ne_eq, ENNReal.ofReal_eq_zero, not_le]; positivity
      calc (⊤ : ℝ≥0∞) = ∑' _ : ℕ, ENNReal.ofReal (lam ^ p) :=
            (ENNReal.tsum_const_eq_top_of_ne_zero hl).symm
        _ ≤ ∑' n : ℕ, ENNReal.ofReal ((lam * 2 ^ (((n : ℤ)) : ℝ)) ^ p) := by
            refine ENNReal.tsum_le_tsum fun n => ENNReal.ofReal_le_ofReal ?_
            refine rpow_le_rpow hlam.le ?_ hp.le
            refine le_mul_of_one_le_right hlam.le (one_le_rpow one_le_two ?_)
            exact_mod_cast Int.natCast_nonneg n
        _ ≤ ∑' j : ℤ, ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) :=
            ENNReal.tsum_comp_le_tsum_of_injective Nat.cast_injective
              (fun j : ℤ => ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p))
    rw [hsum, ENNReal.mul_top h2p]; exact le_top
  have hGpos : 0 < G.toReal := ENNReal.toReal_pos h0 htop
  obtain ⟨n, hn1, hn2⟩ := exists_mem_Ioc_zpow (div_pos hGpos hlam) one_lt_two
  rw [← rpow_intCast, lt_div_iff₀ hlam, mul_comm] at hn1
  rw [← rpow_intCast, div_le_iff₀ hlam, Int.cast_add, Int.cast_one, rpow_add two_pos,
    rpow_one, mul_comm] at hn2
  have hτ : 0 ≤ lam * 2 ^ (n : ℝ) := by positivity
  have hif : ENNReal.ofReal (lam * 2 ^ (n : ℝ)) < G :=
    (ENNReal.ofReal_lt_iff_lt_toReal hτ htop).mpr hn1
  calc G ^ p = ENNReal.ofReal (G.toReal ^ p) := by
        rw [← ENNReal.ofReal_rpow_of_nonneg ENNReal.toReal_nonneg hp.le, ENNReal.ofReal_toReal htop]
    _ ≤ ENNReal.ofReal ((lam * (2 ^ (n : ℝ) * 2)) ^ p) :=
        ENNReal.ofReal_le_ofReal (rpow_le_rpow ENNReal.toReal_nonneg hn2 hp.le)
    _ = ENNReal.ofReal (2 ^ p) * ENNReal.ofReal ((lam * 2 ^ (n : ℝ)) ^ p) := by
        rw [← ENNReal.ofReal_mul (by positivity), ← mul_rpow (by norm_num) hτ]
        ring_nf
    _ ≤ _ := by
        gcongr
        refine le_trans (le_of_eq ?_) (ENNReal.le_tsum n)
        simp only [hif, ↓reduceIte]

/-- Discrete layer cake: `∫ G^p ≤ 2^p ∑_j τ_j^p ν{τ_j < G}`, `τ_j = λ 2^j`. -/
theorem rti_lintegral_rpow_le (ν : Measure Y) (G : Y → ℝ≥0∞) {lam p : ℝ} (hlam : 0 < lam)
    (hp : 0 < p) :
    ∫⁻ y, G y ^ p ∂ν ≤ ENNReal.ofReal (2 ^ p) * ∑' j : ℤ,
      ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
        ν {y | ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < G y} := by
  calc ∫⁻ y, G y ^ p ∂ν
      ≤ ∫⁻ y, ENNReal.ofReal (2 ^ p) * ∑' j : ℤ,
          {y | ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < G y}.indicator
            (fun _ => ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p)) y ∂ν := by
        refine lintegral_mono fun y => ?_
        simp only [indicator_apply, mem_ofPred_eq]
        exact rti_rpow_le_tsum (G y) hlam hp
    _ = ENNReal.ofReal (2 ^ p) * ∫⁻ y, ∑' j : ℤ,
          {y | ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < G y}.indicator
            (fun _ => ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p)) y ∂ν :=
        lintegral_const_mul' _ _ ENNReal.ofReal_ne_top
    _ ≤ _ := by
        gcongr
        exact rti_lintegral_tsum_indicator_le ν _ _

/-- Union bound for a countable sum: if `∑ t_k ≤ τ` then `ν{τ < ∑ g_k} ≤ ∑ ν{t_k < g_k}`. -/
theorem rti_measure_lt_tsum_le (ν : Measure Y) (g : ℤ → Y → ℝ≥0∞) (τ : ℝ≥0∞)
    (t : ℤ → ℝ≥0∞) (ht : ∑' k, t k ≤ τ) :
    ν {y | τ < ∑' k, g k y} ≤ ∑' k, ν {y | t k < g k y} := by
  refine (measure_mono ?_).trans (measure_iUnion_le _)
  intro y hy
  by_contra hc
  simp only [mem_iUnion, mem_ofPred_eq, not_exists, not_lt] at hc
  exact (not_lt.mpr ((ENNReal.tsum_le_tsum hc).trans ht)) hy

end LayerCake

/-! ### The core summation estimate -/

theorem rti_term_eq {lam W p q γ : ℝ} (hlam : 0 < lam) (hW : 0 < W) (j k : ℤ) :
    (lam * 2 ^ (j : ℝ)) ^ p * ((W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ^ (-q) *
      2 ^ ((k : ℝ) * q)) =
    lam ^ (p - q) * W ^ q *
      2 ^ ((k : ℝ) * p + ((j : ℝ) - k) * (p - q) + γ * |(k : ℝ) - j| * q) := by
  rw [← exp_log hlam, ← exp_log hW]
  simp only [rpow_def_of_pos two_pos, ← exp_neg, ← exp_add, ← exp_mul]
  congr 1
  ring

/-- The term estimate for the levels `k ≤ j` (upper exponent `b`). -/
theorem rti_term_le_low {lam W p b γ δ A : ℝ} (hlam : 0 < lam) (hW : 0 < W) (hA : 0 ≤ A)
    (hγδ : γ * b + δ ≤ b - p) {j k : ℤ} (hkj : k ≤ j) :
    (lam * 2 ^ (j : ℝ)) ^ p * ((W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ^ (-b) *
      A * 2 ^ ((k : ℝ) * b)) ≤
    lam ^ (p - b) * W ^ b * A * (2 ^ (-(δ * |(k : ℝ) - j|)) * 2 ^ ((k : ℝ) * p)) := by
  have hkj' : (k : ℝ) ≤ j := by exact_mod_cast hkj
  rw [show ∀ x y z : ℝ, x * (y * A * z) = A * (x * (y * z)) by intros; ring,
    rti_term_eq hlam hW, ← rpow_add two_pos]
  rw [show ∀ x y z : ℝ, A * (x * y * z) = x * y * A * z by intros; ring]
  refine mul_le_mul_of_nonneg_left (rpow_le_rpow_of_exponent_le one_le_two ?_) (by positivity)
  rw [abs_of_nonpos (by linarith)]
  nlinarith [mul_nonneg (sub_nonneg.mpr hkj') (show 0 ≤ b - p - γ * b - δ by linarith)]

/-- The term estimate for the levels `k > j` (lower exponent `a`). -/
theorem rti_term_le_high {lam W p a γ δ A : ℝ} (hlam : 0 < lam) (hW : 0 < W) (hA : 0 ≤ A)
    (hγδ : γ * a + δ ≤ p - a) {j k : ℤ} (hjk : j < k) :
    (lam * 2 ^ (j : ℝ)) ^ p * ((W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ^ (-a) *
      A * 2 ^ ((k : ℝ) * a)) ≤
    lam ^ (p - a) * W ^ a * A * (2 ^ (-(δ * |(k : ℝ) - j|)) * 2 ^ ((k : ℝ) * p)) := by
  have hjk' : (j : ℝ) < k := by exact_mod_cast hjk
  rw [show ∀ x y z : ℝ, x * (y * A * z) = A * (x * (y * z)) by intros; ring,
    rti_term_eq hlam hW, ← rpow_add two_pos]
  rw [show ∀ x y z : ℝ, A * (x * y * z) = x * y * A * z by intros; ring]
  refine mul_le_mul_of_nonneg_left (rpow_le_rpow_of_exponent_le one_le_two ?_) (by positivity)
  rw [abs_of_pos (by linarith)]
  nlinarith [mul_nonneg (sub_nonneg.mpr hjk'.le) (show 0 ≤ p - a - γ * a - δ by linarith)]

section Core

variable {Y : Type*} [MeasurableSpace Y]

/-- **Core estimate.** Let `g_k ≥ 0` (`k ∈ ℤ`) satisfy the distributional bounds
`ν{g_k > t} ≤ t^(-a) A₀ 2^(k a) s_k` and `ν{g_k > t} ≤ t^(-b) A₁ 2^(k b) s_k` for `t > 0`, where
`a < p < b`. Then for decay parameters `γ, δ > 0` with `γ a + δ ≤ p - a`, `γ b + δ ≤ b - p`
and every `λ > 0`,
`∫ (∑_k g_k)^p ≤ 2^p Ψ (λ^(p-a) W^a A₀ + λ^(p-b) W^b A₁) ∑_k 2^(k p) s_k`, where
`W = ∑_n 2^(-γ|n|)` and `Ψ = ∑_n 2^(-δ|n|)`. -/
theorem rti_lintegral_tsum_rpow_le (ν : Measure Y) (g : ℤ → Y → ℝ≥0∞) (s : ℤ → ℝ≥0∞)
    {a b p γ δ lam A₀ A₁ : ℝ} (hp : 0 < p) (hγ : 0 < γ)
    (hδ : 0 < δ) (hγa : γ * a + δ ≤ p - a) (hγb : γ * b + δ ≤ b - p) (hlam : 0 < lam)
    (hA₀ : 0 ≤ A₀) (hA₁ : 0 ≤ A₁)
    (h₀ : ∀ k : ℤ, ∀ t : ℝ, 0 < t → ν {y | ENNReal.ofReal t < g k y} ≤
      ENNReal.ofReal (t ^ (-a) * A₀ * 2 ^ ((k : ℝ) * a)) * s k)
    (h₁ : ∀ k : ℤ, ∀ t : ℝ, 0 < t → ν {y | ENNReal.ofReal t < g k y} ≤
      ENNReal.ofReal (t ^ (-b) * A₁ * 2 ^ ((k : ℝ) * b)) * s k) :
    ∫⁻ y, (∑' k, g k y) ^ p ∂ν ≤
      ENNReal.ofReal (2 ^ p * rtiSeries δ * (lam ^ (p - a) * rtiSeries γ ^ a * A₀ +
        lam ^ (p - b) * rtiSeries γ ^ b * A₁)) *
      ∑' k : ℤ, ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * s k := by
  have hW : 0 < rtiSeries γ := rtiSeries_pos hγ
  have hΨ : 0 < rtiSeries δ := rtiSeries_pos hδ
  generalize hWdef : rtiSeries γ = W at hW ⊢
  generalize hKdef : lam ^ (p - a) * W ^ a * A₀ + lam ^ (p - b) * W ^ b * A₁ = K
  have hK₀ : lam ^ (p - a) * W ^ a * A₀ ≤ K := by
    rw [← hKdef]; exact le_add_of_nonneg_right (by positivity)
  have hK₁ : lam ^ (p - b) * W ^ b * A₁ ≤ K := by
    rw [← hKdef]; exact le_add_of_nonneg_left (by positivity)
  have hK : 0 ≤ K := le_trans (by positivity) hK₀
  have ht_pos : ∀ j k : ℤ, 0 < W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ)) :=
    fun j k => by positivity
  have ht_sum : ∀ j : ℤ, ∑' k : ℤ,
      ENNReal.ofReal (W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ≤
      ENNReal.ofReal (lam * 2 ^ (j : ℝ)) := by
    intro j
    have e : ∀ k : ℤ,
        ENNReal.ofReal (W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) =
        ENNReal.ofReal (2 ^ (-(γ * |(k : ℝ) - j|))) *
          ENNReal.ofReal (W⁻¹ * (lam * 2 ^ (j : ℝ))) := by
      intro k
      rw [← ENNReal.ofReal_mul (rpow_nonneg (by norm_num) _)]
      congr 1
      ring
    simp_rw [e]
    rw [ENNReal.tsum_mul_right, rti_tsum_ofReal_shift hγ j, hWdef,
      ← ENNReal.ofReal_mul hW.le]
    apply le_of_eq
    congr 1
    field_simp
  have hterm : ∀ j k : ℤ, ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
      ν {y | ENNReal.ofReal (W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) < g k y}
      ≤ ENNReal.ofReal K * ENNReal.ofReal (2 ^ (-(δ * |(k : ℝ) - j|))) *
        (ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * s k) := by
    intro j k
    have hfin : ∀ X : ℝ, ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) * (ENNReal.ofReal X * s k) =
        ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p * X) * s k := by
      intro X
      rw [ENNReal.ofReal_mul (by positivity), mul_assoc]
    have hend : ENNReal.ofReal (K * (2 ^ (-(δ * |(k : ℝ) - j|)) * 2 ^ ((k : ℝ) * p))) * s k =
        ENNReal.ofReal K * ENNReal.ofReal (2 ^ (-(δ * |(k : ℝ) - j|))) *
          (ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * s k) := by
      rw [ENNReal.ofReal_mul hK, ENNReal.ofReal_mul (by positivity)]
      ring
    rcases le_or_gt k j with hkj | hjk
    · calc _ ≤ ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
            (ENNReal.ofReal ((W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ^ (-b) *
              A₁ * 2 ^ ((k : ℝ) * b)) * s k) := mul_le_mul_right (h₁ k _ (ht_pos j k)) _
        _ ≤ ENNReal.ofReal (K * (2 ^ (-(δ * |(k : ℝ) - j|)) * 2 ^ ((k : ℝ) * p))) * s k := by
            rw [hfin]
            refine mul_le_mul_left (ENNReal.ofReal_le_ofReal ?_) _
            refine (rti_term_le_low hlam hW hA₁ hγb hkj).trans ?_
            gcongr
        _ = _ := hend
    · calc _ ≤ ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
            (ENNReal.ofReal ((W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) ^ (-a) *
              A₀ * 2 ^ ((k : ℝ) * a)) * s k) := mul_le_mul_right (h₀ k _ (ht_pos j k)) _
        _ ≤ ENNReal.ofReal (K * (2 ^ (-(δ * |(k : ℝ) - j|)) * 2 ^ ((k : ℝ) * p))) * s k := by
            rw [hfin]
            refine mul_le_mul_left (ENNReal.ofReal_le_ofReal ?_) _
            refine (rti_term_le_high hlam hW hA₀ hγa hjk).trans ?_
            gcongr
        _ = _ := hend
  calc ∫⁻ y, (∑' k, g k y) ^ p ∂ν
      ≤ ENNReal.ofReal (2 ^ p) * ∑' j : ℤ, ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
          ν {y | ENNReal.ofReal (lam * 2 ^ (j : ℝ)) < ∑' k, g k y} :=
        rti_lintegral_rpow_le ν _ hlam hp
    _ ≤ ENNReal.ofReal (2 ^ p) * ∑' j : ℤ, ∑' k : ℤ, ENNReal.ofReal ((lam * 2 ^ (j : ℝ)) ^ p) *
          ν {y | ENNReal.ofReal (W⁻¹ * 2 ^ (-(γ * |(k : ℝ) - j|)) * (lam * 2 ^ (j : ℝ))) <
            g k y} := by
        refine mul_le_mul_right (ENNReal.tsum_le_tsum fun j => ?_) _
        rw [ENNReal.tsum_mul_left]
        exact mul_le_mul_right (rti_measure_lt_tsum_le ν g _ _ (ht_sum j)) _
    _ ≤ ENNReal.ofReal (2 ^ p) * ∑' j : ℤ, ∑' k : ℤ, ENNReal.ofReal K *
          ENNReal.ofReal (2 ^ (-(δ * |(k : ℝ) - j|))) *
            (ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * s k) :=
        mul_le_mul_right (ENNReal.tsum_le_tsum fun j => ENNReal.tsum_le_tsum fun k =>
          hterm j k) _
    _ = ENNReal.ofReal (2 ^ p) * ∑' k : ℤ, ENNReal.ofReal K * ENNReal.ofReal (rtiSeries δ) *
          (ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * s k) := by
        rw [ENNReal.tsum_comm]
        congr 1
        refine tsum_congr fun k => ?_
        rw [ENNReal.tsum_mul_right, ENNReal.tsum_mul_left]
        congr 2
        simp_rw [abs_sub_comm (k : ℝ)]
        exact rti_tsum_ofReal_shift hδ k
    _ = _ := by
        rw [ENNReal.tsum_mul_left, ENNReal.ofReal_mul (by positivity),
          ENNReal.ofReal_mul (by positivity), ← hKdef]
        ring

end Core

/-! ### Constants -/

/-- The decay parameter `γ = min ((b-p)/(2b)) ((p-a)/(2a))` of the splitting weights. -/
def rtiGamma (a b p : ℝ) : ℝ := min ((b - p) / (2 * b)) ((p - a) / (2 * a))

/-- The decay parameter `δ = min ((b-p)/2) ((p-a)/2)` of the off-diagonal terms. -/
def rtiDelta (a b p : ℝ) : ℝ := min ((b - p) / 2) ((p - a) / 2)

/-- The interpolation constant
`C(a,b,p) = 2 (Ψ ((2W)^a + (2W)^b))^(1/p)`, `W = ∑_n 2^(-γ|n|)`, `Ψ = ∑_n 2^(-δ|n|)`. -/
def rtiConst (a b p : ℝ) : ℝ :=
  2 * (rtiSeries (rtiDelta a b p) * ((2 * rtiSeries (rtiGamma a b p)) ^ a +
    (2 * rtiSeries (rtiGamma a b p)) ^ b)) ^ (1 / p)

section ConstLemmas

variable {a b p : ℝ}

theorem rtiGamma_pos (ha : 0 < a) (hap : a < p) (hpb : p < b) : 0 < rtiGamma a b p :=
  lt_min (div_pos (by linarith) (by linarith)) (div_pos (by linarith) (by linarith))

theorem rtiDelta_pos (hap : a < p) (hpb : p < b) : 0 < rtiDelta a b p :=
  lt_min (by linarith) (by linarith)

theorem rti_gamma_delta_low (ha : 0 < a) :
    rtiGamma a b p * a + rtiDelta a b p ≤ p - a := by
  have h1 : rtiGamma a b p * (2 * a) ≤ p - a :=
    (le_div_iff₀ (by linarith)).mp (min_le_right _ _)
  have h2 : rtiDelta a b p ≤ (p - a) / 2 := min_le_right _ _
  linarith

theorem rti_gamma_delta_high (ha : 0 < a) (hap : a < p) (hpb : p < b) :
    rtiGamma a b p * b + rtiDelta a b p ≤ b - p := by
  have h1 : rtiGamma a b p * (2 * b) ≤ b - p :=
    (le_div_iff₀ (by linarith)).mp (min_le_left _ _)
  have h2 : rtiDelta a b p ≤ (b - p) / 2 := min_le_left _ _
  linarith

theorem rtiConst_pos (ha : 0 < a) (hap : a < p) (hpb : p < b) : 0 < rtiConst a b p := by
  have hW := rtiSeries_pos (rtiGamma_pos ha hap hpb)
  have hΨ := rtiSeries_pos (rtiDelta_pos hap hpb)
  unfold rtiConst
  positivity

/-- The optimization of the scaling parameter `λ = (M₁^b / M₀^a)^(1/(b-a))`. -/
theorem rti_scaling_identity {M₀ M₁ θ : ℝ} (ha : 0 < a) (hap : a < p) (hpb : p < b)
    (hθ : 1 / p = (1 - θ) / a + θ / b) (hM₀ : 0 < M₀) (hM₁ : 0 < M₁) :
    ((M₁ ^ b / M₀ ^ a) ^ (1 / (b - a))) ^ (p - a) * M₀ ^ a = (M₀ ^ (1 - θ) * M₁ ^ θ) ^ p ∧
    ((M₁ ^ b / M₀ ^ a) ^ (1 / (b - a))) ^ (p - b) * M₁ ^ b = (M₀ ^ (1 - θ) * M₁ ^ θ) ^ p := by
  have hp : 0 < p := ha.trans hap
  have hb : 0 < b := hp.trans hpb
  have hba : b - a ≠ 0 := by linarith
  have hθ' : θ = b * (p - a) / (p * (b - a)) := by
    field_simp at hθ
    rw [eq_div_iff (by positivity)]
    linear_combination hθ
  subst hθ'
  constructor
  · rw [← exp_log hM₀, ← exp_log hM₁]
    simp only [← exp_mul, ← exp_sub, ← exp_add]
    congr 1
    field_simp
    ring
  · rw [← exp_log hM₀, ← exp_log hM₁]
    simp only [← exp_mul, ← exp_sub, ← exp_add]
    congr 1
    field_simp
    ring

end ConstLemmas

/-! ### Chebyshev's inequality for `ℝ≥0∞`-valued functions -/

section Chebyshev

variable {Y : Type*} [MeasurableSpace Y] {ν : Measure Y}

theorem rti_measure_lt_le_eLpNorm {g : Y → ℝ≥0∞} {q t : ℝ} (hq : 0 < q) (ht : 0 < t) :
    ν {y | ENNReal.ofReal t < g y} ≤
      ENNReal.ofReal (t ^ (-q)) * eLpNorm g (ENNReal.ofReal q) ν ^ q := by
  have h := meas_ge_le_mul_pow_eLpNorm_enorm ν (p := ENNReal.ofReal q) (f := g)
    (by simpa using hq) ENNReal.ofReal_ne_top (ε := ENNReal.ofReal t)
    (by simpa using ht) (fun h => absurd h ENNReal.ofReal_ne_top)
  rw [ENNReal.toReal_ofReal hq.le] at h
  refine (measure_mono fun y (hy : ENNReal.ofReal t < g y) => ?_).trans (h.trans_eq ?_)
  · change ENNReal.ofReal t ≤ ‖g y‖ₑ
    rw [enorm_eq_self]
    exact hy.le
  · rw [← ENNReal.ofReal_inv_of_pos ht, ENNReal.ofReal_rpow_of_pos (inv_pos.mpr ht),
      inv_rpow ht.le, rpow_neg ht.le]

/-- A restricted strong-type bound at level `k` gives the distributional bound used in the core
estimate. -/
theorem rti_measure_lt_le_of_eLpNorm_le {g : Y → ℝ≥0∞} {q M : ℝ} {S : ℝ≥0∞} (hq : 0 < q)
    (hM : 0 ≤ M) (k : ℤ)
    (h : eLpNorm g (ENNReal.ofReal q) ν ≤ ENNReal.ofReal (M * 2 ^ ((k : ℝ) + 1)) * S ^ (1 / q))
    {t : ℝ} (ht : 0 < t) :
    ν {y | ENNReal.ofReal t < g y} ≤
      ENNReal.ofReal (t ^ (-q) * (2 * M) ^ q * 2 ^ ((k : ℝ) * q)) * S := by
  refine (rti_measure_lt_le_eLpNorm hq ht).trans ?_
  calc ENNReal.ofReal (t ^ (-q)) * eLpNorm g (ENNReal.ofReal q) ν ^ q
      ≤ ENNReal.ofReal (t ^ (-q)) * (ENNReal.ofReal (M * 2 ^ ((k : ℝ) + 1)) * S ^ (1 / q)) ^ q := by
        gcongr
    _ = ENNReal.ofReal (t ^ (-q) * (2 * M) ^ q * 2 ^ ((k : ℝ) * q)) * S := by
        rw [ENNReal.mul_rpow_of_nonneg _ _ hq.le, ← ENNReal.rpow_mul, one_div_mul_cancel hq.ne',
          ENNReal.rpow_one, ENNReal.ofReal_rpow_of_nonneg (by positivity) hq.le, ← mul_assoc,
          ← ENNReal.ofReal_mul (by positivity)]
        congr 2
        rw [rpow_add two_pos, rpow_one, rpow_mul (by norm_num : (0 : ℝ) ≤ 2),
          show M * (2 ^ (k : ℝ) * 2) = (2 * M) * 2 ^ (k : ℝ) by ring,
          mul_rpow (by positivity) (by positivity), mul_assoc]

end Chebyshev

/-! ### The dyadic level decomposition -/

section Levels

variable {X E : Type*} [MeasurableSpace X] [NormedAddCommGroup E] {μ : Measure X}

/-- The dyadic level set `{2^k < ‖f‖ ≤ 2^(k+1)}`. -/
def rtiLevel (f : X → E) (k : ℤ) : Set X :=
  {x | (2 : ℝ) ^ (k : ℝ) < ‖f x‖ ∧ ‖f x‖ ≤ 2 ^ ((k : ℝ) + 1)}

/-- The dyadic piece `f 𝟙_{2^k < ‖f‖ ≤ 2^(k+1)}`. -/
def rtiPiece (f : X → E) (k : ℤ) : X → E :=
  fun x => if (2 : ℝ) ^ (k : ℝ) < ‖f x‖ ∧ ‖f x‖ ≤ 2 ^ ((k : ℝ) + 1) then f x else 0

omit [MeasurableSpace X] in
theorem rti_level_unique {f : X → E} {x : X} {k k' : ℤ} (h : x ∈ rtiLevel f k)
    (h' : x ∈ rtiLevel f k') : k = k' := by
  have key : ∀ {k k' : ℤ}, x ∈ rtiLevel f k → x ∈ rtiLevel f k' → k ≤ k' := by
    intro k k' h h'
    have hlt : (2 : ℝ) ^ (k : ℝ) < 2 ^ ((k' : ℝ) + 1) := h.1.trans_le h'.2
    rw [rpow_lt_rpow_left_iff one_lt_two] at hlt
    have : (k : ℝ) < ((k' + 1 : ℤ) : ℝ) := by push_cast; exact hlt
    exact Int.lt_add_one_iff.mp (by exact_mod_cast this)
  exact le_antisymm (key h h') (key h' h)

omit [MeasurableSpace X] in
theorem rti_exists_level {f : X → E} {x : X} (hx : f x ≠ 0) : ∃ k, x ∈ rtiLevel f k := by
  obtain ⟨n, hn1, hn2⟩ := exists_mem_Ioc_zpow (norm_pos_iff.mpr hx) one_lt_two
  refine ⟨n, ?_, ?_⟩
  · rw [rpow_intCast]; exact hn1
  · rw [← Int.cast_one, ← Int.cast_add, rpow_intCast]; exact hn2

omit [MeasurableSpace X] in
theorem rtiPiece_apply_of_mem {f : X → E} {x : X} {k : ℤ} (h : x ∈ rtiLevel f k) :
    rtiPiece f k x = f x := by
  unfold rtiPiece; split_ifs with h'
  · rfl
  · exact absurd h h'

omit [MeasurableSpace X] in
theorem rtiPiece_apply_of_notMem {f : X → E} {x : X} {k : ℤ} (h : x ∉ rtiLevel f k) :
    rtiPiece f k x = 0 := by
  unfold rtiPiece; split_ifs with h'
  · exact absurd h' h
  · rfl

omit [MeasurableSpace X] in
theorem rti_tsum_piece (f : X → E) (x : X) : f x = ∑' k, rtiPiece f k x := by
  by_cases hx : f x = 0
  · have : ∀ k, rtiPiece f k x = 0 := fun k => by
      unfold rtiPiece; split_ifs <;> simp [hx]
    simp [this, hx]
  obtain ⟨k, hk⟩ := rti_exists_level hx
  rw [tsum_eq_single k fun k' hk' => rtiPiece_apply_of_notMem fun h => hk' (rti_level_unique h hk),
    rtiPiece_apply_of_mem hk]

omit [MeasurableSpace X] in
theorem rti_support_piece_subset (f : X → E) (k : ℤ) :
    Function.support (rtiPiece f k) ⊆ rtiLevel f k := by
  intro x hx
  by_contra h
  exact hx (rtiPiece_apply_of_notMem h)

omit [MeasurableSpace X] in
theorem rti_pairwise_disjoint_support (f : X → E) :
    Pairwise fun i j => Disjoint (Function.support (rtiPiece f i))
      (Function.support (rtiPiece f j)) := by
  intro i j hij
  refine Set.disjoint_left.mpr fun x hi hj => hij ?_
  exact rti_level_unique (rti_support_piece_subset f i hi) (rti_support_piece_subset f j hj)

theorem rti_norm_piece_le (f : X → E) (k : ℤ) (x : X) :
    ‖rtiPiece f k x‖ ≤
      2 ^ ((k : ℝ) + 1) * (toMeasurable μ (rtiLevel f k)).indicator 1 x := by
  by_cases h : x ∈ rtiLevel f k
  · rw [rtiPiece_apply_of_mem h, indicator_of_mem (subset_toMeasurable μ _ h)]
    simpa using h.2
  · rw [rtiPiece_apply_of_notMem h, norm_zero]
    exact mul_nonneg (by positivity) (indicator_nonneg (fun _ _ => zero_le_one) _)

theorem rti_nullMeasurableSet_level {f : X → E} (hf : AEStronglyMeasurable f μ) (k : ℤ) :
    NullMeasurableSet (rtiLevel f k) μ :=
  (nullMeasurableSet_lt aemeasurable_const hf.norm.aemeasurable).inter
    (nullMeasurableSet_le hf.norm.aemeasurable aemeasurable_const)

/-- `∑_k 2^(k p) μ(E_k) ≤ ∫ ‖f‖^p` for the dyadic level sets `E_k` of `f`. -/
theorem rti_tsum_level_le {f : X → E} (hf : AEStronglyMeasurable f μ) {p : ℝ} (hp : 0 < p) :
    ∑' k : ℤ, ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * μ (rtiLevel f k) ≤
      ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  have hpt : ∀ x, ∑' k : ℤ, (rtiLevel f k).indicator
      (fun _ => ENNReal.ofReal (2 ^ ((k : ℝ) * p))) x ≤ ‖f x‖ₑ ^ p := by
    intro x
    by_cases hx : ∃ k, x ∈ rtiLevel f k
    · obtain ⟨k, hk⟩ := hx
      rw [tsum_eq_single k fun k' hk' =>
        indicator_of_notMem (fun h => hk' (rti_level_unique h hk)) _, indicator_of_mem hk,
        ← ofReal_norm, ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) hp.le]
      refine ENNReal.ofReal_le_ofReal ?_
      rw [rpow_mul (by norm_num : (0 : ℝ) ≤ 2)]
      exact rpow_le_rpow (by positivity) hk.1.le hp.le
    · simp only [not_exists] at hx
      simp [indicator_of_notMem (hx _)]
  calc ∑' k : ℤ, ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * μ (rtiLevel f k)
      = ∫⁻ x, ∑' k : ℤ, (rtiLevel f k).indicator
          (fun _ => ENNReal.ofReal (2 ^ ((k : ℝ) * p))) x ∂μ := by
        rw [lintegral_tsum fun k => aemeasurable_const.indicator₀
          (rti_nullMeasurableSet_level hf k)]
        congr 1
        funext k
        rw [lintegral_indicator_const₀ (rti_nullMeasurableSet_level hf k)]
    _ ≤ _ := lintegral_mono hpt

end Levels

/-! ### Interpolation -/

section Interpolation

variable {X Y E : Type*} [MeasurableSpace X] [MeasurableSpace Y] [NormedAddCommGroup E]
  {μ : Measure X} {ν : Measure Y}

/-- `D` is closed under the level truncations `f ↦ f 𝟙_{s < ‖f‖ ≤ t}`, `0 ≤ s < t`. -/
def IsLevelTruncationClosed (D : Set (X → E)) : Prop :=
  ∀ f ∈ D, ∀ s t : ℝ, 0 ≤ s → s < t →
    (fun x => if s < ‖f x‖ ∧ ‖f x‖ ≤ t then f x else 0) ∈ D

/-- `T` is countably sublinear on disjoint decompositions in `D`: if `f = ∑_k f_k` pointwise with
`f, f_k ∈ D` and the `f_k` have pairwise disjoint supports, then `T f ≤ ∑_k T f_k` a.e. -/
def IsDisjointSublinearOn (T : (X → E) → Y → ℝ≥0∞) (D : Set (X → E)) (ν : Measure Y) : Prop :=
  ∀ f ∈ D, ∀ F : ℤ → X → E, (∀ k, F k ∈ D) →
    Pairwise (fun i j => Disjoint (Function.support (F i)) (Function.support (F j))) →
    (∀ x, f x = ∑' k, F k x) → ∀ᵐ y ∂ν, T f y ≤ ∑' k, T (F k) y

/-- `T` is of restricted strong type `(q, q)` with constant `M` on `D`: for every measurable `E`
with `μ E < ∞`, every `c ≥ 0` and every `g ∈ D` with `‖g‖ ≤ c 𝟙_E`,
`‖T g‖_{L^q(ν)} ≤ M c μ(E)^(1/q)`. -/
def HasRestrictedStrongTypeOn (T : (X → E) → Y → ℝ≥0∞) (D : Set (X → E)) (q M : ℝ)
    (μ : Measure X) (ν : Measure Y) : Prop :=
  ∀ S : Set X, MeasurableSet S → μ S < ∞ → ∀ c : ℝ, 0 ≤ c → ∀ g ∈ D,
    (∀ x, ‖g x‖ ≤ c * S.indicator 1 x) →
    eLpNorm (T g) (ENNReal.ofReal q) ν ≤ ENNReal.ofReal (M * c) * μ S ^ (1 / q)

/-- The interpolation estimate with a free scaling parameter `λ > 0`, for `∫ ‖f‖^p < ∞`. -/
theorem rti_lintegral_rpow_le_of_restrictedType {T : (X → E) → Y → ℝ≥0∞} {D : Set (X → E)}
    {a b p lam M₀ M₁ : ℝ} (ha : 0 < a) (hap : a < p) (hpb : p < b) (hlam : 0 < lam)
    (hM₀ : 0 ≤ M₀) (hM₁ : 0 ≤ M₁)
    (hDm : ∀ f ∈ D, AEStronglyMeasurable f μ) (hDtr : IsLevelTruncationClosed D)
    (hsub : IsDisjointSublinearOn T D ν) (h₀ : HasRestrictedStrongTypeOn T D a M₀ μ ν)
    (h₁ : HasRestrictedStrongTypeOn T D b M₁ μ ν) {f : X → E} (hf : f ∈ D)
    (hfin : ∫⁻ x, ‖f x‖ₑ ^ p ∂μ ≠ ∞) :
    ∫⁻ y, T f y ^ p ∂ν ≤
      ENNReal.ofReal (2 ^ p * rtiSeries (rtiDelta a b p) *
        (lam ^ (p - a) * rtiSeries (rtiGamma a b p) ^ a * (2 * M₀) ^ a +
          lam ^ (p - b) * rtiSeries (rtiGamma a b p) ^ b * (2 * M₁) ^ b)) *
      ∫⁻ x, ‖f x‖ₑ ^ p ∂μ := by
  have hp : 0 < p := ha.trans hap
  have hb : 0 < b := hp.trans hpb
  have hfm := hDm f hf
  have hpieceD : ∀ k, rtiPiece f k ∈ D := fun k =>
    hDtr f hf _ _ (by positivity) (rpow_lt_rpow_of_exponent_lt one_lt_two (by linarith))
  have hlev : ∀ k : ℤ, μ (rtiLevel f k) < ∞ := by
    intro k
    have h1 : ENNReal.ofReal (2 ^ ((k : ℝ) * p)) * μ (rtiLevel f k) ≤ ∫⁻ x, ‖f x‖ₑ ^ p ∂μ :=
      (ENNReal.le_tsum (f := fun k : ℤ => ENNReal.ofReal (2 ^ ((k : ℝ) * p)) *
        μ (rtiLevel f k)) k).trans (rti_tsum_level_le hfm hp)
    refine ENNReal.lt_top_of_mul_ne_top_right (ne_top_of_le_ne_top hfin h1) ?_
    rw [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    positivity
  have hdist : ∀ (q M : ℝ), 0 < q → 0 ≤ M → HasRestrictedStrongTypeOn T D q M μ ν →
      ∀ k : ℤ, ∀ t : ℝ, 0 < t → ν {y | ENNReal.ofReal t < T (rtiPiece f k) y} ≤
        ENNReal.ofReal (t ^ (-q) * (2 * M) ^ q * 2 ^ ((k : ℝ) * q)) * μ (rtiLevel f k) := by
    intro q M hq hM h k t ht
    refine rti_measure_lt_le_of_eLpNorm_le hq hM k ?_ ht
    have := h (toMeasurable μ (rtiLevel f k)) (measurableSet_toMeasurable _ _)
      (by rw [measure_toMeasurable]; exact hlev k) _ (by positivity) _ (hpieceD k)
      (rti_norm_piece_le f k)
    rwa [measure_toMeasurable] at this
  have hdom : ∀ᵐ y ∂ν, T f y ≤ ∑' k, T (rtiPiece f k) y :=
    hsub f hf _ hpieceD (rti_pairwise_disjoint_support f) (rti_tsum_piece f)
  calc ∫⁻ y, T f y ^ p ∂ν
      ≤ ∫⁻ y, (∑' k, T (rtiPiece f k) y) ^ p ∂ν :=
        lintegral_mono_ae (hdom.mono fun y hy => ENNReal.rpow_le_rpow hy hp.le)
    _ ≤ _ := rti_lintegral_tsum_rpow_le ν _ _ hp (rtiGamma_pos ha hap hpb)
        (rtiDelta_pos hap hpb) (rti_gamma_delta_low ha) (rti_gamma_delta_high ha hap hpb)
        hlam (by positivity) (by positivity) (hdist a M₀ ha hM₀ h₀) (hdist b M₁ hb hM₁ h₁)
    _ ≤ _ := by gcongr; exact rti_tsum_level_le hfm hp

/-- **Interpolation of operators of restricted strong type.** Let `T` map functions on `(X, μ)`
to nonnegative functions on `(Y, ν)`, be countably sublinear on disjoint decompositions in a class
`D` of a.e. strongly measurable functions closed under level truncations, and of restricted
strong type `(p₀, p₀)` and `(p₁, p₁)` with constants `M₀, M₁ > 0`, where `0 < p₀ < p < p₁ < ∞`.
Then for every `f ∈ D` with `T f` a.e. strongly measurable,
`‖T f‖_{L^p(ν)} ≤ C(p₀, p₁, p) M₀^(1-θ) M₁^θ ‖f‖_{L^p(μ)}`, `1/p = (1-θ)/p₀ + θ/p₁`,
with the explicit constant `C(p₀, p₁, p) = rtiConst p₀ p₁ p`. -/
theorem eLpNorm_le_of_restrictedType {T : (X → E) → Y → ℝ≥0∞} {D : Set (X → E)}
    {p₀ p₁ p θ M₀ M₁ : ℝ} (hp₀ : 0 < p₀) (hp₀p : p₀ < p) (hpp₁ : p < p₁)
    (hθ : 1 / p = (1 - θ) / p₀ + θ / p₁) (hM₀ : 0 < M₀) (hM₁ : 0 < M₁)
    (hDm : ∀ f ∈ D, AEStronglyMeasurable f μ) (hDtr : IsLevelTruncationClosed D)
    (hsub : IsDisjointSublinearOn T D ν) (h₀ : HasRestrictedStrongTypeOn T D p₀ M₀ μ ν)
    (h₁ : HasRestrictedStrongTypeOn T D p₁ M₁ μ ν) {f : X → E} (hf : f ∈ D)
    (hTf : AEStronglyMeasurable (T f) ν) :
    eLpNorm (T f) (ENNReal.ofReal p) ν ≤
      ENNReal.ofReal (rtiConst p₀ p₁ p * M₀ ^ (1 - θ) * M₁ ^ θ) *
        eLpNorm f (ENNReal.ofReal p) μ := by
  have hp : 0 < p := hp₀.trans hp₀p
  have hp' : ENNReal.ofReal p ≠ 0 := by simpa using hp
  have hfm := hDm f hf
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp' ENNReal.ofReal_ne_top hTf,
    eLpNorm_eq_lintegral_rpow_enorm_toReal hp' ENNReal.ofReal_ne_top hfm,
    ENNReal.toReal_ofReal hp.le]
  simp only [enorm_eq_self]
  have hC := rtiConst_pos hp₀ hp₀p hpp₁
  have hN : 0 < rtiConst p₀ p₁ p * M₀ ^ (1 - θ) * M₁ ^ θ := by positivity
  by_cases hfin : ∫⁻ x, ‖f x‖ₑ ^ p ∂μ = ∞
  · rw [hfin, ENNReal.top_rpow_of_pos (by positivity), ENNReal.mul_top (by simpa using hN)]
    exact le_top
  obtain ⟨key₀, key₁⟩ := rti_scaling_identity hp₀ hp₀p hpp₁ hθ hM₀ hM₁
  have hW := rtiSeries_pos (rtiGamma_pos hp₀ hp₀p hpp₁)
  have hΨ := rtiSeries_pos (rtiDelta_pos (b := p₁) hp₀p hpp₁)
  have hCp : rtiConst p₀ p₁ p ^ p = 2 ^ p * (rtiSeries (rtiDelta p₀ p₁ p) *
      ((2 * rtiSeries (rtiGamma p₀ p₁ p)) ^ p₀ + (2 * rtiSeries (rtiGamma p₀ p₁ p)) ^ p₁)) := by
    rw [rtiConst, mul_rpow (by norm_num) (by positivity), ← rpow_mul (by positivity),
      one_div_mul_cancel hp.ne', rpow_one]
  set lam : ℝ := (M₁ ^ p₁ / M₀ ^ p₀) ^ (1 / (p₁ - p₀)) with hlam_def
  have hlam : 0 < lam := by positivity
  have hbound := rti_lintegral_rpow_le_of_restrictedType hp₀ hp₀p hpp₁ hlam hM₀.le hM₁.le hDm
    hDtr hsub h₀ h₁ hf hfin
  have hK : 2 ^ p * rtiSeries (rtiDelta p₀ p₁ p) *
      (lam ^ (p - p₀) * rtiSeries (rtiGamma p₀ p₁ p) ^ p₀ * (2 * M₀) ^ p₀ +
        lam ^ (p - p₁) * rtiSeries (rtiGamma p₀ p₁ p) ^ p₁ * (2 * M₁) ^ p₁) =
      (rtiConst p₀ p₁ p * M₀ ^ (1 - θ) * M₁ ^ θ) ^ p := by
    rw [mul_assoc (rtiConst p₀ p₁ p), mul_rpow hC.le (by positivity), hCp,
      mul_rpow (by norm_num : (0 : ℝ) ≤ 2) hM₀.le, mul_rpow (by norm_num : (0 : ℝ) ≤ 2) hM₁.le,
      mul_rpow (by norm_num : (0 : ℝ) ≤ 2) hW.le, mul_rpow (by norm_num : (0 : ℝ) ≤ 2) hW.le]
    linear_combination (2 ^ p * rtiSeries (rtiDelta p₀ p₁ p) * 2 ^ p₀ *
      rtiSeries (rtiGamma p₀ p₁ p) ^ p₀) * key₀ + (2 ^ p * rtiSeries (rtiDelta p₀ p₁ p) *
      2 ^ p₁ * rtiSeries (rtiGamma p₀ p₁ p) ^ p₁) * key₁
  rw [hK] at hbound
  calc (∫⁻ y, T f y ^ p ∂ν) ^ (1 / p)
      ≤ (ENNReal.ofReal ((rtiConst p₀ p₁ p * M₀ ^ (1 - θ) * M₁ ^ θ) ^ p) *
          ∫⁻ x, ‖f x‖ₑ ^ p ∂μ) ^ (1 / p) := by gcongr
    _ = _ := by
        rw [ENNReal.mul_rpow_of_nonneg _ _ (by positivity),
          ← ENNReal.ofReal_rpow_of_nonneg (by positivity) hp.le, ← ENNReal.rpow_mul,
          mul_one_div_cancel hp.ne', ENNReal.rpow_one]

end Interpolation

end

end Auto
