/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import VariationalSW.Auto.Sec4ShortJumpEstimatesLargeP

/-!
# Section 5 of Guo–Roos–Yung: short jump estimates for p ≤ 2

This file was automatically generated by Claude.

Part of the formalization of S. Guo, J. Roos, P.-L. Yung, *Sharp variation-norm estimates for
oscillatory integrals related to Carleson's theorem*, Anal. PDE 13 (2020), arXiv:1710.10988v3,
Section 5 (`section:short-jump-small`).

## Contents and source mapping

* **Seeger's constant for `p ≤ 2`**: `seeger_rhs_smul_le_two` (homogeneity) and
  `seeger_rhs_le_le_two` (the decay `λ^{1/2 - n/p'}`, paper (`eq:square_fcn_4`) and the display
  after it).
* **Case 1 single pieces for `1 < p ≤ 2`**:
  `IsHomogeneousCZKernel.eLpNorm_shortPieceVar_le_of_le_two`.
* **The Case 1 sum** and **(`eq:mainest_Sect5`)**:
  `IsHomogeneousCZKernel.tsum_eLpNorm_shortPieceVar_case1_le_of_le_two`,
  `IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_le_two`.
* **All `p > 2n/(2n-1)`** (Prop 1.5 for `n ≥ 2`, any `r ≥ 2`):
  `IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_two_le_n_all`, with `ℝ≥0`-constant versions
  (`..._nnreal`), and the `n = 1` restatement
  `IsHomogeneousCZKernel.eLpNorm_shortVariation_le_n_one'`.

## Route

As prescribed by `automation/instructions.md` (route item 3), Case 1 for `p ≤ 2` is proved with the
vector-valued Seeger-type theorem for `1 < p ≤ 2` (`seeger_le_two`: weak type (1,1) with constant
`A₁ log(2 + B/A₁)` plus `L²` plus Marcinkiewicz) and the `V²`-embedding
(`IsHomogeneousCZKernel.eLpNorm_shortPieceVar_le_of_sgrSq`), instead of the paper's Prop 5.1 /
Thm 5.2 (Hardy space `H¹`, complex interpolation). This also repairs the source's use of Prop 4.2
(stated only for `p ≥ 2`) for `p < 2`; see `automation/ErrorReport.md`.
-/

@[expose] public section

namespace Auto

open MeasureTheory Complex Filter Set
open scoped ENNReal NNReal SchwartzMap

noncomputable section

/-! ## Seeger's constant for `p ≤ 2` -/

/-- Seeger's constant `(A log(2 + B/A) + A₂)^{2/p-1} A₂^{2-2/p}` for `p ≤ 2` is homogeneous of
degree one in `(A, A₂, B)` (used for `∂_v k_{ℓ,k}`, paper §5, Case 1). -/
theorem seeger_rhs_smul_le_two {p s A A₂ B : ℝ} (hs : 0 < s) (hA : 0 < A) (hA₂ : 0 < A₂)
    (hB : 0 ≤ B) :
    (s * A * Real.log (2 + s * B / (s * A)) + s * A₂) ^ (2 / p - 1) * (s * A₂) ^ (2 - 2 / p) =
      s * ((A * Real.log (2 + B / A) + A₂) ^ (2 / p - 1) * A₂ ^ (2 - 2 / p)) := by
  have hL : 0 ≤ Real.log (2 + B / A) := Real.log_nonneg (by
    have : 0 ≤ B / A := by positivity
    linarith)
  rw [mul_div_mul_left _ _ hs.ne', show s * A * Real.log (2 + B / A) + s * A₂ =
    s * (A * Real.log (2 + B / A) + A₂) by ring, Real.mul_rpow hs.le (by positivity),
    Real.mul_rpow hs.le hA₂.le]
  have : s ^ (2 / p - 1) * s ^ (2 - 2 / p) = s := by
    rw [← Real.rpow_add hs]; norm_num
  calc s ^ (2 / p - 1) * (A * Real.log (2 + B / A) + A₂) ^ (2 / p - 1) *
        (s ^ (2 - 2 / p) * A₂ ^ (2 - 2 / p))
      = (s ^ (2 / p - 1) * s ^ (2 - 2 / p)) *
          ((A * Real.log (2 + B / A) + A₂) ^ (2 / p - 1) * A₂ ^ (2 - 2 / p)) := by ring
    _ = _ := by rw [this]

/-- **The decay of Seeger's constant in Case 1 for `1 < p ≤ 2`** (paper (`eq:square_fcn_4`) and
the display after it): with `A₁ = K`, `A₂ = K λ^{-n/2}`, `λ ≥ 1`,
`λ^{1/2} (A₁ L + A₂)^{2/p-1} A₂^{2-2/p} ≤ K (L + 1) λ^{-(n(1-1/p) - 1/2)}`
(`n(1 - 1/p) = n/p'`). -/
theorem seeger_rhs_le_le_two (n : ℕ) {p K L lam : ℝ} (hp1 : 1 < p) (hp2 : p ≤ 2) (hK : 0 < K)
    (hL : 0 ≤ L) (hlam : 1 ≤ lam) :
    lam ^ (1 / 2 : ℝ) * ((K * L + K * lam ^ (-(n : ℝ) / 2)) ^ (2 / p - 1) *
      (K * lam ^ (-(n : ℝ) / 2)) ^ (2 - 2 / p)) ≤
      K * (L + 1) * lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2)) := by
  have hl0 : 0 < lam := by linarith
  have hp0 : 0 < p := by linarith
  have hθ0 : 0 ≤ 2 / p - 1 := by rw [sub_nonneg, le_div_iff₀ hp0]; linarith
  have hθ1 : 2 / p - 1 ≤ 1 := by rw [sub_le_iff_le_add, div_le_iff₀ hp0]; linarith
  have hn0 : (0 : ℝ) ≤ n := Nat.cast_nonneg n
  set b := lam ^ (-(n : ℝ) / 2)
  have hb : 0 < b := by positivity
  have hb1 : b ≤ 1 := Real.rpow_le_one_of_one_le_of_nonpos hlam (by linarith)
  have h1 : K * L + K * b ≤ K * (L + 1) := by nlinarith
  have h2 : (K * L + K * b) ^ (2 / p - 1) ≤ (K * (L + 1)) ^ (2 / p - 1) :=
    Real.rpow_le_rpow (by positivity) h1 hθ0
  have h3 : (L + 1) ^ (2 / p - 1) ≤ L + 1 := by
    calc (L + 1) ^ (2 / p - 1) ≤ (L + 1) ^ (1 : ℝ) :=
          Real.rpow_le_rpow_of_exponent_le (by linarith) hθ1
      _ = L + 1 := Real.rpow_one _
  have hexp : lam ^ (1 / 2 : ℝ) * b ^ (2 - 2 / p) =
      lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2)) := by
    simp only [b]
    rw [← Real.rpow_mul hl0.le, ← Real.rpow_add hl0]
    congr 1
    field_simp
    ring
  have hK' : K ^ (2 / p - 1) * K ^ (2 - 2 / p) = K := by rw [← Real.rpow_add hK]; norm_num
  calc lam ^ (1 / 2 : ℝ) * ((K * L + K * b) ^ (2 / p - 1) * (K * b) ^ (2 - 2 / p))
      ≤ lam ^ (1 / 2 : ℝ) * ((K * (L + 1)) ^ (2 / p - 1) * (K * b) ^ (2 - 2 / p)) := by
        gcongr
    _ = (K ^ (2 / p - 1) * K ^ (2 - 2 / p)) * (L + 1) ^ (2 / p - 1) *
          (lam ^ (1 / 2 : ℝ) * b ^ (2 - 2 / p)) := by
        rw [Real.mul_rpow hK.le (by linarith), Real.mul_rpow hK.le hb.le]
        ring
    _ ≤ K * (L + 1) * lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2)) := by
        rw [hK', hexp]
        gcongr

/-! ## Case 1 for `1 < p ≤ 2` (paper §5, Case 1) -/

set_option maxHeartbeats 1000000 in
-- The proof checks the hypotheses of the vector-valued Seeger theorem twice.
/-- **Case 1 single pieces for `1 < p ≤ 2`** (paper §5, Case 1, (`eq:square_fcn_4`); route:
`seeger_le_two` and the `V²`-embedding instead of Prop 4.2 / Thm 5.2): for `α > 1`, `r ≥ 2`,
`1 < p ≤ 2` there is `C` such that for all `ℓ ≥ 0`, all `k` and Schwartz `f`, with
`λ = 2^{ℓα}` and `L = log(2 + (2^{-k} + 2^{ℓ+1} + 2^k) λ^{1/2})`,
`‖(∑_j V^r_j(𝓗^{(u)}_{ℓ-j} P_{j+k} f)^r)^{1/r}‖_p ≤ C (L + 1) λ^{1/2 - n/p'} ‖f‖_p`. -/
theorem IsHomogeneousCZKernel.eLpNorm_shortPieceVar_le_of_le_two {n : ℕ} {Ω : Rn n → ℝ}
    (hΩ : IsHomogeneousCZKernel n Ω) (hn : 1 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ} (hr : 2 ≤ r)
    {p : ℝ} (hp1 : 1 < p) (hp2 : p ≤ 2) :
    ∃ C : ℝ, 0 < C ∧ ∀ ℓ k : ℤ, 0 ≤ ℓ → ∀ f : 𝓢(Rn n, ℂ),
      eLpNorm (shortPieceVar r n α Ω ℓ k f) (ENNReal.ofReal p) ≤
        ENNReal.ofReal (C * (Real.log (2 + case1Scale ℓ k * dyadicPoint α ℓ ^ (1 / 2 : ℝ)) + 1) *
          dyadicPoint α ℓ ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2))) *
            eLpNorm f (ENNReal.ofReal p) := by
  have hα0 : 0 < α := by linarith
  have hp0 : 0 < p := by linarith
  obtain ⟨CS, hCS, hSeeger⟩ := seeger_le_two (n := n) (by omega) hp1 hp2
  obtain ⟨C2, hC2, hH2⟩ := hΩ.case1_H2 hα
  obtain ⟨A1, B0, hA1, hB0, hL1⟩ := hΩ.case1_L1 hα0.le
  have h2α : (1 : ℝ) ≤ 2 ^ α := Real.one_le_rpow (by norm_num) hα0.le
  obtain ⟨K, hK⟩ : ∃ K : ℝ, K = √C2 + (A1 + B0) * 2 ^ α + 1 := ⟨_, rfl⟩
  have hK0 : 0 < K := by rw [hK]; positivity
  have hKC2 : C2 ≤ K ^ 2 := by
    have : √C2 ≤ K := by rw [hK]; nlinarith
    calc C2 = √C2 ^ 2 := (Real.sq_sqrt hC2.le).symm
      _ ≤ K ^ 2 := pow_le_pow_left₀ (Real.sqrt_nonneg _) this 2
  have hKA : A1 * 2 ^ α ≤ K := by rw [hK]; have := Real.sqrt_nonneg C2; nlinarith
  have hKB : B0 * 2 ^ α ≤ K := by rw [hK]; have := Real.sqrt_nonneg C2; nlinarith
  have hKA' : A1 ≤ K := le_trans (le_mul_of_one_le_right hA1.le h2α) hKA
  have hKB' : B0 ≤ K := le_trans (le_mul_of_one_le_right hB0.le h2α) hKB
  refine ⟨√32 * CS * K, by positivity, fun ℓ k hℓ f => ?_⟩
  obtain ⟨lam, hlam⟩ : ∃ lam, lam = dyadicPoint α ℓ := ⟨_, rfl⟩
  have hl0 : 0 < lam := hlam ▸ dyadicPoint_pos α ℓ
  have hl1 : 1 ≤ lam := by
    rw [hlam]; exact Real.one_le_rpow (by norm_num) (by positivity)
  obtain ⟨S, hS⟩ : ∃ S, S = case1Scale ℓ k := ⟨_, rfl⟩
  have hS0 : 0 < S := hS ▸ case1Scale_pos ℓ k
  have hfp : MemLp (f : Rn n → ℂ) (ENNReal.ofReal p) := f.memLp _
  have hf2 : MemLp (f : Rn n → ℂ) 2 := f.memLp _
  set A₂ := K * lam ^ (-(n : ℝ) / 2)
  have hA₂ : 0 < A₂ := by positivity
  -- the parameters for `k_{ℓ,k}`: `A₁ = K`, `B = K S`, `A₂ = K λ^{-n/2}`
  have hX : ∀ J : Finset ℤ, eLpNorm (sgrSq (uMeasure α) (case1Ker hΩ α ℓ k) J f)
      (ENNReal.ofReal p) ≤ ENNReal.ofReal (CS * ((K * Real.log (2 + K * S / K) + A₂) ^
        (2 / p - 1) * A₂ ^ (2 - 2 / p))) * eLpNorm f (ENNReal.ofReal p) := by
    intro J
    have := hSeeger (uMeasure α) (case1Ker hΩ α ℓ k) J K A₂ (K * S) hK0 hA₂ (by positivity)
      (fun j => (hΩ.measurable_case1Ker α ℓ k j).1) ?_ ?_ ?_ ?_ f hfp hf2
    · refine this.trans (le_of_eq ?_); rw [mul_assoc]
    · intro g hg
      refine (hH2 ℓ k J g hg).1.trans (mul_le_mul' (ENNReal.ofReal_le_ofReal ?_) le_rfl)
      rw [← hlam, mul_pow, ← Real.rpow_natCast (lam ^ (-(n : ℝ) / 2)) 2,
        ← Real.rpow_mul hl0.le, show -(n : ℝ) / 2 * ((2 : ℕ) : ℝ) = -n by push_cast; ring]
      exact mul_le_mul_of_nonneg_right hKC2 (by positivity)
    · intro j _ R hR
      refine ((hL1 ℓ k j _ 0 (Or.inl ⟨rfl, rfl⟩)).2.1 R (by linarith)).trans
        (ENNReal.ofReal_le_ofReal ?_)
      rw [← hS, mul_zero, Real.rpow_zero, mul_one]
      gcongr
    · intro j _ y
      refine ((hL1 ℓ k j _ 0 (Or.inl ⟨rfl, rfl⟩)).2.2 y).trans (ENNReal.ofReal_le_ofReal ?_)
      rw [← hS, mul_zero, Real.rpow_zero, mul_one]
      gcongr
    · intro j _
      refine ((hL1 ℓ k j _ 0 (Or.inl ⟨rfl, rfl⟩)).1).trans (ENNReal.ofReal_le_ofReal ?_)
      rw [mul_zero, Real.rpow_zero, mul_one]
      exact hKA'
  -- the parameters for `∂_v k_{ℓ,k}`: `λ` times those for `k_{ℓ,k}`
  have hY : ∀ J : Finset ℤ, eLpNorm (sgrSq (uMeasure α) (case1KerD n α Ω ℓ k) J f)
      (ENNReal.ofReal p) ≤ ENNReal.ofReal (CS * (lam * ((K * Real.log (2 + K * S / K) + A₂) ^
        (2 / p - 1) * A₂ ^ (2 - 2 / p)))) * eLpNorm f (ENNReal.ofReal p) := by
    intro J
    have := hSeeger (uMeasure α) (case1KerD n α Ω ℓ k) J (lam * K) (lam * A₂) (lam * (K * S))
      (by positivity) (by positivity) (by positivity)
      (fun j => (hΩ.measurable_case1Ker α ℓ k j).2) ?_ ?_ ?_ ?_ f hfp hf2
    · refine this.trans (le_of_eq ?_)
      rw [← seeger_rhs_smul_le_two hl0 hK0 hA₂ (by positivity), mul_assoc]
    · intro g hg
      refine (hH2 ℓ k J g hg).2.trans (mul_le_mul' (ENNReal.ofReal_le_ofReal ?_) le_rfl)
      rw [← hlam, mul_pow, mul_pow, ← Real.rpow_natCast (lam ^ (-(n : ℝ) / 2)) 2,
        ← Real.rpow_mul hl0.le, show -(n : ℝ) / 2 * ((2 : ℕ) : ℝ) = -n by push_cast; ring]
      nlinarith [mul_le_mul_of_nonneg_right hKC2
        (by positivity : 0 ≤ lam ^ 2 * lam ^ (-(n : ℝ)))]
    · intro j _ R hR
      refine ((hL1 ℓ k j _ α (Or.inr ⟨rfl, rfl⟩)).2.1 R (by linarith)).trans
        (ENNReal.ofReal_le_ofReal ?_)
      rw [← hS, two_rpow_add_one_mul, ← hlam]
      have : B0 * (2 ^ α * lam) * S ≤ lam * (K * S) := by
        calc B0 * (2 ^ α * lam) * S = (B0 * 2 ^ α) * (lam * S) := by ring
          _ ≤ K * (lam * S) := mul_le_mul_of_nonneg_right hKB (by positivity)
          _ = lam * (K * S) := by ring
      exact div_le_div_of_nonneg_right this (by linarith)
    · intro j _ y
      refine ((hL1 ℓ k j _ α (Or.inr ⟨rfl, rfl⟩)).2.2 y).trans (ENNReal.ofReal_le_ofReal ?_)
      rw [← hS, two_rpow_add_one_mul, ← hlam]
      have : B0 * (2 ^ α * lam) * S ≤ lam * (K * S) := by
        calc B0 * (2 ^ α * lam) * S = (B0 * 2 ^ α) * (lam * S) := by ring
          _ ≤ K * (lam * S) := mul_le_mul_of_nonneg_right hKB (by positivity)
          _ = lam * (K * S) := by ring
      exact mul_le_mul_of_nonneg_right this (norm_nonneg _)
    · intro j _
      refine ((hL1 ℓ k j _ α (Or.inr ⟨rfl, rfl⟩)).1).trans (ENNReal.ofReal_le_ofReal ?_)
      rw [two_rpow_add_one_mul, ← hlam]
      calc A1 * (2 ^ α * lam) = (A1 * 2 ^ α) * lam := by ring
        _ ≤ K * lam := mul_le_mul_of_nonneg_right hKA hl0.le
        _ = lam * K := by ring
  -- combine with the `V²` reduction
  have hKS : K * S / K = S := by field_simp
  set Q := (K * Real.log (2 + K * S / K) + A₂) ^ (2 / p - 1) * A₂ ^ (2 - 2 / p)
  have hL : 0 ≤ Real.log (2 + S) := Real.log_nonneg (by linarith)
  have hQ : 0 ≤ Q := by
    have : 0 ≤ Real.log (2 + K * S / K) := by rw [hKS]; exact hL
    positivity
  refine (hΩ.eLpNorm_shortPieceVar_le_of_sgrSq hα0 hr hp0 ℓ k f hX hY).trans
    (mul_le_mul' ?_ le_rfl)
  rw [← ENNReal.ofReal_ofNat, ← ENNReal.ofReal_mul (by norm_num), ← ENNReal.ofReal_mul
    (by positivity), ENNReal.ofReal_rpow_of_nonneg (by positivity) (by norm_num)]
  refine ENNReal.ofReal_le_ofReal ?_
  have hdec := seeger_rhs_le_le_two n hp1 hp2 hK0 hL hl1
  have hsq : (32 * (CS * Q) * (CS * (lam * Q))) ^ (1 / 2 : ℝ) =
      √32 * CS * (lam ^ (1 / 2 : ℝ) * Q) := by
    rw [show 32 * (CS * Q) * (CS * (lam * Q)) = (√32 * CS * Q) ^ 2 * lam by
      rw [mul_pow, mul_pow, Real.sq_sqrt (by norm_num)]; ring,
      Real.mul_rpow (by positivity) hl0.le, ← Real.sqrt_eq_rpow, Real.sqrt_sq (by positivity)]
    ring
  rw [hsq]
  have hlog : Real.log (2 + S) ≤ Real.log (2 + S * lam ^ (1 / 2 : ℝ)) := by
    refine Real.log_le_log (by linarith) ?_
    have : 1 ≤ lam ^ (1 / 2 : ℝ) := Real.one_le_rpow hl1 (by norm_num)
    nlinarith
  have hQ' : lam ^ (1 / 2 : ℝ) * Q ≤
      K * (Real.log (2 + S) + 1) * lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2)) := by
    simp only [Q, hKS]; exact hdec
  calc √32 * CS * (lam ^ (1 / 2 : ℝ) * Q)
      ≤ √32 * CS * (K * (Real.log (2 + S) + 1) *
          lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2))) := by gcongr
    _ ≤ √32 * CS * (K * (Real.log (2 + S * lam ^ (1 / 2 : ℝ)) + 1) *
          lam ^ (-((n : ℝ) * (1 - 1 / p) - 1 / 2))) := by gcongr
    _ = _ := by rw [hS, hlam]; ring

/-- The Case 1 decay exponent for `p ≤ 2`: `n/p' - 1/2 > 0` iff `p > 2n/(2n-1)`
(paper §5, display after (`eq:square_fcn_4`)). -/
theorem case1_exponent_pos_of_le_two {n : ℕ} (hn : 2 ≤ n) {p : ℝ} (hp1 : 1 < p)
    (hpn : 2 * n / (2 * n - 1) < p) : 0 < (n : ℝ) * (1 - 1 / p) - 1 / 2 := by
  have hn' : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hp0 : 0 < p := by linarith
  have hd : 0 < 2 * (n : ℝ) - 1 := by linarith
  rw [div_lt_iff₀ hd] at hpn
  have : (n : ℝ) * (1 - 1 / p) - 1 / 2 = ((2 * n - 1) * p - 2 * n) / (2 * p) := by
    field_simp; ring
  rw [this]
  exact div_pos (by linarith) (by positivity)

/-- **The Case 1 sum for `n ≥ 2`, `2n/(2n-1) < p ≤ 2`** (paper §5, Case 1):
`∑_{(ℓ,k) ∈ Case 1} ‖(∑_j V^r_j(𝓗^{(u)}_{ℓ-j} P_{j+k} f)^r)^{1/r}‖_p ≤ C₁ ‖f‖_p` (`r ≥ 2`). -/
theorem IsHomogeneousCZKernel.tsum_eLpNorm_shortPieceVar_case1_le_of_le_two {n : ℕ}
    {Ω : Rn n → ℝ} (hΩ : IsHomogeneousCZKernel n Ω) (hn : 2 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ}
    (hr : 2 ≤ r) {p : ℝ} (hpn : 2 * n / (2 * n - 1) < p) (hp2 : p ≤ 2) :
    ∃ C₁ : ℝ≥0∞, C₁ ≠ ∞ ∧ ∀ f : 𝓢(Rn n, ℂ),
      ∑' ℓ : ℤ, ∑' k : ℤ, case1RegionInd α ℓ k *
        eLpNorm (shortPieceVar r n α Ω ℓ k f) (ENNReal.ofReal p) ≤
        C₁ * eLpNorm f (ENNReal.ofReal p) := by
  have hn' : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hp1 : 1 < p := by
    refine lt_of_le_of_lt ?_ hpn
    rw [le_div_iff₀ (by linarith)]; linarith
  obtain ⟨C, hC, hpiece⟩ := hΩ.eLpNorm_shortPieceVar_le_of_le_two (by omega) hα hr hp1 hp2
  obtain ⟨C₁, hC₁, hsum⟩ :=
    case1_tsum_le_of_decay hα (case1_exponent_pos_of_le_two hn hp1 hpn) hC.le
  exact ⟨C₁, hC₁, fun f => hsum _ _ fun ℓ k h => hpiece ℓ k h.1 f⟩

/-- **The short variation estimate for `n ≥ 2`, `2n/(2n-1) < p ≤ 2`** (paper (`eq:mainest_Sect5`);
route item 3 of `automation/instructions.md`): for `α > 1` and `r ≥ 2` there is `C < ∞` such that
for all Schwartz `f`, `‖S_r(𝓗 f)‖_p ≤ C ‖f‖_p`, where `S_r` is the short variation
`(∑_j V^r_{J_j}(u ↦ 𝓗^{(u)}f)^r)^{1/r}`. The case `r = 2` is included. -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_le_two {n : ℕ} {Ω : Rn n → ℝ}
    (hΩ : IsHomogeneousCZKernel n Ω) (hn : 2 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ} (hr : 2 ≤ r)
    {p : ℝ} (hpn : 2 * n / (2 * n - 1) < p) (hp2 : p ≤ 2) :
    ∃ C : ℝ≥0∞, C ≠ ∞ ∧ ∀ f : 𝓢(Rn n, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI n α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) := by
  have hn' : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hp1 : 1 < p := by
    refine lt_of_le_of_lt ?_ hpn
    rw [le_div_iff₀ (by linarith)]; linarith
  obtain ⟨C, hC, hmain⟩ := hΩ.eLpNorm_shortVariation_le_of_case1 (by omega) hα hr hp1
  obtain ⟨C₁, hC₁, h1⟩ := hΩ.tsum_eLpNorm_shortPieceVar_case1_le_of_le_two hn hα hr hpn hp2
  exact ⟨C + C₁, ENNReal.add_ne_top.2 ⟨hC, hC₁⟩, fun f => hmain C₁ f (h1 f)⟩

/-! ## The short variation estimate for all `p > 2n/(2n-1)` -/

/-- **The short variation estimate for `n ≥ 2`, `2n/(2n-1) < p < ∞`** (paper (`eq:mainest_Sect4`)
and (`eq:mainest_Sect5`); this is Prop 1.5 for `p > 2n/(2n-1)`, `n ≥ 2`, including `r = 2`): for
`α > 1` and `r ≥ 2` there is `C < ∞` such that for all Schwartz `f`,
`‖S_r(𝓗 f)‖_p ≤ C ‖f‖_p`. -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_two_le_n_all {n : ℕ}
    {Ω : Rn n → ℝ} (hΩ : IsHomogeneousCZKernel n Ω) (hn : 2 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ}
    (hr : 2 ≤ r) {p : ℝ} (hpn : 2 * n / (2 * n - 1) < p) :
    ∃ C : ℝ≥0∞, C ≠ ∞ ∧ ∀ f : 𝓢(Rn n, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI n α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) := by
  rcases le_total p 2 with hp2 | hp2
  · exact hΩ.eLpNorm_shortVariation_le_of_le_two hn hα hr hpn hp2
  · exact hΩ.eLpNorm_shortVariation_le_of_two_le_n hn hα hr hp2

/-- Converting a constant `C ≠ ∞` into a constant in `ℝ≥0`. -/
theorem exists_nnreal_of_exists_ne_top {P : ℝ≥0∞ → Prop} (hP : ∃ C : ℝ≥0∞, C ≠ ∞ ∧ P C) :
    ∃ C : ℝ≥0, P C := by
  obtain ⟨C, hC, h⟩ := hP
  exact ⟨C.toNNReal, by rwa [ENNReal.coe_toNNReal hC]⟩

/-- `ℝ≥0`-constant version of
`IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_two_le_n_all` (paper (`eq:mainest_Sect4`),
(`eq:mainest_Sect5`); Prop 1.5 for `n ≥ 2`, `p > 2n/(2n-1)`). -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_two_le_n_all_nnreal {n : ℕ}
    {Ω : Rn n → ℝ} (hΩ : IsHomogeneousCZKernel n Ω) (hn : 2 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ}
    (hr : 2 ≤ r) {p : ℝ} (hpn : 2 * n / (2 * n - 1) < p) :
    ∃ C : ℝ≥0, ∀ f : 𝓢(Rn n, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI n α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) :=
  exists_nnreal_of_exists_ne_top (hΩ.eLpNorm_shortVariation_le_of_two_le_n_all hn hα hr hpn)

/-- `ℝ≥0`-constant version of `IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_le_two`
(paper (`eq:mainest_Sect5`)). -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_of_le_two_nnreal {n : ℕ}
    {Ω : Rn n → ℝ} (hΩ : IsHomogeneousCZKernel n Ω) (hn : 2 ≤ n) {α : ℝ} (hα : 1 < α) {r : ℝ}
    (hr : 2 ≤ r) {p : ℝ} (hpn : 2 * n / (2 * n - 1) < p) (hp2 : p ≤ 2) :
    ∃ C : ℝ≥0, ∀ f : 𝓢(Rn n, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI n α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) :=
  exists_nnreal_of_exists_ne_top (hΩ.eLpNorm_shortVariation_le_of_le_two hn hα hr hpn hp2)

/-- **The short variation estimate for `n = 1`, `2 < p < ∞`, `2 < r < ∞`** (paper
(`eq:mainest_Sect4`) for `n = 1`; restatement of
`IsHomogeneousCZKernel.eLpNorm_shortVariation_le_n_one`). -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_n_one' {Ω : Rn 1 → ℝ}
    (hΩ : IsHomogeneousCZKernel 1 Ω) {α : ℝ} (hα : 1 < α) {r : ℝ} (hr : 2 < r) {p : ℝ}
    (hp : 2 < p) :
    ∃ C : ℝ≥0∞, C ≠ ∞ ∧ ∀ f : 𝓢(Rn 1, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI 1 α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) :=
  hΩ.eLpNorm_shortVariation_le_n_one hα hr hp

/-- `ℝ≥0`-constant version of `IsHomogeneousCZKernel.eLpNorm_shortVariation_le_n_one`
(paper (`eq:mainest_Sect4`) for `n = 1`, `p, r > 2`). -/
theorem IsHomogeneousCZKernel.eLpNorm_shortVariation_le_n_one_nnreal {Ω : Rn 1 → ℝ}
    (hΩ : IsHomogeneousCZKernel 1 Ω) {α : ℝ} (hα : 1 < α) {r : ℝ} (hr : 2 < r) {p : ℝ}
    (hp : 2 < p) :
    ∃ C : ℝ≥0, ∀ f : 𝓢(Rn 1, ℂ),
      eLpNorm (fun x => shortVariation r α (fun u => modulatedSI 1 α Ω u f x))
        (ENNReal.ofReal p) ≤ C * eLpNorm f (ENNReal.ofReal p) :=
  exists_nnreal_of_exists_ne_top (hΩ.eLpNorm_shortVariation_le_n_one hα hr hp)

end

end Auto
