/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib

/-!
# Sharp variation-norm estimates for oscillatory integrals related to Carleson's theorem

This file was automatically generated by Claude.

Formalization of S. Guo, J. Roos, P.-L. Yung, *Sharp variation-norm estimates for oscillatory
integrals related to Carleson's theorem*, Anal. PDE 13 (2020), arXiv:1710.10988v3.

This file contains the objects of Section 1 of the paper: the `r`-variation norm `V^r`, the
`λ`-jump function `N_λ`, homogeneous Calderón–Zygmund kernels `Ω(x)/|x|ⁿ`, and the modulated
singular integrals `𝓗^{(u)}` of (1.1).
-/

@[expose] public section

namespace Auto

open MeasureTheory Complex Filter Set
open scoped ENNReal NNReal Topology

/-- The Euclidean space `ℝⁿ`. -/
abbrev Rn (n : ℕ) := EuclideanSpace ℝ (Fin n)

/-- The `r`-variation norm of a family `a : ℝ → ℂ` over an index set `𝒥 ⊆ ℝ`
(Section 1 of the paper, display before (1.3)):
`V^r{a_u : u ∈ 𝒥} = sup_{J ∈ ℕ} sup_{u₀ < ⋯ < u_J in 𝒥}`
`(∑_{j=1}^J |a_{u_j} - a_{u_{j-1}}|^r)^{1/r}`.
It takes values in `[0, ∞]`. -/
noncomputable def variationNorm (r : ℝ) (𝒥 : Set ℝ) (a : ℝ → ℂ) : ℝ≥0∞ :=
  ⨆ (J : ℕ) (u : Fin (J + 1) → ℝ) (_ : StrictMono u) (_ : ∀ i, u i ∈ 𝒥),
    (∑ i : Fin J, (‖a (u i.succ) - a (u i.castSucc)‖ₑ) ^ r) ^ (1 / r)

/-- The `λ`-jump function `N_λ{a_u : u ∈ 𝒥}` (Section 1 of the paper): the supremum of all
`N` for which there is a strictly increasing sequence `s₁ < t₁ < s₂ < t₂ < ⋯ < s_N < t_N` in `𝒥`
with `|a_{t_j} - a_{s_j}| > λ` for all `j`. It takes values in `[0, ∞]`; it is `0` when no
such `N ≥ 1` exists. -/
noncomputable def jumpFunction (lam : ℝ) (𝒥 : Set ℝ) (a : ℝ → ℂ) : ℝ≥0∞ :=
  ⨆ (N : ℕ) (s : Fin N → ℝ) (t : Fin N → ℝ) (_ : ∀ i, s i < t i)
    (_ : ∀ i j, i < j → t i < s j) (_ : ∀ i, s i ∈ 𝒥 ∧ t i ∈ 𝒥)
    (_ : ∀ i, lam < ‖a (t i) - a (s i)‖), (N : ℝ≥0∞)

/-- A homogeneous Calderón–Zygmund kernel `K(x) = Ω(x)/|x|ⁿ` (Section 1, (1.2)): `Ω : ℝⁿ → ℝ`
is smooth on `ℝⁿ ∖ {0}`, homogeneous of degree `0`, and has mean zero on the unit sphere with
respect to surface measure. -/
structure IsHomogeneousCZKernel (n : ℕ) (Ω : Rn n → ℝ) : Prop where
  smooth : ContDiffOn ℝ (⊤ : ℕ∞) Ω {0}ᶜ
  homogeneous : ∀ (c : ℝ), 0 < c → ∀ x : Rn n, Ω (c • x) = Ω x
  mean_zero : ∫ ω, Ω (ω : Rn n) ∂(volume : Measure (Rn n)).toSphere = 0

/-- The truncated modulated singular integral
`∫_{|t| > ε} f(x - t) e^{i u |t|^α} Ω(t)/|t|ⁿ dt`. -/
noncomputable def truncatedModulatedSI (n : ℕ) (α : ℝ) (Ω : Rn n → ℝ) (u ε : ℝ)
    (f : Rn n → ℂ) (x : Rn n) : ℂ :=
  ∫ t in {t : Rn n | ε < ‖t‖},
    f (x - t) * exp (I * u * (‖t‖ ^ α : ℝ)) * ((Ω t / ‖t‖ ^ n : ℝ) : ℂ)

/-- The modulated singular integral (1.1) of the paper,
`𝓗^{(u)} f(x) = p.v. ∫_{ℝⁿ} f(x - t) e^{i u |t|^α} K(t) dt` with `K(t) = Ω(t)/|t|ⁿ`, defined as
the principal value limit `ε → 0⁺` of the truncated integrals. -/
noncomputable def modulatedSI (n : ℕ) (α : ℝ) (Ω : Rn n → ℝ) (u : ℝ)
    (f : Rn n → ℂ) (x : Rn n) : ℂ :=
  limUnder (𝓝[>] 0) fun ε => truncatedModulatedSI n α Ω u ε f x

end Auto
